### ISSUE TITLE
"CBA_fnc_taskDefend" does not ignore locked statics.

### ISSUE THREAD

**Issue by Neciota** [CBATeam/CBA_A3#1013]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.9.0` (stable)

**Mods:**
```
- CBA_A3
- ACE3
- CUP Weapons/Vehicles/Units
- ACRE2
```

**Description:**
AI groups given the taskDefend function will mount statics that are fully locked (not just locked for players). 

**Steps to reproduce:**
- Place AI group.
- Give AI group CBA_fnc_taskDefend.
- Place static near them.
- Lock the static.

**Where did the issue occur?**
- Dedicated

**Comment by commy2** [comment]
What happens if an AI tries to man a locked static weapon?

**Comment by Neciota** [comment]
It kills my platoon with the ZU-23 it mounted.

**Comment by dedmen** [comment]
>"CBA_fnc_taskDefend" does not ignore locked statics.

Is that a typo? You mean it "does ignore locked statics" right?

**Comment by Drofseh** [comment]
Doesn't seem like a type to me.
Statics are not ignored when locked, the AI get into them.

**Comment by dedmen** [comment]
Ahh. I read it as "does ignore locked-statics" which they don't. As they enter it.
But it's meant as "does ignore (locked) statics"
Dedmen being dumb again
