### ISSUE TITLE
variable _turn get never used in function isTurnedOut

### ISSUE THREAD

**Issue by shukari** [CBATeam/CBA_A3#1014]
**Arma 3 Version:** stable
**CBA Version:** stable

**Mods:**
```
- CBA_A3
```

**Description:**
https://github.com/CBATeam/CBA_A3/blob/fbd59d2ac1f85da79ea18a53b2d14e3ea285f60a/addons/common/fnc_isTurnedOut.sqf#L53

**Comment by commy2** [comment]
Will be closed by merge.
