### ISSUE TITLE
CBA PREP() macro could be useful thing to have documented

### ISSUE THREAD

**Issue by Bummeri** [CBATeam/CBA_A3#1021]
**CBA Version:**  stable

**Description:**
For example ACE mentions this about the PREP macro:

> Functions shall be created in the functions\ subdirectory, named fnc_functionName.sqf They shall then be indexed via the PREP(functionName) macro in the XEH_preInit.sqf file.
> 
> The PREP macro allows for CBA function caching, which drastically speeds up load times. Beware though that function caching is enabled by default and as such to disable it you need to #define DISABLE_COMPILE_CACHE above your #include "script_components.hpp" include!

As it is useful outside CBA, maybe it should be documented also on the wiki and or here:
http://cbateam.github.io/CBA_A3/docs/files/main/script_macros_common-hpp.html

**Comment by commy2** [comment]
https://github.com/CBATeam/CBA_A3/blob/master/addons/main/script_macros_common.hpp#L896

PREP has no doc, because it lacks a "header" like i.e. `PATHTO_FNC` a few lines below.
