### ISSUE TITLE
Request: CBA based project template

### ISSUE THREAD

**Issue by severgun** [CBATeam/CBA_A3#1033]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.9.0` (stable)

**Mods:**
```
- CBA_A3
```

**Description:**
- Add a project template for addon makers like ACE3 has.

**Comment by commy2** [comment]
How would it be different from the ACE one?

**Comment by dedmen** [comment]
Not use ACE path for the script macros. And don't use ace in requiredAddons. That's about it.

**Comment by commy2** [comment]
I could upload one to this repo, but I don't think I can create a separate repo for CBATeam.
