### ISSUE TITLE
Pointer Switch incompatible with Arsenal

### ISSUE THREAD

**Issue by commy2** [CBATeam/CBA_A3#1035]
State changed pointer attachments have scope 1, but the Arsenal refuses to save those.
This means that once the pointer mode is changed to something else that the default mode, the Arsenal saves no pointer attachment.
Solution is to change to the scope 2 version when the Arsenal is opened (and to change back once it is closed?). ACE Arsenal is untested, but I believe it is not affected and stores scope=1 items just fine.

**Comment by Blutze** [comment]
ACE ARSENAL
RHS frontgrips seem to work fine. They show the non-gripped classname and displayname after going back into the arsenal, and after loading a loadout that was saved with the gripped variant, you have the non-gripped thing equipped. They are `scope = 2`, but have a `baseWeapon` property defined that might be a vanilla feature allowing predefined attachment lists in scripted missions etc.
RHS and 3cb LLMs work by simply making both variants `scope = 2` (one of the reasons the RHS list is so cluttered).
The NIArms magswitch needs two clicks on the magazine to show up and not make you exit the arsenal with an empty gun (first simply deletes the normal mag), and leaves display name and class name unchanged until you go back into the arsenal. Loading a loadout with an special mag variant doesn't even give you a gun. Special guns are `scope = 2; scopeArsenal = 0;`.
The RHS G33 magnifier for holo sights has `scope = 1` on the flipped variant, which gets removed from saved loadouts. Base, unflipped variant works fine.

VANILLA ARSENAL
NIArms magswitched guns work fine. Obviously can't change the loaded mag without closing the arsenal.
The RHS G33 works fine through a saving -> restarting -> reloading cycle, but the flipped variant gets deleted when you go back to the rifle tab. The vanilla laser seems to work the same.
Frontgrips and RHS/3cb LLMs behave like in the ACE arsenal.

SOLUTIONS
Would it be the end of the world to show both versions of an LLM? Regardless of this bug, I'd prefer them to change display name btw.
In the ACE arsenal, there is `ace_arsenal_hide`. Not sure if that works for attachments.
For NIArms, maybe we should look at this `baseWeapon` thing, though now that it supports RHS grips on most guns that might become unwieldy and/or unreliable. @robalo

**Comment by commy2** [comment]
I would've just switched back to the scope=2 variant when opening the Arsenal. Similar to this:
https://git.koffeinflummi.de/bwmod-team/bwa3-public/blob/master/bwa3_optics/XEH_preInit.sqf#L41-60

**Comment by dedmen** [comment]
>State changed pointer attachments have scope 1, but the Arsenal refuses to save those.

Just make it a unique item and set the base class to the starting pointer attachment. Then arsenal will store that.

**Comment by commy2** [comment]
Can't reproduce in 1.88.
Vanilla Arsenal ¯\\_(ツ)\_/¯

**Comment by commy2** [comment]
Close until someone finds how to repro this issue again.
