### ISSUE TITLE
XEH: PostInit and InitPost Not Running on HC

### ISSUE THREAD

**Issue by KHunter-Arma** [CBATeam/CBA_A3#1046]
**Arma 3 Version:** `1.88.145285` (stable)
**CBA Version:** 3.9.1.181229` (stable)

**Mods:**
Too long - see rpt.

**Description:**
InitPost and PostInit XEH stopped working on HCs on my server. I run a dedicated server with 2 HCs and until recently everything was in order. I'm not sure when exactly the problem started, because it took me a little while to realise, but it's somewhere within the last 2-3 weeks, coinciding with the last CBA update, but also updates on my end - though only one of my updates had to do specifically with XEH and reverting that didn't fix the problem...

Neither mission config nor addon config PostInit/InitPost XEH are executed on the HCs. When in the editor, all the same XEH run just fine. The weirdest thing is, I noticed the PostInit "process" doesn't even initiate on the HCs. In both the dedicated server and my client RPT, I see lines like this

`[11119,502.612,874.138,"XEH: PostInit started. MISSIONINIT:...…blablabla…...`
and 
`[7429,228.392,1.339,"XEH: PostInit finished."]`

but for the HCs, those lines are absent.

I made a test mission with only CBA loaded to see if the problem happens there, and behold my test PostInit XEH inside the mission config worked everywhere. So whatever it is, it happens only with my usual setup, and I've come here to ask for help in diagnosing my problem more than anything else. I don't know nearly enough about the workings of XEH to understand how and why this suddenly started happening. I already spent 20+ hours trying to figure out and fix this to no avail... I'd really appreciate it if you guys can help me understand it. :(

**Steps to reproduce:**

**Where did the issue occur?**
On HC on dedicated

**RPT log file:**
[RPTs.zip](https://github.com/CBATeam/CBA_A3/files/2775588/RPTs.zip)

**Comment by dedmen** [comment]
You have a million and one errors in your HC RPT.
Remove mods one by one until the problem disappears to find out which mod is breaking it.

**Comment by commy2** [comment]
XEH PostInit is executed, in A3 for consistency, by a postInit `CfgFunctions` script. The game internal script that executes all `CfgFunctions` postInit scripts is `initFunctions.sqf` from the `functions_f.pbo`.
Some script errors in Arma abort the execution of the current script instance. Some can continue the script and just throw errors. Which one it is is rather arbitrary, which means that you have to fix all script errors in your mission or you will encounter unexpected behavior like this - postInit scripts, including the XEH postInit event will not be executed.

Some script errors taken from the RPT files are:
```
2019/01/18, 22:12:31 Error in expression <it = true;};

_index = _index + 1;

};

_resultingArray>
2019/01/18, 22:12:31   Error position: <_resultingArray>
2019/01/18, 22:12:31   Error Undefined variable in expression: _resultingarray
2019/01/18, 22:12:31 File x\Hz\Hz_mod_persistency\funcs\Hz_pers_fnc_structArrayElementParser.sqf, line 54
```

```
22:25:56 Error in expression <en {cim_key_pressed = false;};"];


if (CIM_DebugMode) then {diag_log format ["k>
22:25:56   Error position: <CIM_DebugMode) then {diag_log format ["k>
22:25:56   Error Undefined variable in expression: cim_debugmode
22:25:56 File nielsen_cim\nielsen_cim_key_detect.sqf, line 8
```

```
22:27:06 Error in expression <if(Hz_AI_debug) then { if(_grp == grp && _i>
22:27:06   Error position: <Hz_AI_debug) then { if(_grp == grp && _i>
22:27:06   Error Undefined variable in expression: hz_ai_debug
```
All of these will have to be fixed. Start fixing them in chronological order, because some errors may be caused by previous errors, and may disappear once the inital problem is solved.

**Comment by commy2** [comment]
You don't see XEH postInit, because your scripts have script errors that have to be fixed for the game to correctly complete the relevant script instances.

**Comment by KHunter-Arma** [comment]
I agree with you, but I really do feel like what I said last was just ignored...

Anyway, I found the fix where I would've expected least, so prepare to be surprised. I don't know if you're familiar with the "infinite loading screen bug" in Arma 3, where clients joining MP missions get indefinitely stuck in the loading screen. BIS claimed they fixed it "for most cases" with 1.88, and although this used to be a problem with players, I couldn't imagine it being an issue with HCs.

This is some sort of initialisation problem, which I doubt has anything to do with CBA. The known workaround for this is to use "endLoadingScreen;" to force the engine to proceed from some stuck state. That's exactly what I did, by remotely executing that command globally, and boom, PostInit! It's really weird in this case since HCs don't even have an interface... You can check the new RPTs if you don't believe me. Nothing changed for players or dedicated, which had PostInit started normally, whereas the HCs had that happen as soon as I remotely executed endLoadingScreen, which is indicated by a message I logged in RPT "Forcing end load screen...".

[RPTs.zip](https://github.com/CBATeam/CBA_A3/files/2776030/RPTs.zip)

**Comment by KHunter-Arma** [comment]
I do care about fixing my errors, and for the record, I did fix the second error (from your first post). I still assert that the first error is not a real error and the last error disappeared completely with this fix, because it was due to InitPost not running, as I tried to explain.

There's only one error remaining in the Dedicated log, which is already on my todo list. Anything else you might see is due to other authors' addons...

I don't want to steal any more of your time and appreciate you trying to help, but I resent that you think I don't care about my work, which takes a lot of my time...

**Comment by commy2** [comment]
>I still assert that the first error is not a real error 

I assert you're wrong.

>and the last error disappeared completely with this fix

Very good then.

>but I resent that you think I don't care about my work, which takes a lot of my time...

Not true, but it is very irritating if someone seeks help, but then ignores the given advice. And it becomes frustrating if you yourself know for certain that the advice is not only well meant, but actually fixes the underlying issue. And I am sure many people lurking this Github know this as well.

And now instead of fixing the issue, you added a work around. One with unpredictable side effects. Just forcing the loading screen to end is a terrible way to go about this, because it will become the source of other issues in the future. And that "fix" is not advice I want to see on the CBA tracker, which is usually seen, by some people at least, as a place where you can see examples of good, clean code.

**Comment by KHunter-Arma** [comment]
Ok, well I will look into the first script error then, if you say it's an actual problem. I'm assuming you're saying if a variable is initialised in a function explicitly to "nil" and then returned without being changed (as nil), it will normally not output that on the RPT as an error? Because that's what is going on there.

However, that error is thrown by a scheduled script run on the server and delayed 60s after mission start. I honestly can't see how that would relate to the HC not being able to go through PostInit. But maybe there's something else my HCs are going through which gets them stuck and it's not some undefined variable, but just a script getting stuck waiting without throwing any errors. Does that sound possible?

**Comment by brainslush** [comment]
I can tell you that PostInit and InitPost does work on HCs as our HC Framework relies on it and we haven't seen any issues.

**Comment by KHunter-Arma** [comment]
Thanks guys. Just came back to say the problem was in fact likely due to the Tactical Position Ready addon.
