### ISSUE TITLE
Magwells seem to give players an unfair advantage on a MP Server

### ISSUE THREAD

**Issue by TheMasterofBlubb** [CBATeam/CBA_A3#1050]
**Arma 3 Version:** stable
**CBA Version:** stable

**Mods:**
```
- CBA_A3 (for any other mod like Shacktac and Dynasound)
```

**Description:**
If CBA is used (its not mandatory since all allowed mods are just client side) the player can load a 100rnd 6.5mm Mag in to any MX Series Rifle.
I understand that CBA is a Framework for many mods and it wants to give more realism, BUT there are plenty of servers that have optional mods that need CBA (because literaly every mods uses it) so that situation now give a huge advantage to people having CBA active to those not having.
I would like that CFG Entry to be removed at least till its used Vanilla.
And no making CBA mandatory is not an option ;)

If you have a kind of lite CBA for only Clientside stuff that would be nice too , or even a setting to restrict changes done by CBA. 

**Steps to reproduce:**
Start game vanilla
try to load a 100rndMag 
Start Game with only CBA
Now you can load it in

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal (yeah that should sum it up)

**CFG Entry:**
configfile >> "CfgWeapons" >> "arifle_MX_Base_F" >> "magazineWell" There is the MX XL Magwell

**Comment by jonpas** [comment]
All those magazine wells will never be in vanilla.

You can remove `cba_jam.pbo`.

I don't see (or want to see) this being removed from CBA. Why is making CBA mandatory not an option?

**Comment by commy2** [comment]
Agreed with OP, CBA should not do any gameplay modifications.

**Comment by commy2** [comment]
You can use CBA without Dynasound etc. even with a crappy machine.

**Comment by TheMasterofBlubb** [comment]
Im fine with ideas of Magwells, but forcing them on everyone even though you only want a sound mod is not the right way in my opinion?
It would be better to leave Vanilla weapons as they are ( leave the CBA MX Magwell in there) and if someone likes he still can add it in.

Or a even better approach, as everyone using CBA in a heavely modded enviroment will still have more mods. Make a Compat Mod to enable all that fine Stuff on vanilla Weapons.

>You can use CBA without Dynasound etc. even with a crappy machine.

Yes but not Enchanced Soundscape. I like to use them both. It was just an example

**Comment by jonpas** [comment]
Yes, we could do that, keep mag well definitions in core CBA, move magazine additions to optional. I don't like it, but oh well.

**Comment by commy2** [comment]
You can also use CBA without Enhanced Soundscape.

**Comment by TheMasterofBlubb** [comment]
@commy2  but i want it the other way i want Enchaced Soundscape without CBA XD

@jonpas the problem is CBA is so widely used that it even is used on vanilla servers. Thats something that should be considered. There shouldnt be game changing stuff forced upon everybody. That brings us to the idea of forcefully deny CBA because it breaks our carefully balanced gameplay.

**Comment by commy2** [comment]
My point is that your argument is bad, because if someone wanted the advantage and has a crappy pc, they could still use CBA.
I still agree with you that CBA should not do any gameplay modifications like adding mags to weapons or different scopes etc.

**Comment by TheMasterofBlubb** [comment]
@commy2 yeah probably not the best example but many people play vanilla on our servers and we want to keep that. We didnt recognize this problem till a player told us that its possible. And its a huge problem since we restrict a medic to assault rifles and MPs, so technically if used CBA he now can carry a lightweight low recoil MG (yes adding the Mag doesnot change the recoil or sway somehow) and he converts to a super soldier.

**Comment by commy2** [comment]
Yep.
- CBA shouldn't do any gameplay modifications.
- MX being now able to use 100Rnd mags is a gameplay modification

is the better argument, so let's focus on that.

**Comment by TheMasterofBlubb** [comment]
@commy2 agree

**Comment by jonpas** [comment]
In the meantime (if this gets changed), couldn't you also simply restrict what ammo types they have access to?

**Comment by TheMasterofBlubb** [comment]
We have at somepoint decided that everyone should have access to all available ammotypes (for his faction) to have people donating ammo to others (some mags like the Navid ones are quite pricy).
For that we restrict weapons to specific roles, thats why we rely on correct magazine types.
For now we have decided to leave it as is and made the bug public so no one get falsly accused of cheating, but we cant really fix it ourselves.

**Comment by dedmen** [comment]
Ref: https://github.com/CBATeam/CBA_A3/issues/1032#issuecomment-441350969
That comment is about JR but I guess it applies the same to JAM.

**Comment by TheMasterofBlubb** [comment]
The problem is more like the method. There are mods that are purely cosmetic but CBA forces stuff on users and communities that they cant control. Thats not very nice. Especially that will mean that we will need to disallow CBA completly if this is intended behaviour... and with that all others too... imho that shit

**Comment by TheMasterofBlubb** [comment]
BTW that same problem is present on CAR and SPAR 16 too


CBA_A3/addons/jam/CfgWeapons.hpp
Thats the "evil" file

**Comment by tbeswick96** [comment]
This seems like a you problem. There's no reason those magazines can't be used in those weapons.
There's easy scripted solutions you could utilise to block certain unit classes using a particular magazine in a particular weapon

**Comment by TheMasterofBlubb** [comment]
thats correct but CBA should add this funcionality. A mod thats using this should add it. Adding a script solution would mean more points of faliure on our side. Additionaly im not sure if its possible with out adding CBA on the server side?

**Comment by jonpas** [comment]
You already made your point some of us agreed with you on. Don't turn this into "must convince everyone" fest, because you won't, and don't revive old closed issues.

**Comment by Dystopian** [comment]
I think there should not be support if server allows different client mod sets. Or let's move to optionals `laser-flashlight switch` or maybe `extended debug console` or even `keybinding` just because for someone `making CBA mandatory is not an option`.

**Comment by TheMasterofBlubb** [comment]
@Dystopian so to just get that right for me:
You say if we want to have Shacktac (or technically any other CBA based CLIEN side mod) be optional on a public server we should force CBA on everyone regardless if they need it?
The main problem is we have no alternative to CBA, that means either we force CBA on a vanilla community or remove all CBA based mods...

**Comment by commy2** [comment]
Deleted the trolling. Only serious replies please.

**Comment by dedmen** [comment]
https://github.com/CBATeam/CBA_A3/blob/master/addons/jam/CfgWeapons.hpp#L28
Here is the location of your problem.
Feel free to make a pull request to update that config to remove the XL magwell from the MX that shouldn't have it and add it to the MX MG variant that hsould have it instead.

**Comment by Blutze** [comment]
Methinks this is going to be a moot point in the (hopefully) near future, when BI starts using magWells and magProxies themselves. You'll have that issue even without any mods, but it won't be an issue because you will be able to visually identify the type of magazine a player has loaded (like in ye olden days, when some striker fired guns had to have hammer-shaped dinguses so the commanding officer could walk down the line and slap any grunt found having his gun cocked).

And there is zero technical, realism reason for the non-LSW MXs to not be able to take the quadstack mags. Is it a more powerful option in PvP? Sure, but you could just make them more expensive; and magProxies need to be extended to affect handling characteristics (dexterity and inertia at the very least) anyway. 

If all else fails, whats the official stance on custom reuploads of CBA? I know ACE allows it, for reasons such as this.

Something we should actually fix though is Katiba mags being available on MX guns. No idea how that slipped through.

**Comment by commy2** [comment]
CBA uses the same license as ACE, so you can modify and reupload and do whatever with it as long as you keep the license for the new project and make it open source as well.

The realism aspect doesn't matter here, because this limitation of non SW MX being incompatible with 100 Rnd mags may be a gameplay aspect not rooted in realism, but balance or flavor or whatever else.
It's not CBAs job to make things as they are irl. That's what ACE is for.

`CBA_65x39_MX_XL` already is the magwell with the 100 Rnds mags. Currently `CBA_65x39_MX` (30 Rnd mags) and `CBA_65x39_MX_XL` are added to all MX. To fix this issue, all one would have to do is to remove `CBA_65x39_MX_XL` from the MX base class and readd `CBA_65x39_MX` and `CBA_65x39_MX_XL` to the MX SW.

This would not cause any compatibility issues aside from some weirdly configured MX reskins maybe.

**Comment by neilzar** [comment]
Does CBA really need any of the Magazine well stuff? Most mods already add to the vanilla magwells. RHS and NIArms both add to the vanilla magwell arrays, for example.

**Comment by jonpas** [comment]
@neilzar https://github.com/CBATeam/CBA_A3/pull/1030

**Comment by Blutze** [comment]
Neil, you lemon... RHS adds a number of custom magwells for weapon platforms like M240s, 9x39 and others that arent in vanilla at all. Which is what CBA is doing as well - there isn't going to be full coverage for WW2 weapon and ammo types in vanilla, but those guns are being added my multiple mods. So we want a core framework mod like CBA to add a common magWell that both RHS and IFA/FoW can use. 

More applicable to the FK modset: RHS has a 7.5 Swiss ammo class flying around, so they might be planning to introduce guns with that... in which case we'd once again want a common magWell class for both that gun and the NIArms SIG 510s.

Etc.
