### ISSUE TITLE
Add Joint Ammo and Magazines (JAM)

### ISSUE THREAD

**Issue by ViperMaul** [CBATeam/CBA_A3#108]
GOAL: 
Provide common bullet and magazine classes for use by weapon mods in order to achieve better consistency and compatibility

TO DO:
- add common bullets (CfgAmmo classes)
- add magazines (CfgMagazines classes)
- add magazine groups
- provide macros as alternative to magazine groups so mod makers can use them
- configure vanilla weapons to use new magazines
- add support for AB, ACE3

TO NOT DO:
- create too many bullet and magazine variations

Source: https://github.com/robalo/mods/blob/master/asdg_jam/config.cpp
Relates to #43

**Comment by aoighost** [comment]
VM, I want to look in to this, should I do it in a fork of this or JAM?

**Comment by dedmen** [comment]
Problem is that magazineGroups are broken right? Because https://github.com/robalo/mods/blob/master/asdg_jam/config.cpp#L197 is uinsg magazineGroups.
Can someone confirm that they are broken?

**Comment by robalo** [comment]
Last I checked they were broken, long ago but did not see any mention of them since. But this can be done without magazineGroups, carefully appending to magazines[] config array instead.  I'd still like to work on this, only need to find some time to kick-start it. Then I'm sure we'll get people contributing to it fast.

**Comment by dedmen** [comment]
Just tested `magazineGroup` is working fine in the backend.
Just mousewheel action and drag-drop into magazine slot is not working perfectly. See https://feedback.bistudio.com/T82996#1650317

Mouse wheel menu is fixable with script.

**Comment by dedmen** [comment]
I fixed it.
https://feedback.bistudio.com/T82996#1650367
Just took about 3 hours of work. Only possible with a non Battleye compatible hack. But maybe BI will just let me explain them how to fix it and implement that.

**Comment by dedmen** [comment]
Official statement from reyhard that BI is working on magazineGroups (Now called magazineWells).
```
class CfgMagazineWells
{
    class Stanag556x45
    {
        BI_stanags[] = {30Rnd_556x45_Stanag,30Rnd_556x45_Stanag_Tracer_Red,30Rnd_556x45_Stanag_Tracer_Green,30Rnd_556x45_Stanag_Tracer_Yellow,30Rnd_556x45_Stanag_red,30Rnd_556x45_Stanag_green};
        CUP_stanags[] = {CUP_30Rnd_556x45_Stanag1, CUP_30Rnd_556x45_Stanag2};            
    }; 
};

class CfgWeapons
{
 class mk20_base_F: Rifle_Base_F
 {                
  magazines[] = {30Rnd_556x45_Stanag}; // keep non empty, some script (arsenal) reed it only from here
                 magazineWell[] = {Stanag556x45};
```

I tried to push a little that we can get the CfgWeapons `magazineWell` array to become a class like is already possible with weapon attachments in Joint Rails. 
Didn't get any statement on that though.

**Comment by PabstMirror** [comment]
Found another example on pastebin: https://pastebin.com/U7KabeUJ

**Comment by robalo** [comment]
Nice, looks like it's even supported by arsenal:
`					// Magazine wells
					{
						// Find all entries inside magazine well
						{
							// Add all magazines from magazineWell sub class
							{
								private _item = _x;
								if (CONDITION(_virtualMagazineCargo)) then {
									_mag = tolower _item;
									_cfgMag = configfile >> "cfgmagazines" >> _mag;
									if (!(_mag in _magazines) && {getnumber (_cfgMag >> "scope") == 2 || getnumber (_cfgMag >> "scopeArsenal") == 2}) then {
										_magazines set [count _magazines,_mag];
										_value = {_x == _mag} count _itemsCurrent;
										_displayName = gettext (_cfgMag >> "displayName");
										_lbAdd = _ctrlList lnbaddrow ["",_displayName,str _value];
										_ctrlList lnbsetdata [[_lbAdd,0],_mag];
										_ctrlList lnbsetvalue [[_lbAdd,0],getnumber (_cfgMag >> "mass")];
										_ctrlList lnbsetpicture [[_lbAdd,0],gettext (_cfgMag >> "picture")];
										_ctrlList lbsettooltip [_lbAdd * _columns,format ["%1\n%2",_displayName,_item]];
									};
								};
							}foreach (getArray _x);
						}foreach (configProperties [configFile >> "CfgMagazineWells" >> _x,"isarray _x"]);
					} foreach getarray (_cfgMuzzle >> "magazineWell");
`

**Comment by robalo** [comment]
Pushed stuff into JAM branch. Feel free to adjust.

**Comment by dedmen** [comment]
Let's move discussion about how to further seperate the wells to here

So we have my proposal
5/10/20/30/stick/drum (where stick contains 5/10/20/30 too)
Or Drofseh's
Standard/LargeStick/Drum
https://github.com/CBATeam/CBA_A3/pull/928#issuecomment-421405281

I prefer Drofseh's solution.
Need feedback from some actual modders about this. CUP Team?

**Comment by Drofseh** [comment]
This is how I would set it up
Large_Stick doesn't duplicate the smaller mags in Standard, but both magwells are assigned to the weapons that would use them
```
class CfgMagazineWells {
    class MyMagWell_Standard {
        MyStandardMags[] = {
            "5Rnd_Small_Mag",
            "10Rnd_Small_Mag",
            "20Rnd_Small_Mag",
            "30Rnd_Normal_Mag"
        };
    };
    class MyMagWell_Large_Stick {
        MyLargeStickMags[] = {
            "45Rnd_Stick_Mag",
            "60Rnd_Coffin_Mag"
        };
    };
    class MyMagWell_Drum {
        MyDrumMags[] = {
            "75Rnd_Drum_Mag",
            "100Rnd_Drum_Mag"
        };
    };
};

class CfgWeapons {
    class MyBaseRifle;

    class MyStandardRifle: MyBaseRifle {
        magazineWell[] = {"MyStandardMags","MyMagWell_Large_Stick","MyMagWell_Drum"};
    };
    class MyBullpupRifle: MyBaseRifle {
        magazineWell[] = {"MyStandardMags","MyMagWell_Large_Stick"};
    };
    class MyPrecisionRifle: MyBaseRifle {
        magazineWell[] = {"MyStandardMags"};
    };
};
```

**Comment by Drofseh** [comment]
@commy2 I think @dedmen was suggesting this issue be left open for future magwell discussion.

**Comment by PabstMirror** [comment]
We currently have `CBA_40mm_M203` for 40×46mm grenades
The Pike is a longer grenade that can only be fired from the M320 or EGLM because they swing open
Would it be worth adding an extra well for the m320/eglm?

**Comment by robalo** [comment]
Good points, looking into adding more classes and how to name them.

**Comment by PabstMirror** [comment]
```
    class arifle_Katiba_Base_F: Rifle_Base_F {
        class EGLM: UGL_F {
            magazineWell[] = {"CBA_40mm_EGLM"};
        };
    };
    class arifle_SPAR_01_GL_base_F: arifle_SPAR_01_base_F {
        class EGLM: UGL_F {
            magazineWell[] = {"CBA_40mm_EGLM"};
        };
    };
```
Are the 2 vanilla guns that seem to actually be EGLMs
And the `arifle_AK12_GL_base_F` seems to have a GP-25 launcher, so I guess we could set it's well to `CBA_40mm_GP`

**Comment by PabstMirror** [comment]
`CBA_9x19_MP5`?

**Comment by Drofseh** [comment]
How do we want to handle weapons that use loose ammunition such as shotguns or revolvers?
They should always be able to take an amount smaller than their capacity but not larger.

Does this look good?

```
class CfgMagazineWells {
    class CBA_38_Special_Clip_6rnds {}; // 6 round .38 Special moon clip
    class CBA_38_Special_Clip_5rnds {}; // 5 round .38 Special moon clip

    class CBA_38_Special_6rnds {};      // 6 loose rounds of .38 Special
    class CBA_38_Special_5rnds {};      // 5 loose rounds of .38 Special

    class CBA_357_Clip_6rnds {};       // 6 round .357 Magnum moon clip
    class CBA_357_Clip_5rnds {};       // 5 round .357 Magnum moon clip

    class CBA_357_6rnds {};             // 6 loose rounds of .357 Magnum
    class CBA_357_5rnds {};             // 5 loose rounds of .357 Magnum

    class CBA_12g_9rnds {};             // 9 loose rounds of 12 gauge
    class CBA_12g_8rnds {};             // 8 loose rounds of 12 gauge
    class CBA_12g_7rnds {};             // 7 loose rounds of 12 gauge
    class CBA_12g_6rnds {};             // 6 loose rounds of 12 gauge
    class CBA_12g_5rnds {};             // 5 loose rounds of 12 gauge
    class CBA_12g_4rnds {};             // 4 loose rounds of 12 gauge
    class CBA_12g_3rnds {};             // 3 loose rounds of 12 gauge
    class CBA_12g_2rnds {};             // 2 loose rounds of 12 gauge
    class CBA_12g_1rnd {};              // 1 loose round of 12 gauge
};

class CfgWeapons {
    class MyPistolBase;
    class MyShotgunBase;

    class My357_Revolver : MyPistolBase {
        magazineWell[] = {"CBA_357_Clip_6rnds","CBA_357_6rnds","CBA_357_5rnds","CBA_38_Special_Clip_6rnds","CBA_38_Special_6rnds","CBA_38_Special_5rnds"};
    };

    class MySmaller357_Revolver : MyPistolBase {
        magazineWell[] = {"CBA_357_Clip_5rnds","CBA_357_5rnds","CBA_38_Special_Clip_5rnds","CBA_38_Special_5rnds"};
    };

    class My38Special_Revolver : MyPistolBase {
        magazineWell[] = {"CBA_38_Special_Clip_6rnds","CBA_38_Special_6rnds","CBA_38_Special_5rnds"};
    };

    class MyCombatShotgun : MyShotgunBase {
        magazineWell[] = {"CBA_12g_9rnds","CBA_12g_8rnds","CBA_12g_7rnds","CBA_12g_6rnds","CBA_12g_5rnds","CBA_12g_4rnds","CBA_12g_3rnds","CBA_12g_2rnds","CBA_12g_1rnd"};
    };

    class MyDoubleBarrelShotgun : MyShotgunBase {
        magazineWell[] = {"CBA_12g_2rnds","CBA_12g_1rnd"};
    };

    class MySingleBarrelShotgun : MyShotgunBase {
        magazineWell[] = {"CBA_12g_1rnd"};
    };
};
```

**Comment by dedmen** [comment]
@Drofseh For one I think hat would be going too far. But I also think that this is really required sooo..
I think that's a good solution. (Implementation side: we should start splitting stuff into seperate header files to include. It's getting quite clumpy otherwise)

And to the 40mm stuff. Yeah splitting into different launcher types makes sense EGLM, M203, GP. Are there any more?

https://github.com/CBATeam/CBA_A3/issues/108#issuecomment-422539879 Maybe we can push some of this stuff to bohemia to implement it on their side. I wouldn't think about making vanilla compats and stuff yet.

**Comment by robalo** [comment]
Since there's no M203 in vanilla we could have the UGL_F base class set with EGLM. Then it needs to be properly set for M203 in mods when inheriting from the base class.
I guess the 3GL can fit single longer nades as well, since it can do 3 'normal' rounds. Just don't go crazy and define 3 x Pike mags for it.

**Comment by robalo** [comment]
On changes in jam_x branch:

I split some of the mag well classes in order to provide extra flexibility when defining them for weapons.
Allowed C-MAGs on bullpups as a compromise because it looks doable but did not enable the extra large 150rnd twin-drums on them which are really huge.
Don't really see a reason to define a magwell for single drums separately as they are roughly the same length and not as bulky as the twin-drums.
Did not copy magazines into the EGLM class because it would require people to put their mags in multiple places. So just add the Pike into the EGLM magwell class and add M203 magwell to EGLM weapon.

**Comment by Drofseh** [comment]
@robalo So I was just about to PR a bunch of WW2 era magwells when I saw your PR.
Which one should we do first?

**Comment by robalo** [comment]
> 
> 
> @robalo So I was just about to PR a bunch of WW2 era magwells when I saw your PR.
> Which one should we do first?

My preference would be directly into the jam_x branch.

**Comment by Drofseh** [comment]
Ok, done in #991

**Comment by Soldia1138** [comment]
I agree with dedmen, different header files should declutter all the magwells. 

My proposal would be to bucket them by caliber as this would represent a natural sort order. Difficulty here would be mm vs. .in notation. 
Another approach would be: one header file per caliber. 

Looking forward to other proposals

**Comment by robalo** [comment]
It's already split. But I think strictly using caliber would be a mistake.
I'm for easily recognizable names like 45AUTO and 45ACP instead of 10x25mm and 11.43×23mm.

**Comment by dedmen** [comment]
Why is there no 762x51 stanag?

**Comment by da12thMonkey** [comment]
> Why AI? What does that AI stand for?
Accuracy International
There is a common AI magazine design for various rifles in .308 (PSG90, L118, M40A5), .300 (G22, Mk13 Mod 2/3/4/5/6/7, M2010) and .338 (L115A3, TAC 338, Orsis T5000)

Would suggest adding Glock mags too, since they're quite common

**Comment by Drofseh** [comment]
12.7x99mm is .50 BMG

**Comment by Drofseh** [comment]
I will do a little more work on this today.
I plan to add Glock magwells by calibre and frame size as in my example above ^
I will also add more comments to clarify organizational structure and caliber naming.

I also think it would be worth giving every calibre it's own included hpp file, rather than the current setup where an hpp file is used only if there is more than one magwell currently included.

**Comment by Drofseh** [comment]
I may also alphabetize some entries if that's alright with your guys. 

The 9x19mm magwells being out of order is bothering me, and if we call start alphabetizing now then it won't get as messy in the future.

**Comment by robalo** [comment]
> Why is there no 762x51 stanag?
Never heard of it. We have most 762x51 mags covered though.
 
> 762x67 is missing. ACE is using that.
That's .300 WinMag. If there is something else than the AI compatible mag, please add.

> 65x47 is missing.
> 65_Creedmor is missing (Dunno what that is. But ACE ballistics has it)
What weapons use those ? If you have info, please add magwell class.

Would love to see this go beyond magwells and have common ammo and magazines as well.
But they have to be contributed.

**Comment by Drofseh** [comment]
@commy2 why is .300 Blackout using metric instead of imperial?
I'd like to change `CBA_762x35_STANAG` to `CBA_300BLK_STANAG`

**Comment by commy2** [comment]
Don't ask me, I don't want to be part of this.^^

**Comment by Drofseh** [comment]
lol, maybe @robalo is responsible, I'm not exactly sure which commit added it.

**Comment by Drofseh** [comment]
likewise `CBA_68x43_ACR` the ACR takes STANAG magazines, so it should be `CBA_68SPC_STANAG`

**Comment by robalo** [comment]
Is there a reason to make a separate single drum magwell ?
See here for example: http://soldiersystems.net/2015/12/07/magpul-pmag-d-60-comparison/
D-60 or X-15 are roughly same length as the standard mags.

**Comment by robalo** [comment]
If I'm not mistaken CBA_762x51_AR10 and CBA_762x51_SR25 refer to the same thing.

**Comment by robalo** [comment]
If this can work then I guess single drum is not going to be an issue either :)
https://www.mdshooters.com/showthread.php?t=133242
Agree about AR10 naming.

**Comment by Drofseh** [comment]
Yah, I'd like to whittle down the STANAG classes to just
```
    class CBA_xxxxxx_STANAG {};         // normal mag
    class CBA_xxxxxx_STANAG_L {};       // long mag
    class CBA_xxxxxx_STANAG_XL {};      // really long mag
```
Any objections?

**Comment by robalo** [comment]
But also keep the dual drum classes  because the C-MAG 100rnd may or may not fit some bullpups while the 150rnd SAW-MAG will most likely not (that thing is almost twice as huge).

**Comment by Drofseh** [comment]
@robalo does #997 look good to you for STANAG?

**Comment by robalo** [comment]
Uhm, I don't like that you merged the 2 twin-drum classes. The reason for the split was to be able to ban the larger 150rnd from bullpups, because they are almost twice as big that the 100rnd.

**Comment by Drofseh** [comment]
I have unmerged the twin drum classes in my PR

**Comment by Drofseh** [comment]
Change milestone?

**Comment by commy2** [comment]
Either that or new issue.

**Comment by Drofseh** [comment]
What should we do with the vanilla Mk-I EMR 7.62 mm `srifle_DMR_03_F`.
It uses vanilla `20Rnd_762x51_Mag` magazines.

ACE is renaming it the SIG 556 (which it very strongly resembles), but the SIG 556 is well, a 5.56x45 rifle, not 7.62x51.

**Comment by robalo** [comment]
> What should we do with the vanilla Mk-I EMR 7.62 mm `srifle_DMR_03_F`.
> It uses vanilla `20Rnd_762x51_Mag` magazines.
> 
> ACE is renaming it the SIG 556 (which it very strongly resembles), but the SIG 556 is well, a 5.56x45 rifle, not 7.62x51.

Wouldn't worry about BIS's fantasy weaponry much. Add magwells where it makes sense, ignore the weapon where it doesn't :)

**Comment by commy2** [comment]
Close? If more questions, issues, requests arise, one can open a new Issue/PR.
