### ISSUE TITLE
CBA_fnc_addWaypoint

### ISSUE THREAD

**Issue by topden** [CBATeam/CBA_A3#1096]
**Arma 3 Version:** 1.90
CBA_A3 v3.9.1.181229
ACE3
RHS

**Description:**
18:55:58 Error in expression <roup call CBA_fnc_getGroup;
_position = _position call CBA_fnc_getPos;
private >
18:55:58   Error position: <_position call CBA_fnc_getPos;
private >
18:55:58   Error Undefined variable in expression: _position
18:55:58 File \x\cba\addons\ai\fnc_addWaypoint.sqf [CBA_fnc_addWaypoint], line 1798

**Steps to reproduce:**
start to play @heards & minds@ mission (https://github.com/Vdauphin/HeartsAndMinds) and check rpt after. I don’t know, it’s important, it’s not and what it means, but I’ve decided to write it. Maybe you will understand more quickly if there is a mistake and whether it affects something

**Where did the issue occur?**
- Dedicated 
http://joxi.ru/n2YXgExCoX5LGm

**Comment by Drofseh** [comment]
@Vdauphin

**Comment by commy2** [comment]
Full RPT file would be very helpful.

**Comment by dedmen** [comment]
The function was called in scheduled with a nil as argument.
Not a CBA bug
https://github.com/CBATeam/CBA_A3/blob/fbd59d2ac1f85da79ea18a53b2d14e3ea285f60a/addons/ai/fnc_addWaypoint.sqf#L37

**Comment by commy2** [comment]
Close?
