### ISSUE TITLE
error flexmenu

### ISSUE THREAD

**Issue by shukari** [CBATeam/CBA_A3#1100]
**Arma 3 Version:** stable
**CBA Version:** stable

**Mods:**
```
- CBA_A3
```

**Description:**
I dont know if its a cba issue or tfar issue but i report it on both ends
-> https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1458

![19rCjzL](https://user-images.githubusercontent.com/7529291/54482501-fe200c80-4844-11e9-9150-ec2a52c1d347.jpg)

**Comment by commy2** [comment]
Duplicate of https://github.com/CBATeam/CBA_A3/issues/1097. Already fixed in 3.10.1.
