### ISSUE TITLE
Feature request: 2D scopes framework

### ISSUE THREAD

**Issue by 10Dozen** [CBATeam/CBA_A3#1102]
ACE3 and BWMod has sweet custom 2D scopes with bunch of features like recoil animations, reticle switching and so on.

Would be great to have similar framework in CBA and plug custom scopes with minimal set ups from my mod's side.

Expected Minimum: To have all needed settings, scripts, handlers and Rsc base classes in CBA + some documentation

**Comment by 10Dozen** [comment]
As a fancy feature - is it possible to implement additional layer for weapons like M4: http://img.photobucket.com/albums/v131/nickmartinphoto/DSC00292.jpg

Implementation may be like:
- parameter at gun config that marks gun as one with non-foldable sight and RIS not above it (maybe just RIS height and front sight height or their delta - >0 means sight above, <0 - sight below ris mount) and reference to blurry image of front sight scope (maybe even few - blurry for x4 and very blurry for x6+)
- parameter at scope config that defines height of scope optics and scopes's FOV
- if front sight height is in scopes FOV - draw blurry layer of gun's sight

**Comment by commy2** [comment]
You can not blur textures in game. You would need different textures for all of those and blur them yourself in GIMP or Photoshop.
