### ISSUE TITLE
Feature request: Hold trigger option for weapon animations framework

### ISSUE THREAD

**Issue by jonpas** [CBATeam/CBA_A3#1106]
Different handling option for bolt-actions.

**Current:** Exit optics (gunner) view; press RMB when want to bolt
**Requested:** Hold trigger; hold LMB and release when want to bolt

_Noting as requested by a lot of CUP users and developers, as this is how it worked before I replaced custom script with CBA's._

**Comment by commy2** [comment]
I once thought I would reach a point where there was nothing to do for Arma anymore.

That must've been 3 years ago...

**Comment by commy2** [comment]
https://github.com/CBATeam/CBA_A3/pull/1107
