### ISSUE TITLE
Feature request: CBA Settings Button control and public API

### ISSUE THREAD

**Issue by 10Dozen** [CBATeam/CBA_A3#1115]
CBA Settings is very nice thing to use, but sometimes mod may need some specific configurator.
For example - class based settings (e.g. specific settings for specific weapon class), which are easier to keep/change in scripts rather than in configs. To make it easy to set up - i may use some specific UI with lists and search/filters stuff (like [EJAM](https://raw.githubusercontent.com/10Dozen/dzn_EJAM/master/Source/20180825013549_1.jpg) has)
But there is no easy way to link my custom configurator with CBA Settings now.

Would be great to have next addition to CBA Settings:
**(A)** New input for CBA Settings menu - Button:

- it may look similar to other controls (text at the left, button at the right, tooltip)
- onClick code should be set by user (e.g. to launch custom configurator)
- option to make button disabled once clicked (to prevent multiple executions; button may be active again on re-opening settings or switching between mods via dropdown)
- (optional) disabled button text may be configurable.

**(B)** CBA Settings API description of what functions should be used to save data from custom configurator to CBA Settings (guess CBA_settings_fnc_set should be used, but maybe some additional validator is needed for public use) + how to read data from CBA Settings to custom configurator..

Expected:
Ability to call custom configuration function from CBA's Addon Options menu by clicking button with user defined exec code. Ability to save data from custom configurator to CBA Settings framework.

**Comment by commy2** [comment]
FUNC(set) is for permanent or at least applied changes. The changes in the menu are merely temporary and use `SET_TEMP_NAMESPACE_VALUE` and `SET_TEMP_NAMESPACE_PRIORITY`. There are a lot of other interactions between the different controls in the menu. I don't really trust anybody to mess with those tbh.

**Comment by 10Dozen** [comment]
`I don't really trust anybody to mess with those tbh.`
I'm agree, that's why i am asking for some sort of public API - to not screw up someone else settings by direct inject or function calls. Ofc, if it possible without re-writing entire cba settings component ;D
