### ISSUE TITLE
Donation: you might be interested in this function

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [CBATeam/CBA_A3#1119]
Hey! So I've made this function relying on CBA 's PFEH system, it creates a PFEH that will only run for as long as the provided condition is true and exit with provided exit code.
It might need some refinement to be up to CBA standards that's why I don't branch the git, just donate the code. If you feel it has some interest, feel free to use it /modify it / enhance it.
Code here:
https://pastebin.com/4s1P3PWV

**Comment by dedmen** [comment]
>that will only run for as long as the provided condition is true

CBA_fnc_waitUntilAndExecute combined with a `!` ?

**Comment by commy2** [comment]
I can see this being added to the wiki as an example usage for the PerFrameHandler.
But I don't think it is different enough to warrant its own function. This is essentially a framework build upon another framework. We would end up with more specialized code that has less generalized application, but still has to be maintained. And it has to be compiled when starting the game (although a single function makes no difference, it is a design choice that when applied consistently leads to slower game load times eventually).

**Comment by MisterHLunaticwraith** [comment]
Whatever you choose to do with it is fine by me. In essence it allows to do something like a while loop in unscheduled environment that's why I needed something like this, I've been using it in a few scripts and it does the job.

**Comment by commy2** [comment]
Keep open until I added it to the wiki.

**Comment by commy2** [comment]
https://github.com/CBATeam/CBA_A3/wiki/Per-Frame-Handlers
