### ISSUE TITLE
Keybinding: Unknown Code 327778

### ISSUE THREAD

**Issue by ViperMaul** [CBATeam/CBA_A3#113]
#### This was reported to me in a Skype PM but they do not know how to reproduce it. 

![2015-07-02_00001_2_zpsoga01hvs](https://cloud.githubusercontent.com/assets/345876/9278870/988a7f12-4268-11e5-8996-06bb9a92cce9.jpg)

#### If you have seen this before, perhaps you can give us a reproducible case for this so we can fix it.

**Comment by jokoho48** [comment]
this is if you use a Controller and press a Key there

**Comment by ViperMaul** [comment]
Can you recover from it by setting another key? or by hitting default button?

**Comment by jokoho48** [comment]
yes i you remove the controller than yes

**Comment by jokoho48** [comment]
to fix we need add 1. this keys to the allowed key: 
```16:27:50 "[Display #46,327680,false,false,false]" // A
16:28:04 "[Display #46,327681,false,false,false]" // B
16:28:35 "[Display #46,327682,false,false,false]" // X
16:28:49 "[Display #46,327683,false,false,false]" // Y
16:29:16 "[Display #46,327688,false,false,false]" // start
16:29:25 "[Display #46,327689,false,false,false]" // select
16:29:42 "[Display #46,327691,false,false,false]" // RB1
16:30:11 "[Display #46,327690,false,false,false]" // LB1
16:31:21 "[Display #46,327695,false,false,false]" // RB2 (Bumper)
16:31:39 "[Display #46,327694,false,false,false]" // LB2 (Bumper)
16:32:28 "[Display #46,327686,false,false,false]" // Controll Left
16:32:48 "[Display #46,327687,false,false,false]" // Controll Right
16:33:06 "[Display #46,327684,false,false,false]" // Controll Up
16:33:24 "[Display #46,327685,false,false,false]" // Controll Down```

and if one of this are use we must ignore then:
```
16:30:30 "[Display #46,327693,false,false,false]" // RT
16:30:53 "[Display #46,327692,false,false,false]" // LT
16:33:42 "[Display #46,327699,false,false,false]" // RS Up
16:34:01 "[Display #46,327703,false,false,false]" // RS Down
16:34:22 "[Display #46,327702,false,false,false]" // RS Left
16:34:36 "[Display #46,327698,false,false,false]" // RS Right
16:34:54 "[Display #46,327697,false,false,false]" // LS Up
16:35:08 "[Display #46,327701,false,false,false]" // LS Down
16:35:09 "[Display #46,327700,false,false,false]" // LS Right
16:35:10 "[Display #46,327696,false,false,false]" // LS Left```

2. Issue with deleteing Key Occludes if you assign a key they are unkown and than apply a secound that is unkown and than the key gets deleted

**Comment by ViperMaul** [comment]
Another reference to a similar issue: https://www.reddit.com/r/arma/comments/3kce45/im_having_a_serious_problem_with_configuring_my/

**Comment by jokoho48** [comment]
ok i dig the in it and it look like that the issue occludes if you press 2 keys in the same secound. i now try to fix it
