### ISSUE TITLE
Magazine wells 1.92 compatibility

### ISSUE THREAD

**Issue by DoomsdayIsClose** [CBATeam/CBA_A3#1132]
**Arma 3 Version:** `1.92` stable
**CBA Version:** `3.10.1` stable

**Mods:**
```
- CBA_A3
```

**Description:**
- Dynamic Magazine (Proxies) possible issues. i.e: For MX 6.5mm (sand) you cannot attach a 6.5mm black 30 round magazine. But without CBA loaded you can.

**Steps to reproduce:**
- Try loading a 6.5mm 30 round black magazine into the MX (sand) in Tanoa as a Blufor rifleman

**Where did the issue occur?**
- Editor (Singleplayer)

**Comment by commy2** [comment]
This is correct, they are currently incompatible.
Renamed the issue so it makes more sense years from now.

**Comment by dedmen** [comment]
>Dynamic Magazine (Proxies) possible issues.

No. What you are talking about are magazine wells which is a completely different thing.

**Comment by commy2** [comment]
"Dynamic magazines" is what they called it in the changelog. I think "dynamic magazines" is to mag wells as is Zeus to curator.
