### ISSUE TITLE
Donation: Custom Building Position

### ISSUE THREAD

**Issue by G3rrus** [CBATeam/CBA_A3#1136]
So I made this little custom building position, which is basically a small invisible object that can be placed down in the editor with one building position configured at its center.

-What does it do? It adds a small invisible disk object (much like a tiny invisible helipad) that has 1 building position at its center.

-How is this helpful? Well, it works together with scripts that utilize building positions. Its most obvious use would be extending the functionality of garrison and loot scripts. In those cases it would allow for additional building positions to be "added" to buildings that already have some preconfigured, or "adding" building positions to structures that don't have any (such as the bunker tower, used in the sample screenshots).

Sample Screenshots: (note that the disk is still visible in these screenshots as I hadn't configured the invisible texture at that point yet)

https://i.imgur.com/poaiquU.jpg
https://i.imgur.com/Sv51wP0.jpg

Source files can be found here: 

https://github.com/G3rrus/Custom-Building-Position

**Comment by commy2** [comment]
This is a clever idea.

Does it need the visible LODs for something or could that be made empty?

**Comment by G3rrus** [comment]
I honestly don't know, it might be possible to delete them but then that might have unintended consequences.

**Comment by commy2** [comment]
Maybe it needs the LOD, but one could delete all vertices. I will mess around with it tomorrow.

**Comment by G3rrus** [comment]
That would be great, as I merely had the idea and did the config, while I asked a friend from my unit if he would be so kind as to provide me with the necessary .p3d

**Comment by commy2** [comment]
#1138

**Comment by commy2** [comment]
Apparently the model is required for the object to snap to the surface of the bunker and terrain.

I replaced the empty texture with the Arma go to empty texture `a3\weapons_F\data\clear_empty.paa`.

**Comment by G3rrus** [comment]
Ah yes that makes sense, nice!

**Comment by 10Dozen** [comment]
Sorry, if i didn't get the implementation of this feature right, but can we have some custom CBA's `BIS_fnc_buildingPositions` function that will return building and related custom building positions in single array? May be useful for scripts to spawn/garrison units and used for CBA's ai scripts (e.g. ai/fnc_searchNearby.sqf). 

CBA's custom 'nearestBuilding' function will be usefull in this case too (to return only buildings, skipping custom positions).

**Comment by commy2** [comment]
>function that will return building positions and related custom building positions in single array?

What makes them _related_?

Think of these custom building positions to be "invisible micro buildings with a single AI building position at the center".

To return all custom building positions 200 meters around the player, you could use:
```sqf
nearestObjects [player, ["CBA_BuildingPos"], 200] apply {_x buildingPos 0}
```

**Comment by 10Dozen** [comment]
> What makes them related?
Placed inside 'main' building bounding box / synced in editor. 

IMHO, as a scripter i want to be able to treat house and custom position as single entity (e.g. to spawn garrisoned units). Also i may not be aware of does mission have these invisible micro buildings or not (e.g. ai behaviour mod) - using functions will be also helpful to prevent unexpected behavior in that case (e.g. random selected mostly custom position in single building instead of few houses across the village).

**Comment by bux** [comment]
use two functions and merge the results in one array ¯\\_(ツ)_/¯

**Comment by G3rrus** [comment]
I don't really see the problem with only the building position anyway. I mean most garrison scripts for example already have options if units should be garrisoned equally or building by building. In both cases I don't see how the custom building position would make distribution unequal by chance.

**Comment by commy2** [comment]
@10Dozen 
https://github.com/CBATeam/CBA_A3/pull/1138#issuecomment-490549062

**Comment by 10Dozen** [comment]
@commy2 
Thank you very much, sir!
