### ISSUE TITLE
Using CBA_fnc_removeItemCargo removes all vests of specified type, not the quantity asked

### ISSUE THREAD

**Issue by armazac** [CBATeam/CBA_A3#1153]
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** `3.11.2.190515` (stable)

**Mods:**
```
- CBA_A3
```

**Description:**
- Removing vests using CBA_fnc_removeItemCargo on crate will delete all the vests in that crate of that type, even if you only specify to delete 1

**Steps to reproduce:**
- Look at a container
- Run `[cursorObject,"V_PlateCarrier1_rgr",5] call CBA_fnc_addItemCargo`
- Open inventory, see 5 vests
- Run `[cursorObject,"V_PlateCarrier1_rgr",1] call CBA_fnc_removeItemCargo` 
- Open inventory, see no vests

**Where did the issue occur?**
- Dedicated

**RPT log file:**
N/A

**Comment by commy2** [comment]
Can confirm that this is bugged.

**Comment by jonpas** [comment]
@alganthe just confirmed for me last night. I will fix it soonish.
