### ISSUE TITLE
CBA Settings Code

### ISSUE THREAD

**Issue by MaddonutDev** [CBATeam/CBA_A3#1170]
Hi CBA,

This is a question not an issue,

I am very curious how you have made the settings menu allow server settings that can override clients and missions.

I have recently jumped into Arma coding my self and played around but I wish to do something similar with saving an array server side which all clients can access.

Looking into your script_components.hpp you use the
```
uiNamespace
```
namespace to save variables too. 
Looking on the BI Wiki it says these two things:

- Returns the global namespace attached to user interface.
- uiNamespace is persistent even when mission is changed on server.

from this I can only assume this namespace is still client side as only the client has a UI.

I know this probably is not the place to ask but even the slightest hint would help me a great deal.

Thanks in advance,

Maddonut

**Comment by TrainDoctor** [comment]
I would recommend the [ACE3 Slack server](https://slackin.ace3mod.com/), a far better place to ask these sort of questions.

**Comment by commy2** [comment]
Despite the name "ui namespace" and non-interface machines like dedicated servers and headless clients being unable to create CONTROL and DISPLAY types, all of them have an ui namespace that is created at game start, never cleared during the session (unlike mission namespace) and destroyed when the game is closed (unlike profile namespace). A better name that actually describes the purpose is "session namespace" - if it were up to me, that is how it would be named.

The ui namespace contains global variables, but that "global" refers to being "global" across all script instances of the local machine. The variables are not shared between clients. Variables that are truly "global" (as in have shared values in multiplayer) are called "public variables" instead. You can share public variables using `setVariable public` (`setVariable` with the third paramater "public flag" set to true), or using `publicVariable`.

The `publicVariable` command can only be used on the mission namespace. The `setVariable public` command can be used on the mission namespace as well as on certain object namespaces for types that are shared across the network (OBJECT, GROUP, probably more that are irrelevant). For simplicity and clarity I therefore suggest to never use `publicVariable`, but `setVariable` instead, as it is strictly more powerful.

The server's settings are stored on an OBJECT type namespace that is created using `CBA_fnc_createNamespace`.
https://github.com/CBATeam/CBA_A3/blob/master/addons/settings/initSettings.sqf#L15-L17
`CBA_fnc_createNamespace` for the creation of public namespaces creates a simple object OBJECT type, which is the lowest performance costing OBJECT type.

When a (server) setting is changed on the server, the setting value is stored on the server setting namespace.
https://github.com/CBATeam/CBA_A3/blob/master/addons/settings/fnc_set.sqf#L110-L111

This means that no namespace value actually is overwritten. All server settings are shared with all clients via the server setting namespace, but the clients still have their setting values stored on their local client setting namespace.

The actual overwriting just comes from comparing the associated priority values, which are set by checking those "overwrite client", "overwrite mission" checkboxes; and then deciding which namespace (client settings, mission settings, server settings) takes precedence. This means that this logic is entirely scripted and realized by sharing NUMBER types across the network on the "server namespace", which is just a public object namespace, and then looking for the bigger number.

The simplest way (in the CBA framework) to create a public namespace and to share a variable is therefore to do on the server:
```sqf
missionNamespace setVariable ["My_globalNamespace", true call CBA_fnc_createNamespace, true];
My_globalNamespace setVariable ["variable1", 127, true];
```
and then on the client(s):
```sqf
My_globalNamespace getVariable "variable1"
```

**Comment by MaddonutDev** [comment]
Thank you so much for the information!

Just to clarify then I can create a global namespace using the below commands:

```myObjectNamespaceName``` and ```My_globalNamespace``` being whatever name I wish.

```
objectnameSpace = createSimpleObject ["myObjectNamespaceName",[-1000, -1000, 0]];

missionNamespace setVariable ["My_globalNamespace", objectnameSpace, true];

My_globalNamespace setVariable ["variable1", 127, true];
```
Looking into ```createSimpleObject ``` it seems like it creates a physical object in the world hence why you set it position far of the map, so how does this persist between missions and server restarts as the CBA settings do?

Again I understand this probably is not the right place for this so thank you for the help you have given me so far and if you wish to close this without answering my questions I will understand!

**Comment by dedmen** [comment]
>so how does this persist between missions and server restarts as the CBA settings do?

It doesn't. But CBA settings are also stored in profileNamespace, or for mission settings in the missionfile itself.

**Comment by MaddonutDev** [comment]
So then in settings how do the server overridden settings get saved then ? because even if they are stored in the mission file and profileNameSpace which cleint do they use to load back into the object in the mission?

**Comment by dedmen** [comment]
>which cleint do they use to load back into the object in the mission?

None. The server has it's own profileNamespace, it's stored on the server.

**Comment by MaddonutDev** [comment]
> Thank you so much for the information!
> 
> Just to clarify then I can create a global namespace using the below commands:
> 
> `myObjectNamespaceName` and `My_globalNamespace` being whatever name I wish.
> 
> ```
> objectnameSpace = createSimpleObject ["myObjectNamespaceName",[-1000, -1000, 0]];
> 
> missionNamespace setVariable ["My_globalNamespace", objectnameSpace, true];
> 
> My_globalNamespace setVariable ["variable1", 127, true];
> ```
> 
> Looking into `createSimpleObject ` it seems like it creates a physical object in the world hence why you set it position far of the map, so how does this persist between missions and server restarts as the CBA settings do?
> 
> Again I understand this probably is not the right place for this so thank you for the help you have given me so far and if you wish to close this without answering my questions I will understand!

So how does it save it to the profileNameSpace on the sever instead of the client? Because as far as I understand the code above only saves it in the object as well as the missionNameSpace.

**Comment by dedmen** [comment]
>So how does it save it to the profileNameSpace on the sever instead of the client?
if you call "profileNamespace" on the server, you get the servers profile namespace. So just run the code on the server.

>My_globalNamespace setVariable ["variable1", 127, true];

Set's the variable globally, the server can read it, and save a copy into it's profileNamespace.

**Comment by MaddonutDev** [comment]
So I guess the way to do it is via the way Commy2 said with the object to allow all users (including server) to access the public variable then before the mission ends have the server save a copy of the object, then when the new mission is initialised have it recreate the object with the saved version of it so everyone can access the variables again?

If the above is correct could you give me an example how the code of this would look?

I understand the principle behind it but how for example the server would know when the mission ends and to save a copy of the object/which file to put the code in for when the mission starts and it needs to recreate the object.

if you could just give me an example of this I can play around with it tomorrow.

**Comment by MaddonutDev** [comment]
Hi All,

I played around with this a bit tonight and couldn't get it working here is what I did.

I ran a Multiplayer server from the Eden editor, I created a button to run the fn_SetVar.sqf and it hinted the variable out to me. The variable always returned null, However when I got it to hint the ```_thePublicVariable``` it returned null-object so it clearly was retrieving the object correctly.

I tried quite a few things for example just trying to save and read from the object with ```getVariable``` and ```SetVariable``` but that did not work either.

Am I doing something stupid?

```
//initServer.sqf
objectnameSpace = createSimpleObject ["myObjectNamespaceName",[-1000, -1000, 0]];
missionNamespace setVariable ["My_globalNamespace", objectnameSpace, true];
objectnameSpace setVariable ["variable1", 127, true];
```
```
//fn_SetVar.sqf
_thePublicVariable = missionNamespace getVariable "My_globalNamespace";
_thePublicVariable1 = _thePublicVariable getVariable "variable1";

hint format["%1",_thePublicVariable1];
[west, "HQ"] sidechat format["%1",_thePublicVariable1];
```

**Comment by commy2** [comment]
I fail to see how this is relevant to CBA at all. There are Slacks and Discords and forums where you can get scripting help.

**Comment by MaddonutDev** [comment]
The reason I came to CBA is because CBA do it well and from the amount of googling I have done I could not find another way to persist settings through server restarts.

as I previously said thank you for the help as I know this is not a place for asking such questions, I will close the ticket now.

Thanks again.

**Comment by jonpas** [comment]
It's not that hard to join ACE Slack as you were told above.
