### ISSUE TITLE
Files missing from addons folder in the new release

### ISSUE THREAD

**Issue by MunchkinSlayer** [CBATeam/CBA_A3#1178]
**Arma 3 Version:** `1.92.145639` (stable)
**CBA Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
```

**Description:**
- cba_main_a3.pbo is missing from the new update. On ArmA 3 startup and when joining my server I get a warning about the file being missing.
I got my server to run fine for now by using the old cba_main_a3.pbo from the previous release.

**Steps to reproduce:**
- Simply run ArmA 3 with CBA 3.12.0 enabled.

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer

**Comment by ViperMaul** [comment]
Thank you @MunchkinSlayer 
Looks like I missed something very critical here. 
My apologies to all the inconvenience I caused. 
Allow me to fix.

**Comment by jonpas** [comment]
Thank you for the quick report! File is indeed missing for some reason, looks like from the build process.

It will be fixed ASAP.

**Comment by MGTDB** [comment]
Thanks guys for the quick work
[https://media.discordapp.net/attachments/104163051707572224/598300329947168784/Clipboard01.jpg](url)

**Comment by MunchkinSlayer** [comment]
No problem at all, I just happened to be setting up my server when the update dropped. 
Appreciate the quick response!

**Comment by MGTDB** [comment]
The error

WARNING: cba requires cba_main_a3 (@CBA_A3) at version [1,0,0] (or higher). You have none.

**Comment by ReDBaroN1** [comment]
Guys sorry to be a pain but, do you know roughly how long to rectify? Clients have auto updated so, we don't even have the option to run the previous version. Manually adding the file leads to sig kicks and BE initialisation errors/kicks so, we're all on down time atm....

**Comment by ViperMaul** [comment]
@MunchkinSlayer 
STEAM updated. 
-or-
Re-download from the same GitHub Release

Give me a thumbs up from the community so I can have my triple confirmation this time.

**Comment by ReDBaroN1** [comment]
testing now

**Comment by MunchkinSlayer** [comment]
Can you confirm adding the file was the only change on the reupload? I'd rather not upload the entire zip again to my server. Other than that, working great!

**Comment by ReDBaroN1** [comment]
All good here. Thanks for the quick turnaround.

**Comment by jonpas** [comment]
To be sure, reupload the key and signatures as well. To be extra sure, upload the entire thing.

**Comment by delta998** [comment]
> * Falta cba_main_a3.pbo en la nueva actualización. Al iniciar ArmA 3

hola necesito ayuda por favor no entiendo como solucionar ese error ;(

**Comment by synixebrett** [comment]
Create a new issue with more details of your error, in English. This issue is not an error you can be experiencing.
