### ISSUE TITLE
Game freezing when hosting local server

### ISSUE THREAD

**Issue by CDouggy** [CBATeam/CBA_A3#1180]
**Arma 3 Version:** stable
**CBA Version:** `3.12.x` (stable / dev + commit hash)

**Mods:**

- CBA_A3
RHSUSAF
RHSGREF
RHSRUSF
RHSSAF 
CUP TERRAINS 
CUP MAPS

**Description:**
When attempting to Host a server, freezes and unresponsive. 
error code is 0x00000001 -UNABLE_TO_INIT_DXGI

**Steps to reproduce:**
load game with CBA_a3 v 3.12 press "host server" game then freezes on my computer 

**Where did the issue occur?**
Self-Hosted Multiplayer

**RPT log file:**
[ArmaReport_Log_20190714T152657_Ciara.zip](https://github.com/CBATeam/CBA_A3/files/3407039/ArmaReport_Log_20190714T152657_Ciara.zip)
[ArmaReport_Log_20190714T152657_Ciara.zip](https://github.com/CBATeam/CBA_A3/files/3407042/ArmaReport_Log_20190714T152657_Ciara.zip)

**Comment by commy2** [comment]
What about a server with only CBA_A3?
That is what this issue tracker is all about after all.

**Comment by commy2** [comment]
The RPT shows:
```
C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CUP Terrains - Core;
C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CUP Terrains - Maps;
C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CUP Terrains - CWA;
C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@RHSUSAF;
C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@RHSAFRF;
C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@RHSSAF;
C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@RHSGREF;
C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@NATO_Rus_Vehicle;
C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CBA_A3;
C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CUP Weapons;
C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@RKSL Studios- Attachments v3.01;
C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@Spearpoint- Cor [cut off]
```
so there is a different mod set than reported.

**Comment by commy2** [comment]
```
16:14:26 Warning Message: No entry 'bin\config.bin/CfgVehicles/O_Yugoslavia_UAZ_3151_Open_01/Turrets/CargoTurret_01.maxHorizontalRotSpeed'.
```
Looks to me like this config is missing from the modset, but is placed in the mission. You cannot do that, you have to load all addons that the mission depends on.

This class also has a terrible classnames. It mimics the vanilla classnames, but it is not a vanilla vehicle, so this class is using untagged identifiers in global space. It is a shit mod I can tell already.

Has nothing to do with CBA_A3. Close?

**Comment by CDouggy** [comment]
[ArmaReport_Log_20190718T174533_Ciara.zip](https://github.com/CBATeam/CBA_A3/files/3407764/ArmaReport_Log_20190718T174533_Ciara.zip)

**Comment by CDouggy** [comment]
Any mod i try use its the same thing it all leads back to CBA_A3, i rolled back to V 3.10.1 and it was functional. I've been trying to fix the problem myself but I'm no expert. thanks for looking at this.

**Comment by CDouggy** [comment]
I'm not the only one with this issue a few others have said it in the steam workshop.

**Comment by CDouggy** [comment]
Only CBA doesn't work either. I didn't create any of the missions i just wanted to try them. 
[ArmaReport_Log_20190718T174533_Ciara.zip](https://github.com/CBATeam/CBA_A3/files/3407856/ArmaReport_Log_20190718T174533_Ciara.zip)

this is when i launched only CBA.
if I included the wrong report let me know.

thanks

**Comment by commy2** [comment]
Like says "Not Found"

**Comment by CDouggy** [comment]
[ArmaReport_Log_20190718T181748_Ciara.zip](https://github.com/CBATeam/CBA_A3/files/3407884/ArmaReport_Log_20190718T181748_Ciara.zip)

heres a new one.

**Comment by commy2** [comment]
```
19:16:48 [12766,80.966,0,"XEH: PostInit started. MISSIONINIT: missionName=tanoa_intro1, missionVersion=53, worldName=tanoa, isMultiplayer=false, isServer=true, isDedicated=false, CBA_isHeadlessClient=false, hasInterface=true, didJIP=false"]
19:16:48 [12766,80.967,0,"CBA_VERSIONING: cba=3.12.0.190708, "]
19:16:48 [12766,80.968,0,"XEH: PostInit finished."]
19:16:55 Loading movesType CfgMovesBird
19:16:55 Reading cached action map data
```
End of file.

You never tried hosting a server or connecting to one.

You posted multiple RPT's, so I used to one with this timestamp:
`Current time:  2019/07/18 16:36:43`

**Comment by CDouggy** [comment]
because I'm unable to get that far. it just freezes at that point.

**Comment by CDouggy** [comment]
If I do not load CBA_A3 i can host servers.

**Comment by CDouggy** [comment]
[ArmaReport_Log_20190718T182502_Ciara.zip](https://github.com/CBATeam/CBA_A3/files/3407927/ArmaReport_Log_20190718T182502_Ciara.zip)

I left this one running for 5 minutes, on the Host server screen after pressing "host server" once i do that it becomes unresponsive.

**Comment by commy2** [comment]
Try disabling battle eye, remove -beservice

**Comment by CDouggy** [comment]
will do.

**Comment by CDouggy** [comment]
same thing. ceases after pressing "host server"

[ArmaReport_Log_20190718T183805_Ciara.zip](https://github.com/CBATeam/CBA_A3/files/3407966/ArmaReport_Log_20190718T183805_Ciara.zip)

**Comment by commy2** [comment]
Cannot reproduce.

![https://i.imgur.com/Ud9fvE9.png](https://i.imgur.com/Ud9fvE9.png)
![https://i.imgur.com/qBv22FU.png](https://i.imgur.com/qBv22FU.png)
![https://i.imgur.com/jhySjkg.png](https://i.imgur.com/jhySjkg.png)
![https://i.imgur.com/PdmlQkJ.png](https://i.imgur.com/PdmlQkJ.png)

Try deleting your multiplayer mission stash. Backup ofc.

**Comment by CDouggy** [comment]
do you know where I can find the stash?

**Comment by commy2** [comment]
`"C:\Arma 3\MPMissions"`
and
`"C:\Users\admin\Documents\Arma 3 - Other Profiles\commy2\mpmissions"`
Where `C:\Arma 3` is installation path and `admin` is Windows profile name, and commy2 is game profile name.

**Comment by CDouggy** [comment]
thanks, but it didn't work.

**Comment by commy2** [comment]
Then I can't reproduce. Works everything here.

**Comment by CDouggy** [comment]
right now I'm deleting everything and will do a reinstall, download CBA and let you know the result.

**Comment by CDouggy** [comment]
deleting everything, including document files, and reinstalling worked. 
Thanks for the help.
