### ISSUE TITLE
CBA JR

### ISSUE THREAD

**Issue by topden** [CBATeam/CBA_A3#1187]
**Arma 3 Version:**1.94
**CBA Version:** CBA_A3 v3.12.0.190708

**Mods:**
rhs+cba

**Description:**

Hello. Is it possible to finish somehow the compatibility of the RHS sights and silencers for vanilla weapons, for example AK12? Now I can hang a bipod and a flashlight on the ak12, but there is no choice of RHS sights.  
http://joxi.ru/nAyJv5KHg59PDr
http://joxi.ru/xAeBg3MCRBMNgr
http://joxi.ru/n2YXgExCbOkEpm

Although for another weapon the choice is shown. for example for ADR97
http://joxi.ru/8AnbE8qTzVNOPA
or CAR95 or etc. http://joxi.ru/BA0G5wohMz1WJ2

sorry for my google explanations, but i hope you understand what i mean

**Comment by commy2** [comment]
RHS has to adjust this in their configs. BI changed the attachment base class from `asdg_OpticRail1913` from CBA_A3 to `CowsSlot_Rail` from Enoch. RHS has to make their attachments compatible to *both* now.

Can't be changed in CBA_A3, must be done by RHS. Close?

**Comment by commy2** [comment]
Example:
```cpp
class asdg_SlotInfo;
class asdg_OpticRail: asdg_SlotInfo {};
class asdg_OpticRail1913: asdg_OpticRail {
    class compatibleItems {
        My_OpticClass = 1;
    };
};

class CowsSlot;
class CowsSlot_Rail: CowsSlot {
    class compatibleItems {
        My_OpticClass = 1;
    };
};
```

**Comment by topden** [comment]
ok. thx for answer
