### ISSUE TITLE
New Line Issue in Documentation at Authors

### ISSUE THREAD

**Issue by jokoho48** [CBATeam/CBA_A3#119]
as example: http://cbateam.github.io/CBA_A3/docs/files/strings/fnc_capitalize-sqf.html

**Comment by Killswitch00** [comment]
Explain in sufficient detail what the problem is.

**Comment by jokoho48** [comment]
i mean that there are 2 authors behind each other without any indication that they are 2

**Comment by Killswitch00** [comment]
That appears to be how the documentation generation system works. I have changed the files to list the authors on one line, separated by a comma sign.
