### ISSUE TITLE
Feature Request: ExtensionCallback helpers

### ISSUE THREAD

**Issue by synixebrett** [CBATeam/CBA_A3#1196]
With the addition of Extension Callbacks in 1.95 it would be nice to have a set of CBA helper functions exposed to extensions to reduce rewritten code.

Each event has a name, function, and args.

There could be things like
`cba` `hint`
`cba` `notify`
and more that would make it easy to use common functions from extensions without needing to re-implement them for your addon.

**Comment by dedmen** [comment]
Also we could just have a single eventhandler for extension callback in CBA. And CBA then redistributes to registered handlers.
That way people don't need to pay the eventhandler recompilation cost, though once script cache comes back that might not be worth it.

**Comment by commy2** [comment]
Explain how this would work. I don't see it.

**Comment by synixebrett** [comment]
Rather than every mod that wants to use an extension implementing the event in Arma, CBA would have a bunch of common one already implemented.

https://community.bistudio.com/wiki/Arma_3:_Event_Handlers/addMissionEventHandler#ExtensionCallback

So there could be one setup for `cba` `hint`, then if an extension wants to call the hint can just use the one from CBA that is sitting there

**Comment by commy2** [comment]
Why would an extension show a hint?

The only benefit I see here is referencing multiple extensions by local namespace instead of walking over multiple attached scripts all checking the _name with ==.

But is this really necessary? What functionality does this really provide that you wouldn't have without CBA? I don't think the detriment (effort to implement, responsibility for maintenance) proportionate to the benefit we get from having this.

**Comment by dedmen** [comment]
>So there could be one setup for cba hint, then if an extension wants to call the hint command they can just use the one from CBA that is sitting there

Wouldn't it be more sensible to just add a single handler that is able to fire a local/global CBA event?

**Comment by commy2** [comment]
Doubt the overhead you add by this is worth anything. You still need to recompile the event script, so you're worse off with one extension, about the same with two or three, and maybe better starting with four.

SQF overhead is a lot, so I estimate the command required to call the event are worth at least 3 recompiles, possibly more.
