### ISSUE TITLE
Contact DLC issue: SIMCOM Adapter cannot be attached to weapons

### ISSUE THREAD

**Issue by leopard20** [CBATeam/CBA_A3#1198]
**Arma 3 Version:** `1.94` (stable)
**CBA Version:** `3.12.0` (stable)

**Description:**
The first mission of Contact DLC has some problem with CBA. Apparently, the item "SIMCOM Adapter" (muzzle_tma_65) cannot be attached to the weapon, and is not added to the player's inventory either!

**Comment by commy2** [comment]
Was fixed in #1184. Just waiting for a release...

**Comment by commy2** [comment]
Sorry, https://github.com/CBATeam/CBA_A3/pull/1181/files#diff-dc686a1ca51fe1aa9980de2147e04f54R217 I meant.
