### ISSUE TITLE
Custom Key binds won't work.

### ISSUE THREAD

**Issue by Bikaaa** [CBATeam/CBA_A3#1204]
**Arma 3 Version:** `1.94` stable
**CBA Version:** `3.12.0` stable

**Mods:**
```
- CBA_A3
```

**Description:**
Keybinds button on click won't work or do anything whatever I do , but it add the buttons in the controls. I also tried your debug console try with the display ( the Ctrl + T) and it didn't do anything even though it created the button in the control
**Steps to reproduce:**

**Where did the issue occur?**
- Self-Hosted Multiplayer

**RPT log file:**
- https://sqfbin.com/obigoxupeyezahocayer

**Comment by commy2** [comment]
In OP you list as mods only CBA_A3
But the RPT says `-mod=@Backend;@extDB3;@CBA_A3;@A3AL`

>Keybinds button on click 

What is a "keybinds button on click"? You click on buttons with your mouse. For keybinds, you're supposed to press a button on your keyboard.

>I also tried your debug console try with the display ( the Ctrl + T) and it didn't do anything even though it created the button in the control

What?

I don't understand what you're doing and what you're talking about.

**Comment by Bikaaa** [comment]
The other mods are server side for the mission folder. 

What I am trying to do is using this

[["American Life","Menus"],"interaction", "Interaction Menu", {[] call A3AL_fnc_LoadInteraction}, "", [DIK_LWIN, [false, false, false]]] call CBA_fnc_addKeybind;

Now when I press the LWIN nothing happens , However in the control addons I can see the button is created in the configure addons.

So I tried your code from the other issue : https://github.com/CBATeam/CBA_A3/issues/934

And when I press CTRL + T nothing happens also after executing it in the Debug console

**Comment by Bikaaa** [comment]
> The other mods are server side for the mission folder.
> 
> What I am trying to do is using this
> 
> [["American Life","Menus"],"interaction", "Interaction Menu", {[] call A3AL_fnc_LoadInteraction}, "", [DIK_LWIN, [false, false, false]]] call CBA_fnc_addKeybind;
> 
> Now when I press the LWIN nothing happens , However in the control addons I can see the button is created in the configure addons.
> 
> So I tried your code from the other issue : #934
> 
> And when I press CTRL + T nothing happens also after executing it in the Debug console



> The other mods are server side for the mission folder.
> 
> What I am trying to do is using this
> 
> [["American Life","Menus"],"interaction", "Interaction Menu", {[] call A3AL_fnc_LoadInteraction}, "", [DIK_LWIN, [false, false, false]]] call CBA_fnc_addKeybind;
> 
> Now when I press the LWIN nothing happens , However in the control addons I can see the button is created in the configure addons.
> 
> So I tried your code from the other issue : #934
> 
> And when I press CTRL + T nothing happens also after executing it in the Debug console

**Comment by commy2** [comment]
Ah, ok.

- It may be a problem with `A3AL_fnc_LoadInteraction`, so test with debug function first (like systemChat or diag_log).
- It could be that you never included a header that defines DIK_LWIN, thus the key is unassigned. Try rebinding the key from the menu.
- It could be that you are using a keyboard with gaming driver that disabled the windows key., again try rebinding.
- The second argument, the key action id has to be unique. "interaction" is too generic and may be used by you or someone else already. Use something with tag like `Bikaaa_interactionMenu` instead.

```sqf
[
    ["American Life", "Menus"],
    "Bikaaa_interactionMenu",
    "Interaction Menu", {
        systemChat str [_this];
    }, "", [DIK_LWIN, [false, false, false]]
] call CBA_fnc_addKeybind;
```

**Comment by Bikaaa** [comment]
1- A3AL_fnc_LoadInteraction, works fine when I call it from the debug console
2- I have this:  #include "\a3\editor_f\Data\Scripts\dikCodes.h" in the file header
3-Tried that
4- Tried that too , still doesn't work.

**Comment by commy2** [comment]
So, did the systemChat print anything?

**Comment by Bikaaa** [comment]
Nop

**Comment by commy2** [comment]
Try this on an empty mission with only CBA and no other mods.

**Comment by Bikaaa** [comment]
Fixed , I guess this is the way I was calling them ,

call compile preprocessFileLineNumbers , wouldn't work or ?

Cause when I placed that in the init.sqf it started working and when I start calling and putting this on serverside it won't work

**Comment by Bikaaa** [comment]
Fixed , It was mix of lack of sleep and a bit in me being retard

**Comment by commy2** [comment]
No problem. You sounded really tried in the opening post.
