### ISSUE TITLE
unquoted string warning

### ISSUE THREAD

**Issue by s-trooper** [CBATeam/CBA_A3#1206]
**Arma 3 Version:** `latest` (stable)
**CBA Version:** `latest` (stable)

**Mods:**
```
- CBA_A3
```

**Description:**
Sorry to bother you with such a minor question but i am a beginner and would like be sure that things i do, are correct.

I've got i warning about "unquoted string" in config.cpp compiled with armake2. My issue is more sort of question. Are you sure you macro ´´´VERSION_CONFIG´´´ definition/usage  is correct? if so this would a armake2 issue not cba ...

```
In file addons\main\config.cpp:11: warning: String value "0.1.0.0" is not quoted properly. [unquoted-string]
```
addons\main\config.cp:
```
class CfgPatches {
    class ADDON {
        name = CSTRING(COMPONENT);
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {};
        author = "test";
        VERSION_CONFIG;
    };
};
````
**Steps to reproduce:**
1. hemtt create
...
2. hemtt build

**Where did the issue occur?**
using hemtt / armake2 toolset.

**RPT log file:**

**Comment by jonpas** [comment]
Yeah, don't worry about it, game will quote it. This is fixed on HEMTT branch, I completely forgot to pull it in seperately again.

**Comment by s-trooper** [comment]
Sounds great, thank you for your work.

**Comment by commy2** [comment]
Close when PR is merged.
