### ISSUE TITLE
Game freezing when hosting local server with large ui scale

### ISSUE THREAD

**Issue by siredgarhussein** [CBATeam/CBA_A3#1218]
**Arma 3 Version:** `1.94` (stable)
**CBA Version:** `3.12.1` (stable)

**Mods:**
```
- CBA_A3
```

**Description:**
- Cannot host a server when CBA (steam workshop version) is loaded. Game freezes and subsequently crashes.

**Steps to reproduce:**
- load cba
- host an internet server with upnp enabled

**Where did the issue occur?**
- Self-Hosted Multiplayer

**RPT log file:**
- https://pastebin.com/7BVbNxfY

**Comment by dedmen** [comment]
>- load cba
>- host an internet server with upnp enabled

Can't reproduce.

`-cpuCount=6 -exThreads=7 -enableHT -maxmem=6000 -maxvram=4000` These start parameters are all nonsense, you probably want to remove these.

**Comment by siredgarhussein** [comment]
still crashes

**Comment by commy2** [comment]
When does the game freeze?

**Comment by siredgarhussein** [comment]
as soon as you host the server on the loading screen. It stays frozen for a while 5-10 minutes, then it crashes. you can't alt tab while it's frozen.

**Comment by commy2** [comment]
So same as https://github.com/CBATeam/CBA_A3/issues/1180?

**Comment by siredgarhussein** [comment]
yes, but I reinstalled cba, did nothing.

**Comment by commy2** [comment]
The guy reinstalled the whole game as far as I can tell, not just a mod.

**Comment by siredgarhussein** [comment]
ill try that

**Comment by commy2** [comment]
Hoping for the best.

**Comment by commy2** [comment]
Did it help?

**Comment by siredgarhussein** [comment]
nope, still crashes

**Comment by commy2** [comment]
Make a backup of your profile folders. Delete them. Try again.

They are found here by default:
```
"C:\Users\<WINDOWS_USER_NAME>\Documents\Arma 3"
"C:\Users\<WINDOWS_USER_NAME>\Documents\Arma 3 - Other Profiles"
```

**Comment by siredgarhussein** [comment]
I found out why it happened, it's because my ui size was set to very large, it doesn't crash when it's set to normal.

**Comment by commy2** [comment]
Interesting. I will try to reproduce! What screen size and pixel resolution do you use?

**Comment by commy2** [comment]
Thanks, will be fixed in next release.
