### ISSUE TITLE
events added with CBA_fnc_addClassEventHandler ran twice

### ISSUE THREAD

**Issue by mgkid3310** [CBATeam/CBA_A3#1220]
**Arma 3 Version:** `1.94` (stable / rc / dev / **profiling**)
**CBA Version:** `3.12.1` (**stable** / dev + commit hash)

**Mods:**
```
- CBA_A3
- ACE3
- FIR aircrafts (F-16 / F-15 / A-10)
- https://steamcommunity.com/sharedfiles/filedetails/?id=938711359
- and a bunch more
- local test file (https://drive.google.com/open?id=1nICkh7NcKWWEZXWExsHsOVUL7cmT7IY0)
```

**Description:**
- Events added with CBA_fnc_addClassEventHandler is ran twice after postInit is done. "Init" and "Fired" has been confirmed with this bug.
Interesting thing is that this bug doesn't happen when only the CBA is loaded, but with multiple mods including ACE, "Init" and "Fired" events fires twice. I've confirmed the "cba_xeh_Init:Planes" config to see if the postInit itself is ran twice, but no (https://pastebin.com/BCzBAQ8Q).

- One noticeable thing is that for Init event, only the Init events occured after the "postInit Done" message happens twice(https://pastebin.com/c5QCZ7Em L2611-L2645). And only when this happens, the "Fired" event also fires twice each time. One mysterious behavior is that after the game start and clock starts ticking, the duplicated "Init" event does not happen for new objects, but the "Fire" event duplication still happens. Even more mysterious thing is that if I add a "Fired" event with CBA_fnc_addClassEventHandler after the game start, although there are two events I added (one from postInit and one after game start) the event is fired three times (https://pastebin.com/MsRDN2Hn L2705-L2711). I confirmed that there are only two events added to "cba_xeh_Fired:Air" (`[[{diag_log format ["orbis_fired: %1", time]; _this spawn orbis_airforce_fnc_eventWeaponFire},true,[]],[{diag_log format ["orbis_fired: %1", time]; _this spawn orbis_airforce_fnc_eventWeaponFire},true,[]]]`)

- I'm suspecting the Init event with `_applyInitRetroactively` option "true" was ran too late due to many objects/mod that the last item in "cba_xeh_Init:Planes" (https://pastebin.com/BCzBAQ8Q L272) was ran after the postInit process is done, and was duplicated because of that `_applyInitRetroactively` option. Not sure about "Fired" event, but might have some kind of relationships.

**Steps to reproduce:**
- Load a bunch of mods including the local test mod, place objects as in a typical mission file and launch.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / **Singleplayer** / **Editor (Singleplayer)** / Editor (Multiplayer) / Virtual Arsenal

**RPT log file:**
- https://pastebin.com/18vTmk9q

**Comment by commy2** [comment]
Can you upload this "local test mod"?

**Comment by commy2** [comment]
Your example addon does not use the `_applyInitRetroactively` flag.
I am confused which PR belongs to which script. Are you using the events on XEH incompatible classes?

**Comment by mgkid3310** [comment]
Ah sorry I forgot to mention, the `_applyInitRetroactively` option is from AWESome (https://github.com/mgkid3310/AWESome/blob/master/addons/aerodynamics/XEH_postInit.sqf). I've tested with a line to log when the Init script is ran.
"Fired" event handling is from [here](https://drive.google.com/open?id=1RjPe-Hzuk3oxHIPRlLt9AYz4gPFlxjQP), at the postInit.

**Comment by commy2** [comment]
What does this report:
```sqf
[cba_xeh_fallbackRunning, uiNamespace getVariable "cba_xeh_fallbackRunning"]
```

**Comment by commy2** [comment]
Idk what you did, but you should probably just move all addClassEventHandler to preInit, drop the retroactively flag (as it is pointless in preInit) and also use InitPost instead of Init, as BI's Init event has some limitations with setting variables and other stuff over the network.

**Comment by mgkid3310** [comment]
Does working with behicle mass have no problem when ran on preInit? I prefered running code after the object was initialized.

Didn't know about the InitPost, does it have same parameters but just a difference in name?

**Comment by mgkid3310** [comment]
> What does this report:
> 
> ```sqf
> [cba_xeh_fallbackRunning, uiNamespace getVariable "cba_xeh_fallbackRunning"]
> ```

Will test and post here as soon as I get home

**Comment by mgkid3310** [comment]
> > What does this report:
> > ```sqf
> > [cba_xeh_fallbackRunning, uiNamespace getVariable "cba_xeh_fallbackRunning"]
> > ```
> 
> Will test and post here as soon as I get home

returns `[true,<null>]`

**Comment by commy2** [comment]
>Does working with behicle mass have no problem when ran on preInit? I prefered running code after the object was initialized.

You can't work with vehicles before they are created, obviously.
The Init(Post) event handler is executed when the after the vehicle was created, no matter when you added that event handler.
It's just that there is no need to fiddle with the apply retroactively flag when you add the event handler to the class before any object is created.

**Comment by commy2** [comment]
Feel free to reply if anything concrete surfaces. This does not happen with CBA, ACE and BWA3.
