### ISSUE TITLE
Problem with Running Mod on Dedicated Server

### ISSUE THREAD

**Issue by ComfyCozy** [CBATeam/CBA_A3#1230]
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
-ACE3
_Make sure to reproduce the issue with only CBA on a newly created mission!_

**Description:**
My friend and I are trying to run a server with cba and ace on it and the mods work fine when on single player but as soon as we try to get them to work on the server it does not work,  We followed the steps on the official arma 3 website to carry out the server.

**Steps to reproduce:**
- Go to ...
- Click ...
- See ...

**Expected behavior:**

**Where did the issue occur?**
- Dedicated 

**Log Files:**

**Additional context:**
Just wondering if anyone has general guesses or explanations about how to (normally) get the game to recognize the mods are present because it feels as though we have done something wrong

**Screenshots:**

**Comment by commy2** [comment]
This is an issue tracker and not a support forum. You're better of asking this on the BI forums. It has nothing to do with CBA.

**Comment by dedmen** [comment]
Just a crosspost from BIF.
https://forums.bohemia.net/forums/topic/225526-server-issues-with-mods-and-administration/
As we all know if you spam your issue everywhere, you're likely to get more help.
