### ISSUE TITLE
cba optics and using Arsenal in Zeus don't return camera to its original position

### ISSUE THREAD

**Issue by bux** [CBATeam/CBA_A3#1234]
**Mods (complete and add to the following information):**
- **Arma 3:** stable
- **CBA:** `3.12.2`
- **BWMod:** stable

**Description:**
Redirected here by @commy2 
When adding BWMod to the mod list closing the Zeus Arsenal doesn't return the camera to the position when using the Arsenal module on an editable unit but to the first person view of either the unit one is working on or the player unit.

**Steps to reproduce:**
- Add player to a mission
- Add game master module and sync to player
- Start mission
- Open Zeus and place a new unit
- Use the Arsenal module to open Arsenal of newly placed unit
- Close the Arsenal

**Expected behavior:**
Camera returns to the last position where one opened the Zeus Arsenal instead of first person view of a unit

**Where did the issue occur?**
- Editor SP

**Log Files:**
https://pastebin.com/Uddqdx1c

**Additional context:**

**Screenshots:**

**Comment by Blutze** [comment]
Does NOT replicate with [RKSL Attachments](https://steamcommunity.com/sharedfiles/filedetails/?id=1661066023) instead of BWMod, so just getting scripted optics to init is not enough. Maybe the Brits are doing something else janky, or there are remnants of the old BWMod-only implementation.

**Comment by commy2** [comment]
Zeus Arsenal.
What about a regular Mission Arsenal?
What about the 3den Arsenal?
What about the Arsenal Mission from main menu?

**Comment by Blutze** [comment]
> What about a regular Mission Arsenal?
> What about the 3den Arsenal?
> What about the Arsenal Mission from main menu?

Those do not have this issue.

Just remembered I still have [this](https://gist.github.com/Blutze/ac4c972111676349636e039dfaf9a92c). Pay attention to the date and versions, this is before scripted optics got ported to CBA I think (all three mods were Steam Workshop downloads, up to date at that time).

**Comment by bux** [comment]
Any more info needed?

**Comment by commy2** [comment]
No, I just need to find the time to look at it.

**Comment by commy2** [comment]
(Mostly) fixed in a commit that will appear here: https://git.koffeinflummi.de/bwmod-team/bwa3-public/commits/master

**Comment by commy2** [comment]
https://git.koffeinflummi.de/bwmod-team/bwa3-public/commit/f93693a62948018b806586e1df81c90daad829c4
