### ISSUE TITLE
Filtered getUnitLoadout

### ISSUE THREAD

**Issue by synixebrett** [CBATeam/CBA_A3#1236]
**Is your feature request related to a problem?**
Some mods (TFAR, ACRE, Unique Maps) use an ID system to track individual items. This will cause issues with `getUnitLoadout` and `setUnitLoadout`.

**Solution you'd like:**
`CBA_fnc_getUnitLoadout` that is a drop in replacement for its vanilla counterpart. Also create `CBA_fnc_addUnitLoadoutFilter` and `CBA_fnc_removeUnitLoadoutFilter` that take code as a parameter, that code takes a `getUnitLoadout` array and must return a `getUnitLoadout` array. The code will be used to replace any ID items with their base version.

**Additional context:**
[ACRE Example](https://github.com/IDI-Systems/acre2/pull/848/files#diff-b772f408a03abd22c2dab22d1dfc5ba2)

**Comment by commy2** [comment]
Idea:
CBA_fnc_generalizeLoadout
- walks through all items and removes ids

```sqf
CBA_fnc_setUnitLoadout = {
    params ["_unit", "_loadout"];
    _loadout = _loadout call CBA_fnc_generalizeLoadout;
    _unit setLoadout _loadout;
};
```
```sqf
CBA_fnc_getUnitLoadout = {
    params ["_unit"];
    getUnitLoadout _unit call CBA_fnc_generalizeLoadout;
};
```

Question is how it is supposed to know what is a derived item. Would need some config entry pointing to the correct class.
Also, this reminds one of baseWeapon. Should it replace weapons with baseWeapon? Can we recycle baseWeapon for this?

**Comment by synixebrett** [comment]
I like the addition of generalizeLoadout so it can be used without directly affecting a unit, I hadn't considered that.

I do still think it should be using code from mods however, and not doing it automatically.

**Comment by dedmen** [comment]
> Question is how it is supposed to know what is a derived item.
We have ACE Arsenal config entries for that. Might be worth adding a filter for that within ACE?
