### ISSUE TITLE
cba_Settings.sqf stopped working on dedicated server after last ARMA 3 update.

### ISSUE THREAD

**Issue by WarriorJMD** [CBATeam/CBA_A3#1255]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.12.2` [e.g. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA on a newly created mission!_

**Description:**
On all of my dedicated servers we have cba_settings.sqf files to force certain settings on the servers. After the latest upgrade to ARMA 3 (1.96) these file presets no longer work.

**Steps to reproduce:**
- Start server
- Join server
- See example: ACE Medical settings do not work, ACE pointing does not work. Go into configure addons in the server and it is all default settings.

**Expected behavior:**
For all presets to be functional in the server.

**Where did the issue occur?**
- Dedicated Multiplayer server

**Log Files:**
-

**Additional context:**
N/A

**Screenshots:**
N/A

**Comment by commy2** [comment]
Works for me.  Needs RPT log.

**Comment by fencr0c** [comment]
RPT is showing the following message, within editor, when using mission with cba_settings file.
```
13:55:19 [CBA] (settings) INFO: Mission Config: File [cba_settings.sqf] loaded successfully.
13:55:19 Error in expression <ring [10, 13, 9, 32] joinString "";
};

parseSimpleArray (["[", _string, "]"] jo>
13:55:19   Error position: <parseSimpleArray (["[", _string, "]"] jo>
13:55:19   Error Generic error in expression
13:55:19 File x\cba\addons\settings\fnc_parse.sqf..., line 30
```
Code with repo for CBA_A3/addons/settings/fnc_parse.sqf is missing the semi-colon on line 30.

**Comment by commy2** [comment]
>Code within GitHub repo for CBA_A3/addons/settings/fnc_parse.sqf is missing the semi-colon on line 30.

That's false dude. That line is a return value and the last statement in the code block. Thus no semi colon is required.

Ref.: https://github.com/CBATeam/CBA_A3/blob/master/addons/settings/fnc_parse.sqf#L30

Are you @fencr0c related to @WarriorJMD in any way or did you just hijack the issue?

**Comment by fencr0c** [comment]
Yeah sorry I didn't spot that was the returned value and I'm a dirty hijacker, I'll admit it.

My issue appears to be caused by the VCOM_AI settings exported to the cba_settings file. 
These two are causing the issues:
`force VCM_ARTYSIDES = [WEST,EAST];`
`force VCM_SIDEENABLED = [WEST,EAST];`

**Comment by commy2** [comment]
Yes, settings only support values of BOOL, STRING, NUMBER and ARRAY's thereof. SIDE type can not be serialized by the game. Therefore these settings cannot be used with config file:
https://github.com/genesis92x/VcomAI-3.0/blob/develop/Vcom/Functions/VCM_Functions/fn_CBASettings.sqf#L52
https://github.com/genesis92x/VcomAI-3.0/blob/develop/Vcom/Functions/VCM_Functions/fn_CBASettings.sqf#L78

This will not change unless BI decides to make SIDE type serializable. VCOM should change these settings to use STRING or NUMBER instead of SIDE.

**Comment by commy2** [comment]
I notified the author: https://github.com/genesis92x/VcomAI-3.0/issues/155
