### ISSUE TITLE
Class init event does not occur for ContainmentAreas

### ISSUE THREAD

**Issue by mwpowellhtx** [CBATeam/CBA_A3#1257]
**Mods (complete and add to the following information):**
- **Arma 3:** latest
- **CBA:** latest

**Description:**

```
["ContainmentArea_01_sand_F", "init", {

    params ["_vic"];

    private _className = typeOf _vic;

    diag_log format ["[onInit:%1] do some stuff with the %2", __LINE__, _className];

    }, true, [], true] call CBA_fnc_addClassEventHandler;
```

This is also in the context of a KP Liberation fork. I suspect that these assets are being saved/restored somehow differently than the other assets, although not that differently from what I can determine, the types still run through a `createVehicle` opportunity, for example.

As far as I can determine the mission restores containment areas such as:

```
createVehicle [_nextClass, _nextPos, [], 0, "CAN_COLLIDE"]
```

`_nextClass` and `_nextPos` being the respective containment area class name and position, respectively.

**Expected behavior:**
We see events for a dozen other assets in the same event handler occurring in our diagnostic log. And I can promise you we are initializing the `ContainmentArea` classes, we see that in our log as well. However, we are not seeing `init` events for the same, even retroactively.

**Where did the issue occur?**
- MP dedicated (for the time being)

**Additional context:**
Historically, I am beginning to wonder whether *KP Liberation* supported the resource "transport cargo" issue as a separate concern when it comes to `ContainmentArea` classes for this reason, but I wonder if y'all could shed some light on if/whether an `"init"` event ought to be happening for these.

To further complicate matters, if I read some of the [A3 docs](https://community.bistudio.com/wiki/Arma_3_CfgVehicles_Structures), they would suggest that the `ContainmentAreas` were contemporary with the *Helicopters DLC*. Great, not problems so far. However, when I examine the assets in an editor, they are showing under the `Contact DLC` today. Oops! I have Helicopters; not about to be getting Contact any time soon due to cash flow constraints. So I wonder, that being the case, are events disabled for non subscriber content? It is an unsubstantiated theory on my part, just curious if y'all had any insight along these lines.

Let me know if I can log anything else to help drill into this a bit. Worst case, I shimmy in a couple of special cases for the containment areas in the API framework I am working on, but I would like for the containment areas to work transparently alongside the transport concern, no muss no fuss.

**Comment by commy2** [comment]
`ContainmentArea_01_sand_F` has parents:
`ContainmentArea_base_F`:`NonStrategic`:`Building`:`Static`

`Static` class objects have XEH disabled by default: 
https://github.com/CBATeam/CBA_A3/blob/master/addons/xeh/CfgVehicles.hpp#L17-L19

This was a decission made back in A2 for performance: essentially XEH does not run for most terrain object classes (and not for terrain objects in general).

Despite this, some classes were deemed important / useful enough to have XEH enabled anyway, like WeaponHolders, Tents, Wrecks and Modules.

I don't count ContainmentAreas among them though. It seems to me that this is better done by editing KP liberation to execute code after every `createVehicle` using these classes.

Tag question and close?

**Comment by bux** [comment]
Could add a custom config mod to enable xeh on those.

**Comment by mwpowellhtx** [comment]
I am working on an API area in the framework connected to "crate transports", which I think `ContainmentArea` are admittedly a special case of one, but one nonetheless. When we see those, we add resource variables to the objects in order to keep track of resource attachments.

@bux A custom config would be acceptable. How would we go about doing that exactly? So we could do something like this?

```
class Static: All {
    XEH_ENABLED;
};
```

Or specifically for the individual class names?

**Comment by veteran29** [comment]
As I've told you on KP Discord, KP Liberation Legacy does have custom "poors man XEH"  for init:
<https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/kp_objectInits.sqf>

I guess this answer could be easier to find for you if you would not be crossposting same question over A3 Discord, KP Discord AND CBA Issuetracker. 🤷‍♀

**Comment by mwpowellhtx** [comment]
@veteran29 Excuse me? I have not seen any response, and I am investigating through all of the resources at my disposal. But I appreciate the feedback, I was not aware of this one.
