### ISSUE TITLE
MX Rifle Accessories compatibility

### ISSUE THREAD

**Issue by TheNightstalk3r** [CBATeam/CBA_A3#1258]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96 stable`
- **CBA:** `3.13.0`

**Description:**
Rail accessories and silencers from 3rd party mods are not supported by the MX (optics are supported).

**Steps to reproduce:**
(- Use a mod like ACE, CUP, RHS or RKSL Optics)
- Open BIS Arsenal
- Select MX Rifle
- Observe available optics or bipods for the MX (all mods supported)
- Observe available accessories and silencers (only BIS content)

**Expected behavior:**
The 3rd party content should be compatible with the accessories and silencers for the MX.

**Where did the issue occur?**
Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

All of the above.

**Screenshots:**
In this example, CBA and the RHS USAF mod are used for 3rd party content.

![20191124001300_1](https://user-images.githubusercontent.com/17759038/69486749-4d482380-0e4f-11ea-9a5a-a280c9ac25a2.jpg)
![20191124001308_1](https://user-images.githubusercontent.com/17759038/69486750-4de0ba00-0e4f-11ea-9c00-affef61fda90.jpg)
![20191124001315_1](https://user-images.githubusercontent.com/17759038/69486751-4de0ba00-0e4f-11ea-8338-a355453b90fa.jpg)
![20191124001322_1](https://user-images.githubusercontent.com/17759038/69486752-4de0ba00-0e4f-11ea-851b-67f277d00522.jpg)

**Comment by commy2** [comment]
Since Arma 1.94/Enoch, MX and AK12 use their own muzzle and pointer slot classes. To keep CBA compatible with addons that add attachments to those slot classes, JR support was removed. Addon makes will have to add their attachments to the classes `MuzzleSlot_65`, `MuzzleSlot_762`, `PointerSlot_Rail` and whatever BI releases in future.

**Comment by commy2** [comment]
To keep JR support, but lose potential addons, move optionals/cba_legacy_jr.pbo to addons/cba_legacy_jr.pbo.

**Comment by TheNightstalk3r** [comment]
I see. Thanks for the quick reply!
