### ISSUE TITLE
CBA_fnc_dropWeapon errors if no magazines for weapon

### ISSUE THREAD

**Issue by luckyspoon** [CBATeam/CBA_A3#1261]
If you call dropWeapon on a weapon for which the unit has no magazines, it throws an error.

![20191130162914_1](https://user-images.githubusercontent.com/5396950/69896908-29756800-1390-11ea-9b34-b863e9a676d1.jpg)

**Comment by commy2** [comment]
The function should be rewritten anyway to make use of https://community.bistudio.com/wiki/addWeaponWithAttachmentsCargoGlobal
