### ISSUE TITLE
CBA_fnc_addKeybind doesn't works after createDisplay

### ISSUE THREAD

**Issue by xunclex** [CBATeam/CBA_A3#1264]
**Mods:**
- **Arma 3:** `1.96` stable
- **CBA:** `3.13.0.191116` stable

**Description:**
If you create custom keybind which opening display, then after display will be closed you need to use key twice for open display again.

**Steps to reproduce:**
- Execute in debug console: `["TestAddon","TestKey",["Test Key Bind",""],{findDisplay 46 createDisplay "RscDisplayEmpty"},{},[0x25,[false,false,false]],false] call cba_fnc_addKeybind;`
- Press the key K
- Close display by Esc key
- Press K again and nothing will happens
- Press K second time, display will be opened again.

With Dialogs everything wors as expected

I would be grateful if someone could tell me how to solve this problem.

**Comment by PabstMirror** [comment]
A short term fix seems to be reseting `cba_events_keyUpActiveList = [];`
e.g.
```
["TestAddon","TestKey",["Test Key Bind",""],{
    diag_log "createDisplay RscDisplayEmpty";
    findDisplay 46 createDisplay "RscDisplayEmpty";
    cba_events_keyUpActiveList = [];
},{},[0x25,[false,false,false]],false] call cba_fnc_addKeybind
```
but in general, messing with internal cba vars is bad, so this is dangerous and may break things

The cause of the problem is that we get a keyDown, but never get a keyUp event because the new display takes over. So CBA still thinks the key is just being held down and ignores that first keyDown.

**Comment by PabstMirror** [comment]
Perhaps a better solution would be to pass the keydown/keyUp events to CBA
```
["TestAddon","TestKey",["Test Key Bind",""],{
    diag_log "createDisplay RscDisplayEmpty";
    private _display = findDisplay 46 createDisplay "RscDisplayEmpty";
    _display displayAddEventHandler ["KeyDown", {call cba_events_fnc_keyHandlerDown}];
    _display displayAddEventHandler ["KeyUp", {call cba_events_fnc_keyHandlerUp}];
},{},[0x25,[false,false,false]],false] call cba_fnc_addKeybind
```
This will also allow other CBA keybinds to work while your display is up

**Comment by xunclex** [comment]
> Perhaps a better solution would be to pass the keydown/keyUp events to CBA
> 
> ```
> ["TestAddon","TestKey",["Test Key Bind",""],{
>     diag_log "createDisplay RscDisplayEmpty";
>     private _display = findDisplay 46 createDisplay "RscDisplayEmpty";
>     _display displayAddEventHandler ["KeyDown", {call cba_events_fnc_keyHandlerDown}];
>     _display displayAddEventHandler ["KeyUp", {call cba_events_fnc_keyHandlerUp}];
> },{},[0x25,[false,false,false]],false] call cba_fnc_addKeybind
> ```
> 
> This will also allow other CBA keybinds to work while your display is up

it works. thank you

**Comment by commy2** [comment]
Yes, KeyUp is the way to go, as the created display causes the key release event to never happen.

Tagging as question and close.
