### ISSUE TITLE
JSON parse

### ISSUE THREAD

**Issue by ColdEvul** [CBATeam/CBA_A3#1266]
**Is your feature request related to a problem?**
No

**Solution you'd like:**
I whould like the json parser functions from ALIVE to be integrated in to cba. Today a YAML parser exist but one for JSON format whould also be greate. 
Function links below:
- https://github.com/ALiVEOS/ALiVE.OS/blob/4f7ac35a2cc6b257a795eed8d2fbe52e07913c51/addons/x_lib/functions/data/fnc_parseJSON.sqf
- https://github.com/ALiVEOS/ALiVE.OS/blob/4f7ac35a2cc6b257a795eed8d2fbe52e07913c51/addons/x_lib/functions/data/fnc_JSON.sqf
- https://github.com/ALiVEOS/ALiVE.OS/blob/4f7ac35a2cc6b257a795eed8d2fbe52e07913c51/addons/x_lib/functions/data/fnc_encodeJSON.sqf

**Alternatives you've considered:**
Contact maintainers of ALIVE is for rewire and copy paste or rewrite the YAML one. 

**Additional context:**
None

**Comment by commy2** [comment]
Well, am I allowed to just copy these? They look pretty nice aside from small imperfections, mostly newlines and legacy `private array` usage. Can't say if they work as expected though, because idk anything about JSON.

**Comment by ColdEvul** [comment]
`JSON` is basicly `YAML` with `{}`

```
     "firstName": "Jason",
     "lastName": "Smith",
     "age": 25,
     "address": {
         "streetAddress": "21 2nd Street",
         "city": "New York",
         "state": "NY",
         "postalCode": "10021"
     },
     "phoneNumber": [
         { "type": "home", "number": "212 555-1234" },
         { "type": "fax", "number": "646 555-4567" }
     ],
     "newSubscription": false,
     "companyName": null
 }
```

**Comment by bux** [comment]
but indentation is not forced as in yaml.

```json
{"firstname":"Jason","lastName":"Smith"}
```
