### ISSUE TITLE
CBA v1.1.23.150604 Odd error in RPT

### ISSUE THREAD

**Issue by Aquims** [CBATeam/CBA_A3#127]
Hello all,

Two weeks ago running on DevBranch Arma 3 we started hitting this event on the server and clients. When I added the CBA adv logging I did note a event about a 'snake_f.p3d' object that only gets logged when this error is thrown:

23:00:43 No owner
 23:00:43 [4073,17.0576,239.744,0,[446b9600# 95: snake_f.p3d],"Snake_random_F",[4305.31,4184.29,5]]
 23:00:43 Error in expression </*-------------------------------------->
23:00:43 Error position: </*-------------------------------------->
23:00:43 Error Invalid number in expression
 23:00:43 Error in expression </*-------------------------------------->
23:00:43 Error position: </*-------------------------------------->
23:00:43 Error Invalid number in expression

Seems to occur random and also within the Virtual Arsenal. Starting the process to remove all mods and debug one mod at a time, but since this matched log event is occurring with enhanced CBA logging, figured I would try this path. 

If no ideas, don't worry, can close and I will continue to debug.

**Comment by jonpas** [comment]
This has been fixed in today's release of [CBA_A3 v2.0](https://github.com/CBATeam/CBA_A3/releases/tag/v2.0.0.150817). :grinning:

**Comment by ViperMaul** [comment]
@Aquims 
Check out the new release of CBA and let us know. As jonpas says it we put a fix in for that.

**Comment by Aquims** [comment]
=) That just makes my day. Thank you. Let me give it a try.

**Comment by Aquims** [comment]
All fixed up, sorry had missed your update today. Thanks for the great mod, now I can get back to finding horrible ways to make my friends life hell in Arma :)

**Comment by ViperMaul** [comment]
:+1:
