### ISSUE TITLE
1.50 New Commands Conversion

### ISSUE THREAD

**Issue by jonpas** [CBATeam/CBA_A3#129]
- [x] To `joinString` from
  - [x] `CBA_fnc_join`
- [x] To `splitString` from
  - [x] `CBA_fnc_split`
  - [x] `BIS_fnc_splitString`

Add others in comments. Above list stands for both CBA's function conversions (pass through to the script command) and everywhere else in the codebase.

**Comment by Killswitch00** [comment]
CBA_fnc_split is converted, see issue #133

**Comment by jonpas** [comment]
Should the functions which are now simply using the command directly be deprecated as well?

**Comment by Killswitch00** [comment]
CBA_fnc_split behaves differently from splitString, but from what I can tell, CBA_fnc_join is replaced by joinString

**Comment by jonpas** [comment]
> We can at least update the documentation header for CBA_fnc_join to suggest people to use joinString instead.

That works, simply `(Deprecated)` note maybe or only a suggestion.

**Comment by jonpas** [comment]
Note: `CBA_fnc_split` still needs deprecation comment.

**Comment by Killswitch00** [comment]
CBA_fnc_split is slightly different to how splitString works, so it is not subject to deprecation. (`splitString` takes a set of separator characters as input whereas `CBA_fnc_split` is able to split along separator strings longer than one character)

**Comment by jonpas** [comment]
Ah I see, thanks for the explanation!
