### ISSUE TITLE
Type bug in gui_createCategory.sqf

### ISSUE THREAD

**Issue by dpottavio** [CBATeam/CBA_A3#1295]
**Mods (complete and add to the following information):**
- **Arma 3:** `latest`
- **CBA:** `0464ca4`

**Description:**
I am getting type error messages from `settings\gui_createCategory.sqf` when non-numeric values are added to a LIST setting.  The root cause of this seems to be a variable-type bug where a potentially non-numeric value is passed to `param`.  It looks like this was introduced recently as part of a localization update.  

Below is the line causing the issue.  In line 139, `_defaultValue` should probably be `_defaultValueIndex`, as `_defaultValue` could be a string.
https://github.com/CBATeam/CBA_A3/blob/0464ca4a143b92c71a0f8e04c0abac649841358f/addons/settings/gui_createCategory.sqf#L139

This doesn't seem to be causing any major impact to the mission other than the settings tool-tip, but I'm not 100% certain of that.

**Steps to reproduce:**
Add values to a LIST setting that are not numeric.
```
// generates error message
[
    "foo setting",
    "LIST",
    ["my setting", ""],
    "my category",
    [["a", "b", "c"], ["A", "B", "C"],  0],
    true
] call CBA_settings_fnc_init;

// does not generate error message
[
    "foo setting",
    "LIST",
    ["my setting", ""],
    "my category",
    [[0, 1, 2], ["A", "B", "C"],  0],
    true
] call CBA_settings_fnc_init;

```
**Expected behavior:**
No error messages.

**Where did the issue occur?**
- Dedicated
- Multiplayer
- Singleplayer 

**Log Files:**
```
if (isLocali>
23:17:01   Error Type String, expected Number
23:17:01 File x\cba\addons\settings\gui_createCategory.sqf..., line 139
23:17:01 Error in expression <e _label = (_settingData param [1, []]) param [_defaultValue, ""];
```

**Comment by commy2** [comment]
Which setting? Can you give an example to reproduce?

**Comment by dpottavio** [comment]
> Which setting? Can you give an example to reproduce?

This is happening on settings for my mission, but you can reproduce this by creating a LIST setting with non-numeric values.  I updated the description with an example.

**Comment by commy2** [comment]
```sqf
private _label = (_settingData param [1, []]) param [_defaultValue, ""];
```
->
```
private _label = _settingData param [1, []] param [_settingData param [0, []] find _defaultValue, ""];
```
I believe.
