### ISSUE TITLE
Player Events: "Loadout" event returns irrelevant data

### ISSUE THREAD

**Issue by 10Dozen** [CBATeam/CBA_A3#1300]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96.146114 stable`
- **CBA:** `3.14.0.200207`

**Description:**
"Loadout" EH returns weird data. Right after adding EH - it returns empty array as `_this # 1` (_newLoadout). Then each event return _previous_ loadout for some reason.

Example:
1) Initial loadout:
`[["arifle_MX_SW_pointer_F","","acc_pointer_IR","",["100Rnd_65x39_caseless_mag",100],[],"bipod_01_F_snd"],[],["hgun_P07_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_CombatUniform_mcam_tshirt",[["FirstAidKit",1],["HandGrenade",1,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",1,1]]],["V_PlateCarrier2_rgr",[["100Rnd_65x39_caseless_mag",5,100],["16Rnd_9x21_Mag",2,16],["Chemlight_green",1,1]]],[],"H_HelmetB_grass","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]`

2) Add EH :
```
["loadout", { 
    params ["_unit", "_newLoadout"]; 
     MY_LOADOUT = +_newLoadout;
}, true] call CBA_fnc_addPlayerEventHandler;
```

3) MY_LOADOUT after EH added:
`[]
`
4) Drop rifle via inventory:
> getUnitLoadout player
`[[],[],["hgun_P07_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_CombatUniform_mcam_tshirt",[["FirstAidKit",1],["HandGrenade",1,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",1,1]]],["V_PlateCarrier2_rgr",[["100Rnd_65x39_caseless_mag",5,100],["16Rnd_9x21_Mag",2,16],["Chemlight_green",1,1]]],[],"H_HelmetB_grass","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]`

> MY_LOADOUT
`[["arifle_MX_SW_pointer_F","","acc_pointer_IR","",["100Rnd_65x39_caseless_mag",100],[],"bipod_01_F_snd"],[],["hgun_P07_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_CombatUniform_mcam_tshirt",[["FirstAidKit",1],["HandGrenade",1,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",1,1]]],["V_PlateCarrier2_rgr",[["100Rnd_65x39_caseless_mag",5,100],["16Rnd_9x21_Mag",2,16],["Chemlight_green",1,1]]],[],"H_HelmetB_grass","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]`

**Expected behavior:**
(_this # 1) should return changed loadout.

**Where did the issue occur?**
- tested on Client-side only

**Comment by commy2** [comment]
0: unit
1: old loadout
2: new loadout

The old loadout may be empty array for retroactive execution.

**Comment by commy2** [comment]
Doc is here: https://github.com/CBATeam/CBA_A3/pull/1289#issuecomment-581121256

I forgot to update the wiki. Will do immediately.

**Comment by 10Dozen** [comment]
So what is expected solution - do i need to update scripts from my side to match new return values order or return values order will be restored (i mean that event data was [_unit, _newLoadout]  for at least few months, so it's kinda weird that it was changed instead of just adding oldLoadout as _this # 2)

**Comment by PabstMirror** [comment]
We should be eventually changing cba to return new as 2nd arg (`_this # 1`)
`[_unit, _new, _old]`

Until that version is released the safe way will be to manually get it 
```
["loadout", { 
param ["_unit"];
MY_LOADOUT = getLoadout _unit;
```

**Comment by 10Dozen** [comment]
Got it. Thanks!
