### ISSUE TITLE
Inventory Framework

### ISSUE THREAD

**Issue by synixebrett** [CBATeam/CBA_A3#1302]
**Is your feature request related to a problem?**
Some helmets have googles, and some helmets have the exact same helmet without googles. There is no way to wear the googles.

**Solution you'd like:**
Similar to optics, add a standard config property to specify what the other model is and what googles to provide. Have a unbound keybind that switches between the two. ACE self interact would also be a nice way via the equipment category.

**Alternatives you've considered:**
Custom scripting, I worked on a mod that did this when ACE was enabled, It would be a huge pain to add support to all the helmets you wanted manually via a mod.

**Additional context:**
This is a pretty trivial thing to implement in CBA, and pretty trivial for mods to adopt.

also do other inventory things too

**Comment by bux** [comment]
Like it.  Have done the same for my community.

**Comment by commy2** [comment]
Bloat and too specific.

**Comment by 10Dozen** [comment]
I vote for inventory framework instead! :D 
Helmet switching will be a small part of it then, but we can also switch everything else (hedger, masks, attaches mount variants, etc.).
