### ISSUE TITLE
HEMTT vs Mikero Release Build Diffs

### ISSUE THREAD

**Issue by PabstMirror** [CBATeam/CBA_A3#1316]
most cfgPatches
Hemmt0.8/MikroLastFree
- Most CfgPatches 
```
		versionStr = "3.15.0.000000";
		versionAr[] = {3,15,0,0};

		versionStr = "3.15.0.200402";
		versionAr[] = {3,15,0,200402};
```
- MRT_AccFncs (and most other sub addons like `xeh\CBA_Extended_EventHandlers`)
Mikro adds `weapons[] = {};` if not defined (is this required by arma?)

- comon/config.cpp - cleaned up whitespace (shouldn't really matter)
```
onLoad = "                        params ['_ctrlYear'];                        for '_y' from 1900 to 2050 do {                            _ctrlYear lbSetValue [_ctrlYear lbAdd str _y, _y];                        };                        _ctrlYear lbSetCurSel 53;                    ";

onLoad = " params ['_ctrlYear']; for '_y' from 1900 to 2050 do { _ctrlYear lbSetValue [_ctrlYear lbAdd str _y, _y]; }; _ctrlYear lbSetCurSel 53; ";
```

- disposable/jam
mikro adds `magazines[] = {};` (maybe because they touch `class cfgMags`)

- ee major diff (mikro is using nobin so it's raw non-demacroed code) can probably ignore

- events (causes bug - thanks to @Dystopian for spotting this)
```
onKeyDown = "        if ((_this select 1) in [0x1C    , 0x9C    ]) then {            ['cba_events_chatMessageSent', [ctrlText ((_this select 0) displayctrl 101), _this select 0]] call CBA_fnc_localEvent;        };        false\";

onKeyDown = "if ((_this select 1) in [0x1C,0x9C]) then { ['cba_events_chatMessageSent', [ctrlText ((_this select 0) displayctrl 101),_this select 0]] call CBA_fnc_localEvent; }; false";
```
- main_a3/config,cpp CfgMods
`		name = "Community Base Addons v0.0.0";`

- cba_optic_big_100.p3d Binary Files Differ (but can probably ignore)

- ui - looks like bug
```
idc = "__EVAL(12000 + 023)";
idc = 12023;
```

**Comment by jonpas** [comment]
> Most CfgPatches

Issue with my version setting stuff. I'll check it again.

> Mikro adds `weapons[] = {};` if not defined (is this required by arma?)

It's not, but it doesn't matter, in ACE3 it's in the template anyways, but it's not required.

> mikro adds `magazines[] = {};` (maybe because they touch class `cfgMags`)

Same as `weapons[] = {};`.

> ee major diff (mikro is using nobin so it's raw non-demacroed code) can probably ignore

It shouldn't be necessary at all with HEMTT, I have it in the TODO list on the closed HEMTT PR (revert #1199).

> events (causes bug - thanks to @Dystopian for spotting this)

Is the escaped quote at the end the problem? That's the only difference I see.

> main_a3/config,cpp CfgMods <version>

Same as `CfgPatches` stuff, my issue, will look into it.

> cba_optic_big_100.p3d Binary Files Differ (but can probably ignore)

I believe files added by Mikero are useless. But if they improve something, it should be looked into.

> ui - looks like bug

:+1: 

---

@synixebrett tagging you to look at above issues for your new preprocessor. :)

**Comment by dedmen** [comment]
> Is the escaped quote at the end the problem? That's the only difference I see.

Yes syntax error

**Comment by Dystopian** [comment]
- settings (causes script error):
```
onLoad = "        (_this select 0) call cba_settings_fnc_openSettingsMenu;        (_this select 0) closeDisplay 0;\";
onLoad = "(_this select 0) call cba_settings_fnc_openSettingsMenu; (_this select 0) closeDisplay 0;";
```

**Comment by jonpas** [comment]
Same issue as the other one. Good find. :+1:

**Comment by Dystopian** [comment]
> > Mikro adds `weapons[] = {};` if not defined (is this required by arma?)
>
> It's not, but it doesn't matter, in ACE3 it's in the template anyways, but it's not required.

Looks like Zeus when loading requires `units` and `weapons` config arrays (not really sure about `weapons` but there is scanning in code for both arrays). If there are no these arrays you get error in game and RPT:
`Warning Message: No entry 'config.bin/CfgPatches/addon_name_here.units'`.

**Comment by commy2** [comment]
That's not Zeus. The game always required units[], but never weapons[].

**Comment by jonpas** [comment]
Releases are built with HEMTT exclusively now.
