### ISSUE TITLE
Mounted Weapon Hitbox Issue

### ISSUE THREAD

**Issue by Exocoetidae** [CBATeam/CBA_A3#1326]
**Mods (complete and add to the following information):**
- **Arma 3:** 1.98.146303 main
- **CBA:** 3.15.0

**Description:**
Units on mounted weapons do not take damage from body/arm/head shots.

**Steps to reproduce:**
- Shoot at any unit manning a static weapon.

**Expected behavior:**
- Units manning weapons should take damage

**Where did the issue occur?**
- First noticed it on a dedicated server running Antistasi.
- Created a singleplayer scenario in the eden editor to test the issue.

**Log Files:**
https://pastebin.com/7KJ6g0c8

**Additional context:**
I've only tested this with the AAF raised HMGs: I_HMG_01_high_weapon_F, I_HMG_02_high_weapon_F

**Screenshots:**
https://imgur.com/a/zhBw0F9

**Comment by commy2** [comment]
![https://i.imgur.com/J9kMPvQ.png](https://i.imgur.com/J9kMPvQ.png)

Shot in the left arm. Dead after 3 hits. Tried with v3.15.0 and with master branch and got the same results.

From your RPT:
```
@Jurassic Arma - Raptor Pack
@CBA_A3
```

Disable all other mods aside from CBA_A3 and try again.

**Comment by Exocoetidae** [comment]
Sorry I posted the wrong .rpt from before I disabled the last mod.

Anyway I can't reproduce it anymore with either CBA or other mods loaded so I'll close this until I can track it down.

**Comment by commy2** [comment]
May also have been something on the Arma release branch that got fixed. No one knows what exact version one is on thanks to Steam and automatic forced updates...

**Comment by dedmen** [comment]
> May also have been something on the Arma release branch that got fixed.

No updates since release. We had this bug in older ACE versions I think? but was fixed quite a while ago.
