### ISSUE TITLE
CBA_fnc_split - wrong return

### ISSUE THREAD

**Issue by Dorbedo** [CBATeam/CBA_A3#133]
Returns the wrong value if the seperator is longer than the String.

[Line 41](../blob/master/addons/strings/fnc_split.sqf#L41)
Is:
`exitwith {toArray _input};`

should be:
`exitwith {[_input]};`

test with:
`["a","test"] call CBA_fnc_split;`
returns `[97]`instead of `["a"]`

**Comment by Killswitch00** [comment]
We're investigating this. CBA_fnc_split does indeed return a strange value if presented with a separator string longer than the input string. The plan is to rewrite CBA_fnc_split using the new BIS scripting command `splitString`, and that one will return what you expect.

**Comment by Dorbedo** [comment]
There is a difference between `splitstring` and your function.
example:
`test = ["THIS\IS\A\PATH\TO\fnc_test.sqf","\fnc_"] call CBA_fnc_split;`
returns `["THIS\IS\A\PATH\TO","test.sqf"]`

`test = "THIS\IS\A\PATH\TO\fnc_test.sqf" splitString "\fnc_";`
returns `["THIS","IS","A","PATH","TO","test.sq"]`

**Comment by Killswitch00** [comment]
Thanks - I see another unit test case here :-)
