### ISSUE TITLE
Using invisible targets on dedicated server results in server crash

### ISSUE THREAD

**Issue by Hobbnob** [CBATeam/CBA_A3#1331]
**Mods (complete and add to the following information):** Custom repo, but can be repro'd with just cba
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev] Stable 
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash] 3.15.1 stable from workshop
_Make sure to reproduce the issue with only CBA on a newly created mission!_

**Description:**
Running a mission containing a cba invisible target crashes the server, requiring it to reboot its client, and returns the following error in its log:

18:11:34 Error: Neither Geometry nor LandContact level is present in model x\cba\addons\ai\invisibletarget.p3d

Although I haven't checked the logs to see if this error happens on singleplayer, I know it runs fine without crashing.

**Steps to reproduce:**
- Run a mission on a dedicated server that contains a pre-placed invisible target object

**Expected behavior:**
N/A

**Where did the issue occur?**
- Dedicated server only

**Log Files:**
- https://pastebin.com/G6D6NK7a

**Additional context:**
N/A

**Screenshots:**
N/A

**Comment by commy2** [comment]
Needs full RPT file. Can't reproduce in local hosted MP.

**Comment by Hobbnob** [comment]
You won't be able to repro on local hosted mp, this happens on dedi only. I don't have access to a vanilla log atm, it'll be a few weeks at least

**Comment by PabstMirror** [comment]
release:
nothing useful in rpt, just crash on load
Exception code: C0000005 ACCESS_VIOLATION at 016E72A8


dev/non-bin/filepatching:
```
19:21:39 [CBA] (xeh) INFO: [4602,107.197,0] PreInit finished.
... 2 minutes of nothing
19:23:34 [CBA] (xeh) INFO: [4610,221.828,0] PostInit started. MISSIONINIT: missionName=testDedi, missionVersion=53, worldName=Stratis, isMultiplayer=true, isServer=true, isDedicated=true, CBA_isHeadlessClient=false, hasInterface=false, didJIP=false
// finally got in-game, placed another one via zeus and crashed
Exception code: C0000005 ACCESS_VIOLATION at 016E72CE
```

**Comment by PabstMirror** [comment]
Tried adding a basic Geometry LOD with defined mass, but get similar crash

**Comment by dedmen** [comment]
Game crash needs upload of the full crash report. including mdmp.
Also shouldn't you report a game crash with BI? Mods shouldn't be able to crash the game.
