### ISSUE TITLE
CBA Keybinds Wiki page

### ISSUE THREAD

**Issue by johnb432** [CBATeam/CBA_A3#1343]
**Is your enhancement related to a problem?**
I believe [https://github.com/CBATeam/CBA_A3/wiki/Keybinding](https://github.com/CBATeam/CBA_A3/wiki/Keybinding) has a minor error in it.

[https://github.com/CBATeam/CBA_A3/wiki/Keybinding#function-spec](https://github.com/CBATeam/CBA_A3/wiki/Keybinding#function-spec)
"If upCode returns true, block all further actions bound to this key, including base game actions."
I believe it is downCode instead of upCode.

**Solution you'd like:**
Correction of the article if it is wrong or clarification if I am wrong.

**Alternatives you've considered:**
I might be very wrong.

**Additional context:**
I couldn't get the feature described above to work on upCode, but it worked on downCode.
First time reporting such an issues, my apologies in advanced if I have screwed up.

_fixed borked links ~commy_

**Comment by commy2** [comment]
[Fixed it.](https://github.com/CBATeam/CBA_A3/wiki/Keybinding/_compare/4a607e67d25e7ede9f79b5d27b29e942541dce34)
