### ISSUE TITLE
Arma 3 CBA A3 mod save state dependency error.

### ISSUE THREAD

**Issue by otobongetti** [CBATeam/CBA_A3#1351]
This error pops up when I try to load a single player mission checkpoint: "You cannot play/edit this mission, it is dependent on downloadable content that has been deleted. a3_data_f_oldman_loadorder,
a3_data_f_mod_loadorder,
a3_data_f_destroyer_loadorder,
a3_data_f_sams_loadorder."

I am absolutely sure I haven't tempered with any mods or files while I'm playing Arma 3. Even if I restart the mission, I save and immediately load the save and it gives me the exact error.

I have confirmed that this only occurs when CBA A3 mod is activated.

![https://user-images.githubusercontent.com/61942703/86548813-a6278080-bf35-11ea-9311-88515961f049.png](https://user-images.githubusercontent.com/61942703/86548813-a6278080-bf35-11ea-9311-88515961f049.png)

**Comment by dedmen** [comment]
Please send your RPT. and the rest of the issue template.

**Comment by otobongetti** [comment]
Please forgive me, I'm lost. Is rpt the log file of CBA A3? And I have no
idea what an issue template is.

Otobong Etti

**Comment by otobongetti** [comment]
Please ignore this email.

I simply used a previous version.

Thanks anyway.



Otobong Etti

**Comment by commy2** [comment]
Previous version of what? Does this mean your issue is resolved?

**Comment by otobongetti** [comment]
Previous version of CBA A3 (v3.7.0.180430)

Thanks.

Otobong Etti
