### ISSUE TITLE
Allow Disposable Launchers to be replaced in Backpacks

### ISSUE THREAD

**Issue by Eogos** [CBATeam/CBA_A3#1356]
**Is your enhancement related to a problem?**
Currently the Disposable Launcher system, when active, replaces instances of the ammo with the disposable launcher it goes to, however backpacks are excluded from this and only have the ammo removed but no corresponding launcher added to replace the now removed ammo. This can lead to instances of scenarios designed with a certain amount of AT in mind being harder due to missing AT launchers depending on the settings of the host.

**Solution you'd like:**
Ammo in backpacks should be handled the same as every other container and have the ammo directly replaced with disposable launchers rather than just removed.

**Alternatives you've considered:**
Not replacing ammo with launchers anywhere, for consistency.

**Additional context:**
This came up after discussion on the CUP discord where it was learned that backpacks are specifically excluded for some unknown reason and a request to make an issue report was made. To me and some others, it does not make sense to exclude backpacks from the replacement process specifically when it is still done everywhere else.

**Comment by commy2** [comment]
By "instances of the ammo" and "Ammo in backpacks", you mean the loaded launcher classes?

**Comment by Drofseh** [comment]
The idea is that a rocket should get turned into a rocket launcher, regardless of what container it's in.

**Comment by Eogos** [comment]
What Drofseh said

**Comment by commy2** [comment]
No, magazines should not turn into launchers.

**Comment by Drofseh** [comment]
They do though, everywhere except backpacks.

This means that if a mod or mission maker gives a unit a launcher and an additional magazine in their backpack (2 shots total) then when played with CBA the extra magazine gets deleted but not replaced, so the unit now has only a single shot. 

The contention is that magazines in backpacks ought to be replaced with a launcher in the same manner as magazines that are in any other container. 

https://github.com/CBATeam/CBA_A3/blob/ce4cda6320a9b1526cb9c06491c6b818143e1c28/addons/disposable/fnc_replaceMagazineCargo.sqf#L59

**Comment by dedmen** [comment]
Never knew that they get replaced.. because I usually only have the ammo in backpack. Why would anyone put launcher ammo in uniform or vest anyway 🤔

**Comment by jonpas** [comment]
No it isn't. There are various smaller disposable launchers.

**Comment by bux** [comment]
> There are various smaller disposable launchers.

![image](https://user-images.githubusercontent.com/1235520/87405351-9c4def00-c5bf-11ea-8d91-0eae41f46786.png)

**Comment by commy2** [comment]
I think I get what you mean. We're talking about containers, where magazines are replaced with loaded launchers. And these loaded launchers decay into a launcher + magazine on Take.

**Comment by dedmen** [comment]
> We're talking about containers, where magazines are replaced with loaded launchers. And these loaded launchers decay into a launcher + magazine on Take.

yes and no.
> We're talking about containers, where magazines are replaced with loaded launchers. 

That happens in uniform and vest, but not in backpack, thats the problem. And backpack was for some reason specifically disabled.

**Comment by commy2** [comment]
Because the backpack can hold the magazines in vanilla, and I don't want to have base game AT soldiers/ Ammo carries with 4+ launchers in their backpack walking around.

The init script is to mass replace magazines in equipment boxes with loaded launchers. It is meant to exclude backpacks, and all other unit containers as well, it is just that those don't run init scripts anyway and don't contain any launcher magazines due to them being generally incompatible with anything but backpacks.

If you want your soldier to have extra launcher in the backpack, configure them so they have loaded launchers in the backpack.

**Comment by 10Dozen** [comment]
Sorry if that was already disccussed.

> can hold the magazines in vanilla

What about adding extra config property that allows specific magazine to be converted into the launcher in any conditions? 
For NLAW mags it will be considered as false (by default), and it prevent massive disposal launchers from appearing in the backpacks. 
For RPG-18/LAW mags property will be true and all mags will be replaced with launcher everywhere.

**Comment by commy2** [comment]
I am fine with that.

**Comment by commy2** [comment]
I am open to pull requests on this, but Disposable is a port from BWA3 and we have no use for this.
