### ISSUE TITLE
Naked factions of naked units for all sides

### ISSUE THREAD

**Issue by GlutenFreeVapes** [CBATeam/CBA_A3#1361]
**Is your feature request related to a problem?**
No

**Solution you'd like:**
Naked factions for all sides

**Alternatives you've considered:**
none

**Additional context:**
It would be nice to have a faction for every side that does not wear any clothes and have and items.
This will allow people to spawn in naked units and apply custom loadouts during the mission.
Doing this normally would mean that the units spawn, their config clothes are pulled on, then the clothes are pulled off and then the custom loadout clothes are pulled on.

This naked faction will increase performance for situations like this.

**Comment by jonpas** [comment]
> This naked faction will increase performance for situations like this.

Why do you think so? Do you have any data to prove that?

**Comment by GlutenFreeVapes** [comment]
> 
> 
> > This naked faction will increase performance for situations like this.
> 
> Why do you think so? Do you have any data to prove that?
I currently lack the data to prove my theory, but the change would directly reduce the amount of commands required to run to get the desired result.

**Comment by commy2** [comment]
There is only one command that has to run, and that is `setUnitLoadout` once per unit.

**Comment by GlutenFreeVapes** [comment]
> 
> 
> There is only one command that has to run, and that is `setUnitLoadout` once per unit.

The units initially spawn in with the gear and uniforms from the configs, then the gear is removed, then the new gear is added.
This means that the total amount of data loaded is bigger than such would be with naked units

**Comment by commy2** [comment]
What do you mean by "data loaded"?

**Comment by PabstMirror** [comment]
This seems like it could actually be useful if there are either speed or just network traffic improvements.
I will try to create a test unit and try to benchmark creation speed and `#monitor` network use

**Comment by severgun** [comment]
> Textures and models, a lot of vanilla factions come with attachments on the weapons and every attachment is a separate object, it's creating all of that and then deleting it right away.

Isn't unit loadout initialisation finishes before rendering?

Seems like `setUnitLoadout` just overwrite loadout and command is fast enough(much faster than multiple removeVest addVest and add items commands) so it is probably worthless optimisation. But would be interesting to see network benchmarks. Will @dedmen profiller show general arma traffic?
Main issue with `setUnitLoadout` is error prone syntax.

**Comment by GlutenFreeVapes** [comment]
> Why not just add button in right-click 3DEN menu `Clear loadout` for selected units. So mission maker place desired group, clear invetory, save mission, and make script based loadout initialization?

I don't place units manually. There are automated and more efficient methods of getting units in the mission, such as ai scripts which spawn and manage ai.



> Isn't unit loadout initialization finishes before rendering?

From my anecdotal experience, loading in 100s of units, you will see a big difference in STUTTER / lag whenever using loadout scripts like that.\ It's a lot less stuttery to use the correct units and then run scripts to edit their loadout by removing weapon attachemnts and backpacks (which will increase the total FPS).


I don't know how to test this, but I think that whenever a unit is created all of the inventories are created for it's uniform, vest and backpack.\
Using ai caching or creation scripts, these will be created and then delted and then re-created for the correct loadout.\
I think these + accessing uniforms and more, will cause a stutter and lag, __ESPECIALLY ON SLOWER HDDs__

**Comment by commy2** [comment]
These units would be scope 1 (private), completely naked, and have the basic soldier's cost and skills, right?

**Comment by GlutenFreeVapes** [comment]
These would be placable in the editor.\
This would allow pre-placing or assembling squads in code using the classes.
They would preferably be copies of a default vanilla faction with all of it's units and groups.
![image](https://user-images.githubusercontent.com/66107700/93494664-f3e93d80-f915-11ea-920e-276cbdf62100.png)

Having the same displayname and role, etc. from the vanilla configs will help determine different types.
![image](https://user-images.githubusercontent.com/66107700/93495328-ade0a980-f916-11ea-905e-58df74af3a9f.png)

Example of classnames from vanilla that can be used to determine the type
```
B_Soldier_SL_F
B_Soldier_F
B_soldier_LAT_F
B_soldier_M_F
B_Soldier_TL_F
B_soldier_AR_F
B_Soldier_A_F
B_medic_F
```
these would become something like `B_CBA_NAKED_SL_F`

**Comment by commy2** [comment]
Then I don't like this.

**Comment by severgun** [comment]
Naked clone for EVERY unit.
Sounds like a lot of copypaste hardcode and another place where maintainers need to track new classes on updates.
Also almost no one play pure vanilla.

As compromise I would suggest create 4 `Naked man` units for each side and 3DEN button as described earlier.
Mission makers will have option to use predefined groups structures and clear loadout. And ability to use naked man for dynamically spawn.

**Comment by GlutenFreeVapes** [comment]
In general the only ones needed would be 
```
crew man(and pilot man?)
(squad)leader
autorifle man
antitank man
rifle man
medic man
grenade man
markers man
```
these would cover majority of unit compositions

**Comment by severgun** [comment]
> autorifle man
> antitank man
> rifle man
> medic man
> grenade man
> markers man

all of these are JUST men. Difference only in loadout. Loadout is empty. Name does not reflect what you get. Broken logic.

**Comment by GlutenFreeVapes** [comment]
> all of these are JUST men. Difference only in loadout. Loadout is empty. Name does not reflect what you get. Broken logic.

Many mission making frameworks use classes or descriptions to determine the type automatically.
![image](https://user-images.githubusercontent.com/66107700/93668094-194f8600-fa93-11ea-9db9-b5638a2f245e.png)
![image](https://user-images.githubusercontent.com/66107700/93668106-2d938300-fa93-11ea-95c8-69b30cc85d10.png)
![image](https://user-images.githubusercontent.com/66107700/93668124-59166d80-fa93-11ea-8f72-7157e95e68c6.png)
![image](https://user-images.githubusercontent.com/66107700/93668137-6a5f7a00-fa93-11ea-874f-cfbc4a520260.png)

The naked units should have a similar classname and a displayname and roledescription as vanilla units

**Comment by Drofseh** [comment]
I don't like this either.
Way too much duplication even if only done for every vanilla unit and doesn't even consider the dozens of different mods that each have their own sets of units.

**Comment by synixebrett** [comment]
I would actually find something like this useful, but I don't think it is useful enough to everyone to belong in CBA. Could easily be it's own tiny mod, it'd really just be a single config file.

**Comment by jonpas** [comment]
Will not be in CBA.
