### ISSUE TITLE
Muzzle player event handler not returning documented returns

### ISSUE THREAD

**Issue by LorenLuke** [CBATeam/CBA_A3#1363]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98.146373` 
- **CBA:** `v3.15.1` (workshop version as of 8/21/2020)

**Description:**
Muzzle player event handler not returning documented returns

**Steps to reproduce:**
- place the following code in your player unit:
```["muzzle", { 
    params ["_unit", "_newMuzzle", "_oldMuzzle"]; 
    systemChat format ["%1", _this]; 
}, true] call CBA_fnc_addPlayerEventHandler;
```
- Run scenario and change weapon
- See that the first parameter is, in fact, not the unit

**Expected behavior:**
Expected returns to be as documented under the 'muzzle' entry;

**Where did the issue occur?**
- Editor (Singleplayer)

**Log Files:**
- None

**Additional context:**
- N/A

**Screenshots:**
![image](https://user-images.githubusercontent.com/6456096/90920133-a45a3500-e39c-11ea-8955-a68e2fece197.png)
![image](https://user-images.githubusercontent.com/6456096/90920187-b3d97e00-e39c-11ea-90c8-31393f9d8c1b.png)
![image](https://user-images.githubusercontent.com/6456096/90920215-c9e73e80-e39c-11ea-80a0-f729e065c553.png)

**Comment by Ansible2** [comment]
https://github.com/CBATeam/CBA_A3/blob/578b409cf91394866491a671a5a73b08f046a1d4/addons/events/fnc_playerEvent.sqf#L95
Just missing `_unit` from here.

`[QGVAR(muzzleEvent), [_unit, _newMuzzle select 2, GVAR(oldMuzzle) select 2]] call CBA_fnc_localEvent; `
