### ISSUE TITLE
XEH - GM has two classes that don't support XEH

### ISSUE THREAD

**Issue by Cyruz143** [CBATeam/CBA_A3#1365]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98`
- **CBA:** `3.15.1`
- **GM:** `1.2`

**Description:**
Two base classes in GM don't support XEH (logging as per Commy's request).

**Steps to reproduce:**
- Load game with current CBA + GM, check RPT post starting an empty mission.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
```
19:01:27 [CBA] (xeh) WARNING: gm_logistics_object_base does not support Extended Event Handlers! Addon: gm
19:01:27 [CBA] (xeh) WARNING: gm_mg3_aatripod_empty does not support Extended Event Handlers! Addon: gm
```

**GM Config:**
`gm_logistics_object_base`
Config: https://gist.github.com/Cyruz143/74bb1002d968e8b7fabd5f8f706c493a

`gm_mg3_aatripod_empty`
Config: https://gist.github.com/Cyruz143/42319591a8b83297ace13cb07a96bdaf

**Comment by commy2** [comment]
```cpp
class ThingX;
class gm_thingX_base: ThingX {};
class gm_object_base: gm_thingX_base {};
class gm_computers_object_base: gm_object_base {};

class gm_logistics_object_base: gm_object_base {
    class Eventhandlers {
        init = "_this call gm_core_vehicles_fnc_init;";
        respawn = "_this call gm_core_vehicles_fnc_init;";
        getIn = "";
        getOut = "";
        engine = "_this call gm_core_vehicles_fnc_engine;";
        turnIn = "";
        turnOut = "";
        deleted = "_this call gm_core_vehicles_fnc_deleted;";
    };
};
```

```cpp
class gm_staticWeapon_base: StaticWeapon {};
class gm_staticMG_base: gm_staticWeapon_base {};
class gm_mg3_aatripod_base: gm_staticMG_base {};

class gm_mg3_aatripod_empty: gm_mg3_aatripod_base {
    scope = 1;
    class Eventhandlers {
        init = "_this select 0 setVehicleLock 'LOCKED'";
    };
};
```

**Comment by PabstMirror** [comment]
I tested adding
```

    class gm_thingX_base: ThingX {};
    class gm_object_base: gm_thingX_base {};
    class gm_logistics_object_base: gm_object_base {
            XEH_ENABLED;
    };
    class gm_staticWeapon_base: StaticWeapon {};
    class gm_staticMG_base: gm_staticWeapon_base {};
    class gm_mg3_aatripod_base: gm_staticMG_base {};
    class gm_mg3_aatripod_empty: gm_mg3_aatripod_base {
            XEH_ENABLED;
    };
```
to xeh/cfgVeh and it fixes

new entries should be scope 0/1 so won't really have any negative effects for non-gm use?
I don't want to have to fix every mod with missing xeh, but this is a semi-offical dlc/mod so it's a bit more reasonable.
