### ISSUE TITLE
Arma 3 CBA bug

### ISSUE THREAD

**Issue by SamuelLiasam** [CBATeam/CBA_A3#1366]
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA on a newly created mission!_

**Description:**
Whenever I try to launch my Arma 3 via A3sync or the launcher I get this message;
file x/cba/addons/ee/config.cpp, line 12: 'Cfgvehicles/B_W_Story_Protagonist_01_F.XEH_ENABLED': ';' encountered instead of '='

**Steps to reproduce:**
- Go to ...
- Click ...
- See ...

**Expected behavior:**
I normally expect Arma to work with my mods which I normally have

**Where did the issue occur?**
No clue
**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**

**Screenshots:**

**Comment by Drofseh** [comment]
Please fill out the issue report completely and include a link to your rpt file from a session where this error occurred.

**Comment by commy2** [comment]
What's up with the issue title?

**Comment by commy2** [comment]
Obviously user error.
