### ISSUE TITLE
cba_common requires addon A3_Data_F_Oldman_Loadorder

### ISSUE THREAD

**Issue by nPHYN1T3** [CBATeam/CBA_A3#1368]
**Mods**
N/A

Arma 3: 1.96.146114
CBA: 3.15.1

**Description:**
cba_common requires addon A3_Data_F_Oldman_Loadorder seems to work but the nags are annoying and it would be nice to see some type of logic for if a user has or hasn't got something. Hard coding DLC and making assumptions isn't a good idea.

**Steps to reproduce:**
Launch game or load a save without owning Apex DLC with "Old Man."

**Example:**
Start game, get nag dialog about missing dependency A3_Data_F_Oldman_Loadorder 
Load a save, get nag about incompatibility due to missing addon, never play your saves again due to missing DLC you never had to be missing...yay!

**Expected behavior:**
To not have DLC hard coded into the addon that a user may not have.

I can't load saves because cba complains the save is in compatible due to missing or deleted A3_Data_F_Oldman_Loadorder.

As a side note starting error is as displayed, i.e. camel case. Save loading error displays the message all lowercase.

**Where did the issue occur?**
Game Launch / Single player / load save

**Log Files:**
https://gist.github.com/nPHYN1T3/696d537e288aaca45e8263c4981a5bf9 (CBA only)
https://gist.github.com/nPHYN1T3/864801b4fcafae26f7a4e7d1288566d1 (all addons)

**Comment by veteran29** [comment]
The issue template is there not to be deleted. Fill it/send your RPT.

**Comment by nPHYN1T3** [comment]
I don't see a pinned topic for reporting template...

**Comment by Drofseh** [comment]
When you clicked on `New Issue` it would've shown you the template, which you would've had to delete...
```
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA on a newly created mission!_

**Description:**
A clear and concise description of what the bug is.

**Steps to reproduce:**
- Go to ...
- Click ...
- See ...

**Expected behavior:**
A clear and concise description of what you expected to happen.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**
Add any other context about the problem here.

**Screenshots:**
If applicable, add screenshots to help explain your problem.
```

**Comment by nPHYN1T3** [comment]
Yeah it didn't because I didn't post via that. I went to post, but it redirected me to login, then when I was redirected from the login it just gave me a blank text area. Seems the initial login redirect doesn't give you the form Syntax but I have included it now.

**Comment by nPHYN1T3** [comment]
Why is this still marked "invalid?"

**Comment by commy2** [comment]
>Hard coding DLC and making assumptions isn't a good idea.

Not how any of this works. Everyone has the component in config, whether you own the DLC or not. The issue was marked by veteran as "invalid", apparently because it is still missing an RPT log file. Also Arma 1.96.146114 is an outdated version, we are at 1.98 already.

**Comment by nPHYN1T3** [comment]
In which config because there is nothing in my Arma3.cfg about old man, I've never owned Apex. More so I just updated yesterday when all this started happening so if I'm running an outdated build that seems odd given that is the current steam updated to.

As for the RPT log there isn't one. The game doesn't crash, it nags about missing dependencies then carries on once you say "yeah yeah" to the stupid dialog. The only real "affect" on game play is I can no longer load saves.

**Comment by commy2** [comment]
There is always a RPT log file. It can be found at ` %LOCALAPPDATA%\Arma 3 `. The RPT log file also records the game's version number.

**Comment by commy2** [comment]
>In which config

Addon space config ("addon" is unrelated to mods, all base game components are addon space).

**Comment by nPHYN1T3** [comment]
Path is different thus I couldn't find it without a search of the file system.

**Comment by commy2** [comment]
%LOCALAPPDATA% is a windows environment variable. Everyone has this since win 98.

**Comment by nPHYN1T3** [comment]
Yup but only works if you are in Windows or using explorer in Wine, other wise looking for the "advertised" direct file path in the "how to find" doesn't work.

**Comment by commy2** [comment]
OP says you used \@CBA_A3, but the RPT shows a huge list of other mods, as well as a lot of config errors like:

```
 6:18:23 Warning Message: No entry 'bin\config.bin/CfgVehicles/O_Plane_CAS_02_F/ViewPilot.initFov'.
 6:18:23 Warning Message: '/' is not a value
```

which are completely unrelated to \@CBA_A3.

Try with only \@CBA_A3 loaded.

**Comment by nPHYN1T3** [comment]
OP doesn't say *only* CBA. Here is the rpt with only CBA enabled, same outcome. https://gist.github.com/nPHYN1T3/696d537e288aaca45e8263c4981a5bf9

**Comment by commy2** [comment]
But that RPT says you didn't even leave the main menu.

**Comment by nPHYN1T3** [comment]
The error happens as soon as you load the game. Why would I have to leave the menu? Even when I do leave the menu it doesn't change the fact the error has happened and the dependency for something I don't have is breaking saves.

**Comment by commy2** [comment]
You would have to leave the main menu to load a game, which did not happen according to this RPT. The error must be recorded in the RPT, otherwise nothing can be done.

**Comment by nPHYN1T3** [comment]
There error IS recorded in the second CBA only rpt. Line 54  7:47:59 Warning Message: Addon 'cba_common' requires addon 'A3_Data_F_Oldman_Loadorder'

**Comment by commy2** [comment]
Ok, that is what you mean. The description in the OP says an error happens when you load a savegame.

Btw, in the original RPT, the same is logged for RHS:

 6:18:00 Warning Message: Addon 'rhs_main' requires addon 'A3_Data_F_Oldman_Loadorder'
 6:18:04 Warning Message: Addon 'cba_common' requires addon 'A3_Data_F_Oldman_Loadorder'

I think it is just the case that you need the latest version of the game for the latest version of all mods. `A3_Data_F_Oldman_Loadorder` may be a component of the 1.98 patch (whether you own any DLC or not). Legacy versions are not supported, so switch to the main branch in steam.

**Comment by nPHYN1T3** [comment]
OP says on game load AND loading saves

**Comment by commy2** [comment]
ok

Since the game will work with 1.98 (like it does for everyone else), close?

**Comment by nPHYN1T3** [comment]
ug...

**Comment by commy2** [comment]
You could always download the 3.15.0 version (or older?) of @CBA_A3, which should work with 1.96 from the releases page on Github. 1.96 is simply not supported, and there is no reason to use outdated game versions for anyone that actually bought the game ;)

**Comment by nPHYN1T3** [comment]
There is a huge reason to use outdated versions for paid owners, it's called BI screwed everyone running the Mac/Linux port and the Windows version in Wine is often times a big risk. However I'm not running an old version because of that, it's because this is the "newest" steam downloads for me. Perhaps this is because on their end they have started to withhold newer versions when they know it will break it in Proton but this then creates other issues. Like if Steam pulls current addons but keeps your client held back. Or if you did play online now you're going to get client server mismatch problems. Either way this is BS. I mean we all just want to play a damn game and have fun, not debug crap and be stressed. This is why I distrust games in general anymore. Anyhow...I'll see if this moronic steam client will eventually download the current version.

**Comment by commy2** [comment]
As I said, 3.5.0 works with 1.96 (I think, if not go back further) and it can be downloaded from the releases page over there -->

Everything else is up to you.

**Comment by nPHYN1T3** [comment]
I'd rather try to coax out the correct version of Arma, CBA as you noticed isn't the only issue here. However CBA and RHS are the only 2 that seem affected. I will let this pile of crap Steam client check/verify again in a bit and see if it pulls its head out of its arse.
