### ISSUE TITLE
Wrong version of CBA

### ISSUE THREAD

**Issue by Lethal47** [CBATeam/CBA_A3#1370]
When I start Arma 3 "CBA A3" will not be the correct version. The only way it will work is if you unsubscribe to CBA and then re subscribe to CBA from the steam workshop, "with out shutting the game down". The repair option from the game launcher will not repair the mod ether. I have multiple people that have this same issue, as well as 99% of all servers running CBA. Yes I am very experienced with how to run a dedicated server and have never encountered this problem before.

**Comment by commy2** [comment]
Why don't you ask on the BI forum on how to host a server/ install a mod? This is obviously not a bug, which is what this tracker is for.

**Comment by Lethal47** [comment]
BI is not responsible for your mod not updating properly.

**Comment by commy2** [comment]
But it is not my responsibility to set up your server either.

How do you even "unproperply update" a mod? Do you actually expect that there could be some edit I could make and then push to Steam that fixes your issue?

**Comment by Lethal47** [comment]
I will thanks for the help. Sary for waisting your time.
