### ISSUE TITLE
Disposables - Add functionality to require CLU attached to tubes in order to fire

### ISSUE THREAD

**Issue by Freddo3000** [CBATeam/CBA_A3#1371]
**Is your enhancement related to a problem?**
Lots of launchers use a system where the CLU (Command Launch Unit) is reusable, and the tube is disposed of. Right now you're limited to either having magazines stored in the backpack, which isn't particularly realistic or making the entire assembled launcher disposable.

Examples:
* FGM-148 Javelin
* FIM-92 Stinger
* 9K38 Igla
* Panzerfaust 3
* etc

**Solution you'd like:**
Add functionality to require a CLU attachment (scope, attachment, bipod, whatever) before being able to select the launcher, and adding the hidden disposable magazine. Possibly also add an option to play an animation when attaching the optic/attachment.

Additionally for weapons that use this configuration, replace the old magazines with a tube lacking CLU and old weapons with a tube with CLU.

**Alternatives you've considered:**
N/A

**Comment by commy2** [comment]
No.

**Comment by Freddo3000** [comment]
Why not?

**Comment by commy2** [comment]
Because this is a port of what I made for BWA3, similar to the scripted optics, and was moved under the condition that it does not get expanded endlessly.

Close?

**Comment by Freddo3000** [comment]
> 
> 
> Because this is a port of what I made for BWA3, similar to the scripted optics, and was moved under the condition that it does not get expanded endlessly.
> 
> Close?

Where is that even written? I'm not seeing it on the pull requests #1105 or #1116.  
Its fine if you don't want to make it yourself but just saying straight up no to stuff seems to go against the community-based spirit of this project, especially if it's for arbitrary reasons like this.

**Comment by jonpas** [comment]
This seems in-scope to me. The easiest way to implement this without expanding CBA with specific things is providing the ability for the developer to specify his own conditions, which would get evaluated on trigger press.

> Because this is a port of what I made for BWA3, similar to the scripted optics, and was moved under the condition that it does not get expanded endlessly.

There is no such condition, CBA does not get things "under conditions". I assume @commy2 means he will not do it himself, which is fine.

**Comment by commy2** [comment]
No one is picking this up after 2 weeks. Close?

**Comment by Freddo3000** [comment]
Is there a CBA slack?

**Comment by commy2** [comment]
#cba channel on the ACE public Slack.

**Comment by commy2** [comment]
> I am open to pull requests on this, but Disposable is a port from BWA3 and we have no use for this.
