### ISSUE TITLE
Mission settings cannot be changed

### ISSUE THREAD

**Issue by Raptor287** [CBATeam/CBA_A3#1374]
**Mods (complete and add to the following information):**
- **Arma 3:** 1.98.146373 stable
- **CBA:** 3.15
_Make sure to reproduce the issue with only CBA on a newly created mission!_

**Description:**
About 2 weeks ago, I was able to setup singleplayer missions in Eden and apply mod settings through the missions tab in addon options. Ever since then, applying the settings on both the mission and server from Eden has no effect, and settings in the missions tab cannot be changed. The settings are all greyed out, as are the "import" and "load" buttons. The main issue with this is that it overwrites my Zeus settings, specifically the available addons in Zeus, and leaves me with modules that you can select, but not place, and units that cannot be adjusted after being placed due to "insufficient resources".

**Steps to reproduce:**
- Go to Eden editor
- Place any unit, assign a Zeus module with "All addons (including unofficial) selected
- Go to Settings>Addon Options>Mission
- Adjust mission settings
- Play scenario
- Go to Esc>Options>Addon Options>Mission
- Notice Mission settings cannot be changed as they are greyed out
- Notice settings from the Eden editor have not been applied to the actual scenario

**Expected behavior:**
After starting the singleplayer scenario, I should be able to go to "Addon Options>Mission" and adjust the parameters as I see fit and have them applied to the game. I was able to do this up until about 1-2 weeks ago.

**Where did the issue occur?**
- Singleplayer, Editor (Singleplayer)

**Log Files:**
N/A

**Additional context:**
First noticed on 9/14/20
When using my regular modpack, I get "Resource title not found DebugWindow"
I tested with only CBA loaded, Mission settings still greyed out
First noticed after I added 16gb of ram to my pc. (Total 32gb)
Occasional crash, not sure if its related to the issue or just mods being mods.
The game crashes when the error message in the second photo pops up after loading a scenario, but the error doesn't always pop up.

**Screenshots:**
![Error 1](https://user-images.githubusercontent.com/71686177/93845777-95da9400-fc4e-11ea-8dda-440bbbb050cc.jpg)
![Error 2](https://user-images.githubusercontent.com/71686177/93845783-996e1b00-fc4e-11ea-865a-df36d37efb66.jpg)

**Comment by dedmen** [comment]
> Log Files:
N/A

Please attach the RPT file. Reproduce the issue so that you get the error popup, and then grab the RPT file of that Arma run and upload it here.
if you zip it you can directly drag&drop upload it here when posting a comment.
Here is how you find it https://community.bistudio.com/wiki/Crash_Files

**Comment by Raptor287** [comment]
[Arma3_x64_2020-09-18_18-12-39.zip](https://github.com/CBATeam/CBA_A3/files/5263379/Arma3_x64_2020-09-18_18-12-39.zip)

I wasn't able to reproduce the crash, however, I believe this is a report from one of the times it crashed with the same error in the  same scenario in the past. I'm not too adept with coding, but you can see the error taking effect at line 13881.

I also want to clarify that the main issue isn't the crash, but the fact that I cant change the mission settings from addon options in a singleplayer game.

**Comment by commy2** [comment]
OP is wrong. There are a many more mods active than just CBA. You should only try with CBA.

<spoiler><detail>script error</detail>

```
18:17:45 Error in expression <ba_settings_fnc_openSettingsMenu'] call SLX_XEH_COMPILE_NEW;
['\x\cba\addons\set>
18:17:45   Error position: <SLX_XEH_COMPILE_NEW;
['\x\cba\addons\set>
18:17:45   Error Undefined variable in expression: slx_xeh_compile_new
18:17:45 File \x\cba\addons\settings\fnc_addSetting.sqf [CBA_fnc_addSetting]..., line 5634
18:17:45 Error in expression <nit.sqf', 'cba_settings_fnc_init'] call SLX_XEH_COMPILE_NEW;
['\x\cba\addons\set>
18:17:45   Error position: <SLX_XEH_COMPILE_NEW;
['\x\cba\addons\set>
18:17:45   Error Undefined variable in expression: slx_xeh_compile_new
18:17:45 File \x\cba\addons\settings\fnc_addSetting.sqf [CBA_fnc_addSetting]..., line 5622
18:17:45 Error in expression < call SLX_XEH_COMPILE_NEW;
};

};

call cba_settings_fnc_init == 0
}>
18:17:45   Error position: <cba_settings_fnc_init == 0
}>
18:17:45   Error Undefined variable in expression: cba_settings_fnc_init
18:17:45 File \x\cba\addons\settings\fnc_addSetting.sqf [CBA_fnc_addSetting]..., line 5655
```

</spoiler>

`addSettings` is compiled by CfgFunctions. `init` is prepped by XEH. Dunno where addSetting is invoked from, it is probably one of the times it from CBA.

Anyway, this means that the game croaked somewhere in preInit before cba_xeh, which to me means this is most likely a bug in the mission or a third party addon, which is why _you should always try with only CBA enabled on an empty mission_ first.

Do that, otherwise this can be closed.

**Comment by Raptor287** [comment]
As I mentioned before, this crash wasn't the main issue. The main issue is that in a singleplayer scenario loaded from Eden, even when ONLY CBA is loaded, the "Missions" tab under addon options has everything greyed out, ie, I can't change the mod settings. If you'd like, I can upload a photo of exactly what I mean with only CBA on an empty mission.

**Comment by Raptor287** [comment]
![Error3](https://user-images.githubusercontent.com/71686177/93979646-17ebbb00-fd2a-11ea-843c-2bb74865bb84.png)

I went ahead and did that for ya. As you can see, CBA is the only mod loaded, and the scenario is an empty singleplayer mission with a pilot that I plopped down and attached a zeus module to. Notice that the settings are greyed out under the "mission" tab, which means I can't change them. I've tried changing the settings from the "server" tab, but unfortunately, the settings don't apply to the scenario. 

Thanks for the replies btw, didn't expect anything this quickly.

**Comment by commy2** [comment]
Mission settings cannot be edited in game / preview. They can only be edited from the editor.

**Comment by Raptor287** [comment]
That may be true for multiplayer scenarios, however, up until about 2 weeks ago, I was able to change the mission settings dynamically in a single player game using the mission settings tab. Also, I've tried changing mission settings in the editor, but they don't seem to take effect in the scenario itself.

**Comment by Raptor287** [comment]
Found a go-around to make the mission settings apply. I applied the settings under addon options>mission in the editor, then created a zeus via Ace, then reloaded zeus using a seperate cheat menu. This allowed me to use all the mods as I was able to before. I still can't change the mission settings in-game like I used to be able to, but the go-around works for what I need. Appreciate the help!

**Comment by commy2** [comment]
>I still can't change the mission settings in-game like I used to be able to

Mission tab was never editable in the preview:
https://github.com/CBATeam/CBA_A3/blob/master/addons/settings/script_component.hpp#L113

You're just imagining things.

**Comment by Raptor287** [comment]
I think its just Arma being Arma. I'm guessing one of the 180 mods that I run somehow allowed me to change the mission settings in-game, and then out of nowhere decided that wasn't cool anymore. I'm 100% sure I was able to do it before because it was the first thing I'd do every time I started a singleplayer game. Either way, the workaround works, so I'm happy.
