### ISSUE TITLE
Review code with regards to the new remote execution mechanism in A3 1.50

### ISSUE THREAD

**Issue by Killswitch00** [CBATeam/CBA_A3#138]
Where applicable, refactor uses of the old `BIS_fnc_MP` functionality. Reference [Arma 3 Remote Execution](https://community.bistudio.com/wiki/Arma_3_Remote_Execution)

**Comment by jonpas** [comment]
Something to note, `remoteExec` can be completely restricted via server configuration. Something not feasible for CBA.

**Comment by Killswitch00** [comment]
Yes, that will have to be taken into consideration. (I can only find one place in CBA where remoteExec is used by clients and therefore would be subject to limitations imposed by the server/mission configuration. (`CBA_fnc_switchPlayer`))
