### ISSUE TITLE
Typo on Wiki page

### ISSUE THREAD

**Issue by EM-Creations** [CBATeam/CBA_A3#1388]
**Mods (complete and add to the following information):**
- **Arma 3:** N/A
- **CBA:** 21 Sep 2016
_Make sure to reproduce the issue with only CBA on a newly created mission!_

**Description:**
Typo on page: https://github.com/CBATeam/CBA_A3/wiki/Extended-Event-Handlers-(new)

"effecs" should be spelt "effects" (towards the end of the second paragraph).

**Steps to reproduce:**
- Go to https://github.com/CBATeam/CBA_A3/wiki/Extended-Event-Handlers-(new)
- Read

**Expected behavior:**
Should be spelt "effects".

**Where did the issue occur?**
- Wiki

**Log Files:**
- N/A

**Additional context:**
N/A

**Screenshots:**
See link.

**Comment by jokoho48** [comment]
fixed
