### ISSUE TITLE
[JAM] - MP28 and MP35 magazines are not interchangeable

### ISSUE THREAD

**Issue by Drofseh** [CBATeam/CBA_A3#1389]
**Mods (complete and add to the following information):**
- **CBA:** `3.15.1.200418`

**Description:**
The MP28 and MP35 cannot use the same magazines.
This is my bad, as I did this config, so I'll fix it soon

**Steps to reproduce:**
- Go to https://github.com/CBATeam/CBA_A3/blob/311e599727ffd893c35c1f7957c9ce956881347c/addons/jam/magwells_9x19.hpp#L18

**Expected behavior:**
A separate magazine well should be created for the MP35.

Apparently the MP28 can interchange with the STEN (and also the Lancaster) so it might be worth combining the MP28 and STEN magwells.

**Comment by jonpas** [comment]
@Drofseh This still relevant?

**Comment by jonpas** [comment]
Do we want to fix it still? :P

**Comment by Drofseh** [comment]
> Do we want to fix it still? :P

Yeah I do
