### ISSUE TITLE
PIP Optics don't work in MP mission sometimes

### ISSUE THREAD

**Issue by 10Dozen** [CBATeam/CBA_A3#1391]
**Mods (complete and add to the following information):** CBA_A3, CUP Weapons
- **Arma 3:** `2.00 stable`
- **CBA:** `3.15.1 stable`
_Make sure to reproduce the issue with only CBA on a newly created mission!_

**Description:**
In multiplayer mission PIP optics sometimes is not working (no PIP displayed around the 2d scope). It requires to turn `CBA Weapons -> Use picture in picture optics` setting off and on to enable it.
This is not reproducing in singleplayer.

**Steps to reproduce:**
- Go to Multiplayer Editor
- Add unit and give some scope with PIP option to it (e.g. CUP_optic_ACOG_TA01NSN_RMR_Tan)
- Start mission and look through optics
Note: Same behavior if CUP_optic_ACOG_TA01NSN_RMR_Tan_PIP item was used from the start

**Expected behavior:**
2D sight and PIP around it when aiming down

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

**Log Files:**
- [RPT](https://gist.github.com/10Dozen/594e37dbc6b6f73e69518d2bb55b24cf)
- [CBA Settings dump](https://gist.github.com/10Dozen/ce57475e2ce9d286cb6c13a9e055b717)
- [Optics item config](https://gist.github.com/10Dozen/137f482605bc39bcdf716bc820eff296)
- [Test mission](https://github.com/CBATeam/CBA_A3/files/5543145/CBA_PIP_Optics_Test.VR.zip)

**Additional context:**
Sometimes it works for some reason.
If I execute `[call CBA_fnc_currentUnit, true] call CBA_optics_fnc_restartCamera;` after missions start -- all works (PIP displayed).

**Screenshots:**
![20201116002218_1](https://user-images.githubusercontent.com/9357337/99197243-47ef9180-27a2-11eb-805d-234ef3254b45.jpg)

**Comment by jonpas** [comment]
Still an issue?

**Comment by 10Dozen** [comment]
At least I stopped caring about it =) Let's close.
