### ISSUE TITLE
Mk14 (Classic) from Contact/Enoch doesn't have a joint rail?

### ISSUE THREAD

**Issue by arma3marius** [CBATeam/CBA_A3#1396]
**Mods (complete and add to the following information):**
- **Arma 3:** Game version: 2.00.146773
- **CBA:** 3.15.1

**Description:**
The Contact DLC/Enoch Mk14 (Classic) is missing the ability to mount **mod attachments**, such as scopes.

**Steps to reproduce:**
- Go to Arsenal or any Mission
- Compare attachments list with a mod loaded such as CUP weapons
- The Marksmen versions (Camo and Olive) work fine, but not the "Classic" version

**Expected behavior:**
Since all Mk14s have the same rails, all should be able to mount the same attachments. Probably an issue with joint rails.

**Where did the issue occur?**
- General game / weapons

**Log Files:**
- not applicable

**Additional context:**
Please refer to this link on CUP feedback: [link](https://dev.cup-arma3.org/T4294)

**Screenshots:**
![image](https://user-images.githubusercontent.com/22614900/102218121-cf353f80-3edd-11eb-8643-ed776e6121a1.png)

**Comment by pisces72** [comment]
I am currently using this hotfix in my config:

```
// load classes from CBA Joint Rails
class asdg_OpticRail1913_short;
class asdg_UnderSlot;

class cfgWeapons
{
	class DMR_06_base_F;

	class DMR_06_hunter_base_F : DMR_06_base_F {
		class WeaponSlotsInfo;
	};

	class srifle_DMR_06_hunter_F : DMR_06_hunter_base_F {
		class WeaponSlotsInfo: WeaponSlotsInfo {
			class CowsSlot : asdg_OpticRail1913_short {
				iconPosition[] = {0.52,0.36};
				iconScale = 0.15;
			};
			class UnderBarrelSlot : asdg_UnderSlot {
				iconPosition[] = {0.32,0.8};
				iconScale = 0.3;
			};
		};
	};
};
```
