### ISSUE TITLE
What is CBA_fnc_addPlayerAction _actionArray

### ISSUE THREAD

**Issue by mwpowellhtx** [CBATeam/CBA_A3#1411]
Color me ignorant, but where is the documentation for the shape of `_actionArray` vis-a-vis `CBA_fnc_addPlayerAction` if you please. Is it the standard [`addAction`](https://community.bistudio.com/wiki/addAction) parameters? Thank you...

**Comment by veteran29** [comment]
https://cbateam.github.io/CBA_A3/docs/files/common/fnc_addPlayerAction-sqf.html
