### ISSUE TITLE
review request "script_macros_mission.hpp"

### ISSUE THREAD

**Issue by Dorbedo** [CBATeam/CBA_A3#142]
Since Arma Version 1.50 `#include '..\parent'` is possile.
This results in a posiblillity to make mission modular.
Therefore i'd like to request a review of "script_macros_mission.hpp".

**Comment by Killswitch00** [comment]
What kind of review? Please explain.

**Comment by Dorbedo** [comment]
I'll try to explain.
In my opinion, at the current state, CBA is removing to much macros.
There is no more need to remove the `#define MODULAR`.

the compile macros should be changed too:
Since we are already in a mission folder, i think, that we shouldn't use prefix as an folder
This is, in my opinion, the current practice of the most usermade mission
My proposal:
Is: `#define PREP(var1) TRIPLES(ADDON,fnc,var1) = compile preProcessFileLineNumbers 'PATHTO_SYS(PREFIX,COMPONENT_F,DOUBLES(fnc,var1))'`
proposal: `#define PREP(var1) TRIPLES(ADDON,fnc,var1) = compile preProcessFileLineNumbers 'PATHTO_SYS(COMPONENT_F,functions,DOUBLES(fnc,var1))'`

another posibillity:
Is: `#define PATHTO_SYS(var1,var2,var3) ##var1\##var2\##var3.sqf`
proposal: `#define PATHTO_SYS(var1,var2,var3) ##var2\##var3.sqf`

**Comment by Killswitch00** [comment]
Perhaps MODULAR and the related macros could be kept for missions aswell.

Next, the prefix thing. In order to "not use the prefix as a folder", define `CUSTOM_FOLDER` instead. Taking your first proposal for `PREP()`, would mean doing this:
```
// Set PREFIX and COMPONENT as usual
...
...
// Do not use the prefix in the mission folder
#define CUSTOM_FOLDER COMPONENT\functions
#include "\x\cba\addons\main\script_macros_mission.hpp"
```
We do not know how many missions there are that depend on `script_macros_mission.hpp` behaving like it currently does with regards to the prefix use in paths, so changing the default behavior is probably not a good idea.

**Comment by Dorbedo** [comment]
Your solution is an easy and a better one. I didn't come up with this myself. My solution was to redefine the macros.

Nevertheless the file sould get an review e.g.:
[Line 46](../blob/master/addons/main/script_macros_mission.hpp#L46) can be removed, since it is redefined under CUSTOM_FOLDER

Maybe the whole ****MODIFIED**** part should be integrated, instead of moved at the end of the file. This could remove the redefinitions.


Some macros could be added too (maybe even in script_macros_common)
`#define QGVARMAIN(var1) QUOTE(GVARMAIN(var1))`
`#define QEGVAR(var1,var2) QUOTE(EGVAR(var1,var2))`

shorten: `#define EGVAR(var1,var2) DOUBLES(DOUBLES(PREFIX,var1),var2)`
into: `#define EGVAR(var1,var2) TRIPLES(PREFIX,var1,var2)`

**Comment by jonpas** [comment]
> We do not know how many missions there are that depend on script_macros_mission.hpp behaving like it currently does with regards to the prefix use in paths, so changing the default behavior is probably not a good idea. 

Maybe a new script_macros_mission.hpp can be made if it's worth it then.

**Comment by Dorbedo** [comment]
It would be interesting if there are some missions are using the cba macros.
I must admit, I don't know any.

**Comment by jonpas** [comment]
That never means there aren't any, communities might have in-house ones, they might simply not be published. Either way backwards compatibility must stay.

**Comment by Dorbedo** [comment]
Yes of course. My intention was to get an overview how/which the macros are used or how the missions are structured. This could be useful to decide if an additional version should be made.
