### ISSUE TITLE
[Statemachine] Empty list corner case

### ISSUE THREAD

**Issue by mwpowellhtx** [CBATeam/CBA_A3#1433]
**Mods (complete and add to the following information):**
- **Arma 3:** _latest_
- **CBA:** `v3.15.2`

**Description:**
State machine needs to allow for sets of no elements.

**Steps to reproduce:**
Running a state machine that starts with no elements, running into problems in the `select` from no elements:

```
11:30:59 File x\cba\addons\statemachine\fnc_clockwork.sqf..., line 29
11:30:59 Error in expression <

if (_skipNull) then {
while {(_tick < count _list) && {isNull (_list select _t>
11:30:59   Error position: <count _list) && {isNull (_list select _t>
11:30:59   Error Generic error in expression
```

**Comment by PabstMirror** [comment]
`Error position: <count`
I would double check what you are passing as a list, as I think the error is on the `count` statement.

`while {(_tick < count _list) && {isNull (_list select _tick)}} do {`
the select should be safe as it is only done after `_tick < count _list` and if count is 0 that will neve happen

**Comment by mwpowellhtx** [comment]
Have checked already and, initially, as I stated, that is an empty list, literally, `[]`. List may _grow_, _shrink_, as a result of player (i.e. client) engagement with the server.

**Comment by BaerMitUmlaut** [comment]
That is not how lazy evaluation works.

**Comment by mwpowellhtx** [comment]
Hmm, so it is not the logical part. Maybe having more to do with how I am offering the list up to the SM.

```hpp
list = "KPLIB_fnc_logisticsSM_onGetList";
```

Where that is the callback. Perhaps needs to be more an actual call, i.e.:

```hpp
list = "[] call KPLIB_fnc_logisticsSM_onGetList";
```

**Comment by mwpowellhtx** [comment]
With the logic being proven:

```sqf
_list = [];
_tick = 0;
(_tick < count _list) && {isNull (_list select _tick)}
```

Simulating the `while` condition: `false`.

**Comment by BaerMitUmlaut** [comment]
This line should use the GET_FUNCTION macro, which accepts both global variables and code: https://github.com/CBATeam/CBA_A3/blob/master/addons/statemachine/fnc_createFromConfig.sqf#L29
Right now it only accepts code.

```sqf
list = "KPLIB_fnc_logisticsSM_onGetList";
```
Essentially results in:
```sqf
call {KPLIB_fnc_logisticsSM_onGetList}
```
Which obviously does not return a list, but the function, which is never called.

**Comment by BaerMitUmlaut** [comment]
There is no such thing in SQF.
