### ISSUE TITLE
Help: "Addon 'cba_common' requires addon 'A3_Data_F_AoW_Loadorder'"

### ISSUE THREAD

**Issue by kaos1972** [CBATeam/CBA_A3#1435]
**Mods (complete and add to the following information):**
- **Arma 3: 2.02.147359
- **CBA:** `3.15.3`
_Make sure to reproduce the issue with only CBA on a newly created mission!_

**Description:**
I don't have much experience in Arma 3 settings. I updated the mod ace and mod CBA_A3 today. After the update, when trying to load Arma3Server on my dedicated server, I received the following message: "Addon 'cba_common' requires addon 'A3_Data_F_AoW_Loadorder'. Searching the Internet, I didn't get any information about it. If possible, I would like help.

**Steps to reproduce:**
- I try to start Arma3Server through TADST.
- The server is properly created on Port 2302.
- When the mission starts to be loaded on the dedicated server, the message appears and the loading becomes very slow.

**Expected behavior:**
After the dedicated server was created, the mission should be loaded faster and without any error messages.

**Where did the issue occur?**
- Dedicated 

**Log Files:**
[arma3server_x64_2021-03-10_19-30-28.txt](https://github.com/CBATeam/CBA_A3/files/6119348/arma3server_x64_2021-03-10_19-30-28.txt)

**Additional context:**

**Screenshots:**
![WhatsApp Image 2021-03-10 at 19 00 49](https://user-images.githubusercontent.com/80430176/110710235-4546fb00-81dc-11eb-82c8-92a11db23e04.jpeg)
![WhatsApp Image 2021-03-10 at 18 59 27](https://user-images.githubusercontent.com/80430176/110710237-45df9180-81dc-11eb-8bb6-3fb2bbb53f13.jpeg)
![WhatsApp Image 2021-03-10 at 18 58 31](https://user-images.githubusercontent.com/80430176/110710238-46782800-81dc-11eb-8bd6-d702c2a9e851.jpeg)

**Comment by PabstMirror** [comment]
no `\aow` pbo/ebos are being loaded

from a3 patch notes:
>Known issue: Sometimes the add-ons are loaded from the wrong installation (e.g. main game)
Try adding `-mod=curator;kart;heli;mark;expansion;jets;argo;orange;tacops;tank;enoch;aow` to your arma3server.exe shortcut

**Comment by kaos1972** [comment]
> nenhum `\aow`pbo / ebos está sendo carregado
> 
> de notas de patch a3:
> 
> > Problema conhecido: às vezes, os complementos são carregados da instalação errada (por exemplo, jogo principal). 
> > Tente adicionar `-mod=curator;kart;heli;mark;expansion;jets;argo;orange;tacops;tank;enoch;aow`ao atalho arma3server.exe


I tried the solution indicated, but I was unsuccessful. The problem continues.

**Comment by kaos1972** [comment]
I loaded the AoW folder (DLC Art of War) into the TADST Avaliable Mods table and the server started normally. There was no more error notification.
![WhatsApp Image 2021-03-10 at 22 59 58](https://user-images.githubusercontent.com/80430176/110724614-dcb84800-81f4-11eb-9429-0906ea34eae4.jpeg)

**Comment by peypey0212** [comment]
Same issue here. Hosted on dedicated server. Server will not start due to error. Loading aow into -mods didn't solve the issue either. Server is running latest version 2.02.147359.

**Comment by dedmen** [comment]
This seems to be a widespread issue.
Can you upload a RPT log of the server when not loading any mods? to see if `aow` is loaded then?

**Comment by kieranirving** [comment]
Same issue here, our current workaround is to load an earlier version of CBA

**Comment by kaos1972** [comment]
> Carreguei a pasta AoW (DLC Art of War) na tabela de Mods disponíveis do TADST e o servidor iniciou normalmente. Não houve mais notificação de erro.
> ![Imagem WhatsApp 10-03-2021 em 22 59 58](https://user-images.githubusercontent.com/80430176/110724614-dcb84800-81f4-11eb-9429-0906ea34eae4.jpeg)


I am adopting the above solution and it is working so far.

**Comment by MatthiasKunnen** [comment]
> Try adding -mod=curator;kart;heli;mark;expansion;jets;argo;orange;tacops;tank;enoch;aow to your arma3server.exe shortcut

This did not work for me. The problem occurs even when loading only the CBA mod. See the RPT log: [arma3server_x64_2021-05-17_17-46-42.rpt.log](https://github.com/CBATeam/CBA_A3/files/6495062/arma3server_x64_2021-05-17_17-46-42.rpt.log)

Without filepatching also errors. For now I'll be using [v3.15.1.201119](https://github.com/CBATeam/CBA_A3/releases/tag/v3.15.1.201119)

**Comment by commy2** [comment]
^ Your server is running 2.00. The current and only supported game version are 2.02 and 2.04. Therefore the error message is correct.

**Comment by MatthiasKunnen** [comment]
> ^ Your server is running 2.00. The current and only supported game version are 2.02 and 2.04. Therefore the error message is correct.

Yeah, apologies about that. I noticed after commenting that the steamcmd app_update command did not do its job. I just reinstalled the server and it's working now without the need for adding the DLC to the mod parameter.

**Comment by vlisivka** [comment]
The latest version of Arma3 for Linux is 1.84. Where I can find a compatible CBA version?

**Comment by PabstMirror** [comment]
@vlisivka 
https://github.com/CBATeam/CBA_A3/releases/tag/v3.8.0.180801 might work

**Comment by vlisivka** [comment]
I found CBA 3.7.0 in workshop, and it works. Thank you.
