### ISSUE TITLE
CBA_fnc_taskSearchArea does not work, gives 'area' error in rpt.

### ISSUE THREAD

**Issue by Doctor-Butts** [CBATeam/CBA_A3#1437]
**Mods (complete and add to the following information):**
- **Arma 3:** current/stable
- **CBA:** current/stable

**Description:**
CBA_fnc_taskSearchArea does not work. Units do not respond via script, waypoint, in Zeus. arma3 rpt shows the following error each time:
10:57:34 [CBA] (ai) ERROR: Bad Input [_pos: []][_area: tank_pencil][_group: O Alpha 2-1]

**Steps to reproduce:**
Attempted the following combinations:
 [group leader name, "marker"]  call CBA_fnc_taskSearchArea;
 [group leader name, object]  call CBA_fnc_taskSearchArea;
 [group name, "marker"]  call CBA_fnc_taskSearchArea;
 [group name, object]  call CBA_fnc_taskSearchArea;
 [group name, marker]  call CBA_fnc_taskSearchArea;
 [group name, "object"]  call CBA_fnc_taskSearchArea;

Same error each time. 

**Expected behavior:**
Expect the units to move and search area. Not one waypoint is created nor do units move.

**Where did the issue occur?**
 Editor (Singleplayer) / Editor (Multiplayer)

**Log Files:**

**Additional context:**
attempted call in scripts, waypoint activation, trigger activation.

**Screenshots:**

**Comment by Doctor-Butts** [comment]
After further testing, it is still not accepting marker names but will accept an object as long as it is a trigger. I had assumed it would accept all objects as a trigger is an object.

**Comment by commy2** [comment]
Updated to reflect what? I have no idea what you're talking about.

**Comment by Doctor-Butts** [comment]
Fair enough. I wasn't aware until I tried getting it to work more that the above command needs an area to work correctly. If some blurb could be added to the page: https://cbateam.github.io/CBA_A3/docs/files/ai/fnc_taskSearchArea-sqf.html

That would help when I inevitably forget what I did to get it to work the next time. lol

**Comment by commy2** [comment]
The doc already says:

> _area | The area to search [Marker, Trigger or Area Array]

Marker, Trigger, Area Array.

Never says anything about generic objects.

Why write that twice?
