### ISSUE TITLE
CBA causes script errors with ACRE2

### ISSUE THREAD

**Issue by brainslush** [CBATeam/CBA_A3#144]
Running ACRE (2.1.0.811) with the latest CBA (v200150817 + cba_enable_auto_xeh) and Arma3 stable (v1.50) causes script errors.
I also left a bug report at IDI-Systems.

```
14:13:16 Error in expression < _pairs;

if (isNil "_value") exitWith {_default};

_value}>
14:13:16   Error position: <_default};

_value}>
14:13:16   Error Undefined variable in expression: _default
14:13:16 File A3\functions_f\Arrays\fn_getFromPairs.sqf, line 63
14:13:16 Error in expression <astWasSeperator = true;
while {_index < _inputCount} do {
_find = (_input select>
14:13:16   Error position: <_inputCount} do {
_find = (_input select>
14:13:16   Error Undefined variable in expression: _inputcount
14:13:16 File x\cba\addons\strings\fnc_split.sqf, line 19
14:13:16 Error in expression <_index = _index + _find;
};
};
};

if ((_inputCount >= _separatorCount) && {(_in>
14:13:16   Error position: <_inputCount >= _separatorCount) && {(_in>
14:13:16   Error Undefined variable in expression: _inputcount
14:13:16 File x\cba\addons\strings\fnc_split.sqf, line 37
14:13:16 Error in expression <t = [];
_index = 0;
_inputCount = count _input;
_separatorCount = count _separat>
14:13:16   Error position: <_input;
_separatorCount = count _separat>
14:13:16   Error Undefined variable in expression: _input
14:13:16 File x\cba\addons\strings\fnc_split.sqf, line 13
14:13:16 Error in expression <]] call BIS_fnc_getFromPairs;
_knaml = [_knaml, " "] call (uiNamespace getVariab>
14:13:16   Error position: <_knaml, " "] call (uiNamespace getVariab>
14:13:16   Error Undefined variable in expression: _knaml
14:13:16 File x\cba\addons\help\XEH_postClientInit.sqf, line 23
```

**Comment by ViperMaul** [comment]
@brainslush 
Thank you for your report! 
Is this easily reproducible for you? 
Can you give us some steps to reproduce this?

**Comment by brainslush** [comment]
Addons:
CBA (v200150817 + cba_enable_auto_xeh)
ACRE (2.1.0.811)

Steps to reproduce
 * Place unit in editor
 * Preview mission
 * Receive script error after spawning

Sidenote: Doesn't happen with CBA versions <2.0

**Comment by brainslush** [comment]
This error also occurs with other addons, eg. BWA3

**Comment by Killswitch00** [comment]
The error happens in the addon `cba_help.pbo` when it is building a list of key binds shown in the briefing (Press the Map key (default 'M') and view the "CBA->Keybinding" entry to see this list).

What I suspect is happening here is that you have a keybind set where the assigned key is not available in the internal list of "display names for keys with keycode 'x'" that CBA keeps.

In order to find out what the missing keycode is, I need you to replace the `cba_help.pbo` addon with the one linked to below. Then, follow the reproduction steps and check the .RPT log file for a warning from CBA that looks like this: `No string value found for DIK key code <x>`.

We'll need that 'x' (a number)

[cba_help.pbo](https://dev.withsix.com/attachments/download/22718/cba_help.pbo)

**Comment by ViperMaul** [comment]
@brainslush 
See the above request from killswitch. And get back to us. Thanks

**Comment by jonpas** [comment]
Could this this happen with 0 keybind? ACRE2 has few keybinds set to 0 by default (no key) and that could interfere with building display names in briefing screen?

**Comment by Killswitch00** [comment]
I don't think so - the translation table (in keybinding\dikDecToString.sqf) has an entry for key code 0 which resolves into an empty string.

Wild guess: either it's a not-yet-mapped keyboard key or perhaps an external controller key.

In the end, the result from the call to `BIS_fnc_getFromPairs` in cba_help\XEH_postInitClient.sqf will have to be safeguarded to avoid the error. (My working hypothesis is that that call returns a nil result, leading to the breakage)

**Comment by brainslush** [comment]
I'll try it later and report back to you

**Comment by brainslush** [comment]
Seems like you dug in the right place, Killswitch

Undefined default values seem to be the problem now.

```
11:03:36 Error in expression < _pairs;

if (isNil "_value") exitWith {_default};

_value}>
11:03:36   Error position: <_default};

_value}>
11:03:36   Error Undefined variable in expression: _default
11:03:36 File A3\functions_f\Arrays\fn_getFromPairs.sqf, line 63
```

**Comment by Killswitch00** [comment]
I still need the .RPT log line that says something like 
```
No string value found for DIK key code <x>.
```

**Comment by brainslush** [comment]
Sorry, I forgot to mention that there was no such entry.

I saw #113  previously. I haven't checked yet if I got such an entry but since I don't use any other input devices than mouse, keyboard and TrackIR I assume that I won't have such entries.

But for some reason my cba_versioning.pbo is labeled unknown

```
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_ai.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_arrays.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_common.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_diagnostic.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_events.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_extended_eventhandlers.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_hashes.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_help.pbo - unknown
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_jr.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_keybinding.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_main.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_main_a3.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_network.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_strings.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_ui.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_ui_helper.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_vectors.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_versioning.pbo - unknown
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_xeh.pbo - 8eff8eaa
11:02:50 D:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\addons\cba_xeh_a3.pbo - 8eff8eaa
```

**Comment by ViperMaul** [comment]
> But for some reason my cba_versioning.pbo is labeled unknown

That is a known problem. We should have fixed it. But we haven't fixed it yet due to other priorities.

**Comment by brainslush** [comment]
Just to make sure I checked for the occurence of unknown binds as in #113 but there were non.

**Comment by Killswitch00** [comment]
Try this one then:

[cba_help2.pbo](https://dev.withsix.com/attachments/download/22719/cba_help2.pbo)

Note how it is named cba_help**2**.pbo. Replace the previous "cba_help.pbo" you downloaded and place this new file there instead. Load the game and see if the problem persists. Look in the in-game mission map keybinding display ('M' for map, look under the DBA->Keybinding entry) and see if there are any keys named "Unknown key (x)" where **x** is a number.

**Comment by brainslush** [comment]
Seems like you fixed the problem. I didn't find any entry named unknown in the keylist listed in the briefing but at the very end there is following entry
```
cTab
... 
*(some keybinding entries)*
...

Notepad ?
```
