### ISSUE TITLE
cba common requires addon a3_data_f_mod_loadorder

### ISSUE THREAD

**Issue by Arson22** [CBATeam/CBA_A3#1446]
every time i launch the game with cba_a3 enabled i get the error message "cba common requires addon a3_data_f_mod_loadorder" even if its the only mod. ive tried reinstalling the mod, reinstalling arma, repairing the mod, and even downloading the mod from armaholic instead of workshop. nothing seems to work. i cant join any servers that run the mod and my main menu in arma is all bugged out, virtual arsenal is also messed up too. Please Help!

**Comment by commy2** [comment]
This is a bug tracker and not a tech support forum.

**Comment by mora145** [comment]
> This is a bug tracker and not a tech support forum.

This is a loading error, not a request on how to install.

**Comment by PabstMirror** [comment]
try verifying integrity of game in steam

fill out the template, mainly getting us the rpt - https://github.com/CBATeam/CBA_A3/issues/new?assignees=&labels=Bug&template=bug_report.md&title=

we do not support "older" versions of the game

**Comment by commy2** [comment]
> This is a loading error, not a request on how to install.

What is a "loading error"?

**Comment by mora145** [comment]
![image](https://user-images.githubusercontent.com/25883820/114221422-500bc180-993b-11eb-9020-2de42e2ef014.png)
This, is for a mising file... or for obsolete install.

**Comment by commy2** [comment]
Sorry, this is still not a support forum. Close?

**Comment by mora145** [comment]
Here.
https://www.gitmemory.com/issue/CBATeam/CBA_A3/1435/796942411
