### ISSUE TITLE
Add side argument support for CBA_fnc_targetEvent

### ISSUE THREAD

**Issue by johnb432** [CBATeam/CBA_A3#1447]
**Is your enhancement related to a problem?**
Have the possibility to use sides when giving targets for target events (like remoteExec).

**Comment by commy2** [comment]
You can use `units west` as target:
```sqf
["banana", [], units west] call CBA_fnc_targetEvent;
```
It will only raise the event once in case multiple units belong to the same machine.

**Comment by johnb432** [comment]
Thanks, didn't think of that.
