### ISSUE TITLE
[Defend Module] AI task updates

### ISSUE THREAD

**Issue by irvnriir** [CBATeam/CBA_A3#1448]
**Is your enhancement related to a problem?**
The AI don't {reset the / regroup for} defenses after doing counter attacks .

**Solution ideas:**
A check that would redo the Defend, after: the Group gets into Combat Mode and then back into another .

**Additional:**
Would be awesome to add a part to make Units stay on and take in-building positions depending on the ranges of directions to enemies that the group is in contact with . And to add a management for other directions, maybe also including connecting multiple groups on the same objective .

**Info notes:**
The [function](https://github.com/CBATeam/CBA_A3/blob/master/addons/ai/fnc_taskDefend.sqf) uses that AI Squad Leader gives to the Units, Engage orders which overwrite the Stop orders from `doStop` command used for keeping the units in buildings .

**Comment by commy2** [comment]
I have no idea what any of this means.

**Comment by irvnriir** [comment]
@commy2 keep trolling
