### ISSUE TITLE
CBA_fnc_taskDefend picks always first position if array was given

### ISSUE THREAD

**Issue by sarogahtyp** [CBATeam/CBA_A3#1463]
**Mods (complete and add to the following information):**
- **Arma 3: 2.04 stable
- **CBA: v3.15.3.210310 stable
_Make sure to reproduce the issue with only CBA on a newly created mission!_
- thats what I did :-)
- 
**Description:**
if the position parameter is an array which contains positions or objects (mixed not tested) then the function will always choose the first element of that array and therefore the AI defends that position only

**Steps to reproduce:**
- create inf group in eden
- create 3 statics on 3 different positions set variablenames gar1, gar2 and gar3 on it.
- on group leaders init field do: [ this, [ gar1,  gar2, gar3  ], 15 ] call CBA_fnc_taskDefend
- See everytime the group chooses gar1 for defending

**Expected behavior:**
group should randomly choose between gar1, gar2 and gar3

**Where did the issue occur?**
- Editor (Singleplayer)

**Additional context:**
Workaround is currently: [ this, selectRandom [ gar1,  gar2, gar3  ], 15 ] call CBA_fnc_taskDefend

**Comment by sarogahtyp** [comment]
after looking at sources of CBAs taskDefend and getPos it seems not to be a bug but intended behavior.
But the wiki is misleading:
https://cbateam.github.io/CBA_A3/docs/files/ai/fnc_taskDefend-sqf.html
If one reads it one could think the ARRAY could be an array of positions or objects etc. 
meant is a position array. maybe that should be clarified better in the wiki.

**Comment by commy2** [comment]
ARRAY is the type of the various Position3D and Position2D tuples. I think the doc is clear. Use `selectRandom` to make a random choice for this EG functions.

**Comment by sarogahtyp** [comment]
Clear? Maybe. But you could avoid confusions like you can see in [BI-Forum post](https://forums.bohemia.net/forums/forum/154-arma-3-mission-editing-scripting/) with a better labelling. But thats your choice.

**Comment by commy2** [comment]
The actual [form post](https://forums.bohemia.net/forums/topic/234944-some-help-with-array/), I assume.

**Comment by sarogahtyp** [comment]
sorry I linked wrong.
[this post](https://forums.bohemia.net/forums/topic/234944-some-help-with-array/?do=findComment&comment=3439465) and below
