### ISSUE TITLE
Issue with the Callsign attribute

### ISSUE THREAD

**Issue by R3voA3** [CBATeam/CBA_A3#1470]
**Mods**
- **Arma 3:** `2.05` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.1`

**Description:**
When creating a scenario with CBA and setting the Callsign attribute it will replace the default expression with
`expression="[_this, _value] call CBA_fnc_setCallsign";`

This will not create a dependency but if the mission is then played without CBA the attribute will do nothing since the function is not available.

**Steps to reproduce:**
- Place a group
- Set the callsign attribute with CBA loaded
- Export the mission to SP
- Play the mission without CBA
- Check the callsign

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**Comment by commy2** [comment]
https://github.com/CBATeam/CBA_A3/blob/master/addons/common/Cfg3DEN.hpp#L30

->

```cpp
                        expression = "\
                            if (isNil 'CBA_fnc_setCallsign') then {\
                                _this setGroupID [_value];
                            } else {\
                                [_this, _value] call CBA_fnc_setCallsign;\
                            };\
                        ";
```
