### ISSUE TITLE
[common] Doc examples are incorrect

### ISSUE THREAD

**Issue by mwpowellhtx** [CBATeam/CBA_A3#1472]
Minor nit, the docs indicate [`_namespace call CBA_fnc_deleteNamespace`](https://cbateam.github.io/CBA_A3/docs/files/common/fnc_deleteNamespace-sqf.html), however, the [actual parameters](https://github.com/CBATeam/CBA_A3/blob/master/addons/common/fnc_deleteNamespace.sqf#L24) do not agree.

Correct:

```sqf
[_namespace] call CBA_fnc_deleteNamespace;
```

**Comment by jokoho48** [comment]
> [Dedmen](https://community.bistudio.com/wiki/params#Notes)
>  With a function only taking one Parameter, it doesn't matter whether the parameter is in an array or not:

**Comment by mwpowellhtx** [comment]
Oh wow okay, I did not know that.

**Comment by mwpowellhtx** [comment]
> The only thing that is wrong is that it takes Objects and Locations and not only Locations.

@jokoho48 Actually, that's by design as well, depending on whether the namespace `_isGlobal`, so `[locationNull, objNull]` is appropriate.

**Comment by jokoho48** [comment]
> 
> 
> > The only thing that is wrong is that it takes Objects and Locations and not only Locations.
> 
> @jokoho48 Actually, that's by design as well, depending on whether the namespace `_isGlobal`, so `[locationNull, objNull]` is appropriate.

yeah but the function takes objects and locations not just locations as the header/docs say.

**Comment by mwpowellhtx** [comment]
Oh okay, right, I see. Thanks all for clarifying.
