### ISSUE TITLE
Key issue

### ISSUE THREAD

**Issue by xxdant3zz** [CBATeam/CBA_A3#1474]
The key of the addon is broken with the new update.

Screenshots:

![Captura1](https://user-images.githubusercontent.com/87329873/125325337-19ca4d80-e341-11eb-877c-557279cf6c5d.png)

![Caputar2](https://user-images.githubusercontent.com/87329873/125325349-1d5dd480-e341-11eb-9c4c-bbc619eaf487.png)

**Comment by veteran29** [comment]
Works on my end, bisign and key names do not need to match.

It's an issue with your setup.

![image](https://user-images.githubusercontent.com/4293906/125329309-9f4ffc80-e345-11eb-9eec-f6ce2c2017ff.png)
