### ISSUE TITLE
Ace broken on 3.15.4 (7/12/2021 update)

### ISSUE THREAD

**Issue by IcemanLXXXVII** [CBATeam/CBA_A3#1477]
CBA update seems to break Ace 3 hooking on units.  Units aren't able to be interacted with, nor does medical work.  
e.g.:  Afghan National Army and Police, Altian Rebels, Asian Army, CDF, CRTG, Gendarmerie, Hellenic Armed Forces, Iraqi Armed Forces, MNAF, NATO, and USA.  
It seems to be most everything in our extensive mod pack, and it's fixed when the client rolls back to CBA 3.15.3

**Comment by bux** [comment]
Please fill out the issue template: https://github.com/CBATeam/CBA_A3/issues/new/choose

**Comment by commy2** [comment]
?

**Comment by JinougaF** [comment]
Having same issue with ACE 3 medical, others I didn't got time to test yet. The most noticeable thing is that the Prevent Instant Death feature in ACE medical is broken, even if you set this one enable in Addons Setting, the player units would still died with one hit.

**Comment by tyl3r99** [comment]
Please REVERT back to previous version 
It's broken everything

**Comment by tyl3r99** [comment]
> CBA update seems to break Ace 3 hooking on units. Units aren't able to be interacted with, nor does medical work.
> e.g.: Afghan National Army and Police, Altian Rebels, Asian Army, CDF, CRTG, Gendarmerie, Hellenic Armed Forces, Iraqi Armed Forces, MNAF, NATO, and USA.
> It seems to be most everything in our extensive mod pack, and it's fixed when the client rolls back to CBA 3.15.3

Attach your full RPT file

**Comment by JinougaF** [comment]
> > CBA update seems to break Ace 3 hooking on units. Units aren't able to be interacted with, nor does medical work.
> > e.g.: Afghan National Army and Police, Altian Rebels, Asian Army, CDF, CRTG, Gendarmerie, Hellenic Armed Forces, Iraqi Armed Forces, MNAF, NATO, and USA.
> > It seems to be most everything in our extensive mod pack, and it's fixed when the client rolls back to CBA 3.15.3
> 
> Attach your full RPT file

where to find the RPT file?

**Comment by tyl3r99** [comment]
> > > CBA update seems to break Ace 3 hooking on units. Units aren't able to be interacted with, nor does medical work.
> > > e.g.: Afghan National Army and Police, Altian Rebels, Asian Army, CDF, CRTG, Gendarmerie, Hellenic Armed Forces, Iraqi Armed Forces, MNAF, NATO, and USA.
> > > It seems to be most everything in our extensive mod pack, and it's fixed when the client rolls back to CBA 3.15.3
> > 
> > 
> > Attach your full RPT file
> 
> where to find the RPT file?

Open the run command (windows key & R) 
Type %localappdata% enter 
Double click on the arma 3 folder you see 
In this directory you'll find lots of rpt files that are date and time stamped 

They hold the logs of the game and record any errors inside it

**Comment by veteran29** [comment]
> CBA update seems to break Ace 3 hooking on units. Units aren't able to be interacted with, nor does medical work.

![image](https://user-images.githubusercontent.com/4293906/125432544-a19d827a-ae73-42af-ac6c-a9fd5cbaef3d.png)

works on my end. 

Please provide RPT logs.

**Comment by dedmen** [comment]
@tyl3r99 
> Attach your full RPT file

Please attach yours too, seems like noone else is able to

**Comment by tyl3r99** [comment]
> @tyl3r99
> 
> > Attach your full RPT file
> 
> Please attach yours too, seems like noone else is able to

I'm at work at the min ill see if I can get my friends rpt who having same issue

**Comment by tyl3r99** [comment]
![alive_cba_error_July_12_2021](https://user-images.githubusercontent.com/7946533/125439787-18e00ade-c649-4e30-a8e3-e25e1ce0f8aa.JPG)

Some people also getting this error dunno if it's linked. As mentioned earlier I'm on phone at the moment ill seek out the RPTs as soon as I'm home

**Comment by DuckDuckyT** [comment]
Here's the RPT for the above error that is line 39 error, i have it too.
https://pastebin.com/raw/pTzn8jNK

**Comment by bux** [comment]
Can you try to recreate this with just CBA and ACE? Debugging with a gazillion other mods installed is not feasible.

**Comment by jokoho48** [comment]
> 
> 
> Can you try to recreate this with just CBA and ACE? Debugging with a gazillion other mods installed is not feasible.

the script error cant be reproduced with CBA and ACE only because this part of code is only triggered when a Object has not correct Eventhandler setup for XEH.

**Comment by sarogahtyp** [comment]
maybe some usefull information can be found here:
https://forums.bohemia.net/forums/topic/235333-error-every-time-i-shoot-i-get-this-error-pop-up-its-from-a-cba-file-how-do-you-fix-it/

**Comment by dedmen** [comment]
Issue found. Something weird in SQFC, and only happens when spawning an object that doesn't support CBA XEH (is already printing a warning into your RPT)

**Comment by DuckDuckyT** [comment]
Good Job.

**Comment by tyl3r99** [comment]
Well done good sir 🤓

**Comment by dedmen** [comment]
https://github.com/dedmen/ArmaScriptCompiler/commit/701f54dd1cdd7540640033cbe5254907dd718828
Here is the fix.
3 months ago when I optimized params script command, I should've updated all other optimizations that take array.
There are none though.. or so I thought.. 
`-` script command actually checks for array, but its all commented out and disabled so I didn't think of that, but that still got broken.

**Comment by Chelts** [comment]
> 
> 
> [dedmen/ArmaScriptCompiler@701f54d](https://github.com/dedmen/ArmaScriptCompiler/commit/701f54dd1cdd7540640033cbe5254907dd718828)
> Here is the fix.
> 3 months ago when I optimized params script command, I should've updated all other optimizations that take array.
> There are none though.. or so I thought..
> `-` script command actually checks for array, but its all commented out and disabled so I didn't think of that, but that still got broken.
> 
> And noone noticed in months of testing because only CBA has code like that, and it only runs on XEH unsupported objects, which CBA/ACE devs who tested this, usually don't have (as they run good/fixed mods mostly).

Would this fix fix the issue with the ACE prevent instant death setting?

**Comment by dedmen** [comment]
> Would this fix fix the issue with the ACE prevent instant death setting?
No idea how thats related to CBA or this issue

**Comment by jokoho48** [comment]
> 
> 
> > [dedmen/ArmaScriptCompiler@701f54d](https://github.com/dedmen/ArmaScriptCompiler/commit/701f54dd1cdd7540640033cbe5254907dd718828)
> > Here is the fix.
> > 3 months ago when I optimized params script command, I should've updated all other optimizations that take array.
> > There are none though.. or so I thought..
> > `-` script command actually checks for array, but its all commented out and disabled so I didn't think of that, but that still got broken.
> > And noone noticed in months of testing because only CBA has code like that, and it only runs on XEH unsupported objects, which CBA/ACE devs who tested this, usually don't have (as they run good/fixed mods mostly).
> 
> Would this fix fix the issue with the ACE prevent instant death setting?

if that issue is older than 1 day then no, if it only appeared after the update yesterday then it may be related.

**Comment by Chelts** [comment]
> 
> 
> > > [dedmen/ArmaScriptCompiler@701f54d](https://github.com/dedmen/ArmaScriptCompiler/commit/701f54dd1cdd7540640033cbe5254907dd718828)
> > > Here is the fix.
> > > 3 months ago when I optimized params script command, I should've updated all other optimizations that take array.
> > > There are none though.. or so I thought..
> > > `-` script command actually checks for array, but its all commented out and disabled so I didn't think of that, but that still got broken.
> > > And noone noticed in months of testing because only CBA has code like that, and it only runs on XEH unsupported objects, which CBA/ACE devs who tested this, usually don't have (as they run good/fixed mods mostly).
> > 
> > 
> > Would this fix fix the issue with the ACE prevent instant death setting?
> 
> if that issue is older than 1 day then no, if it only appeared after the update yesterday then it may be related.

We have only noticed this being an issue since the update. Was fine before so we're assuming a correlation.

**Comment by atlas1205** [comment]
It broke my hitmarker mod in multiplayer as well (works in singleplayer). Might be easier if you just revert it to 3.15.3.

**Comment by PabstMirror** [comment]
We just released 3.15.5 that should fix these issues, please let us know if there are any problems still

**Comment by Chelts** [comment]
Seems fixed, cheers

**Comment by atlas1205** [comment]
Can confirm. My hitmarker mod works again in MP.

**Comment by jonpas** [comment]
Thanks everyone!
