### ISSUE TITLE
Broken module UI and error EditCodeMulti10

### ISSUE THREAD

**Issue by Stevo-OLY** [CBATeam/CBA_A3#1480]
Description:
Module UI seems broken with the module info covering all the input on the module itself, error code below shows up when opening the module.
![20210714113009_1](https://user-images.githubusercontent.com/62394225/125609438-bbe19ec3-6f2a-47b2-a639-d5c319312efe.jpg)

Also the module info is covering the input as seen below.
![20210714113329_1](https://user-images.githubusercontent.com/62394225/125609548-8e26a002-56d2-48d5-bc07-6b9acfe2ad83.jpg)

Tested with just the latest CBA and the TMF mod running on the latest version of Arma.

Steps to reproduce:
- Go to editor place TMF wave spawner
- Click on TMF wave spawner error code appears and the module info covering the input.
- See pics above for evidence

Expected behavior:
The module opens with no error code and the input fields are not covered by the module info.

Where did the issue occur?
- Editor (Singleplayer) / Editor (Multiplayer)

**Comment by commy2** [comment]
Needs RPT file.

**Comment by veteran29** [comment]
We've removed this class in the recent update.

see: https://github.com/CBATeam/CBA_A3/pull/1452/files#diff-8ca1cdd851d27fa321584fc0e8ffb7456533070afa06f165c26f7a21c227dcd6L43

**Comment by Stevo-OLY** [comment]
Issue fixed on the TMF end code updated by PabstMirror, much appreciated btw.

**Comment by veteran29** [comment]
I'm not sure if we should not restore these classes, just without the logic for the "return nothing" bugfix as it's not needed anymore.

It's possible that other addons used them and got broken due to removal.

**Comment by commy2** [comment]
They never were API.
