### ISSUE TITLE
Vanilla pause menu options not visible through 3den/camera

### ISSUE THREAD

**Issue by Greenfist3000** [CBATeam/CBA_A3#1481]
**Mods (complete and add to the following information):**
- **Arma 3:** `DEV 2.05.147890, PROF/PERF 2.04.147887`
- **CBA:** `v3.15.5.210713` 

**Description:**
In the pause menu, the standard buttons for video, audio, controls and game options don't exist when the dialog is entered through 3den's 'Tools' -> 'Camera' -> Esc key.
To my experience, this issue has been around possibly for years.

**Steps to reproduce:**
- Go to the 3den editor.
- Click Tools menu. Click Camera. Press esc. Expand the 'Options' sub menu.
- Observe an empty space where the options buttons are supposed to be. Only the CBA's 'Addon options' is visible.

**Expected behavior:**
The game options should be accessible presumably.

**Where did the issue occur?**
- Editor.

**Log Files:**
- Will post if needed.

**Additional context:**
Tested without any additional mods, optional DLCs, or startup parameter. And with a fresh player profile and CBA installation.
This issue does not occur when entering menu in normal SP/MP gameplay or in mission preview.

**Screenshots:**
![kuva](https://user-images.githubusercontent.com/87469048/125755039-0b4d14c1-6771-43b0-805e-025e8488a0cb.png)

**Comment by DelsGaming** [comment]
Hi, been having the same problem after enabling the debug console and its a pain to remove, but after testing with launcher I found that if I remove all mods and just enable CBA then the menu appears as normal.
So after some testing in my case it was a mod called @Auto-Medic that was causing the issue possible stopping CBA from loading properly.
So removing that one mod solved it for me.
Can I suggest trying first with only CBA loaded. Then add back in any mods a few at a time until it breaks again.

**Comment by jonpas** [comment]
3rd party mod fault. Contact the other mod authors.
