### ISSUE TITLE
I am Linux "addict" ...

### ISSUE THREAD

**Issue by remi75** [CBATeam/CBA_A3#1482]
Hi, and .. thank you for this great work !!

I am using mods for the Linux supported version of the arma3 client, meaning, I run an arma3 server version 1.82 , to be able to have users/players that use the native Linux version of arma3 (server is under Linux too, with steamcmd.

The theory is "proven", it works with two mods at the least,

I am trying to use CBA with this server, seems like there is an issue with the key, it must a compatibility trick, since, I have the cba key in the root folder of arma3 / keys ...

Can you confirm, incompatibility with arma3 1.82 ?
If not, how can I fix this ?
If yes, can you point at me a CBA version compatible with arma3 1.82 ?
Will I have the right to clone it and name it for example : CBA_Legacy ... ? respecting the license of course !! :)

Thank you in advance .

**Comment by jonpas** [comment]
Last version obviously won't work on 1.82, we require at least 2.04 for new functionality with 3.15.4.

v3.7.0 seems to be the last that supported 1.82.
You can clone CBA all you like under the GPL-2.0 license.

FYI, Linux native version is no longer supported/updated. You should really be using Proton.

**Comment by remi75** [comment]
Thank you very much :)
