### ISSUE TITLE
Game running slow since last update

### ISSUE THREAD

**Issue by Jegukarg** [CBATeam/CBA_A3#1483]
More or less since the last CBA update; my game is running quite slow and laggy for apparently no reason, and I'm trying to identify why. Could it be possible that CBA and the last update are somehow making the game to run slower?

**Comment by Drofseh** [comment]
You need to fill out the issue template that you deleted

**Comment by PabstMirror** [comment]
If be helpful if you could do some performance testing and get some hard numbers to show any differences between these 2 versions

3.15.5 - https://github.com/CBATeam/CBA_A3/releases/download/v3.15.5.210713/CBA_A3_v3.15.5.zip
3.15.3 - https://github.com/CBATeam/CBA_A3/releases/download/v3.15.3.210310/CBA_A3_v3.15.3.zip

e.g. repeatable fps numbers or code-execution times
