### ISSUE TITLE
Ability to transfer fuel between fuelcargo sources

### ISSUE THREAD

**Issue by partycrashr** [CBATeam/CBA_A3#1495]
Not a bug, but was referred here to make requests (I think?).  I tried to make a pull request but wasn't sure how to do it (I've never posted on GitHub before, so please excuse my noobishness)

Is is possible to add code/add an option to transfer fuel between fuelcargo sources?  For example, transfer fuel from a fuel bladder to a fuel truck tank and vis versa?  I was thinking either directly between the two objects (such as adding a fuelcargo refuel point), or maybe creating an additional placeable object that handles the transfer of fuel between the fuelcargo sources?  Maybe the placeable object is a pump that is connected with hoses to both items?  The pumps could be linked to cover longer distances (for example, the 600 GPM pump can only pump so far by itself, but if you place additional pumps along the hose they can pump further).  Opens up a lot of possibilities for logistics based gameplay, allowing for transferring fuel between locations as well as the setup of fuel farms.

**Comment by rautamiekka** [comment]
Is pump linking even possible IRL ? In all cases that'd also be a nice feature and I'll definitely +1 to the transfer between fuel sources.

**Comment by partycrashr** [comment]
Yes, IRL that's what's used to move fuel/water longer distances.  I don't know what the max for the 600GPM pump is, but at my bulk fuel company that was what they would do.  I think we did a 4 or 5 mile run to the top of a hill once with 6 pumps or so at intervals.  There's also a penalty to the max distance if there is an elevation increase, but I'm not sure on the math for what that is.

Basically, what my desire for this feature is to be able to accurately transferring fuel from "ship" to shore and beyond as part of logistics for a MEU unit I want to setup.  Different fuel types would be cool too for the different vehicles (jets/helicopters with JET A vs JP8 diesel for most ground vehicles, etc), but that might be too big an ask lol.  At a minimum I want to be able to transfer fuel between fuel storage tanks though.

Probably wont get as complicated/in depth as this, but here's an example of what I'm looking to do
![Fuel_Farm](https://user-images.githubusercontent.com/88734818/128949649-1f2ffe62-c890-405d-bb51-24f2042250cb.jpg)

**Comment by rautamiekka** [comment]
Right.

1 I was thinking about was like taking from gas station into a fuel truck while the fuel truck is filling a vehicle or even transferring to another fuel truck, cuz in pretty much every fuel-using vehicle the engine must be offline IRL to avoid adding air to the fuel tank.

No clue how a fuel truck would react when simultaneously refilling the storage tank that's refilling another, but I imagine the pump and tank wouldn't mind much. Hell, the tank likely has an air valve to begin with.

**Comment by partycrashr** [comment]
Yes, they do have pressure overflow valves.  Another thing that could be added to this is overfilling a container, such as a fuel bladder, which could rupture, and hose leaks requiring repair kits, etc.  Meters for inventory and valves to control where the fuel is going without having to disconnect/reconnect hoses would be a nice addition as well.  The pumps should also be towable with MTVRs/M1151s.

**Comment by commy2** [comment]
Out of scope for this mod.

**Comment by partycrashr** [comment]
Does that include even just transferring between fuelcargo?  That was the main request, the rest was all extra/wishful thinking.  Willing to help with it as well, just don't have any experience modding for Arma.

**Comment by commy2** [comment]
Yes.

**Comment by jonpas** [comment]
This is suitable for ACE3, not CBA.

**Comment by partycrashr** [comment]
Ah, I thought this was for both, my apologies for the confusion.

**Comment by partycrashr** [comment]
Here is a link for the issue on ACE3's GitHub, in case anyone else ends up here:
https://github.com/acemod/ACE3/issues/8383
