### ISSUE TITLE
Issue at start up

### ISSUE THREAD

**Issue by Secondlt2** [CBATeam/CBA_A3#1501]
whenever I launch the game I get the message "cba.main requires cba.ui" and whenever I try to resume a mission (that had CBA enabled when I first started it) it would load for a bit then give me an error message "cannot resume mission because downloadable content ..../cba.ui is missing"

**Comment by PabstMirror** [comment]
**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by Secondlt2** [comment]
https://pastebin.com/SQVEnnY2

hello, my apologies for the late reply, thank you for your patience.

**Comment by Dahlgren** [comment]
Looks like your `cba_ui.pbo` is broken, it does not report version like the other CBA PBOs.
`D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@CBA_A3\addons\cba_ui.pbo - unknown`

Verify the CBA A3 mod in Arma 3 Launcher or resubscribe on Steam Workshop.
