### ISSUE TITLE
All menus broken on Linux

### ISSUE THREAD

**Issue by lionkor** [CBATeam/CBA_A3#1505]
**Mods (complete and add to the following information):**
- **Arma 3:** `latest linux`
- **CBA:** `v3.15.6.211004`

**Description:**
All menus in the game are completely broken on the Linux version, see screenshots. Works flawlessly without. Please keep in mind that Arma 3 has an official linux release, and thus this should be supported. 

**Steps to reproduce:**
- Run Linux Kernel 5.14.6, no idea what else matters here
- Run the game with mods enabled, native version (not proton)
- Watch the menu break

**Expected behavior:**
Menus should work

**Where did the issue occur?**
- In menus

**Log Files:**
- Didn't generate one, I looked, it's not there.

**Screenshots:**

![image](https://user-images.githubusercontent.com/29932116/136556841-57d5e2ce-e040-4a86-8479-d3487d0e5449.png)
![image](https://user-images.githubusercontent.com/29932116/136556904-95b4baa5-e5a8-4613-80e4-0f6f2b19d05f.png)
![image](https://user-images.githubusercontent.com/29932116/136557111-2a6df219-724b-42f3-b220-1807299f3451.png)

**Comment by lionkor** [comment]
> I think the official Linux releases stopped at 1.76?

No, I'm currently on build 7459498, which is 1.82.144710.

**Comment by lionkor** [comment]
I'll switch to proton, sadly that redownloads the entire game's content (thanks, steam). Would still be interesting to know why CBA doesn't work at all on the official linux release (which got it's latest update on october 5th).

**Comment by jonpas** [comment]
But those games are the same version on both platforms, not different over 2 years.
