### ISSUE TITLE
No entry 'bin\config.bin/CfgWeapons.muzzleflash_tma'

### ISSUE THREAD

**Issue by ehylla93** [CBATeam/CBA_A3#1512]
please see: https://feedback.bistudio.com/T161503

**Comment by ehylla93** [comment]
This seems correct. 

Hence CBA_A3 should be updated in that way, that the muzzle only shows up in compatibleItems when Enoch is really loaded.

**Comment by commy2** [comment]
I disagree. You made the assumption that every item listed as compatible is valid. This assumption does not seem warranted to me. I think you should modify your script so it looks more like:
```sqf
_weaponSelected = "arifle_MSBS65_GL_black_F";

private _muzzlesList = getArray (
    configFile >> "CfgWeapons" >> _weaponSelected >> "WeaponSlotsInfo" >> "MuzzleSlot" >> "compatibleItems"
) select {
    isClass (configFile >> "CfgWeapons" >> _x)
};

_muzzle = selectRandom _muzzleList;
player addPrimaryWeaponItem _muzzle;
```
