### ISSUE TITLE
Code section of CBA_fnc_addSetting is run after module code on mission start

### ISSUE THREAD

**Issue by Seb105** [CBATeam/CBA_A3#1518]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.06.148373`
- **CBA:** `v3.15.6.211004`
_Make sure to reproduce the issue with only CBA on a newly created mission!_

**Description:**

When using `CBA_fnc_addSetting`, the script executed parameter is run at mission start, but module functions are called before it.
This means that attempting to use a global variable defined in the code section too early, such as during module initialisation will cause an undefined variable error.

This means I have to do an ugly workaround of effectively checking if the variable exists in the code section of the module.

**Steps to reproduce:**
Addon preInit:
```sqf
[
    "my_bool",  // varName
    "CHECKBOX",               // type
    "title",        // title
    "category",  // Category
    false,                  // Values 
    true,                   // isGlobal?
    {  
        my_list = if (my_bool) then {
            [1, 2, 3, 4]
        } else {
            [4, 5, 6, 7]
        };
    },                      // Script executed
    false                   // Requires restart?
] call CBA_fnc_addSetting;
```
Addon module function:
```sqf
params ["_logic", "_units", "_activated"];
systemChat str my_list; // my_list is undefined here at mission start
```

If this module is placed in Eden, there will be a script error on mission start as `my_list` is undefined. After mission start, the module functions correctly when placed.

**Expected behavior:**
The variable should be defined

**Where did the issue occur?**
- Anywhere

**Comment by veteran29** [comment]
You can use `CBA_settingsInitialized` event to run after settings init.

```sqf
["CBA_settingsInitialized", {
    systemChat "afterSettings!";
}] call CBA_fnc_addEventHandler;
```

**Comment by Seb105** [comment]
I don't see how that helps for module code, though.

**Comment by commy2** [comment]
This seems like a design flaw in your scripting rather than an actual issue with the settings. Changing this to fit your special use case would break everything else than depends on the current/ sane behaviour.

**Comment by Seb105** [comment]
Trying to use a variable defined via setting in a module at mission start is 'insane'? What? 

Fair enough if fixing this would cause issues elsewhere, as the workaround is easy enough but the documentation says `function that will be executed once on mission start and every time the setting is changed.`, which is ambiguous/wrong here.

**Comment by PabstMirror** [comment]
The init order is something like
- preInit - add setting here, BUT network settings from sever are not available yet!!
- unit init runs - module runs now
- postInit - settings will be ready after next frame

So we intentionally don't run the setting's script in preInit because we don't know what the actual setting will be then.

A safe way that will support modules both placed in editor and by zeus (at runtime)
```
if (missionNamespace getVariable ["cba_settings_ready", false]) then {
    diag_log text format ["xxx Settings ready now: %1", my_list]; 
} else {
    ["CBA_settingsInitialized", {
         diag_log text format ["xxx Settings ready after delay: %1", my_list];
    }] call CBA_fnc_addEventHandler;
};
```

**Comment by commy2** [comment]
Iirc, standard modules executed scheduled, so there is no way to predict when these run anyway. It also means you'd just put a `waitUntil` in them to wait for the setting being done.

**Comment by commy2** [comment]
Working as intended.
