### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Goz420** [CBATeam/CBA_A3#1529]
**Description:**
I'm not sure what I'm doing wrong but everytime I use your cba add on for arma I get all these waypoints that pop up on my screen showing all characters movements. How do I get those off my screen.

**Steps to reproduce:**
- Go to ...
- Click ...
- See ...

**Expected behavior:**

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**

**Screenshots:**

**Comment by commy2** [comment]
I don't know what you're doing wrong either, but what has this to do with CBA? This is a bug tracker, for bugs in CBA_A3, and I don't think whatever you're doing is related to that.

**Comment by Goz420** [comment]
Thanks for replying. I got it figured out.
