### ISSUE TITLE
Not causing Player to be entered into Account table in MySQL

### ISSUE THREAD

**Issue by Crasha** [CBATeam/CBA_A3#154]
I've noticed that when my character is created and I spawn in Arma 3 Excile on the map Esseker, and then disconnect, my character is not created in the account table in MySQL. Inside the players table, my character is there. I've narrowed it down to this mod (CBA_A3). This causes the player to be "frozen" in a camera view with no character, somewhere on the map rendering them unable to disconnect also.

Any ideas?

**Comment by Killswitch00** [comment]
This needs more information on how to reproduce the problem. Detailed descriptions of exactly what addons are used, both on the server and on the client.

**Comment by AzrA91** [comment]
Sorry to necro an old issue, but I'm having the same problem on my exile Altis server, and crasha hasn't responded... I have Ryan's Zombies and Deamons, CBA, Tao's folding map, NATO SF and Russian weapons, and TRYK's uniforms mod installed.. The first time a player connects to the server there's no problem, they can play just fine.. The problem occurs when a player dies and respawns or after a server restart. I traced this down to a possible database error, to fix the issue I have to manualy delete the player's charecter from the "players" table from the database. After that the player can once again play normaly, but this repeats itself once the player respawns or the sever restarts. Also, this does not happen to everyone, this issue does not occur to me and I'm the only player that actually shows up in the "accounts" table in MySql.. I haven't tried to disable CBA to see if it's the cause as I just found this thread and am currently at work, but will try as soon as I get home. 

Thanks in advance for your time.
Regards,
AzraeL
azrael.aresclan@gmail.com

**Comment by dixon13** [comment]
Need more info guys. So far all I can see is that you have a database problem, which CBA would not cause. Also, if you can, try and only use CBA to make sure that it's a CBA problem.

**Comment by Crasha** [comment]
Hi,

I did narrow the problem down to CBA. As soon as I removed it, it worked
fine. Database was correctly updating etc. I've gone through and added each
mod I had on one by one and its always CBA every time.

**Comment by AzrA91** [comment]
Will test later to confirm.. Crasha can you tell US which other mods you have? May help find The solution, i'd hate not to be able to run CBA.. Forgot, i've also got A3XAI installed server side

**Comment by Crasha** [comment]
The other mods don't matter. If I run the server with any mod, and then add
CBA, it'll just cause this issue we're all having. The mods I had installed
is what "Frankie" (not a fan) listed on his video on YouTube for Exile on
Esseker.

**Comment by Killswitch00** [comment]
This needs more information on how to reproduce the problem. Detailed descriptions of exactly what addons are used, both on the server and on the client.

**Comment by AzrA91** [comment]
As I said earlier.. @Ryan zombies and demons, @cba, @mas, @tao folding map, @exile.. Player's did not save to database, "account" wouldn't be created for anyone. Removed, CBA and everything works as it should.. I thought maybe it was tao's folding map, as it depends on CBA, but removing only that did nothing.. Removed CBA and it all works now.. I run everything on stock Altis, MySQL, hosted on vilayer.. Also had The same problem on Nitrado.. Hope this helps, it would be nice if you could work With The exile crew to get this working.. Will be making a post on their forums later today.

**Comment by AzrA91** [comment]
If you want i can teamview everything for you guys when i'm not at work and you guys feel like it

**Comment by Killswitch00** [comment]
What's used on the server when this happens? (Which mods, which version of Exile?)
Does the issue occur if you only use CBA and Exile both on the server and client?

**Comment by AzrA91** [comment]
Exile 0.9.35, A3XAI (npc spawning mod), and CBA... Full list above (most
are client side).. I run a custom @server mod client side so our players
can download just one file to play on our server.. I ran CBA through that
folder, and also tried running it in it's own @folder but The result was
The same.. Have not been able to try it without @exile running, but i'm
sure it won't give The issue.. Your Mod is used on lots of servers.. If it
was a more widespread issue i'm sure you guys would have known about it

What's used on the server when this happens? (Which mods, which version of
Exile?)
Does the issue occur if you only use CBA and Exile both on the server and
client?

—
Reply to this email directly or view it on GitHub
<https://github.com/CBATeam/CBA_A3/issues/154#issuecomment-147113774>.

**Comment by Killswitch00** [comment]
I found the issue. The Exile mod is using the now deprecated [onPlayerConnected](https://community.bistudio.com/wiki/onPlayerConnected) and [onPlayerDisconnected](https://community.bistudio.com/wiki/onPlayerDisconnected) commands instead of the new [stacked event system](https://forums.bistudio.com/topic/158256-stacked-event-handlers-oneachframe-onplayerconnected-etc/).

The reason it appears that CBA "breaks" Exile is that CBA uses the stacked event system and the BIS stacked event system actually makes use of the `onPlayerConnected` and `onPlayerDisconnected` commands to handle the stacking system.

When Exile starts, it actually disables the BIS stacked event system, which, as mentioned, CBA needs. CBA calls the `BIS_fnc_addStackedEventHandler` (for the onPlayerConencted event) after Exile has initialized, which restores the BIS system and, at the same time, disables the Exile onPlayerConnected event handler.

The solution to the problem is for Exile to change the *ExileServer_system_process_preInit.sqf* file to use the (https://community.bistudio.com/wiki/BIS_fnc_addStackedEventHandler) command to hook into the *onPlayerConnected* and *onPlayerDisconnected* events.

**Comment by torchgodz** [comment]
I know this is not an exile site but couldn't we overwrite that script and use your code that you have pasted here?

**Comment by AzrA91** [comment]
As per license core exile mod files cannot be altered.. I'd be carefull
With that.. I've already created a topic on www.exilemod.com under "ask a
developer" section, you might want to wait for their answer regarding CBA
compatability.. Plus, i'm guessing there would have to be some
modifications to client side files ad well though i'm not sure..
Il 12/ott/2015 15:05, "Ryan" <notifications@github.com> ha scritto:

**Comment by torchgodz** [comment]
/*
		You can overwrite every single file of our code without touching it.
		To do that, add the function name you want to overwrite plus the 
		path to your custom file here. If you wonder how this works, have a
		look at our bootstrap/fn_preInit.sqf function.

		Simply add the following scheme here:

		<Function Name of Exile> = "<New File Name>";

		Example:

		ExileClient_util_fusRoDah = "myaddon\myfunction.sqf";
	*/

I did see your post on there ask the devs section thats how i found this github, but they do have this in the mission file config.cpp so if we were to take killswitch00's code there and overwrite with by using this section then you wouldn't technically be touching there code.

**Comment by AzrA91** [comment]
Well, you're free to do so i guess, but i think The smartest and most
correct thing to do is wait for an ufficial word from The devs.. If they
give The green light to do so then I will
Il 12/ott/2015 15:19, "Ryan" <notifications@github.com> ha scritto:

**Comment by torchgodz** [comment]
Yea true i was also digging through some more of the ask the devs post and have found http://www.exilemod.com/topic/5749-use-bis_fnc_addstackedeventhandler/ this post here so they are planning on using the function but i think right now that they are busy fixing bugs within the mod that external mods are the least of there worries.
