### ISSUE TITLE
CBA outdated?

### ISSUE THREAD

**Issue by joeballsballs** [CBATeam/CBA_A3#1542]
Ok, so basically Arma has been constantly kicking me out whenever I load into a map. It seems fine in Eden, but as soon as I start to play, it gives me an error stating that CBA is outdated. I have redownloaded CBA multiple times and checked my mods to see if anything was conflicting but I couldn't find anything. My CBA is in 15.6, yet my Arma keeps kicking me out for being in 15.3.

![image](https://user-images.githubusercontent.com/103394896/162649097-c43ef636-396a-4ac3-958c-3a0a2a88ecbe.png)
The error message here.

**Comment by commy2** [comment]
RPT file?

**Comment by joeballsballs** [comment]
It doesn't crash my game, it kinda just ends the shit and gives me an option to restart the scenario and then it becomes a cycle.
[rpt.docx](https://github.com/CBATeam/CBA_A3/files/8468539/rpt.docx)

**Comment by commy2** [comment]
The CBA version you're loading is from inside the \@TFB-CoreMods addons folder:

19:57:27 D:\New steam\steamapps\common\Arma 3\!Workshop\@TFB-CoreMods\addons\cba_accessory.pbo - 5ee330dc

None of the loaded components are from the \@CBA_A3: See section: `==== Loaded addons ====`

Disable \@TFB-CoreMods and the correct version of CBA will be loaded.

Close?

**Comment by joeballsballs** [comment]
thank you brother you are a life saver

**Comment by Pappy38** [comment]
My CBA does not worked and it says that it is outdated I need help and it's just like joeballsballs and the solution won't work.pls help
