### ISSUE TITLE
Added class EH is not invoked

### ISSUE THREAD

**Issue by mwpowellhtx** [CBATeam/CBA_A3#1559]
**Mods (complete and add to the following information):**
- **Arma 3:** 2.10+ (stable)
- **CBA:** 3.15+ (stable)

**Description:**
Trying to get `CBA_fnc_addClassEventHandler` to work, but the EH are not working.

**Steps to reproduce:**
The basic code is this:
```sqf
[
    MY_preset_fobBoxE
    , MY_preset_fobBoxF
    , MY_preset_fobTruckE
    , MY_preset_fobTruckF
    , MY_preset_fobBuildingE
    , MY_preset_fobBuildingF
    , MY_preset_respawnTruckF
] call {
    private _classesToInit = _this arrayIntersect _this;
    {
        private _mayInherit = true;
        private _excludeNothing = [];
        private _retroactive = true;
        [_x, "init", MY_fnc_onObjectInit, _mayInherit, _excludeNothing, _retroactive] call CBA_fnc_addClassEventHandler;
    } forEach _classesToInit;
};
```

I have verified the basics, CBA is loaded, the CBA function exists, so does the MY function.

With specific log evidence indicating the classes are there:

```
20:13:28 [KP LIBERATION] [35508.4] [PRE] [FOBS] [fn_fobs_onPreInit::forEach] Classes: [count _classesToInit, _classesToInit]: [6,["Land_Pod_Heli_Transport_04_box_F","B_Slingload_01_Cargo_F","O_Truck_03_device_F","B_Truck_01_box_F","Land_Cargo_HQ_V1_F","B_Truck_01_medical_F"]]
20:13:28 [KP LIBERATION] [35508.4] [PRE] [FOBS] [fn_fobs_onPreInit::forEach:0] CBA Init EH: [_class, count _classesToInit]: ["Land_Pod_Heli_Transport_04_box_F",6]
20:13:28 [KP LIBERATION] [35508.4] [PRE] [FOBS] [fn_fobs_onPreInit::forEach:1] CBA Init EH: [_class, count _classesToInit]: ["B_Slingload_01_Cargo_F",6]
20:13:28 [KP LIBERATION] [35508.4] [PRE] [FOBS] [fn_fobs_onPreInit::forEach:2] CBA Init EH: [_class, count _classesToInit]: ["O_Truck_03_device_F",6]
20:13:28 [KP LIBERATION] [35508.4] [PRE] [FOBS] [fn_fobs_onPreInit::forEach:3] CBA Init EH: [_class, count _classesToInit]: ["B_Truck_01_box_F",6]
20:13:28 [KP LIBERATION] [35508.4] [PRE] [FOBS] [fn_fobs_onPreInit::forEach:4] CBA Init EH: [_class, count _classesToInit]: ["Land_Cargo_HQ_V1_F",6]
20:13:28 [KP LIBERATION] [35508.4] [PRE] [FOBS] [fn_fobs_onPreInit::forEach:5] CBA Init EH: [_class, count _classesToInit]: ["B_Truck_01_medical_F",6]
```

Have even tried the brain dead thing in the debug console to no avail, nothing happens:

```sqf
["Land_Cargo_HQ_V1_F", "init", {systemChat str _this}, true, [], true] call CBA_fnc_addClassEventHandler
```

I can tell you there is at least one instance of the class; in fact there are several, but one right under my cursor, i.e. `(cursorTarget isKindOf 'Land_Cargo_HQ_V1_F') == true`.

**Expected behavior:**
Obviously, the EH should fire.

**Where did the issue occur?**
- _Self-Hosted Multiplayer_ (KPLIB refactor)

**Comment by mwpowellhtx** [comment]
So I did try another case:

```sqf
["Helicopter", "init", {systemChat str _this}, true, [], true] call CBA_fnc_addClassEventHandler
```

That does _'work'_ loosely speaking in that it does what the EH does.

But I have specific classes I want to key on. I could say `"Building"`, I suppose, but this is a bit broad of a brush I think.

**Comment by mwpowellhtx** [comment]
Actually, no, hold the phone, `"Building"`, `"Static"`, neither of these work. Is it a problem in the classes themselves? Or something CBA is assuming about those classes?

```sqf
// no joy
["Building", "init", {systemChat str _this}, true, [], true] call CBA_fnc_addClassEventHandler;
// no joy
["Static", "init", {systemChat str _this}, true, [], true] call CBA_fnc_addClassEventHandler;
```

**Comment by commy2** [comment]
See: https://github.com/CBATeam/CBA_A3/issues/311#issuecomment-212285477

Close?
