### ISSUE TITLE
CBA issues

### ISSUE THREAD

**Issue by Kristopher9999** [CBATeam/CBA_A3#1560]
So I have been playing SP for years. As of lately, I am unable to load from previous save points in any SP Campaign/scenario. After I die, I get the large text box (Debug Console) which has buttons at the bottom and I have no clue why this happens.

I have seemed to narrow it down to the CBA\_A3 mod. When not loaded it plays fine. I have deleted and reinstalled. I have tried different CBA mods ect. This is especially irritating, as most community developed campaigns require it.

Thank you for any insight. I will also attempt a screen shot of the dialogue box I am seeing upon dying.

**Comment by Drofseh** [comment]
Please fill out the issue template correctly.

**Comment by Pappy38** [comment]
My CBA mod seems to say that's outdated and can't play the scenario and it's causing me frustration.
