### ISSUE TITLE
User action keys

### ISSUE THREAD

**Issue by Triumphator** [CBATeam/CBA_A3#1574]
20 user action keys are not enough in addon rich environment. Would be nice to increase their count to 80.

**Comment by commy2** [comment]
The number of User Actions is hard-coded to 20 in engine, unless something changed in that regard recently.

**Comment by veteran29** [comment]
As commy2 said the User Actions are provided by the game itself, if you think there should be more of them you can create a feedback ticket for BI here: https://feedback.bistudio.com/
