### ISSUE TITLE
can someone help

### ISSUE THREAD

**Issue by Cuda71666** [CBATeam/CBA_A3#1576]
Everytime I launch my arma 3 game it says that my CBA_A3 is version 3.12, nut when I go over to the extensions option in main window of the game it says its version 3.15.  I have downloaded and upgraded the file now at least a 100 times.  Now I just finished uninstalling the entire game and re installing everything and it still is saying its version 3.12.  Can anyone please help with a fix for this problem.  Thank you in advance.

**Comment by Cuda71666** [comment]
Also when I go into the workshop folder in steam steamapps common arma 3 workshops CBA_A3  every thing in that folder says it is 3.15 as well

**Comment by PabstMirror** [comment]
**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

we've seen other mods "include" a old version of cba, so you might need to enable/disable mods to see which one is doing it
or check the rpt
but a good first step it to try loading just cba
