### ISSUE TITLE
CBA_fnc_taskPatrol creates too many waypoints on dedicated

### ISSUE THREAD

**Issue by whiztler** [CBATeam/CBA_A3#158]
**CBA Version:**
* Latest Steam.

**Mods:**
* `@CBA_A3`
* `@AIATP

**Description:**
* The add waypoint function creates too many waypoints when executing CBA_fnc_taskPatrol. In below mission a squad is placed with the following init:  [this, this, 300, 3, "MOVE", "AWARE", "YELLOW", "FULL", "STAG COLUMN", "", [3,6,9]] call CBA_fnc_taskPatrol;
* In editor preview CBA_fnc_taskPatrol creates 4 waypoints as it should. On dedicated it creates 5-12 waypoints. One time I observed 17 waypoints incl 4 cycle waypoints.

**Steps to reproduce:**
* Start dedi, load mission, start zeus.

**Where did the issue occur?**
* Dedi

**Mission:**
* https://mega.nz/#!EIolxA7A!vWazQeFCUtXlE9oHSRnVeN5HN_IkFRtlsGHd_cbmyoc

**Comment by Killswitch00** [comment]
There was a fix for fnc_taskPatrol just after CBA A3 v2.0 was released which hopefully takes care of this for v2.1. (https://github.com/CBATeam/CBA_A3/commit/4b1db955a0e7a0c01c57f98bcba3c35aaa548269)

**Comment by SilentSpike** [comment]
A locality check should probably also be added into the other 3 "task" functions too :+1:
