### ISSUE TITLE
Latest CBA version does not honor white space in the CBA settings Configuration File for Task Force Arrowhead Radio (BETA)

### ISSUE THREAD

**Issue by EagleTrooper91** [CBATeam/CBA_A3#1619]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14` 
- **CBA:** `CBA_A3 v3.16.0.231017`
_Make sure to reproduce the issue with only CBA on a newly created mission!_

**Description:**
After the recent update to CBA, CBA settings for Task Force Radio Arrowhead (Beta) version 1.0.334 no longer is honored if the CBA settings for TFAR contains spaces. I believe it is related to #1581 which I believe is stripping white space to support multi line.

**Steps to reproduce:**
 - Create a Teamspeak Channel for Task Force Arrowhead Radio with Spaces in the name such as `Main Operation Server`
 - Under the CBA settings configure the TFAR settings... `TFAR_Teamspeak_Channel_Name = "Main Operations Server"`
 - Join a server.
 - You will not get pulled in to the channel but instead stay in the channel you were initially
 - Review the Server Settings and you notice that the Spaces are not honored. You must Change the Teamspeak Channel to have no spaces.
 - Edit the Teamspeak Channel to Match the CBA Settings but without spaces. 
 - You will be instantly moved into the matching channel (Ignoring Spaces)

**Expected behavior:**
 - Be pulled in to the matching Task Force Teamspeak Channel that is listed in the CBA settings Configuration under user config.

**Where did the issue occur?**
- Dedicated & Self-Hosted Multiplayer

**Log Files:**
https://gist.github.com/EagleTrooper91/597f20d60c8144271c7e225263ab42c1

**Additional context:**
This was working just prior to the October 17th 2023 update.

![image](https://github.com/CBATeam/CBA_A3/assets/73040843/a5b11b0b-30f8-47e5-b7a8-2f84ce6f31ee)

![image](https://github.com/CBATeam/CBA_A3/assets/73040843/93d5295d-6e7a-484e-b457-072ecde7f538)

![image](https://github.com/CBATeam/CBA_A3/assets/73040843/790c73a9-73c7-45a3-9fdb-181cc61dde2f)

**Comment by johnb432** [comment]
https://discord.com/channels/976165959041679380/976228110078992456/1164261712371916830

I'm searching for a fix.
