### ISSUE TITLE
Camera not working in Keyframe animation

### ISSUE THREAD

**Issue by EliteGriffin** [CBATeam/CBA_A3#1625]
Idk about all this stuff sorry for not using whatever it is you guys wanted me to use.

Anyway
The keyframe animations are not working with the camera
I wanted to make a short fil and i needed CBA for my other mods. In eden editor I got a camera and simply put down two keys, a curve and a timeline. Connected keys to curve and curve to timeline yatayatayata. When entering the game in singleplayer and I could not get it to work moving the camera, it did work without cba but not with. Idk if this will even be looked at as I did not use the proper format anyway hope it gets fixed soon, thanks.

**Comment by jonpas** [comment]
Post more information on what you did please.

**Comment by EliteGriffin** [comment]
**Mods (complete and add to the following information):**
I ahve used lots of mods but I managed to recreate the issue with only CBA so I am pretty sure this is where the issue lies. It also worked without any mods at all.

I'm sorry I don't know what the below text means really if it's really needed please tell me how I can acces it and maybe explain what it is I would access in that case. If they are verions of game/mod I always use the lastest the auto update gives me.
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]

_Make sure to reproduce the issue with only CBA on a newly created mission!_

**Description:**
I am unable to use keyframe animation with the camera module in the eden editor with CBA enabled.

**Steps to reproduce:**
Create a new scenario. I chose Altis to test this on.
Place a camera, rich curve, 2x rich curve key and a timeline module down.
Sync rich curve to timeline.
On rich curve set orientation mode to "Animation".
On the camera. Enable "Switch to at start".
On the timeline. Enable "Play from start" aswell as "Loop".
Sync rich curve keys to rich curve.
Set time on ONE of the rich curve keys to 10 and leave the other on 0.
(There should now be a red dotted line between thge rich curve keys when one or both are highlighted)
Sync camera to rich curve.
(You should now be able to see a green circle move along the red line between the keys when one or both are highlighted.)
(If you have the little camera window you should be able to see the camera move in real time)

Now play cenario in singleplayer and you should have the view of the camera moving along the red line. However this is not the case.

If you spawn a unit and enter zeus when testing. Right click and press editeble objects > add > 250m.
You should now be able to see a circle moving between two other circles. This is the camera which you should be able to verify by clicking it twice.

Save scenario and try again but with 100% vanilla. The camera should now move with the animation. (At least it does for me)

**Expected behavior:**
For the camera to follow the animation path we created.

**Where did the issue occur?**
-Singleplayer

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
^Don't know what all that means, checked the link and I understand which files you want I think but there are like 10 of them, I do not think they have anything to do with it really and also I don't know how to send them but what do I know^

Sorry for the ver very late response. I hope this helps. If you need anything more please just explain and I am happy to share. (I will respond faster this time I hope lol)

Also github does not seem to support the file type  for the mission. ( The mission fiel is .sqm)

Error message:
We don’t support that file type.
Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP.

**Comment by dive155** [comment]
I wanted to chime in because I'm also experiencing this bug. Removing CBA finally let me use the camera module.

**Comment by EliteGriffin** [comment]
Yea, I tried that but a lot of other mods seem to rely  on CBA so I can't make animations with the mids I want to use

**Comment by Grovac** [comment]
I'm experiencing a similar issue. Switch To At Start does not work for the Keyframe Animation camera with CBA enabled, without CBA it functions as intended.

**Comment by tyehya** [comment]
This issue appears to actually be related to ACE3 rather than CBA_A3. I have filed an issue over there instead.

I tested with only CBA_A3 loaded, worked OK.

Tested with ACE3 on CBA_A3, does not work.

Issue: https://github.com/acemod/ACE3/issues/10387

**Comment by EliteGriffin** [comment]
> This issue appears to actually be related to ACE3 rather than CBA_A3. I have filed an issue over there instead.
> 
> I tested with only CBA_A3 loaded, worked OK.
> 
> Tested with ACE3 on CBA_A3, does not work.
> 
> Issue: [acemod/ACE3#10387](https://github.com/acemod/ACE3/issues/10387)

Ahhh, you are correct. I just done some testing. Idk what I did when testing the first time but it seems I done something wrong (Sorry..) Thank you, now i know how I can make cinematics while keeping most my mods. It is an issue in ACE3 and not CBA
