### ISSUE TITLE
Vehicle Parameter in GetIn Extended Eventhandler has wrong value

### ISSUE THREAD

**Issue by ASDFGamer** [CBATeam/CBA_A3#1635]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.14.151210`
- **CBA:** `3.16.1.231025`

**Description:**
I try to add a GetIn Extended EventHandler to a LandVehicle. I expected to get the Vehicle as a Paramter like it is described in [GetIn EventHandler](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#GetIn), but the first element contained the same player name as the thrid element.  

**Steps to reproduce:**
- Create a new mission in the Editor
- Create a description.ext and insert
  `class Extended_GetIn_EventHandlers {
    class LandVehicle {
        class LandVehiclePhysicalAmmo_GetIn_eh {
            getIn = "diag_log str (_this)";
        };
    };
};`
- Add a Land Vehicle like a Car and a playable Character to the Simulation
- Start the simulation
- Get into the Vehicle

**Expected behavior:**
I would expect that the rpt log contains  a line with the parameters where the first parameter is the vehicle object
Output:  
[B Alpha 1-1:1 ({Player Name}),"gunner",B Alpha 1-1:1({Player Name}),[0]]
Expected Output:  
[{Vehicle Object ID},"gunner",B Alpha 1-1:1({Player Name}),[0]]

**Where did the issue occur?**
Editor (Singleplayer)

**Log Files:**
22:31:19 Starting mission:
22:31:19  Mission file: PhysicalAmmo
22:31:19  Mission world: VR
22:31:19  Mission directory: C:\Users\User\Documents\Arma 3 - Other Profiles\Presa\missions\PhysicalAmmo.VR\
22:31:19 EPE manager release (0|3|0)
22:31:20 [CBA] (xeh) INFO: [522552,16182.7,0] PreInit started. v3.16.1.231025
22:31:20 [CBA] (settings) INFO: Reading settings from settings file.
22:31:20 [CBA] (settings) INFO: Finished reading settings from settings file.
22:31:20 [CBA] (xeh) INFO: [522552,16182.8,0] PreInit finished.
22:31:21 [CBA] (xeh) INFO: [522554,16183.3,0] PostInit started. MISSIONINIT: missionName=PhysicalAmmo, missionVersion=54, worldName=VR, isMultiplayer=false, isServer=true, isDedicated=false, CBA_isHeadlessClient=false, hasInterface=true, didJIP=false
22:31:21 [CBA] (versioning) INFO: [522554,16183.3,0] VERSIONING:cba=3.16.1.231025
22:31:21 [CBA] (xeh) INFO: [522554,16183.3,0] PostInit finished.
22:31:21  Mission id: 9277d417ef72ca5cba208faaa999026e2b956090
22:31:21 [B Alpha 1-1:1 ({Player Name}),"gunner",B Alpha 1-1:1({Player Name}),[0]]

**Comment by PabstMirror** [comment]
`_this select 0` is the vehicle
 `diag_log str (typeOf _this # 0)` and you'll see the vehicles classname
`str vehicle player` and you get `"B Alpha 1-1:1 (Player Name)"`

**Comment by ASDFGamer** [comment]
Thanks for the quick help, that fixes the Problem.
I forgot to check the type of the object, because i was confused by the string representation of it.
