### ISSUE TITLE
 Problem when running arma with cba Addon "cba_ jam _spe" requires addon "WW2_spe_core_c_zzz_lastloaded_c" 

### ISSUE THREAD

**Issue by Martiosivtes** [CBATeam/CBA_A3#1639]
This writing appears and I enter the game normally, but ZEUS & enhanced movement stops working and Other mods that require CBA also do not work even though it is activated (but with the problem)

**Comment by Martiosivtes** [comment]
![20240120_201641](https://github.com/CBATeam/CBA_A3/assets/157266504/357ef7a4-60ee-493e-a9ca-862806d16c62)

**Comment by PabstMirror** [comment]
Please post rpt
latest version of CBA requires 2.14

**Comment by Martiosivtes** [comment]
> Please post rpt latest version of CBA requires 2.14

I have cba v3.16 isn't it the latest  ?

**Comment by Martiosivtes** [comment]
> Please post rpt latest version of CBA requires 2.14

Does my version v3.16.1.231025 require the latest update from Arma?

**Comment by Drofseh** [comment]
> > Please post rpt latest version of CBA requires 2.14
> 
> Is this problem because I need to update Arma? What if I install an older version of CBA, will it be solved?

Steam should automatically update Arma for you.

Upload your RPT as requested.

**Comment by rautamiekka** [comment]
> Steam should automatically update Arma for you.

By no means guaranteed even when an update has already been released by the time you launch the game, often you need to verify the installation to make it realize that.
