### ISSUE TITLE
Server doesn't read cba_settings.sqf file in userconfig

### ISSUE THREAD

**Issue by tiapfy** [CBATeam/CBA_A3#1652]
**Mods:**
- **Arma 3:** `2.16.151618 stable`
- **CBA:** `3.16.1.231025 stable`

**Description:**
I have a server on Linux and I put the cba_settings.sqf file in the userconfig folder, but it doesn't get read and the settings are not applied. I removed the profile files that store the settings selected from the in-game menu. The mission is empty with all default settings. The server is managed by [arma-server-manager](https://github.com/fugasjunior/arma-server-manager) but the developer told me that it shouldn't interfere with the capability of the mods to read the userconfig folder. I guess I'm missing something very obvious but I don't know what to try anymore.

**Where did the issue occur?**
- Dedicated on Ubuntu VPS

**Files:**
- [Server log](https://gist.github.com/tiapfy/45bfc0a6a3b1b9ce3fb07e5109f48dac)
- [cba_settings.sqf file I used](https://gist.github.com/tiapfy/8254f2b4e0f09dff3ce77b58e8dc9a6f)

**Screenshots:**
![image](https://github.com/CBATeam/CBA_A3/assets/31632081/e1cc94c4-e684-4c16-afdd-6cbe2579aea7)
![image](https://github.com/CBATeam/CBA_A3/assets/31632081/e8e7416d-c01f-40ff-b051-6bc54291deca)
![image](https://github.com/CBATeam/CBA_A3/assets/31632081/55709a95-8df1-4a75-aabe-96604075451c)

**Comment by PabstMirror** [comment]
make sure filepatching is enabled on server

**Comment by tiapfy** [comment]
It's should be enabled by looking at the settings page on the manager, is there a way to check if it's really enabled?

**Comment by PabstMirror** [comment]
not familiar with launcher, but you might be able to just add `-filePatching` to the param list?

**Comment by tiapfy** [comment]
> not familiar with launcher, but you might be able to just add `-filePatching` to the param list?

I tried it this afternoon but the custom parameter just disappeared because I guess it figured out that it was already enabled?
