### ISSUE TITLE
removePerframeHandler: Undefined Variable in expression: _x

### ISSUE THREAD

**Issue by ViperMaul** [CBATeam/CBA_A3#169]
<pre> 6:01:17 Error in expression <ewHandle", "_return"];
_return = false;
_x params ["", "", "", "", "", "_publicH>
 6:01:17   Error position: <_x params ["", "", "", "", "", "_publicH>
 6:01:17   Error Undefined variable in expression: _x
 6:01:17 File x\cba\addons\common\fnc_removePerFrameHandler.sqf, line 17</pre>
Reported by the CityLifeRPG.com dev team: ArMaTeC

**Comment by ViperMaul** [comment]
> I think its this http://pastebin.com/36xK8cZb  -ArMaTeC

**Comment by jokoho48** [comment]
found it posible open

**Comment by ViperMaul** [comment]
> I can reproduce error with https://gist.github.com/PabstMirror/ef3e12712269ec63d989 - pabstmirror
