### ISSUE TITLE
Error Local variable in global space in build df1b28c9 

### ISSUE THREAD

**Issue by ViperMaul** [CBATeam/CBA_A3#174]
In testing the latest master df1b28c9 I get the following error 
![Screenshot](https://i.gyazo.com/d57f43783bd3fb01bfa15acf30512d06.png)

__Steps to Repro:__
Start a Client hosted Multiplayer Session
1. Click Play
2. Click Multiplayer
3. Click New
4. Click Ok

Other notes:
This does not repro in an Editor SP mission.

**Comment by ViperMaul** [comment]
The problem does not happen in CBA v2.1

**Comment by Killswitch00** [comment]
Unable to reproduce. *scratching head*

**Comment by jokoho48** [comment]
same as @Killswitch00 can not reproduce

**Comment by jonpas** [comment]
Same, can not reproduce.

**Comment by ViperMaul** [comment]
Probably being triggered by an old mission in my MPMissions directory. We will push this back to 2.2

**Comment by PabstMirror** [comment]
@vipermaul: check JR\config.cpp
`access = ReadAndWrite;`
and config.cpp defines it as `#define ReadAndWrite 0      //! any modifications enabled`
if something got screwed up in the preprocessor, it might be a string in the config?

Can you depbo your JR.pbo and see what it is set to?

**Comment by ViperMaul** [comment]
@PabstMirror
@killswitch pointed me in the same direction. 
But v2.1 does not give me the error. And the JR code hasn't changed between 2.1 and 2.1.1.
But we will check the JR theory anyway. Thanks for the heads up.

**Comment by killswitch** [comment]
I cannot reproduce this either. :)

**Comment by Cuel** [comment]
@khkhalily  This issue isn't the right place to discuss this but you can find older CBA releases right here:
https://github.com/CBATeam/CBA_A3/releases
Here is 2.1.1
https://github.com/CBATeam/CBA_A3/releases/tag/v2.1.1.151010

**Comment by Drofseh** [comment]
@khkhalily Based on the website you linked this isn't the CBA you're looking for.
This is modification called Community Base Addons for the video game Arma3.
Not a data mining tool called Classification Based on Associations.
