### ISSUE TITLE
CBA_ai_fnc_taskPatrol - typo

### ISSUE THREAD

**Issue by Dorbedo** [CBATeam/CBA_A3#175]
typo in CBA_ai_fnc_taskPatrol

[Line 42](../blob/master/addons/ai/fnc_taskPatrol.sqf#L42)
Is:
`[_group] call CBA_fnc_getGroup;`

should be:
`_group call CBA_fnc_getGroup;`

**Comment by Dorbedo** [comment]
As an addition:
`#define NULL    "$null$"`
is obsolete

**Comment by Killswitch00** [comment]
Fixed in eccb431856603650a97a7762d64f895e07cb92b7
