### ISSUE TITLE
CBA_common_fnc_getGroup - toLower instead of toUpper 

### ISSUE THREAD

**Issue by Dorbedo** [CBATeam/CBA_A3#176]
wrong command in CBA_common_fnc_getGroup

[Line 23](../blob/master/addons/common/fnc_getGroup.sqf#L23)
Is:
`if (tolower (typeName _this) == "GROUP") exitwith {_this};`

should be:
`if (toUpper (typeName _this) == "GROUP") exitwith {_this};`

or maybe:
`if (toUpper (typeName _this) isEqualTo "GROUP") exitwith {_this};`

**Comment by dixon13** [comment]
should `isEqualTo` be used since it's faster?

**Comment by jonpas** [comment]
Preferably yes.

**Comment by Dorbedo** [comment]
This was my proposal.

**Comment by Killswitch00** [comment]
Fixed in eb6eae8b91eefa8f0b15685f7e418e2924a1f423
