### ISSUE TITLE
getGroup error

### ISSUE THREAD

**Issue by whiztler** [CBATeam/CBA_A3#182]
getGroup throws an error:

> 18:52:24 Error in expression <me _this) == "GROUP") exitwith {_this};
> group _this
> }>
> 18:52:24   Error position: <group _this
> }>
> 18:52:24   Error group: Type Array, expected Object
> 18:52:24 File x\cba\addons\common\fnc_getGroup.sqf, line 24

Called from taskPatrol:

> [_g, _spawnPos, 350, 4, "MOVE", "SAFE", "RED", "LIMITED", "", "", [0,0,0]] call CBA_fnc_taskPatrol;

Where _g is a valid group. 

Possible fix for getGroup:

```javascript
	params ["_g"];
	if (tolower (typeName _g) == "GROUP") exitwith {_g};
	group _g
```

Currently functions that call CBA_fnc_getGroup break scripts (and missions).

Possible to release a hotfix?

**Comment by jokoho48** [comment]
this fix the issue https://github.com/CBATeam/CBA_A3/commit/6a4ab283bba98a96576bf9abb538dd31ab82a1a9 but this is not in release

**Comment by MikeMatrix** [comment]
Maybe we should auto transform the parameter, if it's given in array form. Makes sense anyways imo, and keeps call styles more consistent, to avoid errors like these.

**Comment by whiztler** [comment]
Bit of compliancy will go a long way. 

Pass as array:
> [x] call CBA_fnc_XXX

Define a local var in the function:
> params ["_passedVar"];
