### ISSUE TITLE
getPos is a brittle function

### ISSUE THREAD

**Issue by SilentSpike** [CBATeam/CBA_A3#187]
Same deal as fix #183 for #182.

`CBA_fnc_getPos` uses brittle code that can't handle input in array form because it deals directly with variable `_this`, however it's a bit more problematic to fix and retain backwards compatibility since the parameters passed can be an array of the form `[x,y,z]`.

**Comment by MikeMatrix** [comment]
`params ["_x", "_y", "_z"]` and then check if _x is array, if so, then `_x params ["_x", "_y", "_z"]` as a potential solution? (didn't check if this code is viable at all)

**Comment by Killswitch00** [comment]
Please unbrittle it and submit a PR :-)

**Comment by SilentSpike** [comment]
Internally debating whether it's worth it :smile:

Just reported for tracking purposes. If you guys think it shouldn't be then I'll go ahead and fix it

**Comment by commy2** [comment]
Why would someone do
`[x,y,z] call CBA_fnc_getPos`

I guess the description states that `Marker, Object, Location, Group or Position` are supported (but not Task apparently) but that doesn't really make sense to me.

**Comment by SilentSpike** [comment]
^ Commy's changes do fix it, a good solution :+1:
