### ISSUE TITLE
CBA Interaction with Arma Eden editor can cause a crash

### ISSUE THREAD

**Issue by Aquims** [CBATeam/CBA_A3#198]
Hey guys, hope you can get something from this.

Been looking into a DevBrach Eden Editor crash and have been able to reproduce it with a blank map, with only one player object, and only CBA running (have 2.1.2.151016) 

This issue occurs with a Saved map, after you preview, you will get a popup and a warning like the following in the rpt:
0:01:45 Warning Message: '/' is not a class ('Extended_PostInit_EventHandlers' accessed)
0:01:45 Warning Message: '/' is not a class ('Extended_InitPost_EventHandlers' accessed)

At this point if you attempt to preview again odds are it will crash, or for sure if you try and exit the editor it will crash. 

Did report this to the Bohemia guys (http://feedback.arma3.com/view.php?id=26572) so see where that goes. But I did not see anything logged around this, so wanted to point it out incase you can handle things on your end. 

Let me know if I can grab any data for you.

**Comment by PabstMirror** [comment]
If it happens with just CBA, we should throw the issue over to CBA's tracker https://github.com/CBATeam/CBA_A3/issues.

We're still waiting on on 1.54, so this problem is pretty far away, if you do have a full RPT we might be able to take a look.

**Comment by jonpas** [comment]
@PabstMirror This is the CBA issue tracker.

**Comment by PabstMirror** [comment]
opps,
When going from in game back to eden, CBA will re run init, and at some point `missionConfigFile` doesn't exist anymore.  `isClass missionConfigFile` = false???

Made a test branch that fixes error warnings https://github.com/CBATeam/CBA_A3/compare/local_keyword_fixes...dev155-missingMissionConfig?expand=1
However it didn't fix the crash, which really could be from anything.

**Comment by Aquims** [comment]
Thanks :) Working with Bohemia to have them repro the crash so hopefully they can address from there side. The more mods you have the greater the RPT spam with warnings gets. How the editor handles the dialog box that gets displayed while you have autosave enabled at mission end, may also be tied to a nasty bug they have that results in the mission file being reset to blank.

**Comment by Aquims** [comment]
Thanks for the input on the BI thread, but they seem to have closed the ticket. So not sure if you can/want to try and push it further: http://feedback.arma3.com/view.php?id=26572

Almost ready to go back to the 2d editor. 

Anyway, love the CBA guys, keep doing great work.

Thanks, Matt.
