### ISSUE TITLE
building keybinding addon gives error

### ISSUE THREAD

**Issue by kOepi123** [CBATeam/CBA_A3#222]
Hey guys,

I have this problem here, very serious for my work, I dont know any way around it.

extracted a pbo, made it with addonbuilder, pboproject ( full build ) and makepbo.

Run into this error, when starting in the editor:

RPT:
18:35:11 [735,56.057,0,"CBA_VERSIONING: cba=2.2.0.151130, "]
18:35:11 [735,56.071,0,"XEH: PostInit Finished. State: _isClient=true, _isJip=false, _isDedClient=false, _isServer=true, _isDedServer=false, _playerCheckDone=true, _sp=true, _startInitDone=true, _postInitDone=true, _mpRespawn=false, _machineType=1, _sessionId=1, _level=0, _timeOut=false, _game=3, BIS_functions=<NULL-object>, group=<NULL-group>, player=C Alpha 3-3:1 (kOepi), _playerType="C_man_p_beggar_F", _playerGroup=C Alpha 3-3"]
18:35:13 Error in expression <ding_dikDecToStringTable, format ["%1", _x], format ["Unknown key (%1)",_x]] cal>
18:35:13   Error position: <_x], format ["Unknown key (%1)",_x]] cal>
18:35:13   Error Undefined variable in expression: _x
18:35:13 File x\cba\addons\help\XEH_postClientInit.sqf, line 22
18:35:13 Error in expression <9} else {0};
_keys = [_shift,_ctrl,_alt,_dikKey];
_keystrg = "^";
{
_knaml = [cb>
18:35:13   Error position: <_dikKey];
_keystrg = "^";
{
_knaml = [cb>
18:35:13   Error Undefined variable in expression: _dikkey
18:35:13 File x\cba\addons\help\XEH_postClientInit.sqf, line 19
18:41:47 Starting mission:

------------------------------------------------------------------------------------------------

Strange thing is, sometimes I just load the original PBO and it does not give me any error.

Is this a problem on my end or really something in the CBA?

greetz

kOepi

**Comment by PabstMirror** [comment]
Try downloading a clean copy from github
Run setup.py in tools to add a p:\x\cba link
then run make.py

That will be the same build path that we know is working ok.

**Comment by kOepi123** [comment]
@PabstMirror 
I have no idea what you mean with ".py" and "tools" or how to run make .py

This is what I did:
I installed github desktop, download the cba version and tried to build it on my p drive with addonbuilder and pboproject.

I get these errors, addonbuilder, pboproject:

Include file x\cba\addons\main\script_mod.hpp not found.
Error reading config file P:\CBA_repository\CBA_A3\addons\ai\config.cpp

and

config.cpp In File CBA_repository\CBA_A3\addons\ai\script_component.hpp: Line 2 Cannot include file

**Comment by jokoho48** [comment]
@kOepi123 execute this:
`profileNamespace setVariable ["cba_keybinding_registryNew", nil]; saveProfileNamespace;`
and then restart arma and try to reporduce

**Comment by kOepi123** [comment]
I was able to build the CBA_A3 from the github, but with one error in xeh_a3.
Executed jokos command, perror was gone, restarted the game with the newly packed cba and had the same problem again.
Might be I have done something wrong, no idea.

**Comment by Killswitch00** [comment]
@kOepi123 - you need to have CBA on the P drive in the folder `P:\x\cba`, not in `P:\CBA_repository\CBA_A3` in order to build CBA.

setup.py is a [Python](https://www.python.org/downloads/release/python-2711/) script file in the CBA repository `tools` folder that helps you set up P:\x\cba. (You can do it manually too, of course).

**Comment by Killswitch00** [comment]
If this is still an issue, please see [Building CBA from source](https://github.com/CBATeam/CBA_A3/wiki/Building-CBA-from-source)
