### ISSUE TITLE
Kicked from server: cba_ai.pbo not the signed version

### ISSUE THREAD

**Issue by raziel420** [CBATeam/CBA_A3#224]
After exhausting every possible combination of "Reinstall" I'm still running into the same issue.  I have a dedicated server running ArmA3, CBA, and ACRE 2.  Other people can join the server with no issues, but I get kicked due to cba_ai.pbo not being the signed version.  I've copied my local CBA to the server for operation there, and others can join, but I get kicked, I've copied the server version to local, same issue, I've completely removed both, downloaded fresh copies, and still same issue.

**Comment by commy2** [comment]
Can you provide a RPT from the server and your client?
The kick only happens to you and everybody else can connect without problem, correct?

**Comment by Rainemakerx** [comment]
The kick only happens when I the server Owner/Operator, tries to join, I have made 100% sure that the data for the server is identical to that for the clients, I am the only person who has the issue, I don't have a proper Log of the server kicking me sadly, but if you can tell me where to hunt the logs down I'll see if i can produce one.

**Comment by dixon13** [comment]
Logs by default are stored in "AppData\Local\Arma 3\blahblah.rpt

**Comment by Rainemakerx** [comment]
[arma3_2015-12-19_22-05-16.zip](https://github.com/CBATeam/CBA_A3/files/68034/arma3_2015-12-19_22-05-16.zip)

Attached is a zipped version of the RPT from the client, the server is running on a linux machine, and I cannot seem to find the log files in the server directory at all.

**Comment by commy2** [comment]
The opening post mentions that the game was started using `@CBA` and `@ACRE 2`. The RPT however says that `@CBA_A3` and `@USAF` were used.

There is a large amount of potentially critical errors in your RPT that could lead to a server kick.

1. disable the `@USAF` and __all other addons__ except `@CBA_A3` on your server __and__ on __all clients__ connecting to the server.

If that doesn't work then __also__:
2. Unplug the Joystick/Controller, restart the computer and then try to connect again.

```
22:05:28 Updating base class ->BulletCore, by a3\weapons_f\config.bin/CfgAmmo/BulletBase/
22:05:28 Updating base class ->MissileCore, by a3\weapons_f\config.bin/CfgAmmo/MissileBase/
22:05:28 Updating base class ->RocketCore, by a3\weapons_f\config.bin/CfgAmmo/RocketBase/
22:05:28 Updating base class ->GrenadeCore, by a3\weapons_f\config.bin/CfgAmmo/GrenadeBase/
22:05:28 Updating base class ->MissileBase, by a3\weapons_f\config.bin/CfgAmmo/M_Scalpel_AT/
22:05:28 Updating base class ->MissileBase, by a3\weapons_f\config.bin/CfgAmmo/M_Air_AA/
22:05:28 Updating base class ->CA_Magazine, by a3\weapons_f\config.bin/CfgMagazines/VehicleMagazine/
22:05:28 Updating base class ->60Rnd_CMFlare_Chaff_Magazine, by a3\weapons_f\config.bin/CfgMagazines/300Rnd_CMFlare_Chaff_Magazine/
22:05:28 Updating base class ->LauncherCore, by a3\weapons_f\config.bin/cfgWeapons/RocketPods/
22:05:28 Updating base class ->MGunCore, by a3\weapons_f\config.bin/cfgWeapons/MGun/
22:05:28 Updating base class ->SmokeLauncher, by a3\weapons_f\config.bin/cfgWeapons/CMFlareLauncher/
22:05:28 Updating base class ->LauncherCore, by a3\weapons_f\config.bin/cfgWeapons/MissileLauncher/
22:05:28 Updating base class ->CannonCore, by a3\weapons_f\config.bin/cfgWeapons/gatling_20mm/
22:05:28 Updating base class ->RocketPods, by a3\weapons_f\config.bin/cfgWeapons/missiles_SCALPEL/
22:05:28 Updating base class ->CannonCore, by a3\weapons_f\config.bin/cfgWeapons/cannon_120mm/
22:05:28 Updating base class ->GrenadeLauncher, by a3\weapons_f\config.bin/cfgWeapons/UGL_F/
22:05:28 Updating base class ->Rifle, by a3\weapons_f\config.bin/cfgWeapons/Rifle_Base_F/
22:05:28 Updating base class ->Default, by a3\weapons_f\config.bin/cfgWeapons/ItemCore/
22:05:29 Updating base class ->InventoryItem_Base_F, by a3\characters_f\config.bin/cfgWeapons/HeadgearItem/
22:05:29 Updating base class ->SlotInfo, by a3\weapons_f_mark\config.bin/UnderBarrelSlot/
22:05:29 Updating base class ->Turrets, by USAF_cv22\config.bin/CfgVehicles/Plane_Base_F/Turrets/
22:05:29 Updating base class Crew->Mi17_Cargo02, by USAF_cv22idws\config.bin/CfgMovesMaleSdr/States/Stryker_Commander_EP1/
22:05:29 Updating base class ->Turrets, by USAF_hh60g\config.bin/CfgVehicles/Helicopter/Turrets/
22:05:29 Updating base class ->Crew, by a3\cargoposes_f\config.bin/CfgMovesMaleSdr/States/pilot_plane_cas_01/
22:05:29 Updating base class ->PreciseCrew, by a3\cargoposes_f\config.bin/CfgMovesMaleSdr/States/pilot_plane_cas_01_getin/
22:05:29 Updating base class ->pilot_plane_cas_01_getin, by a3\cargoposes_f\config.bin/CfgMovesMaleSdr/States/pilot_plane_cas_01_getout/
```
```
22:05:53   bin\config.bin/CfgMovesMaleSdr/States/F22_Pilot.interpolateTo: Bad move KIA_AH1Z_Pilot
22:05:53   bin\config.bin/CfgMovesMaleSdr/States/F16_Pilot.interpolateTo: Bad move KIA_F35B_Pilot
22:05:53   bin\config.bin/CfgMovesMaleSdr/States/otkkneela1_cargo.interpolateTo: Bad move KIA_AH6_Gunner
22:05:53   bin\config.bin/CfgMovesMaleSdr/States/otkkneels1_cargo.interpolateTo: Bad move KIA_AH6_Gunner
22:05:53   bin\config.bin/CfgMovesMaleSdr/States/otkkneela3_cargo.interpolateTo: Bad move KIA_AH6_Gunner
22:05:53   bin\config.bin/CfgMovesMaleSdr/States/otkkneelA2_cargo.interpolateTo: Bad move KIA_AH6_Gunner
```
```
22:06:39 Inventory item with given name: [B_UavTerminal] not found
22:06:39 Inventory item with given name: [itemcompass] not found
22:06:39 Inventory item with given name: [itemmap] not found
22:06:39 Inventory item with given name: [itemwatch] not found
22:06:39 Inventory item with given name: [nvgoggles] not found
```

**Comment by Rainemakerx** [comment]
2015/12/21, 23:17:23 Unsupported language English in stringtable
This is the Raw Dump from the server, Not a log file sadly, this connection was attempted with the server and client both only running CBA_A3, No control interfaces other than mouse and keyboard connected

2015/12/21, 23:17:23 Unsupported language English in stringtable
2015/12/21, 23:17:23 A3\Missions_F_Heli\MPScenarios\MP_GroundSupport04.Altis: string @STR_A3_MP_GS_SC_04_Overview_text cannot be localized client-side - move to global stringtable
23:17:25 Player Raine: Wrong signature for file D:\Steam\steamapps\common\Arma 3\@CBA_A3\addons\cba_ai.pbo
23:17:25 Player Raine disconnected.
23:17:25 BattlEye Server: Player #0 Raine disconnected

**Comment by commy2** [comment]
https://github.com/CBATeam/CBA_A3/issues/224#issuecomment-166202875

**Comment by Killswitch00** [comment]
Unable to reproduce problem with signature verification on a Linux server with A3 1.54 and CBA 2.2.0 - it works just fine.

Rainemakerx, do exactly what commy2 tells you to do - remove all other addons and mods except CBA on both client and server.

**Comment by commy2** [comment]
Related? http://feedback.arma3.com/view.php?id=22914

**Comment by Rainemakerx** [comment]
ok so here is the latest output from server, with CBA_A3 only, and the zipped RPT from the client attached,

Setting breakpad minidump AppID = 107410
18:11:35 Game Port: 2302, Steam Query Port: 2303
2015/12/26, 18:11:35 Initializing Steam server - Game Port: 2302, Steam Query Port: 2303
Arma 3 Console version 1.54 : port 2302
2015/12/26, 18:11:35 Connected to Steam servers
18:14:44 Raine uses modified data file
18:14:44 BattlEye Server: Player #0 Raine (192.168.1.10:2304) connected
18:14:44 Player Raine connecting.
18:14:46 BattlEye Server: Player #0 Raine - GUID: d20c49479e0fd155a54d96c297f3a263 (unverified)
18:14:46 Player Raine connected (id=76561197976808854).
18:14:46 BattlEye Server: Verified GUID (d20c49479e0fd155a54d96c297f3a263) of player #0 Raine
2015/12/26, 18:14:47 Unsupported language English in stringtable
2015/12/26, 18:14:47 Unsupported language English in stringtable
2015/12/26, 18:14:47 A3\Missions_F_Heli\MPScenarios\MP_GroundSupport04.Altis: string @STR_A3_MP_GS_SC_04_Overview_text cannot be localized client-side - move to global stringtable
18:15:09 Player Raine: Wrong signature for file D:\Steam\steamapps\common\Arma 3\@CBA_A3\addons\cba_ai.pbo
18:15:09 Player Raine disconnected.
18:15:09 BattlEye Server: Player #0 Raine disconnected



[arma3_2015-12-26_18-11-55.zip](https://github.com/CBATeam/CBA_A3/files/72542/arma3_2015-12-26_18-11-55.zip)

**Comment by Rainemakerx** [comment]
removed my IP from the list of accepted headless client IPs, was still kicked from the server, server messages were identical to above, with a different timestamp.

**Comment by Rainemakerx** [comment]
at this point i've tried everything mentioned as well as unmentioned things like disabling signature checks on the server (disabling signature checks worked by the way, but leaves my server vulnerable)

**Comment by commy2** [comment]
Thats certainly strange. The keys seem to work correctly as no one else has any problems with them.
I have no explanation for this. If you downloaded CBA from Steam then you could try to use CBA from this DL instead: http://www.armaholic.com/page.php?id=18767 .

**Comment by Glowbal** [comment]
Just to diagnose the problem; try to remove cba_ai.pbo and reconnect to your signature enabled server. That would let you know if the problem is just with that pbo or if something else is going on.

If it is just that pbo, it could indicate a faulty download. Try from armaholic (like @commy2 linked) or [latest from Github](http://github.com/CBATeam/CBA_A3/releases/latest).

Otherwise, it may still be worth an attempt to replace your CBA installation with one of the above, but look into duplicate CBA installations (for example: `@CBA_A3` in your documents Arma3 folder).

Oh, and you have checked that signature checking is set to 2 and on your machine file patching is not enabled?

**Comment by Rainemakerx** [comment]
I just discovered this happens with Epoch as well, joining a server other than my own, at this point I have no earthly idea what is going on. I have completely reinstalled Arma 3, deleting everything and installing fresh from steam, and I'm still experiencing the same issue.

**Comment by dixon13** [comment]
Must be related to @commy2's post above: https://github.com/CBATeam/CBA_A3/issues/224#issuecomment-167310298

**Comment by Rainemakerx** [comment]
@dixon13 there is no headless client being run, at all,

**Comment by dixon13** [comment]
I know there are no headless clients, but the issue related to server keys could be the issue related to your problem.

**Comment by commy2** [comment]
I'm sorry, but I don't think we can resolve that issue. You probably have to turn either BI or to Battle eye.
http://www.battleye.com/contact/

**Comment by Cuel** [comment]
I'm the reporter for [invalid bisign on linux](http://feedback.arma3.com/view.php?id=27172) and I've only seen it happen for headless clients.

The invalid signatures will actually change as mods are added / disabled, and if enough are disabled it'll magically work again. Only running CBA on the HC would work fine from my earlier tests.
