### ISSUE TITLE
No information on CBA wiki about how to manually seutp the dev environment

### ISSUE THREAD

**Issue by dixon13** [CBATeam/CBA_A3#225]
I noticed when using setup.py, I for some reason had to manually setup the symbolic links. Well, there is no information on how to create a symbolic link between folders on the CBA wiki.

**Comment by jonpas** [comment]
setup.py creates junctions for you, make sure to start it as administrator. If it doesn't work I can take a look at it, but it worked for me just 2 days ago.

**Comment by dixon13** [comment]
I think it was just me and my comp being weird, but I just wanted to point out that it told me I could manually create the junctions by going to the CBA wiki and following the instructions, there are no instructions.

**Comment by jonpas** [comment]
Ah I see what you mean now, I'll add it later today, thanks for noticing!

**Comment by Killswitch00** [comment]
@jonpas - the add-to-wiki still needs to be done.

**Comment by jonpas** [comment]
@Killswitch00 I totally forgot about this! However, now I see I can't edit the wiki anymore, since it was closed to only team members can edit.

**Comment by Killswitch00** [comment]
Great - I'll review the article as soon as I can and give you feedback, if needed.

**Comment by Killswitch00** [comment]
Article added to wiki: [Building CBA from source](https://github.com/CBATeam/CBA_A3/wiki/Building-CBA-from-source)

**Comment by jonpas** [comment]
The link to my gist won't work anymore as I removed it.

Really didn't need to write me down as author anyways. ;)
