### ISSUE TITLE
Battleye Script Error #22 "fnc_addWeaponCargoGlobal"

### ISSUE THREAD

**Issue by DougieDayz** [CBATeam/CBA_A3#227]
#22 "fnc_addWeaponCargoGlobal","CBA_fnc_createCenter","CBA_fnc_createMarker","CBA_fnc_createTrigger","CBA_fnc_defaultParam","CBA_fnc_"

**Comment by commy2** [comment]
Can you please give more context? Or at least one full sentence?

The server you are playing on has battle eye set up to block one or more SQF commands. You can't use CBA with those battle eye settings. If you are the server admin, then remove the commands from the battle eye blacklist.

**Comment by commy2** [comment]
@DougieDayz

**Comment by janek26** [comment]
OK, so I think @DougieDayz is afk forever. :smile: 

But I got the same prob, and will give you my files, so maybe you can help me, and many others :smile: 

[scripts.txt](https://github.com/CBATeam/CBA_A3/files/103165/scripts.txt)

[scripts.log](https://github.com/CBATeam/CBA_A3/files/103166/scripts.log.txt)

If you need any more Information just let me know :+1:
Its actually an ARMA3 Server with Exile and CBA. scripts.txt fom ExileMod.

**Comment by commy2** [comment]
This is solved by adding exceptions to Battle eye.
