### ISSUE TITLE
 cba_common_PFHhandles, Error Max array size would be reached.

### ISSUE THREAD

**Issue by commy2** [CBATeam/CBA_A3#229]
>Error Max array size would be reached. Current size: 999999, wanted size: 1000000.

Another one of these:
https://forums.bistudio.com/topic/168277-cba-community-base-addons-arma-3/?p=2962614

Apparently happens only after long sessions. Might be caused by misuse of `CBA_fnc_addPerFrameHandler` (could also be something in ACE, or some different addon entirely)

I think this needs some debuging messages when the 1kk array size is reached to figure out what the cause is.

Related:
```
_publicHandle = cba_common_PFHhandles pushback _handle;
_data = [_func, _delay>
 7:10:18   Error position: <pushback _handle;
_data = [_func, _delay>
 7:10:18   Error Max array size would be reached. Current size: 999999, wanted size: 1000000.
 7:10:18 File x\cba\addons\common\fnc_addPerFrameHandler.sqf, line 16
 7:10:18 Error in expression <
```

No idea if related, but this error was spammed before PFH started:
```
if (alive btr_1) then {
btr_1 setpos [ getmarkerPo>
 3:57:43   Error position: <btr_1) then {
btr_1 setpos [ getmarkerPo>
 3:57:43   Error Undefined variable in expression: btr_1
 3:57:43 File mpmissions\__cur_mp.Woodland_ACR\mission\vehicle_fix.sqf, line 3
 6:44:23 Error in expression <e_fix.sqf"
while {true} do {
```

**Comment by jokoho48** [comment]
i think this "bug" is not fixable without changing the system completly

**Comment by PabstMirror** [comment]
I think it should be fixed by the people calling the code, adding PFEH each frame should not be happening.  

otherwise I see two options:

 - `GVAR(PFHhandles)` would become an array of arrays.  E.G. 0-100,000 in first array, 0-200,000 in 2nd array, and so on. Downside is increased complexity, and at some point we're going still going to have floating point precision problem of huge handle numbers.

 - Reuse old handles. biggest problem is you can get unexpected results. It breaks the promise we give that handles will always be unique.  It would only kick in after there is a problem so it's more about keeping the game working. Made a quick (untested) prototype here: https://github.com/CBATeam/CBA_A3/commit/cf8babfdeba9f89d4d8af7382806c89f1817d37a

**Comment by commy2** [comment]
My first step would simply adding debug into the RPT to see which function(s) are added so much. Both cases here used ACE, so maybe we can fix it ourselves.

**Comment by Killswitch00** [comment]
`pushBack` will return a negative array index (-1) when you add the millionth element to an array. In this case, it happens in `CBA_fnc_addPerFrameHandler` and we then put that result (`_publicHandle`) into an array that is then added to the end of `cba_common_perFrameHandlerArray`.

Later, when `CBA_fnc_removePerFrameHandler` is called and that negative array index is used in the expression `GVAR(PFHhandles) set [_publicH, _newHandle]` and the followup error is logged.
(`publicH` will be -1 here)

Possible fixes and workarounds:

 * Put a check in `CBA_fnc_addPerFrameHandler` to avoid adding "element 1M". (Return -1 indicating failure to the caller)

However, as mentioned, the core issue is why is CBA_fnc_addPerFrameHandler being called one million times?

**Comment by commy2** [comment]
Related issue: https://github.com/CBATeam/CBA_A3/issues/230

**Comment by commy2** [comment]
In the current 1.55 dev there seems to be a different array size limit:
```
_a = []; _a resize 1E6; _a pushBack 1
-> 1e+006
```

```
_a = []; _a resize 1E7+1; _a pushBack 1
-> 0
```

They seem to overflow instead:
```
_a = []; _a resize (1E7+1); _a pushBack 1; _a
-> [1]
```

**Comment by commy2** [comment]
I think this can be closed. I'm pretty sure now, that this happened, because BI was tinkering with array size limits. There seem to be no more reports of this.
