### ISSUE TITLE
Cba_a3 issue when starting arma

### ISSUE THREAD

**Issue by krispycrunch** [CBATeam/CBA_A3#237]
When I try to start arma with cba it says this, Cannot open file 'D:\Steam\steamapps\common\Arma3\@cba_a3.\addons\cba_ai'

I have reinstalled uninstalled a bunch of times and still get this issue. I restarted my computer and my steam and still nothing. Please help.

**Comment by dixon13** [comment]
could be that there is a dot after '@CBA_A3'

**Comment by PabstMirror** [comment]
Could you post a copy of the RPT file of when you encounter this issue.

It can be found at`%localappdata%/Arma 3/`, post file to https://gist.github.com/, and post link back here.

**Comment by commy2** [comment]
No response, close. If the issue persists, feel free to open another issue.
