### ISSUE TITLE
JM coding for MX Rifles

### ISSUE THREAD

**Issue by EricJ562** [CBATeam/CBA_A3#252]
I brought this up on the BI Forums but only issue is that the MX rifles (MX,MXC,MX 3GL, and MXM) simply don't have coding for the JM portion of the CBA_JR module. Personally its obviously not game breaking but overall other weapons have it.

**Comment by PabstMirror** [comment]
Looks like all these need joint muzzles as well.
```
LMG_Mk200_F - bin\config.bin/CfgWeapons/LMG_Mk200_F/WeaponSlotsInfo/MuzzleSlot
LMG_Zafir_F - bin\config.bin/CfgWeapons/LMG_Zafir_F/WeaponSlotsInfo/MuzzleSlot
srifle_DMR_01_F - bin\config.bin/CfgWeapons/srifle_DMR_01_F/WeaponSlotsInfo/MuzzleSlot
srifle_GM6_F - bin\config.bin/CfgWeapons/srifle_GM6_F/WeaponSlotsInfo/MuzzleSlot
srifle_LRR_F - bin\config.bin/CfgWeapons/srifle_LRR_F/WeaponSlotsInfo/MuzzleSlot
arifle_Katiba_F - bin\config.bin/CfgWeapons/arifle_Katiba_F/WeaponSlotsInfo/MuzzleSlot
arifle_MX_F - bin\config.bin/CfgWeapons/arifle_MX_F/WeaponSlotsInfo/MuzzleSlot
srifle_DMR_04_F - bin\config.bin/CfgWeapons/srifle_DMR_04_F/WeaponSlotsInfo/MuzzleSlot
```

**Comment by robalo** [comment]
MX and Katiba only.

Mk200, Zafir, DMR_01 have JR muzzle slots already.
GM6, LRR don't support suppressors in vanilla, not sure if they even have the required proxies, so why bother.
DMR_04 is integrally suppressed.
