### ISSUE TITLE
Addons keybinds control panel not working in eden

### ISSUE THREAD

**Issue by SzwedzikPL** [CBATeam/CBA_A3#253]
Eden editor -> Settings -> Controls  -> Configure Addons
http://i.imgur.com/B9uf6Id.jpg

Arma 1.56 RC (1.56.134344)
CBA latest master (https://github.com/CBATeam/CBA_A3/commit/1fde193c22308f3719715e7b3c28d1a357b7986c)

**Comment by PabstMirror** [comment]
Looks like in the eden editor, preInit but not postInit happens.
That's BIS behaviour, I think best we can do is to just throw a warning up.
Previewing from eden editor works fine/
