### ISSUE TITLE
Array Function CBA_fnc_findMin is broken.

### ISSUE THREAD

**Issue by Sergeant-Rock** [CBATeam/CBA_A3#257]
In the function the variable _max need to be replaced with _min. I think this may havbe resulted from a copy/paste error with CBA_fnc_findMax. Simple fix.

I've highlighted in the current function the issues:

#include "script_component.hpp"
SCRIPT(findMin);

private ["_index"];

if (!IS_ARRAY(_this)) exitWith {nil};
if (_this isEqualTo []) exitWith {nil};

params ["_min"];
_index = 0;

{
    if (isNil "_x" || {(typeName _x) != (typeName 0)}) exitWith {**_max** = nil; _index = nil;};
    if (_min > _x) then {_min = _x; _index = _forEachIndex};
} forEach _this;

if (isNil "**_max**") exitWith {nil};
[_min, _index] // Return

**Comment by jokoho48** [comment]
https://github.com/CBATeam/CBA_A3/blob/master/addons/arrays/fnc_findMin.sqf
allready fixed

**Comment by Sergeant-Rock** [comment]
Great, I take it this will be in the next release? Thx.

**Comment by jonpas** [comment]
Yes it will be.

**Comment by commy2** [comment]
Close, because already fixed.

**Comment by commy2** [comment]
ref: https://github.com/CBATeam/CBA_A3/pull/207
