### ISSUE TITLE
Script error: fnc_removeKeyHandler

### ISSUE THREAD

**Issue by BABACHORI** [CBATeam/CBA_A3#259]
ACE3 Version: 3.4.2.0(some files is moded: ace_maptools, ace_compat_rhs_afrf3, ace_compat_rhs_usf3)
**Mods:**
* `@ACE3`
* `@REALWAR`
* `@REALWAR_islands`
* `@task_force_radio`
* `@DynaSound`
and both RHS

**Placed Modules:**
Set Medical Vehicle
Set Medical Facility
Set Medic Class
Medical Settings
Advanced Medical Settings
Assign Repair Vehicle
Assign Repair Facility
Assign Engineer
Repair Settings
Cargo Settings
Explosive System
Pointing Settings
Hearing
Sitting
Weather
Advanced Balistics sync with Wind Deflection
WMT Main
WMT Time
View Distance Limiter
TFAR - Enforce Usage
**Description:**
I have only this:
```
_idx = _keyData select 0;
if (count _handlers > _idx) then {
    _myHandlers = _handlers select _idx;
```
Error undefined variable in expression: _idx
File x\cba\addons\events\fnc_removeKeyHandler.sqf, line 39

**Steps to reproduce:**

You need to run mission with this mission.sqm https://goo.gl/RnVi2x
Go to editor and load mission
When you loading and if you have **Show scripted errors** turn on you see this error
If you try to go to Arsenal you got the same
RPT File: https://goo.gl/EpD3wN

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by commy2** [comment]
Hello,
Can you please upload the RPT file?

You can find it under: `%LOCALAPPDATA%/Arma 3`
It is the newest file as long as you just tried to start your repro mission.

**Comment by commy2** [comment]
I loaded the mission, but no error happened.

I opened the RPT (https://goo.gl/EpD3wN), but there was no error inside either. The displayed error did not happen in that game session either. (You can open the .rpt file with any text editor)

Can you try to reproduce this with only @CBA_A3 enabled?

**Comment by BABACHORI** [comment]
I will try but do you turn on an **Show scripted errors**?

**Comment by commy2** [comment]
Yes. All displayed script errors are always logged inside the RPT file too.

**Comment by BABACHORI** [comment]
The problem is in @REALWAR(has cba_a3) and @ACE3

**Comment by commy2** [comment]
Where can I download @REALWAR ?
I suggest removing CBA from the @REALWAR folder and using an offical version of CBA instead.

**Comment by BABACHORI** [comment]
https://arma3realwar.ru/mirror1/.a3s/autoconfig repository link for Arma3Sync.
CBA in @REALWAR is official and not moded, but I will try to delete CBA and use it in other folder instead @REALWAR

**Comment by commy2** [comment]
I downloaded ArmaSync, but it crashed on me. Any alternative download link?

**Comment by BABACHORI** [comment]
http://net2ftp.ru/node0/realwar@inbox.ru/%40REALWAR.rar

**Comment by commy2** [comment]
Thanks! Download will take several hours unfortunately.
I just need to start @Realwar and @ACE and the error will happen or do I need anything else?

**Comment by BABACHORI** [comment]
Yes, i see error in rpt. But @REALWAR needs RHS and there not critical errors

**Comment by commy2** [comment]
`@RHSAFRF;@RHSUSAF;@REALWAR;@ACE`

**Comment by commy2** [comment]
will take another look at this after #284 , which potentially fixes this

**Comment by BABACHORI** [comment]
The "new one" error with re-written fnc_removeKeyHandler: https://goo.gl/cWeLsx

**Comment by commy2** [comment]
What other addons are you using? Can you upload the RPT file? Thanks.

**Comment by BABACHORI** [comment]
Here is the RPT: https://goo.gl/8LexA0

**Comment by commy2** [comment]
There seems to be something seriously wrong with your mod repository. There are over 4.5k duplicate stringtable entries.

**Comment by BABACHORI** [comment]
I know but REALWAR is only build of addons.

**Comment by commy2** [comment]
Putting all kinds of different mods into one folder is a really bad idea. I don't think we can fix this without knowing what actual mod causes this. There are also literally thousands of other errors in this repository.

**Comment by commy2** [comment]
This is what my Pause menu looks like:
![http://i.imgur.com/ximZ5rB.png](http://i.imgur.com/ximZ5rB.png)

What actual addon does that change? 3rd party modifications of CBA are not supported.

**Comment by BABACHORI** [comment]
REALWAR doesnt change CBA its only build of addons for our community to play arma. We make build of addons we made addons assembly to the people who play them can download without problems

**Comment by BABACHORI** [comment]
Problem with CBA Events can be in any addon, even in those that we do not use

**Comment by commy2** [comment]
check the screen shot. something in the repository tinkers with CBA. That "configure addons" button and the box on the right are not from the original ACE.
Please figure out what addon does this or I can't fix anything. I don't have the time to debug a multi giga byte repository. Sorry.

**Comment by commy2** [comment]
My conclusion is that there is no problem in CBA events. The errors in the provided RPT files are caused by an unknown issue in a large collection of mods. The size of the repository and the fact that all files are thrown into one folder makes debugging the issue nearly impossible.
I suggest abandoning the approach of putting addons that don't belong to each other into one folder. Activating one addon after another should reveal potential problems.

**Comment by BABACHORI** [comment]
Sorry for that the configuring addons is from d_uac add-on and d_CBA_to_uac. Okay I figure out what the add-on causing this. I find this but not so fast. Yes you may
