### ISSUE TITLE
[major] DefaultEventhandlers compatibility issues

### ISSUE THREAD

**Issue by ghost** [CBATeam/CBA_A3#276]
DefaultEventhandlers is redefined and thus cleared by XEH. This makes XEH incompatible with everything else that edits DefaultEventhandlers.

If you want to clear DefaultEventhandlers and retain compatibility it should look like this:

class CBA_Extended_DefaultEventhandlers 
{
   class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers{};
};
class DefaultEventhandlers : CBA_Extended_DefaultEventhandlers
{
   init = "";
   fired = "";
   animChanged = "";
   animDone = "";
   animStateChanged = "";
   containerClosed = "";
   containerOpened = "";
   controlsShifted = "";
   dammaged = "";
   engine = "";
   epeContact = "";
   epeContactEnd = "";
   epeContactStart = "";
   explosion = "";
   firedNear = "";
   fuel = "";
   gear = "";
   getIn = "";
   getOut = "";
   handleHeal = "";
   hit = "";
   hitPart = "";
   incomingMissile = "";
   inventoryClosed = "";
   inventoryOpened = "";
   killed = "";
   landedTouchDown = "";
   landedStopped = "";
   local = "";
   respawn = "";
   put = "";
   take = "";
   seatSwitched = "";
   soundPlayed = "";
   weaponAssembled = "";
   weaponDisassembled = "";
   weaponDeployed = "";
   weaponRested = "";
};

**Comment by commy2** [comment]
@BakermanZA

The only place `DefaultEventhandlers` is used in CBA is here:
https://github.com/CBATeam/CBA_A3/blob/master/addons/xeh/CfgEventHandlers.hpp#L6

It's not redefined there and all edits should be compatible

Your proposed syntax is wrong:
`class DefaultEventhandlers: CBA_Extended_DefaultEventhandlers`

What exactly are you trying to do?
Can you post an example config?

Thank you.

**Comment by ViperMaul** [comment]
No response. Users account has been deleted so we probably won't get a response.
