### ISSUE TITLE
CBA_A3 causes Eden 3D Editor Camera Freeze

### ISSUE THREAD

**Issue by ctrsnarebear** [CBATeam/CBA_A3#282]
The CBA_A3 mod causes the Eden 3D editor's camera to freeze after returning from "Previewing" a scenario in the editor.

Steps to reproduce:
1) Run Arma 3 with CBA_A3 mod
2) Open the Eden 3D editor.
3) Place a unit.
4) Click "Play Scenario" on bottom right corner of the screen.
5) Press Esc
6) Click "Return to Eden Editor"
7) Attempt to move the camera using the W, S, A, or D keys, or the mouse wheel, or by dragging the cursor with the right mouse button.

The camera is frozen. Although the X, Y, Z, and (eye) values at the bottom of the screen change as if everything were fine, the actual view is frozen.

Everything else still works, and the mission can still be edited, but it is practically impossible because the user cannot see anything but what the camera is stuck showing.

Map View works fine (M key, or click Toggle Map in the toolbar).

My only known workaround is to exit back to Arma 3's main menu, then reload the editor.

**Comment by commy2** [comment]
Please post the RPT file. We can't help otherwise.

**Comment by ctrsnarebear** [comment]
Sorry, I have no idea what an RPT file is.

**Comment by commy2** [comment]
Are you by any chance using R3F_Armes mod too?

**Comment by ctrsnarebear** [comment]
Why, yes I am. Is that the problem?

**Comment by commy2** [comment]
No hold on. There is a bug in 3den and R3F and CBA that causes this to happen. I'm currently working on a fix. Give me 10 minutes.

**Comment by ctrsnarebear** [comment]
Okay thanks. FYI, I haven't tried disabling R3F. I only tried disabling CBA, which made everything work fine.

**Comment by commy2** [comment]
The bug is with a script in R3F that is never executed without CBA. Disableing either mod fixes it, but the faulty line is in R3F.

**Comment by ctrsnarebear** [comment]
I see. So I should talk to the R3F people about it then?

**Comment by commy2** [comment]
No, I'll do that and explain the issue in more detail

**Comment by commy2** [comment]
Can you try out this PBO?
http://www.mediafire.com/download/2os5vm16534o039/cba_r3f_3den_fix.pbo
Just put it INSIDE the addons folder INSIDE the @R3F_Armes folder.

**Comment by ctrsnarebear** [comment]
Yes. I've copied the file into Arma 3\@R3F_ARMES\Addons, and I'm just waiting for Arma 3 to load.

**Comment by ctrsnarebear** [comment]
That seems to have fixed it!

**Comment by commy2** [comment]
Nice. Thanks for testing. Feel free to use the fix and don't worry about contacting anyone. I'll do that.

**Comment by ctrsnarebear** [comment]
Thank you so much for your time and attention!

**Comment by commy2** [comment]
ref: https://forums.bistudio.com/topic/143825-r3f-french-weapons-pack/page-23
