### ISSUE TITLE
DEFAULT_PARAM default Value seems to choke on a certain array

### ISSUE THREAD

**Issue by jaynus** [CBATeam/CBA_A3#30]
DEFAULT_PARAM(3,_defaultKeybind,[-1, false, false, false]);
results in an error

<pre>
Error in expression <ame = (_this) select 2; ;

 false, false]);

 private "_overwrite";  _overwrite >
  Error position: <]);

 private "_overwrite";  _overwrite >
  Error Missing ;

</pre>
The work
_nullKeybind = [-1,false,false,false];
DEFAULT_PARAM(3,_defaultKeybind,_nullKeybind);

REFERENCE: https://dev.withsix.com/docs/cba/files/extended_eventhandlers/script_macros_common-hpp.html#DEFAULT_PARAM
__Reporter:__ ViperMaul
__Begin:__ 2014-06-30
__Completed:__ 0

**Comment by dixon13** [comment]
I have changed the value to : [-1,false] so it looks like this...

DEFAULT_PARAM(3,_defaultParam3,[-1,false]);

Now I am getting "_defaultParam3 = any"

**Comment by dixon13** [comment]
So I have come to find out that you cannot insert arrays into a macros from reading this post: http://forums.bistudio.com/showthread.php?173775-Preprocessor-macros-using-arguments-limits

It's very odd though because you can insert an array with one element it works, but two will give 'any', and three or more will result in script error.

**Comment by dixon13** [comment]
Only way to insert array is to put the array into a variable as @jaynus has done above. I have spent quite awhile thinking of away to try and implement a way so you can insert variables but the easiest way always ends up being to just put the array in a variable.

**Comment by Glowbal** [comment]
If you want to use this: `DEFAULT_PARAM(3,_defaultParam3,[-1,false]);` 

You will need to make use of the 'ARR_X' macro family:
```sqf
DEFAULT_PARAM(3,_defaultParam3,[ARR_2(-1,false)]);
```

**Comment by dixon13** [comment]
Well tried your method @Glowbal and now getting 'null'. I give up. I would say just store your array in a local variable and use that local variable. It works! I would say just make notes on the wiki and in the "script_macros_common.hpp" file, make some notes notifying people to store their arrays in variables and to not pass arrays directly into the 'DEFAULT_PARAM' macro.

**Comment by ViperMaul** [comment]
@dixon13, @jaynus 
DEFAULT_PARAM is now obsolete in favor of the new BI commands
https://community.bistudio.com/wiki/params
https://community.bistudio.com/wiki/param
