### ISSUE TITLE
Missing XEH classes on objects

### ISSUE THREAD

**Issue by Insnee** [CBATeam/CBA_A3#311]
XEH is not working on objects like
Land_HBarrier1
Land_HBarrierWall6_F
...

configfile >> "CfgVehicles" >> "Land_HBarrier1" >> "EventHandlers" >> "CBA_Extended_EventHandlers"
is empty...

manually adding CBA_Extended_EventHandlers's master class to EventHandlers solves this problem
http://puu.sh/oozNq/f70bb15328.png

**Comment by bux578** [comment]
AFAIK this is by design to preserve performance. Not every object needs XEH always.

Manually adding them via config is the way to go:

```c++
class CBA_Extended_EventHandlers;

class CfgVehicles {

    class Sign_F;
    class SignAd_Sponsor_F: Sign_F {
        class EventHandlers;
    };

    class my_custom_xeh_sign: SignAd_Sponsor_F {
        class EventHandlers {
            class CBA_Extended_EventHandlers: CBA_Extended_EventHandlers {};
        };
        ....
    };
};
```

@commy2 correct me, if i'm wrong.

**Comment by commy2** [comment]
completely correct. Although we could review if - due to the latest changes to xeh - we could not simply expand the number of objects that do support XEH. For example, buildings and static objects like hesco barriers could have this by default, while trees, rocks and fences are disabled.

**Comment by Killswitch00** [comment]
By designs as bux578 explained.
