### ISSUE TITLE
Modules for basic attack,patrol, and defend functions

### ISSUE THREAD

**Issue by Wired-Tiger** [CBATeam/CBA_A3#315]
I'm going to be creating some modules to help simplify basic functions for people that may not be familiar with scripting. Would this be something appropriate to be added into cba directly or should this be a separate addon? I could go into more detail on what I'm planning if need be.

**Comment by Killswitch00** [comment]
It sounds like something that could be useful to add to CBA. Please elaborate.

**Comment by Wired-Tiger** [comment]
The basic idea is to have three separate modules each: attack, defend, and patrol. Inside each module is various options for customization. An input box to enter a config entry or array of class names for soldiers. Then various boxes to choose the rest of the options. I would like to set it up so syncing to editor placed soldiers would be an option if possible, but at the very least syncing with triggers will be a must. So the attack menu would be something like the following:

-Config or soldier array   //If not synced to editor placed units
-Headless client   //If present, spawn on HC otherwise server
    Yes/No    //Drop down box options(Maybe dialog box to enter HC name instead?)
-Attack Position  //Enter position, marker name, etc
-Search Radius  //Enter number for desired area of search

The module would then, if not already spawned, create the units and have them attack the desired position. 
I'm completely open to suggestions, tips, or criticism. This was just the idea I had for the most flexible, yet straightforward, way of doing it.

**Comment by Killswitch00** [comment]
Sounds good. CBA has functions for attack, defend, patrol and area search tasks that could be used.

**Comment by Wired-Tiger** [comment]
Are you talking about having pre-defined groups as another choice or instead of the option I proposed? The main reason I went with the config/array idea is because I thought otherwise it would either limit the options of what could be chosen too much, or to get the desired group would need multiple options selected, side, faction, type, group, and still not have the same functionality.

I'm still a bit new to working with the code at this low of a level so if I'm not seeing a way of doing this please let me know.

**Comment by Killswitch00** [comment]
Yes, I meant the pre-defined groups that one can select when placing groups in the editor. However, that might be too complicated what with the side,faction type and group selections. (This would be in addition to your suggested config names/array of config names)

**Comment by Wired-Tiger** [comment]
Well, I'll stick with my original idea for now then. If later it needs to be changed then so be it.

**Comment by Killswitch00** [comment]
Implemented in PR #342
