### ISSUE TITLE
closure support

### ISSUE THREAD

**Issue by jaynus** [CBATeam/CBA_A3#32]
Contribution by zx64

https://dl.dropboxusercontent.com/u/1542468/temp/cba_ui_closure.diff is the diff for the "closure support" for interact menu actions.

> [8/5/2014 3:21:13 PM] zx64
> I've not tested it against heavy users of the interact menu like ACE but it gives you an idea of what the change currently is.
> https://www.dropbox.com/s/t5b7rjlxabbm7jk/cba_ui_test.Desert_E.pbo.7z is the mission I've used to test the changes.
__Reporter:__ ViperMaul
__Begin:__ 2014-09-11
__Completed:__ 100

**Comment by Killswitch00** [comment]
Can we contact zx64 to have this thing reviewed for the current version of cba_ui's flexiMenu implementation?

**Comment by ViperMaul** [comment]
He says we can expire it.
