### ISSUE TITLE
Blank screen after update

### ISSUE THREAD

**Issue by wasantosfi** [CBATeam/CBA_A3#326]
Recently I updated the cba_a3 mod using Steam Workshop (before this I used a Armaholic link, without automatic updates), after this, I logged in my dedicated server (coop mission) normally, but when another player logs in, my screen gets blank (but I still can move myself, can hear game sounds and I still can see the HUD). 
If I logout and login, it backs to normal, but the another player gets blank screen (and I get blank screen again if he/she logout and login). Tested with other players too, all of us with updated mods.
How can I fix this?
Thanks in advance.

**Comment by Killswitch00** [comment]
The version of CBA available in Steam Workshop is the same as the one available on Armaholic - 2.3.1.160220 so there is no difference in functionality between them. 

Test with no other mods than CBA loaded on the server and clients and see if the problem persists.

**Comment by Killswitch00** [comment]
No feedback after almost a month, so it's probably no longer a problem.
