### ISSUE TITLE
Keybinding - for KeyUp and KeyDown keybing make it impossible to setup it

### ISSUE THREAD

**Issue by jaynus** [CBATeam/CBA_A3#34]
1) Do someting like this:

["TFAR", "SW Transmit", {call TFAR_fnc_onSwTangentReleased}, [TF_tangent_sw_scancode] + TF_tangent_sw_modifiers, false, "KeyUp"] call cba_fnc_registerKeybind;	
["TFAR", "SW Transmit", {call TFAR_fnc_onSwTangentPressed}, [TF_tangent_sw_scancode] + TF_tangent_sw_modifiers] call cba_fnc_registerKeybind;	

["TFAR", "SW Transmit Additional", {call TFAR_fnc_onAdditionalSwTangentPressed}, [TF_tangent_additional_sw_scancode] + TF_tangent_additional_sw_modifiers] call cba_fnc_registerKeybind;
["TFAR", "SW Transmit Additional", {call TFAR_fnc_onAdditionalSwTangentReleased}, [TF_tangent_additional_sw_scancode] + TF_tangent_additional_sw_modifiers, false, "KeyUp"] call cba_fnc_registerKeybind;

2) Try to open key configure interface and setup key for "SW Transmit Additional"

Result: error on fnc_onLBDblClick.sqf:59
__Reporter:__ nkey
__Assigned to:__ nkey
__Begin:__ 2014-09-26
__Completed:__ 0

**Comment by dixon13** [comment]
Should this be closed since this issue is related to a depreciated function?

**Comment by Killswitch00** [comment]
Yeah.
