### ISSUE TITLE
error starting arma 3

### ISSUE THREAD

**Issue by RoguePA** [CBATeam/CBA_A3#344]
"Warning Message: Addon 'cba_ui' requires addon 'A3_Ui_F_Data'"

thats the message I get, it's broken our server as well

**Comment by PabstMirror** [comment]
Is Arma updated to version 1.60?
CBA_A3 v2.4.0 should work on 1.54, but we think it might throw a warning about missing CfgPatches on version less than 1.60.

**Comment by RoguePA** [comment]
yes that was my problem, seems I started Arma 3 before my update finished.
My bad! haha

**Comment by commy2** [comment]
Update your game.
