### ISSUE TITLE
Unexpected dependency on A3_Ui_F_Data added to cba_ui

### ISSUE THREAD

**Issue by Killswitch00** [CBATeam/CBA_A3#346]
The 2.4.0.160530 cba_ui.pbo has a dependency on `A3_Ui_F_Data` that is not there in the source file. This causes problems with the 1.54 Linux/MacOS ports - "A3_Ui_F_Data" is a new thing for A3 v1.60.

Possible build issue.

**Comment by PabstMirror** [comment]
open pboPrject -> setup -> uncheck setting and close pboProject
make.py will build with that setting

![image](https://cloud.githubusercontent.com/assets/9376747/15689273/c99f7c68-2743-11e6-9cfb-29fe69ec0a86.png)

**Comment by commy2** [comment]
I wonder why the tools add this as requirement. With or without it there are no UBC warnings. And `A3_Ui_F_Data` doesn't even have a config besides CfgPatches.

**Comment by Killswitch00** [comment]
Technically, cba_ui should depend on `A3_UI_F` (cba_ui references `RscText` and `RscShortcutButton` which are, as far as I can tell, defined in `A3_UI_F` (aka `ui_f.pbo`). As to why proProject adds `A3_Ui_F_Data` could be because that addon (in 1.60) depends on `A3_UI_F`, which is backwards - it is the config in `ui_f.pbo` that references files in `ui_f_data.pbo`.

**Comment by ViperMaul** [comment]
> "What happens if we add A3_UI_F to the list of dependencies in cba_ui.pbo and run pboProject"  @Killswitch00 

Here is the response from MikeRo, creator of pboProject: 
**_"Let them know that, as per the readme, pboProject will honor any hard-wired dependencies pre-stated in requiredaddons."_** -MikeRo
