### ISSUE TITLE
Mines / IED's wont register for the Fleximenu

### ISSUE THREAD

**Issue by NeKo-ArroW** [CBATeam/CBA_A3#348]
I've been working on making a custom action for defusing mines and IED's using the fleximenu. 
However Mines and IED's don't register under CursorTarget. They do register under CursorObject.

From what I understand CursorObject registers more things than CursorTarget and is mostly an improvement of CursorTarget. Using CursorObject will unlock alot more potential with this menu.

From my own little research I believe all that needs to be changed is line 45 in cba_ui\flexiMenu\fnc_openMenuByDef.sqf. But I may be getting ahead of myself.

**Comment by Killswitch00** [comment]
This needs investiaging. Is it as simple as replacing `cursorTarget` with `cursorObject` or will that cause problems?

**Comment by esteldunedain** [comment]
I'm not exactly sure how fleximenu works, but afaik mines don't support getVariable/setVariable. It may or may not be a problem.

**Comment by NeKo-ArroW** [comment]
I've noticed that CursorTarget tends to connect to units and vehicles somewhat better than CursorObject, since CursorObject is extra picky. When the fleximenu grabs a cursortarget it checks if there is an actual target, possibly you could add a new line just after Line 45 similar to this.
if (isNull "_potentialTarget") then {_potentialTarget = CursorObject};

Then if there is no CursorTarget, it will check if there's an object it can register instead.

I haven't dug deep in to this but I don't see why variables would be used upon simply opening the fleximenu.

**Comment by commy2** [comment]
^ good idea. The flexi menu doesn't set variables as far as I can tell and even if, it doesn't error, it just doesn't work with CfgAmmo (and CfgNonAiVehicle and roads).

**Comment by esteldunedain** [comment]
Mines are CfgAmmo, aren't they?

**Comment by commy2** [comment]
Yes

**Comment by Zealot111** [comment]
IMHO CursorTarget should be replaced by CursorObject where it is possible, CursorTarget is just limited and bugprone version of CursorObject. There is just no reason to use CursorTarget at all now, after CursorObject is available.

**Comment by dixon13** [comment]
Would there be a huge performance dip to using `cursorObject` over `cursorTarget`? That is the question now. If not, I say replace it.

**Comment by PabstMirror** [comment]
cursorTarget seems to require the player to know about the target
So a newly created object doesn't always show up right away.
Overall I think the command is much better and it should be fine to replace.
But `cursorObject` can return map objects that aren't CfgVehicles
So `typeof cursorObject = ""`.  I am not sure if that could cause any problems
