### ISSUE TITLE
Error position: <getVariable [SLX_XEH_STR_GetInMan,[]]) >

### ISSUE THREAD

**Issue by jaynus** [CBATeam/CBA_A3#35]
Reported by BI forum user "stlassen":
<pre>
Error in expression <eh_ar call _x }forEach((_this select 2) getVariable [SLX_XEH_STR_GetInMan,[]]) >
  Error position: <getVariable [SLX_XEH_STR_GetInMan,[]]) >
  Error getvariable: Type Number, expected Namespace,Object,Group,Control,Team member,Task,Location  
</pre>

Reference: [here](https://forums.bistudio.com/topic/168277-cba-community-base-addons-arma-3/page-8#entry2717012)
__Reporter:__ stlassen
__Begin:__ 2014-10-06
__Completed:__ 0

**Comment by Killswitch00** [comment]
Lack of info. If the error should occur again in the wild, we will most likely hear about it again.
