### ISSUE TITLE
XEH fails on slingload pods

### ISSUE THREAD

**Issue by PabstMirror** [CBATeam/CBA_A3#355]
For the slingload pods under opfor->storage -> "Taru Medical Pod"
```
class Extended_Init_EventHandlers {
    class Land_Pod_Heli_Transport_04_medevac_F {
        class test {  init = "diag_log text format ['XEH init - %1',_this];"; };
```

No XEH event happens and `allVariables cursorTarget = []`,

If I do ` call CBA_fnc_startFallbackLoop;` and then 
`"Land_Pod_Heli_Transport_04_medevac_F" createVehicle (getpos player)`

I do get an event for the new one.

Not sure why XEH is failing, the EventHandler configs seem to be correct.

If I explicitly re-add with 
```
    class Pod_Heli_Transport_04_crewed_base_F;
    class Land_Pod_Heli_Transport_04_medevac_F: Pod_Heli_Transport_04_crewed_base_F {
        XEH_ENABLED;
    };
```
It will work.  Not sure if something broke in 1.60?

**Comment by commy2** [comment]
This is indeed very very strange . I think our best bet is to readd the events like you did for all pods.
