### ISSUE TITLE
CBA Keys - display assigned key in game?

### ISSUE THREAD

**Issue by jaynus** [CBATeam/CBA_A3#36]
In my Raven addon, I have a button that you press to bring up the assigned keybinds. Once I switched the keys over to CBA Keybinding, I can't figure out how to get these assigned keys easily.

I've come up with a way to test which group the keys are assigned to:
```
_mainIndex = 0;

{
if ("RQ-11B Raven Addon" in ((profileNamespace getVariable "cba_keybinding_registry") select _x))
exitWith {_mainIndex = _x};
} forEach [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20];

_mainTitle = (profileNamespace getVariable "cba_keybinding_registry") select _mainIndex select 0;
hint format ["%1",_mainTitle]; // returns "RQ-11B Raven Addon"
```
This tests up to 21 addons using CBA Keys and returns the index that contains my Raven Addon key title. If I drill down more, I can get to the key names and assigned key "number" but for example, "Altitude Raise" is assigned key "17" which equates to DIK_W. But how do I know that Key "17" is DIK_W?

And, is there an easier way to do this? Currently to get "17", I have to find this:
`(profileNamespace getVariable "cba_keybinding_registry") select 1 select 1 select 0 select 1 select 0 select 0;`

It would be a lot easier if I could instead type this: 
`["RQ-11B Raven Addon", "Altitude Raise"] call CBA_fnc_revealKeybind;`
which would return [DIK_W, [false, false, false]] (or whatever the key has been changed to from the default).

Currently, in my addon, I have a page pop up with the default keybinds, but not what the user changes those keybinds to. I know the user can hit escape and just look there by drilling down into the menus, but in my Raven, I like having a quick page pop up with the Raven operation and the assigned keys while they are operating the Raven.

Thanks in advance if this is possible.
__Reporter:__ feint
__Begin:__ 2015-03-22
__Completed:__ 0

**Comment by Killswitch00** [comment]
Something like this could possibly be done using [CBA_fnc_getKeybind](https://dev.withsix.com/docs/cba_a3/files/keybinding/fnc_getKeybind-sqf.html#CBA_fnc_getKeybind) but I notice that it is incorrectly documented (the function does not return a numerical index value, but rather an array of...stuff.

**Comment by ViperMaul** [comment]
@jaynus 
Checking status on this.
How does killswitch's response work for you?

**Comment by Killswitch00** [comment]
It's "feint" who had the issue and jaynus copied it here from the one at [Dev-Heaven](https://dev.withsix.com/issues/76128)

With no feedback from feint here or at DH, we have no idea of the status.

**Comment by jonnyfilmboy** [comment]
Hey, this is Feint (Feint username is taken).  Sorry for the delay in my feedback.  This is working great for me.  I set up the following code to display the key in my Raven 3.0 addon that's coming out soon.

```
findCBAKeyAssignments = {
  private ["_addonToSearchFor","_keyToSearchFor","_keyConfig","_prettyKeyName","_shiftState","_ctrlState","_altState","_assignedKey","_keyResults"];
  _addonToSearchFor = _this select 0;
  _keyToSearchFor = _this select 1;

  _keyConfig = [_addonToSearchFor,_keyToSearchFor] call cba_fnc_getKeybind;
  _prettyKeyName = _keyConfig select 2;
  _shiftState = _keyConfig select 5 select 1 select 0;
  _ctrlState = _keyConfig select 5 select 1 select 1;
  _altState = _keyConfig select 5 select 1 select 2;
  _assignedKey = keyName (_keyConfig select 5 select 0);

  if (_shiftState) then {_shiftState = "Shift"} else {_shiftState = ""};
  if (_ctrlState) then {_ctrlState = "Ctrl"} else {_ctrlState = ""};
  if (_altState) then {_altState = "Alt"} else {_altState = ""};

  _keyResults = [_prettyKeyName,_shiftState,_ctrlState,_altState,_assignedKey];
  _keyResults
};
```
Example: 
```
_testResults = ["RQ-11B Raven Addon","Altitude_Raise"] call MAV_fnc_findCBAKeyAssignments;
_instructions = format ["%1 = %2%3%4 %5",_testResults select 0,_testResults select 1,_testResults select 2,_testResults select 3,_testResults select 4];
(_dspl displayCtrl 2020667) ctrlSetStructuredText parseText _instructions;
```

Result:
"Altitude Raise" = "W"

Thanks for adding this to your fine code.  It really helps.
