### ISSUE TITLE
ACRE2 radio PTT doesn't work when a modifier key is held

### ISSUE THREAD

**Issue by jaynus** [CBATeam/CBA_A3#37]
Tested with CBA_A3_DEV_RC6_v1.1.20.150407 and ACRE2.1.0.786 (specifically built for testing with new CBA)
The binds were all set from within the game. Expectation was for everything to work out-of-the-box.

Examples: 
If your PTT key is Home -> Push Home -> PTT successful
Players who have no TrackIR and use ALT for freelook, or players who Sprint/Walk with Shift, etc, cant transmit at the same time as holding the Modifier key

Possibly reproducible with other mods as well.
**Reporter:** BullHorn
**Assigned to:** Nou
**Begin:** 2015-04-08
**Completed:** 0

**Comment by commy2** [comment]
Modifier keys don't need three issues #213
