### ISSUE TITLE
Need help with BE filters

### ISSUE THREAD

**Issue by DedFusion** [CBATeam/CBA_A3#376]
im getting this since i installed CBA_A3 i have the BE filters but still get the restriction kick on server connect can anyone help me sort it please?

 #0 "x;
} forEach configProperties [_x >> format ["Extended_%1_EventHandlers", _event] >> _className, "isText _x"];
} forEach [config"

**Comment by commy2** [comment]
Looks like you have to update your battle eye filters. This doesn't belong on our issue tracker.
