### ISSUE TITLE
Update menu additions for new Apex menu

### ISSUE THREAD

**Issue by jonpas** [CBATeam/CBA_A3#379]
1. Random mod selection display (middle bottom) - that actually looks quite good but might be to bottom row maybe?
https://gyazo.com/a604ba01358b25a30cfb5f8b56fd3616

2. Configure Addons button is on old location (same will be with Settings I imagine)
https://gyazo.com/5a8210c5b642e7c2cc0798359498e1b8

Keep in mind, those menus might be changed further before release.

**Comment by commy2** [comment]
1 looks good tbh.

**Comment by commy2** [comment]
fixed with #396 and #397 / #420
