### ISSUE TITLE
Clean Up Wiki Examples for Keybind Docs

### ISSUE THREAD

**Issue by jaynus** [CBATeam/CBA_A3#38]
The examples run together and are difficult to read. Let's beautify them. 

[fnc_addKeybind](https://cbateam.github.io/CBA_A3/docs/files/keybinding/fnc_addKeybind-sqf.html)
[fnc_addKeybindToFlexiMenu](https://cbateam.github.io/CBA_A3/docs/files/keybinding/fnc_addKeybindToFleximenu-sqf.html)
[fnc_getKeybind](https://cbateam.github.io/CBA_A3/docs/files/keybinding/fnc_getKeybind-sqf.html)

Use the formatting from this example as a reference:
[fnc_test](http://dev.withsix.com/docs/cba_a3/files/diagnostic/fnc_test-sqf.html)
__Reporter:__ ViperMaul
__Begin:__ 2015-04-09
__Completed:__ 0

**Comment by Killswitch00** [comment]
These have been made purdy again.
