### ISSUE TITLE
Update the Wiki Docs Overview page

### ISSUE THREAD

**Issue by jaynus** [CBATeam/CBA_A3#39]
We should update the CBA Wiki Docs Overview page. We have added a few features sense its first writing.
http://dev.withsix.com/docs/cba_a3/files/overview-txt.html

For example we can reference CBA Keybinging, Debug Enhancement for A3, Interaction Framework and XEH. 
We should also have a brief paragraph on WHY to use CBA XEH for mod compatibility.
**Reporter:** ViperMaul
**Begin:** 2015-04-09
**Completed:** 0

**Comment by Killswitch00** [comment]
The new function docs overview page [here](http://cbateam.github.io/CBA_A3/docs/files/overview-txt.html) has been updated and links to [wiki articles](https://github.com/CBATeam/CBA_A3/wiki) describing many of the features.

Needed: improvements of the keybinding, debug enhancement and interaction framework articles.

**Comment by commy2** [comment]
Closing in favor of #564.
