### ISSUE TITLE
Add example of passed arguments to callback functions to funciton headers

### ISSUE THREAD

**Issue by bux578** [CBATeam/CBA_A3#392]
To get better information/help from the function headers I'd suggest that arguments passed to a callback function are documented aswell:  

e.g. the `_this` variable that is used in the `cba_fnc_addPerFrameHandler` callback function contains `[args, pfhID]`. This could be e.g. part of the example in the function header.

**Comment by bux578** [comment]
The same for waitAndExecute and waitUntilAndExecute

**Comment by commy2** [comment]
Anything else, @bux578 ?

**Comment by bux578** [comment]
not that i know of atm.
