### ISSUE TITLE
Publish CBA on the Steam Workshop

### ISSUE THREAD

**Issue by jaynus** [CBATeam/CBA_A3#40]
From the "BI forums":http://forums.bistudio.com/showthread.php?178224-CBA-Community-Base-Addons-ARMA-3&p=2923036&viewfull=1#post2923036

??Why is CBA3 not in Steam Workshop? I searched but i can't find it. It seems to me it would be a lot easier to keep this up to date for us.??

Apparently, one can now publish mods (collections of addons) on Steamworks, so it might be worth looking into publishing CBA there as well.
__Reporter:__ killswitch
__Assigned to:__ ViperMaul
__Begin:__ 2015-04-18
__Completed:__ 30

**Comment by ViperMaul** [comment]
Completed
