### ISSUE TITLE
Motorcycle does not support Extended Event Handlers

### ISSUE THREAD

**Issue by Cyruz143** [CBATeam/CBA_A3#406]
`18:31:18 [XEH]: Motorcycle does not support Extended Event Handlers! Addon: @ace`

Jonpas asked me drop an issue here

**Comment by PabstMirror** [comment]
Full RPT would be helpfull - can upload here: https://gist.github.com/

**Comment by Cyruz143** [comment]
Just wiped all my RPTs 5 minutes ago... Will get a fresh one.

**Comment by Cyruz143** [comment]
CBA + ACE + CUP (all latest stable)
https://gist.github.com/Cyruz143/c93a7e76b2442b731dcb2191cf9dc3f8

CBA + ACE (all latest stable)
https://gist.github.com/Cyruz143/ffeb0c110653b73bfc0c1bd132155f6a

Looks like CUP is causing it but it's getting tagged as `@ace` in the RPT.

**Comment by PabstMirror** [comment]
From CUP_Vehicles_Fastrope:
```
class CfgVehicles {
	class Motorcycle {
		class EventHandlers;
	};
	class CUP_C_Fastrope: Motorcycle {
```

I have yet to see a motorcycle in arma, so it's probably not a big deal; but I think that's the cause.

**Comment by jonpas** [comment]
@PabstMirror CUP has a Motorcycle, I already added support to some things in ACE3 (ref. https://github.com/acemod/ACE3/pull/3787), but it is still lacking XEH support for majority of the other functionality.

**Comment by commy2** [comment]
This is something CUP has to fix. Close?

**Comment by commy2** [comment]
forwarded
