### ISSUE TITLE
Spam No owner few times in .rpt only with CBA

### ISSUE THREAD

**Issue by jaynus** [CBATeam/CBA_A3#41]
Reproduce:

    Load Arma 3 only and CBA 1.1.20.150416
    Editor -> Stratis
    Put soldier
    Preview

When loading mission appears *No owner* few times in .rpt 

+More info:+

With script CSSA3: http://forums.bistudio.com/showthread.php?187688-CSSA3-A-Spectator-Script-for-Arma-3&highlight=cssa3

Install in mission and execute Spectator mode with the instructions of CSSA3.

If the camera moves are appearing more *No owner* especially if the ALT LEFT key is pushed.
__Reporter:__ oscarmolinadev
__Begin:__ 2015-05-08
__Completed:__ 0

**Comment by oscarmolinadev** [comment]
**More info:**
On the map VR nothing appears.

**Comment by commy2** [comment]
Here is a way to reproduce this rpt error _even in the VR_

`"Snake_random_F" createUnit [ position player, createGroup sideLogic ];`

It does not happen with "Rabbit_F"

**Comment by commy2** [comment]
Removing this line:
https://github.com/CBATeam/CBA_A3/blob/master/addons/xeh_a3/CfgVehicles.hpp#L22
`delete Eventhandlers;`
fixes the issue, but then the XEH `init` eventhandler is overwritten by the snakes config.
