### ISSUE TITLE
Most of scripts is not working

### ISSUE THREAD

**Issue by vlad8011** [CBATeam/CBA_A3#412]
I know how it sound, its very overall description, but i cant say directly which function are affected. Most of missions simply cannot progress with CBA loaded. I'm using RC branch, maybe thats the issue, but for example try this mission :
http://steamcommunity.com/sharedfiles/filedetails/?id=652763080&tscn=1467977371
and this :
http://steamcommunity.com/sharedfiles/filedetails/?id=652763080

Some triggers are not trigerring.

**Comment by commy2** [comment]
Uhm, okay.
Can I download this mission without having to use the Workshop?
Also, can you upload a RPT file please?

**Comment by BABACHORI** [comment]
commy, you can use this site to download missions http://steamworkshopdownloader.com

vlad, maybe its just bad mission or you running this mission with incompatible mod

**Comment by vlad8011** [comment]
You know, there is problem with almost every mission. Every mission (i like) is based on some mod, mod is based on CBA. Mod developers cannot reproduce issue, Bohemia clean their hands etc. I have so much RPT......

**Comment by vlad8011** [comment]
It would be this....

[arma3_2016-07-08_12-36-06.zip](https://github.com/CBATeam/CBA_A3/files/355579/arma3_2016-07-08_12-36-06.zip)

**Comment by commy2** [comment]
There is a script error with the `@Vcom_AI` mod. You should remove that mod and contact the author. He has to fix it.

```
13:31:34 Error in expression <osestObject;};


while {(_Unit distance _ClosestPos) > 3 && alive _Unit} do
{

_>
13:31:34   Error position: <_ClosestPos) > 3 && alive _Unit} do
{

_>
13:31:34   Error Nieokreślona zmienna w wyrażeniu: _closestpos
13:31:34 File vcomai\VCOMAI\Functions\VCOMAI_GarrisonClearPatrol.sqf, line 31
```

There is another error in the mission you are playing. Ask the author of the mission to fix that too.
```
13:26:06 Error in expression <if (!is3DEN && (_value > 0)) then {_value remoteExec ['setViewD>
13:26:06   Error position: <> 0)) then {_value remoteExec ['setViewD>
13:26:06   Error >: Typ Pole, potrzebny Liczbowe,To nie liczba
```

And lastly, you are playing on 1.62 - the release candidate branch, but we do not support RC/dev/sneak peak/whatever builds that are not the current stable version.

I don't know why you made the ticker here. We cannot do anything about these mods, as we are not the authors of them.

**Comment by vlad8011** [comment]
Sorry, i didnt know where to ask. As i writed above, most of mods base on CBA, but ok, i'll contact with mission author.

**Comment by esteldunedain** [comment]
Sorry @vlad8011, but that's a problem inherent to the current state of the Arma-verse. BIS keeps updating the game, so mods need to get updated constantly to remain functional. If missions don't do the same then things start to break. You have to assume that any mod or mission that's not updating regularly is doomed to break sooner or later.
