### ISSUE TITLE
'cba_ui requires a3_ui_f_data'

### ISSUE THREAD

**Issue by leopard20** [CBATeam/CBA_A3#414]
Arma version 1.56. (Windows version, not Linux,...  port)
CBA 2.4.1 gives this error when I launch the game: 'cba_ui requires a3_ui_f_data'
But CBA 2.3.1 works fine. How can I fix this? (there's no add-on named a3_ui_f_data in my addon folder, but I do have ui_f_data.)

**Comment by Killswitch00** [comment]
Hmm...that was supposed to be fixed in the 2.4.1 build, but I see now that it wasn't.

The "fix" is to use Arma 3 version 1.58 or later.

**Comment by commy2** [comment]
Why do you have Windows v1.56?
Illegal copies are not supported.

**Comment by leopard20** [comment]
@Killswitch00 
So all versions from 1.58 and above work? I can update my ARMA if that's the definite fix.

@commy2 
Well, I use an illegal copy because I'm an Iranian and, as you know, ARMA 3 is sort of anti-Iranian. I could buy the game from Steam (it would cost me a lot more than what you pay for it, but the multiplayer is definitely worth it) but then I would be helping the developers and betraying my country. I didn't have much of a choice here. Still, it would be nice if you helped me out.
By the way, where is this RPT file located?

**Comment by jokoho48** [comment]
as Commy sad we don't support Illegal version of ArmA 3 Please buy it and then ask for help again before we don't provide support

**Comment by leopard20** [comment]
Well, at least can you answer my first question? If I update to 1.58 will CBA work flawlessly or not?

**Comment by jokoho48** [comment]
we dont support Illegal version of ArmA 3 Please buy it and then ask for help again before we don't provide support

**Comment by bux578** [comment]
@leopard20 

>  as you know, ARMA 3 is sort of anti-Iranian

> I would be helping the developers and betraying my country

That's a very screwed up logic. I'm German and I still enjoy playing seconds world war games, even against the "German Faction". I don't know why you even think that you would betray your country? That doesn't make sense.

**Comment by jonpas** [comment]
> I would be helping the developers and betraying my country

If you like the game and want to play it, then the only viable thing to do is support the developers. Rest assured that they didn't have any intentions of being anti-Iranian.

**Comment by RavingCraze** [comment]
Man all the Russian betrayers that play(ed)/modd(ed) Arma 2 -,-
[sarcasm]But hey, I'm free to torrent all the anti-german games. F-you developers [/sarcasm]

**Comment by Killswitch00** [comment]
Solution has been provided.
