### ISSUE TITLE
CBA PostInit was designed to fail specifically on units and heavy load scenarios

### ISSUE THREAD

**Issue by jaynus** [CBATeam/CBA_A3#42]
https://github.com/acemod/ACE3/issues/1281#issuecomment-103011254

When PostInit is conducted specifically for CAManBase under certain circumstances, the XEH System is designed to switch to a scheduled mode execution and then fail its execution, or to bypass its execution for continuation of XEH. This poses several problems:

1. This means that CAManBase specifically loses its guarantee of synchronicity for event handlers, due to them running in the scheduled environment
2. The execution time on these handlers is garunteed to be excessive, as running in scheduled space during mission start is the most intensive time on the scheduler
3. If the handler takes too long to execute (10s) than the handler is bypassed, and the rest of XEH continues without it. This means that we lose all XEH PostInit order guarantees
__Reporter:__ jaynus
__Assigned to:__ jaynus
__Begin:__ 2015-05-18
__Completed:__ 0

**Comment by ViperMaul** [comment]
@jaynus 
Come back and work your magic.
