### ISSUE TITLE
Incorrect results for fnc_find when using initialIndex

### ISSUE THREAD

**Issue by nilsms** [CBATeam/CBA_A3#422]
The example from fnc_find.sqf:
_result = ["frog-headed fish", "f", 5] call CBA_fnc_find;
// _result => 12
Returns -1 (no "f" found from character 5 and onwards) due to an substring call with incorrect parameters.
I have submitted a pull request which fixes this error #421

**Comment by jonpas** [comment]
No need to open issues if you already PRed a fix. :)

**Comment by Killswitch00** [comment]
Can't hurt (and if one references the issue in the commit, it'll auto-close when merged)
