### ISSUE TITLE
Server Will not start

### ISSUE THREAD

**Issue by Spackler** [CBATeam/CBA_A3#425]
Just updated to the latest cba and my server will not start now. I get the following during startup. Any help would be greatly appreciated.

Script userconfig\cba\settings.sqf not found

**Comment by Spackler** [comment]
I resolved this by creating a dummy cba folder with an empty settings.sqf file.

**Comment by alexcroox** [comment]
Our clients are all reporting this error too

**Comment by commy2** [comment]
alternatively remove `-filePatching`

**Comment by ViperMaul** [comment]
@killswitch: has confirmed 
Workaround: create a dummy file in that location

**Comment by joshmanders** [comment]
Negative, I have not confirmed.

**Comment by killswitch** [comment]
Unconfirmed.

**Comment by Spackler** [comment]
Not sure if it matters, but I have confirmed on three of my Exile servers that my fix above resolved the problem so that they were able to start. Not sure if that is right or not, but what I did to get my servers back up and running.

**Comment by ViperMaul** [comment]
Thanks for the quick correction.

**Comment by shallowfoot** [comment]
So how do we fix this issue cause I am having the same problem tried the dummy file workaround had no luck. It created a run time error and crashed my arma3server that I was hosting threw TASDT.

**Comment by commy2** [comment]
You wait for the update.
