### ISSUE TITLE
ASDG Joint Rails(JR) Integration

### ISSUE THREAD

**Issue by ViperMaul** [CBATeam/CBA_A3#43]
Add ASDG Joint Rails

**Comment by robalo** [comment]
JR is here: https://github.com/robalo/mods/tree/master/asdg_jointrails

**Comment by ViperMaul** [comment]
That sounds like a proper course of action with emphasis on backward compatibility.

**Comment by robalo** [comment]
Added JR. A couple notes:
- original classes preserved because there's no way to ensure backwards compatibility unless everyone uses exactly the same class names.
- updating original BIS slot classes for vanilla weapons is intentional.

**Comment by jonpas** [comment]
I thought spaces is the way to go nowadays. :grimacing:

**Comment by ViperMaul** [comment]
@robalo Status?

**Comment by robalo** [comment]
JR done a month ago.
JAM, perhaps this week-end. Need to make a list and ask Ruthberg to calculate some values.

**Comment by ViperMaul** [comment]
Splitting out JAM Feature for another milestone.
