### ISSUE TITLE
Requires missing addon "3DEN"

### ISSUE THREAD

**Issue by Pydrex** [CBATeam/CBA_A3#433]
**Arma 3 Version:**  stable apex
**CBA Version:** `2.5.x` stable

**Mods:**
- `@CBA_A3`
- `@AiA`
- `@AN_Takistan`
- `@TFR`

**Description:**
- Warning on launching server  - Warning Message: Addon 'cba_diagnostic' requires addon '3DEN'

**Steps to reproduce:**
- Launch our server with the new 2.5 CBA

**Where did the issue occur?**
- Dedicated 

[arma3server_2_2016-07-13_18-14-40.txt](https://github.com/CBATeam/CBA_A3/files/362055/arma3server_2_2016-07-13_18-14-40.txt)

**Comment by Pydrex** [comment]
I have reinstalled Arma 3 server on this box and also included / removed the "3DEN" as a required addon, I can only recall in 1.52 or something like that they had a bug with "3DEN" in mission files prior.

**Comment by commy2** [comment]
Remove this file:
`18:14:58 C:\Arma3\Server-2\@AN_Taki\addons\asdg_jointrails.pbo - unknown`

Joint Rails is now part of CBA and the old one *must* not be loaded.

**Comment by Pydrex** [comment]
I will try this Thanks <3

**Comment by Killswitch00** [comment]
`-mod=@AN_Taki;@AllInArmaTerrainLite;@task_force_radio;@CBA_A3;`

- load CBA first
- stop using AiA. It's 2016 and CUP Terrains is the modern, maintained AiA

**Comment by Pydrex** [comment]
Hi, I believe the issue to be located inside the AiA files.

@Killswitch00 We have to use AiA as CUP Terrains is not allowed to be used on servers which are approved for Bohemia's monetization -  https://www.bistudio.com/monetization/approved/arma3

Do you know which file would be looking for CBA / 3DEN on this?

**Comment by Killswitch00** [comment]
> Do you know which file would be looking for CBA / 3DEN on this?
Yes - cba_diagnostics and cba_settings both depend on 3DEN. That is fine because 3DEN is part of the Arma 3 core content and if you load the server with only CBA_A3 there should be no errors.

The RPT file contains a great many warnings and errors unrelated to CBA, including several warnings about conflicting addons. We cannot solve those problems.
