### ISSUE TITLE
my server crash after instal CBA not possible to log in server have messege error 

### ISSUE THREAD

**Issue by tufaischier** [CBATeam/CBA_A3#460]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `2.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by Glowbal** [comment]
hi, could you please provide additional details? I understand from your title you are not able to log in on the server - could you perhaps ask the host or server provider to get the rpt log files for you?

We cannot help you without more information and those log files.

**Comment by tufaischier** [comment]
im re instal all im send u fils after

**Comment by tufaischier** [comment]
![20160813114359_1](https://cloud.githubusercontent.com/assets/21009448/17644108/9745c46a-614b-11e6-9ef0-9ebd452e832a.jpg)
![20160813114426_1](https://cloud.githubusercontent.com/assets/21009448/17644110/9aae1990-614b-11e6-9ff3-38e42f7242df.jpg)
[arma3server_2016-08-13_16-41-54.txt](https://github.com/CBATeam/CBA_A3/files/416645/arma3server_2016-08-13_16-41-54.txt)

**Comment by Glowbal** [comment]
```
16:44:04 "ExileServer - Starting session for '[LFQ] Rocky' with ID 'pKfNkYtj'..."
16:44:04 "ExileServer - Dispatching hasPlayerRequest for session 'pKfNkYtj'..."
16:44:07 Error in expression <llExtension _query);
(_result select 1) select 0>
16:44:07   Error position: <select 0>
16:44:07   Error Generic error in expression
16:44:07 File exile_server\code\ExileServer_system_database_query_insertSingle.sqf, line 16
16:44:07 Error in expression <llExtension _query);
(_result select 1) select 0>
16:44:07   Error position: <select 0>
16:44:07   Error Generic error in expression
16:44:07 File exile_server\code\ExileServer_system_database_query_insertSingle.sqf, line 16
16:44:41 Client: Remote object 3:0 not found
```

Not a CBA issue. Not a server crash. Please report this issue with the Exile devs, there is nothing CBA can do to fix this for you.

**Comment by commy2** [comment]
@tufaischier
You might want to check out this:
http://www.exilemod.com/topic/9817-extdb2-error-with-exile_server-error/
