### ISSUE TITLE
[CBA_help] script error on headless clients

### ISSUE THREAD

**Issue by Dorbedo** [CBATeam/CBA_A3#467]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)

**Mods:**
- `@CBA_A3`
- ....

**Description:**
`Error Undefined variable in expression: cba_keybinding_activemods
File x\cba\addons\help\XEH_postClientInit.sqf, line 70`

Script error since headlessClient don't get the variable initialized
See: https://github.com/CBATeam/CBA_A3/blob/master/addons/keybinding/XEH_preInit.sqf#L4
the whole help component shouldn't be executed on the headless clients.

**Steps to reproduce:**
- Setup a server
- load a mission with headless Clients
- let a headless connect
- take a look at the log

**Where did the issue occur?**
- Headless Client

**RPT log file:**
- http://pastebin.com/m32wqb1R

**Comment by commy2** [comment]
Problem is not that the variable is not initialized on headless clients, but that `CBA_fnc_fnc_addKeybind` has been called on the headless client.

This line has to be changed to make `CBA_fnc_fnc_addKeybind` safe:
https://github.com/CBATeam/CBA_A3/blob/2bf631362781b7a44198047e309e3c125339ffa8/addons/keybinding/fnc_addKeybind.sqf#L44

If it's your mod then maybe you can for now restrict `CBA_fnc_fnc_addKeybind` to only be executed where `hasInterface` is `true`?

**Comment by Dorbedo** [comment]
It's not my mod/Mission where addkeybind is called on an headless client.
I'll try to spot the causing mod.

Nevertheless your push should fix the Issue anyway. Thx.

**Comment by commy2** [comment]
Yup. Issue will be fixed. I just thought that this could help solving the problem without having to wait for a CBA update.

**Comment by Dorbedo** [comment]
Since it's nothing critical, just an single script error - I can live with that until the next CBA release ;-)
