### ISSUE TITLE
Align hash functions in CBA with ACE/ACRE

### ISSUE THREAD

**Issue by Soldia1138** [CBATeam/CBA_A3#47]
The hash functions in CBA have been improvement mainly by ACRE (Hashlists etc.) which have been adopted by ACE. Currently the cba hashes and ace/acre ones are neither the same nor compat.

Would be a nice feature to give 3rd party scripts independency of ACE/ACRE but the same functionality.

List of differences:
- `hashCreate` contains a **TYPE_HASH** designator which is only used by the `isHash` and not used by ACE/ACRE. How often is the `isHash`function used?
- Add hashLists-functions

Could jump on that and create a merge-request, if pleased.

**Comment by commy2** [comment]
for ACE, done in:
https://github.com/acemod/ACE3/pull/4181
https://github.com/acemod/ACE3/pull/4183
https://github.com/acemod/ACE3/pull/4186
https://github.com/acemod/ACE3/pull/4187
https://github.com/acemod/ACE3/pull/4188

dunno about ACRE

**Comment by jonpas** [comment]
I think ACRE will use it's own implementation until we get around to changing it. Does this impact anything?

**Comment by commy2** [comment]
No

**Comment by Soldia1138** [comment]
Yeah, tbh we switched to our own hashList implementation in the meantime and afaik we converted almost every hash to that. But nevertheless I will check.

**Comment by commy2** [comment]
CBA and ACE use the same system. ACRE can only be handled by the ACRE team and if there are missing features, pull requests.
Close?
