### ISSUE TITLE
x\cba\addons\events\fnc_keyHandlerDown.sqf, line 46 - Error in expression

### ISSUE THREAD

**Issue by pultho** [CBATeam/CBA_A3#483]
**Arma 3 Version:** `1.62.137494` (stable / rc / dev)
**CBA Version:** `3.0.0 160713` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.

**Steps to reproduce:**
Called by: 
`0 = ["Some name","open_menu", "Some title", {_this call LIGHT_fnc_showDialog;}, "", [DIK_HOME, [false, false, false]]] call CBA_fnc_addKeybind;`

LIGHT_fnc_showDialog;
`if(!dialog)then
{
    createDialog "AMCS_Gui";
};
`

**Where did the issue occur?**
By pressing the home button (DIK_HOME) the following RPT error occurs.

**RPT log file:**
`if (_blockIn>
 0:19:32   Error Allgemeiner Fehler in Ausdruck (Engl: Error in expression)
 0:19:32 File x\cba\addons\events\fnc_keyHandlerDown.sqf, line 46
 0:19:33 Error in expression <rams;
_params pushBack _x;

_blockInput = _params call _code;

};

if (_blockIn>
 0:19:33   Error position: <= _params call _code;

};`

**Comment by commy2** [comment]
Hello,

Can you upload the full RPT file? Can you execute:
`diag_log LIGHT_fnc_showDialog` via debug console too?

**Comment by commy2** [comment]
I tried the following:

```
LIGHT_fnc_showDialog = {
    if(!dialog)then { createDialog "RscDisplayInventory"; };
};

["Some name","open_menu", "Some title", {_this call LIGHT_fnc_showDialog;}, "", [15, [false, false, false]]] call CBA_fnc_addKeybind;
```
(15 == tab key)

No error happens there. Did you edit some of the code?

**Comment by AACO** [comment]
Just a random shot in the dark, did you define the `DIK_HOME` variable/preprocessor definition? ArmA doesn't do any setup for those items, but you can view a list of DIK codes here: https://community.bistudio.com/wiki/DIK_KeyCodes#Numeric_sort (Note, the numeric values are in hexidecimal, which you should be able to use fine or you can convert those values to decimal here: http://www.binaryhexconverter.com/hex-to-decimal-converter)

**Comment by pultho** [comment]
Sorry for my late reply. I was not able to reproduce the error after I've changed some parts of my code, especially in some configs. As @AACO said, just a random shot in the dark. But the error was definitely not caused by the DIK codes! Thanks anyway.

**Comment by commy2** [comment]
solution: 
https://forums.bistudio.com/topic/168277-cba-community-base-addons-arma-3/page-43#entry3097095

**Comment by 7rust** [comment]
Awesome, thanks! We should definitely add that to the wiki 👍
