### ISSUE TITLE
CBA_fnc_formatNumber returns bad values in some cases

### ISSUE THREAD

**Issue by Sniperhid** [CBATeam/CBA_A3#486]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)

**Mods:**
- `@CBA_A3`

**Description:**
With some inputs CBA_fnc_formatNumber will not behave as expected.

**Steps to reproduce:**
In debug console variable watch put -> `[65.200, 2, 3] call CBA_fnc_formatNumber`

Observed result: `"65.299"`

Expected result: `"65.200"`

**Comment by PabstMirror** [comment]
Joys of floating points
```
(65.2 * 10^2) % 10 = 9.99951
(65.2 * 100) % 10 = 9.99951
(65.2 * 10 * 10) % 1 = 0
```

**Comment by jokoho48** [comment]
https://www.youtube.com/watch?v=PZRI1IfStY0
if you want to know why this happend :)

**Comment by dixon13** [comment]
Probably best to avoid floating points whenever you can.

**Comment by commy2** [comment]
Question is: can we improve `CBA_fnc_formatNumber` to be as precise as possible with all SQF tricks or is it already as good as it gets?
