### ISSUE TITLE
remove team color synchronization

### ISSUE THREAD

**Issue by freghar** [CBATeam/CBA_A3#487]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)

**Mods:**
- `@CBA_A3`

**Description:**

With 354f1b189e889ca63b333dceb682498a3c30b7d2, CBA added custom loop-based team color synchronization logic for MP. As of Arma 1.62, `assignTeam` [now has global effect](https://community.bistudio.com/wiki/assignTeam), rendering the functionality redundant. This is not a big issue, but the custom CBA logic should probably now be removed.

**Comment by jonpas** [comment]
This was already done, simply disabled on 1.64+ https://github.com/CBATeam/CBA_A3/pull/424.

**Comment by freghar** [comment]
Ah, sorry, was searching for "team" and "color" and the code seemed to still be there.
