### ISSUE TITLE
B_Story_Protagonist_F not receiving InitPost/XEH functionality

### ISSUE THREAD

**Issue by jaynus** [CBATeam/CBA_A3#49]
Reference ACE Ticket: https://github.com/acemod/ACE3/issues/1423

**Comment by Killswitch00** [comment]
Yeah, that one and several others do not get a proper XEH init event handler. Core issue understood, am pondering solution.

**Comment by ViperMaul** [comment]
So far I tested Killswitch's initial solution and it fixes the ACE Self-Interaction issues reported. We still have to test for other concerns over the next 24 hours or so.

**Comment by ViperMaul** [comment]
For those that wants to help make sure we got the final fix. Please test this version v1.1.22
http://bit.ly/1FgMf16
