### ISSUE TITLE
No documentation for settings framework

### ISSUE THREAD

**Issue by dixon13** [CBATeam/CBA_A3#492]
At the moment there is no documentation of the settings framework in the GitHub Wiki. Maybe someone could copy and paste the documentation from https://github.com/CBATeam/CBA_A3/pull/317#issuecomment-227116446 into the wiki.

**Comment by 654wak654** [comment]
@commy2 on the ace3public slack: https://ace3public.slack.com/archives/cba/p1471859264000425

> will do full doc when stuff is set in stone

**Comment by dixon13** [comment]
Ah ok. Closing for now.

**Comment by commy2** [comment]
https://github.com/CBATeam/CBA_A3/wiki/Settings-system
