### ISSUE TITLE
Force Mission Settings deletes mission name

### ISSUE THREAD

**Issue by GuzzenVonLidl** [CBATeam/CBA_A3#501]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0.160713` (stable)

**Mods:**
- `@CBA_A3`

**Description:**
When forcing 2 or more settings to "mission" via Game Options from CBA, Mission name gets ignored and uses folder name instead.
Name still exist in mission.sqm
This only happens in mission select

**Steps to reproduce:**
Load a scenario,
Add 2 or more and force them to mission
Change name and export
MP- Local or Dedi
Mission display name will be mission folders name

Mission example:
Use ([] execVM "init.sqf") start the 2 dropdown menus
Select and force them
Save
Mission folder name: "NameTest_Incorrect"
Once "init.sqf" have run Mission name is: "NameTest Working"

**Where did the issue occur?**
Only tested on Dedicated and Self-Hosted Multiplayer
Note: 3den Multiplayer always shows incorrect, none related to this issue

**RPT log file:**
[RPT](http://pastebin.com/MMwXUq7s) - Nothing is shown
[Mission Example](https://www.dropbox.com/s/g9fumqvx06cktj5/NameTest_Incorrect.VR.pbo?dl=0)

**Comment by GuzzenVonLidl** [comment]
Issue still exists in version 1.64

**Comment by commy2** [comment]
https://feedback.bistudio.com/T120767

**Comment by commy2** [comment]
Is this still a problem?

**Comment by GuzzenVonLidl** [comment]
Just tested, It is still a problem from what I can tell and BI will probably not fix this unless they make a new version for .sqm
I believe current version is 53 since the 3den update

**Comment by jonpas** [comment]
> Not reproduceable in v2.04.

Re-open if still a problem.
