### ISSUE TITLE
Proper default value for hashHasKey

### ISSUE THREAD

**Issue by bux578** [CBATeam/CBA_A3#502]
@commy2 

https://github.com/CBATeam/CBA_A3/blob/master/addons/hashes/fnc_hashHasKey.sqf#L26-L28

![a](https://i.gyazo.com/5f3c0a7bbdc149a70dbb5489207b9a24.png)

_sorry for this few detail, I'm in a hurry, but don't want to forget_

**Comment by PabstMirror** [comment]
This is only a problem if your first arg isn't a valid hash
I think it should be up to the user to verify `CBA_fnc_isHash`

**Comment by commy2** [comment]
the default value in `params` should be a valid hash though. And not an empty array.
