### ISSUE TITLE
Setting not forceable when _isGlobal = true

### ISSUE THREAD

**Issue by Rall3n** [CBATeam/CBA_A3#506]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace3`
- `@WIP (Testing)`

**Description:**
Settings is not giving me the option to force a setting, even if _isGlobal parameter is set to `true`.

`[
    "variablename",
    "CHECKBOX",
    "description",
    "WIP",
    false,
    true
] call CBA_Settings_fnc_init;`

**Steps to reproduce:**
- Create setting and set `_isGlobal` parameter to `true`.
- Start game.
- Go into editor and check settings menu.

**Where did the issue occur?**
- Editor (Singleplayer)

**RPT log file:**
- [ArmA 3 RPT](https://gist.github.com/Rall3n/f62009e6193b970edb6a59e6d177f2c4)

**Comment by commy2** [comment]
The `_isGlobal` settings should _always_ be forced. I think they are only displayed on the server (and the client in SP). It should be impossible to change them as dedicated client.

**Comment by Rall3n** [comment]
I thought it would be possible to change and save them in the mission file from the editor. I know there is the save feature to save a setting template on the local machine.

**Comment by commy2** [comment]
Yeah. isGlobal settings cannot be forced by the mission, but are always overwritten by the server...
This should be addressed here: https://github.com/CBATeam/CBA_A3/pull/437
And therefore be fixed in the next version.

**Comment by Rall3n** [comment]
That's good to hear. Then I have to wait for the newest version of CBA.

**Comment by commy2** [comment]
Plan is to release it when 1.64 comes. So in a week. We have to wait for https://github.com/CBATeam/CBA_A3/pull/500 which needs the update and is needed after the update...

**Comment by commy2** [comment]
done #437
