### ISSUE TITLE
ErrorMessage: Include file x\cba\addons\main\script_macros_common.hpp not found.

### ISSUE THREAD

**Issue by Nickeep** [CBATeam/CBA_A3#512]
**Arma 3 Version:** `Game version: 1.64.138497` (stable)
**CBA Version:** `3.0.0.160713` (stable)

**Mods:**
- `@CBA_A3`

**Description:**
- i launch my server and everytime i launch it. it comes with this error. "ErrorMessage: Include file x\cba\addons\main\script_macros_common.hpp not found." ive tried editing the scrips but it didnt work. i tried a CBA with folder inside the addons folder but it still didnt work.

**Steps to reproduce:**
- Add CBA to your server
- Add @CBA_A3 to the start line
- Launch the server

**Where did the issue occur?**
- Dedicated Server/ Console Server

**RPT log file:**
- http://pastebin.com/NJEF5tEc

**Comment by robalo** [comment]
> "D:\TCAFiles\Users\NickR\11259\arma3server.exe" -server -ip=94.23.23.103 -port=2312 -profiles=arma3 -config=server.cfg -cfg=arma3\arma3.cfg  -mod=@ace;@CUP Terrains - Core;@ACE3 RHS compatibility files;@RHSUSF;@AH-64D Apache Longbow;@Ares;@Arma Enhanced Movement;**_cba_**;@CUP Terrains - Maps;@CUP Units;@CUP Vehicles;@CUP Weapons;@MCC Sandbox 4;@ShackTac User Interface;@task_force_radio;@ZEC - Zeus and Eden Templates - Building Compositions;@CBA_A3;

What's the "cba" mod for ? The one right before CUP Terrains. Try removing that one.

**Comment by Nickeep** [comment]
ok, but that cba in tiny text was a earlier attempt to fix it but it didnt work, ive tried different CBA's now. that one is not the one causing a problem, that wont give me an error like that. because it has to read an init for the error to come and if there is a mod missing then it will just ignore it.

**Comment by commy2** [comment]
Try `-mod=@ace;@CBA_A3;`
You always need the latest version of CBA: https://github.com/CBATeam/CBA_A3/releases

Btw. This is a bug tracker and not a forum for questions like "how do I set up my server?". Just saying.

**Comment by Nickeep** [comment]
i know ive tried everything, im pretty sure its only a problem with the virtual console at this point

**Comment by commy2** [comment]
ok

**Comment by sargken** [comment]
I had this same issue a while back. Its the script that is causing the issue. If i remember what i did to fix it I will let you know.
