### ISSUE TITLE
MRT Accessory Functions

### ISSUE THREAD

**Issue by madpat3** [CBATeam/CBA_A3#513]
Ever thought about integrating mrt accessory functions?

for you already integrated JR.
MRT would take it to the next level, from my point of view.

**Comment by dixon13** [comment]
Would need to probably get approval from the author of MRT Accessory Functions and then he or someone else would need to integrate it.

**Comment by madpat3** [comment]
Robalo is one of the authors of that mod, or at least he wrote some configs for it. Maybe worth a discussion with him?

**Comment by robalo** [comment]
I already asked da12thMonkey, the main author of MRT Accfncs. He allowed me to integrate it and further develop as needed into CBA.

**Comment by sargken** [comment]
I am willing to help if you need it @robalo

**Comment by commy2** [comment]
PR #555 is merged.
