### ISSUE TITLE
Fx errors.  

### ISSUE THREAD

**Issue by dvdbrewster** [CBATeam/CBA_A3#515]
**Arma 3 Version:** `1.64` (stable )
**CBA Version:** 3.0.1xx` (stable)  --latest--

**Mods:**
1)- `@CBA_A3`
-@ace3
2) @cba,@rhs escalation,

**Description:**
1. ace missions reveal " CBA fx error No Position reported after init."
2 ace export server settings error "cba fx--error.."
----   

**Steps to reproduce:**
these problems occurred on 3 different machines. (2 ded servers running  'different mods.' and client.)
install latest cba to ded server. start mission.(cti dynamic spawn towngroups)  cr cti KB edition ALTIS(ace3)
install  latest cba on client  open ace export settings menu- attempt export to clipboard
install latest cba and attempt cti mission(liberation rhs no ace, and receive no position error  cba fx.  Greuh Lib.Altis v,924. (rhs)
**Where did the issue occur?**
- Dedicated /   Editor (Singleplayer) 

**RPT log file:**
logging disabled

**Comment by commy2** [comment]
>logging disabled

Please upload an RPT file

**Comment by dvdbrewster** [comment]
I dont have a complete rpt.. I have logs off when I notice.
  Its weird though, Yesterday all seemed ok, Now any mission seems to cause 2-3 fps. And the' no Pos.' thing could have been a New Read  from CBA, and the game launched anyway but that the fps thing is an ongoing problem.
  The fx error message.. Bright red banner  . I rolled back to previou cba vers. on servers, and the error went away.. but the fps problem showed up in its place.

Ill try and reinstall latest cba...  and reproduce with logs on.

**Comment by dvdbrewster** [comment]
Here we go..  I got the error Only after switch to latest cba on client. If run latest on server only.. no error but vehicles donnot move.  So installed on client too  also U lose ACE self interaction ,  The message said 
fx  cba settings error  no server settings after init.

https://www.dropbox.com/s/is4iwlw6er4g7fr/arma3server_2016-09-30_23-34-57.rpt?dl=0

**Comment by commy2** [comment]
Can you also upload the clients RPT? Thanks.

**Comment by dvdbrewster** [comment]
Heres an awful screebshot of the error message.
![cba fx](https://cloud.githubusercontent.com/assets/11699529/19012241/ae7f39a6-8764-11e6-82f3-cff8d57c3ec7.JPG)

It will be a little while b4 I get the client rpt

**Comment by abramsba** [comment]
I'm also having the same issue, after updating to the latest version of CBA from steam workshop my server is broken. Originally I had a mission running alive which flooded my error log when trying to call CBA functions. I've since removed alive, but now I see the orange box and vehicles don't behave as they should. 

I see this on connection: http://i.imgur.com/ZBsQJBM.jpg

There are no errors on the RPT file, from either client or server.

**Comment by commy2** [comment]
Please upload the server and client RPT file. Thanks.

**Comment by commy2** [comment]
Btw. This error message has nothing to do with how vehicles behave and has nothing to do with "fps problems" either.

**Comment by abramsba** [comment]
There is nothing to show you in the logs otherwise I would have posted them.  I can also confirm that using https://github.com/CBATeam/CBA_A3/releases/tag/v3.0.0.160713 instead of the version of the steam workshop works.

**Comment by commy2** [comment]
I cannot help you without the RPT file. It contains necessary information to do so.

**Comment by abramsba** [comment]
https://gist.github.com/abramsba/8b59508e16237e4c5b2f360d1165cafa

**Comment by commy2** [comment]
Thanks. This looks like the dedicated servers RPT. Can you also upload the clients RPT (of the same session)?

**Comment by commy2** [comment]
@abramsba 
Looks like you didn't do a clean installation of CBA on the server:

```
 1:20:33 C:\mods\@CBA_A3\addons\cba_ai.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_arrays.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_common.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_diagnostic.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_events.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_hashes.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_help.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_jr.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_jr_prep.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_keybinding.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_linux.pbo - 7b37670b
 1:20:33 C:\mods\@CBA_A3\addons\cba_main.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_main_a3.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_modules.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_network.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_settings.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_statemachine.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_strings.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_ui.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_ui_helper.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_vectors.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_versioning.pbo - fc3156bf
 1:20:33 C:\mods\@CBA_A3\addons\cba_xeh.pbo - fc3156bf
```

Note how the commit hash of  `cba_linux.pbo` is `7b37670b` instead of `fc3156bf`. This is because the file no longer exists since a few versions.

Please delete: `C:\mods\@CBA_A3\addons\cba_linux.pbo` on the server and try again.

**Comment by abramsba** [comment]
Kudos on spotting that, I'll try a clean install and report findings.

**Comment by commy2** [comment]
That's great! Leaving the ticket open for dvdbrewster.

**Comment by dvdbrewster** [comment]
I rebooted latest vers.  no overwrite files...   The error has disappeared,   The fps 'drop' remains
 This is not something I normally would  overlook.  thx

**Comment by exYU** [comment]
How to fix this problem if server only have the key so the clients can use the addon?

**Comment by commy2** [comment]
@exYU That is not supported.

**Comment by dvdbrewster** [comment]
Server pho is only needed on server.

**Comment by exYU** [comment]
@commy2 Thanks.

@dvdbrewster Mod is not installed on the server side only have the key so that clients can use @CBA mod.

**Comment by LOOP3PARA** [comment]
is there is fix to this issue?

Is got the same red thing and didt try new install.. a older version.. nothings helps

**Comment by commy2** [comment]
See: https://github.com/CBATeam/CBA_A3/issues/515#issuecomment-250901886

**Comment by LOOP3PARA** [comment]
Sorry, i am new here...

Do you mean the "remove linux thing?

**Comment by commy2** [comment]
Yes

**Comment by LOOP3PARA** [comment]
i dont have the file...

http://peecee.dk/uploads/102016/cba.png

**Comment by commy2** [comment]
Then you have a different problem. Upload your server and client RPT.

**Comment by LOOP3PARA** [comment]
hmm oki, i am off to work, will get back to you to morrow...

TNx

**Comment by LOOP3PARA** [comment]
server RPT
http://pastebin.com/pskgQxv0

**Comment by commy2** [comment]
There are script errors in your mission. PreInit never finishes! Nothing works there!

Notice how it says:
>15:26:46 [798,104.671,0,"XEH: PreInit started. v3.1.0.160928"]

but `PreInit finished` never appears. Broken missions or broken addons.

**Comment by commy2** [comment]
cause is probably this:
```
15:27:30 "THERE IS A PROBLEM WITH THE ALIVE PLUGIN!"
15:27:30 ALIVE_SYS_DATA START PLUGIN: SYS_DATA_ERROR
15:27:30 "THERE IS A PROBLEM WITH THE ALIVE PLUGIN!"
15:27:30 DATA: Loading ALiVE config from database.
15:27:30 "THERE IS A PROBLEM WITH THE ALIVE PLUGIN!"
15:27:30 Error in expression <peName _config == "STRING" || (_initmsg select 1 == "ERROR" && _initmsg select 2>
15:27:30   Error position: <select 1 == "ERROR" && _initmsg select 2>
15:27:30   Error Generic error in expression
15:27:30 File x\alive\addons\sys_data\fnc_dataInit.sqf, line 109
15:27:30 Error in expression <peName _config == "STRING" || (_initmsg select 1 == "ERROR" && _initmsg select 2>
15:27:30   Error position: <select 1 == "ERROR" && _initmsg select 2>
15:27:30   Error Generic error in expression
15:27:30 File x\alive\addons\sys_data\fnc_dataInit.sqf, line 109
```

**Comment by LOOP3PARA** [comment]
oki. everthings works in the editor and didt work befor this update...

**Comment by commy2** [comment]
Nope. Maybe you just didn't noticed, because you didn't try the right things. This error message was added in the recent version so by reverting all you do is disable the message. It's like closing your eyes and going lalala.

**Comment by dvdbrewster** [comment]
Allright...  I  remember trying other missions..  so they might be corrupt too.   I thought I saw  "cba ok"  but mayB Im wrong.





 Signed by  my Computer Laptop 

    On Tuesday, October 4, 2016 7:37 AM, commy2 <notifications@github.com> wrote:
 

 There are script errors in your mission. PreInit never finishes! Nothing works there!Notice how it says:
15:26:46 [798,104.671,0,"XEH: PreInit started. v3.1.0.160928"]
but PreInit finished never appears. Broken missions or broken addons.—

**Comment by LOOP3PARA** [comment]
You where right, it was alive...

will wortk on thos script errors..

TNX SIR!!!

**Comment by delta998** [comment]
BRO TENGO UN ERROR CON EL CBA _A3 me sale un error al iniciar el arma 3

**Comment by delta998** [comment]
![bandicam 2019-10-19 10-10-40-474](https://user-images.githubusercontent.com/56765450/67345336-4781ba00-f500-11e9-9a86-d33f12702599.jpg)

**Comment by PabstMirror** [comment]
Verify files in steam, we do not support old versions

Please don't bump old issues, make a new one if you are still having problems: https://github.com/CBATeam/CBA_A3/issues/new?assignees=&labels=Bug&template=bug_report.md&title=

**Comment by commy2** [comment]
Probably cracked Arma, which is not supported. Please buy the game.
And do not bump 3 year old resolved issues.
Locked.
