### ISSUE TITLE
upon joining dedicated server an error box pops up

### ISSUE THREAD

**Issue by hobart666** [CBATeam/CBA_A3#519]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `2.x.x` (stable / dev + commit hash)  ver 3.1

**Mods:**
- `@CBA_A3`   <---this one only

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.
I added the new bikey to the keys folder restarted the server and joined then an orange/red error box popped up containing the message "no server settings after postinit phase" 

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
Just enable CBA_A3 and join.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
Dedicated a3 server. upon join after the latest cba update.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by commy2** [comment]
You have to have CBA on the server. Keys only is not supported.

**Comment by hobart666** [comment]
Well this is a first. Sad face.
