### ISSUE TITLE
XEH getin is being triggered when assembling uav

### ISSUE THREAD

**Issue by ylguf** [CBATeam/CBA_A3#527]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.0.160928` (stable)

**Mods:**
- `@CBA_A3`
- just a test mod with the code below

**Description:**
- XEH getin is being activated when a uav is assembled. havent tested this with other things being assembled. maybe change class Air with class All and test assembling other objects.

**Steps to reproduce:**
- code to reproduce as follows
- config.cpp:

```
class CfgPatches {
	class TEST {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"Extended_EventHandlers"};
	};
};

class Extended_GetIn_Eventhandlers
{
    class Air
    {
		scope = 0;
		getin = "hint 'getin XEH triggered';";
    };
};

```

- and then place a UAV operator(B_soldier_UAV_F) and when the darter ar-2 darter(B_UAV_01_F) is assembled the XEH is triggered.

**Where did the issue occur?**
- Singleplayer

**RPT log file:**
- no crash happens it just seems like unintended functionality as the getin event is being triggered on something being assembled and 'vehicle player == player'.

**Comment by PabstMirror** [comment]
I think UAV's have dummy AI units inside of them
So on assembly those units are created as well and loaded in.

**Comment by ylguf** [comment]
k good to know. i just ran into this when doing some stuff and wasnt sure what was causing it or if it was unintended
 i was using the XEH to run some functions when getting into vehicles and the function was running when i wasnt actually getting into anything

**Comment by commy2** [comment]
`GetIn` does indeed trigger for drone logics. You could simply exclude the UAVs from your event handler to prevent this:
```
class Extended_GetIn_Eventhandlers
{
    class Air
    {
        scope = 0;
        getin = "hint 'getin XEH triggered';";
        exclude = "UAV_01_base_F";
    };
};
```

Since the same happens with vanilla event handlers, I don't think we should change anything about this.

**Comment by PabstMirror** [comment]
If we filter it, it could break other addons that are counting on the current behaviour.
So there really isn't anything CBA can do about this.

**Comment by ylguf** [comment]
k thank you for clarifying. just something i ran into and wasnt sure if it was intended behavior. at least i know to filter it out.
