### ISSUE TITLE
Missing way to get count of elements in Hash.

### ISSUE THREAD

**Issue by dedmen** [CBATeam/CBA_A3#528]
**CBA Version:** `3.1.0.160928` (stable)

**Mods:**
- `@CBA_A3`

**Description:**
There is currently no function to retrieve the number of elements that are currently in a Hash.

**Comment by PabstMirror** [comment]
Should just be:
`count (_hash select 1)`

**Comment by bux578** [comment]
A wrapper around doing this would be useful though (in case the hash layout changes)

**Comment by dedmen** [comment]
I don't think users should have to check how hashes are implemented to get something that every standard c++ container has as method.
