### ISSUE TITLE
Strange key handling.

### ISSUE THREAD

**Issue by dedmen** [CBATeam/CBA_A3#529]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.0.160928` (stable)

I have these two keys

```
["TFAR","SWTransmit",["SW Transmit","SW Transmit"],{systemChat "SW DOWN";},{systemChat "SW UP";},[58, [false,false,false]],false] call cba_fnc_addKeybind;

["TFAR","LRTransmit",["LR Transmit","LR Transmit"],{systemChat "LR DOWN";},{systemChat "LR UP";},[58, [false, true, false]],false] call cba_fnc_addKeybind;
```

SWTransmit bound to CAPS
LRTransmit bound to STRG+CAPS

following thing happens (1st case)

```
<CAPS Down> SW DOWN
<CAPS Up> SW UP
<STRG Down>
<CAPS Down> LR DOWN
<Wait over 1 second>
<STRG Up> LR UP LR DOWN SW DOWN -- What the hell is LR DOWN doing here??
<CAPS Up> LR UP -- Should trigger SW UP
```

I don't know why a KeyUp can cause a KeyDown event to be called. Especially when the modifiers for the keybinds aren't even currently pressed.
Leaving out the wait causes (2nd case)

```
<CAPS Down> SW DOWN
<CAPS Up> SW UP
<STRG Down>
<CAPS Down> LR DOWN
<STRG Up> LR UP SW DOWN
<CAPS Up> SW UP
```

Only happens when releasing Modifier before main key. Else: (3rd case)

```
<CAPS Down> SW DOWN
<CAPS Up> SW UP
<STRG Down>
<CAPS Down> LR DOWN
<CAPS Up> LR UP
<STRG Up>
```

**Comment by commy2** [comment]
I think I described the same thing here: #213 Please check.

The standard windows interface behaviour of the modifier keys is, that releasing a modifier key while the main key is held down will trigger the unmodified behaviour.
On the other hand, pressing any modifier key while any main (+other modifiers) is held, will stop the input.

Windows behaviour is pretty intuitive in my opinion, so I should try to recreate that in the eventual rewrite I'd say.

**Comment by dedmen** [comment]
#213 seems fine though.. as when I Release CTRL only CAPS is pressed so it kinda makes sense that would trigger the SWTransmit event like in my 2nd case. Just 1st case is very weird

**Comment by commy2** [comment]
Problem is similar enough to #529, so this doesn't need two tickets.
