### ISSUE TITLE
Global Setting not configurable in MissionSettings

### ISSUE THREAD

**Issue by dedmen** [CBATeam/CBA_A3#533]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.1.161012` (stable)

**Mods:**
- `@CBA_A3`

**Description:**
- Global setting can't be set in missionSettings because ServerSetting is always forced.

**Steps to reproduce:**
- Add setting in Preinit:
```
["testVar, "CHECKBOX", "testvar", "CBA Setting test", true, true] call CBA_Settings_fnc_init;
```
- Create a test mission in 3DEN and set testVar in the MissionSettings to false.
- Test on dedicated server
- Outcome is testVar == true. Because the serverSetting is still set to the default and forced because its a global Setting. So MissionSettings are ignored.

**Where did the issue occur?**
- Dedicated

**Additional Info**
Init.sqf:
```
diag_log ["Pre init.sqf","testVar" call cba_settings_fnc_get,
"testVar" call cba_settings_fnc_isForced,
missionNamespace getVariable ["testVar",nil]];


diag_log (["testVar", false, true,"mission"] call CBA_settings_fnc_set);


diag_log ["Post init.sqf","testVar" call cba_settings_fnc_get,
"testVar" call cba_settings_fnc_isForced,
missionNamespace getVariable ["testVar",nil]];

[] spawn {
	sleep 10;
	diag_log ["After init.sqf","testVar" call cba_settings_fnc_get,
	"testVar" call cba_settings_fnc_isForced,
	missionNamespace getVariable ["testVar",nil]];
diag_log ["testVar","mission"] call cba_settings_fnc_get;
};
```
Output is (same on clientSide and serverSide):
```
19:01:03 ["Pre init.sqf",true,true,true]
19:01:03 2
19:01:03 ["Post init.sqf",true,true,true]
19:20:10 ["After init.sqf",true,true,true]
19:20:10 false
```
CBA_settings_fnc_set is returning 2 because it is checking the "mission" source. Which is indeed already set to false.

Repro mission is in progress.

**Comment by commy2** [comment]
problem is that the mission setting is not forced.
![http://i.imgur.com/AAyulKf.png](http://i.imgur.com/AAyulKf.png)

**Comment by dedmen** [comment]
Server was running CBA 3.0.0. Didn't see any warning I don't know why. Please document that Variables get overwritten after PostInit and how to use CBA_settings_setSettingMission. Would spare other people from the hassle i had.

**Comment by commy2** [comment]
```
client: 1
server: 0,2,4
mission: 0,3
```
