### ISSUE TITLE
Script Error with Massive Client .rpt Spam

### ISSUE THREAD

**Issue by JHill29th** [CBATeam/CBA_A3#535]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.1.161012` (stable)

**Mods:**
- `@CBA_A3`

**Description:**
When entering the Zeus interface the following script error spams the client .rpt.  Not a small amount of spam either; caused the client .rpt to reach well over 2 MB in size.

``` sqf
1:09:20 Error in expression <= _pos distance curatorcamera;
if (_dis < _fadeEnd) then {
_coef = linearconvers>
 1:09:20   Error position: << _fadeEnd) then {
_coef = linearconvers>
 1:09:20   Error <: Type code, expected Number,Not a Number
```

Originally reported at https://github.com/oOKexOo/AresModAchillesExpansion/issues/22

**Steps to reproduce:**

- Build scenario with a single player object and curator GM module (#adminLogged)
- export to MP mission.
- Load onto Dedi server and launch mission.
- Enter zeus mode

**Where did the issue occur?**

- Dedicated

**RPT log file:**
 Link to [.rpt file](https://www.dropbox.com/s/u1lzho4cnhz6bzm/arma3_2016-10-16_00-52-42.7z?dl=0)

**Comment by PabstMirror** [comment]
\a3\ui_f_curator\ui\displays\rscdisplaycurator.sqf: line 146 is this gem:
```
				_fadeStart = uinamespace getvariable ["",1000];
				_fadeEnd = uinamespace getvariable ["",2000];
```

Which is being set by CBA's https://github.com/CBATeam/CBA_A3/blob/master/addons/xeh/fnc_preStart.sqf#L20
```
uiNamespace setVariable ["", compileFinal ""];
```
Not sure why CBA has to do that?
