### ISSUE TITLE
Error on startup (Empty namespace variable names are no longer allowed)

### ISSUE THREAD

**Issue by shukari** [CBATeam/CBA_A3#539]
**Arma 3 Version:** `1.64.139117` (performance v10)
**CBA Version:** `3.1.1` (stable)

**Mods:**
- `@CBA_A3`

**Description:**
Get this error on startup.
The cause might be from performance v10 -> fixed some previous tweaks (e.g. with empty variable names)
From dev to performance... from dev: Tweaked: Empty namespace variable names are no longer allowed (https://forums.bistudio.com/topic/140837-development-branch-changelog/?p=3111946)

```
19:07:04 Error in expression <ns\xeh\fnc_preStart.sqf"



uiNamespace setVariable ["", compileFinal ""];



wi>
19:07:04   Error position: <setVariable ["", compileFinal ""];



wi>
19:07:04   Error Reservierte Variable in Ausdruck
19:07:04 File x\cba\addons\xeh\fnc_preStart.sqf, line 5
```

**Steps to reproduce:**
- Start the game with CBA

**Where did the issue occur?**
- on startup

**RPT log file:**
- http://pastebin.com/hFcEzpWT

**Comment by jokoho48** [comment]
allready fixed in master. 24330abec622bd5eb15d375ee48c7f195fb23ff1

**Comment by shukari** [comment]
From this moment on... it is not possible to change modules in eden because of the performance v10 and cba... eden warning appears if you click ok on a module with: "Variablenname: Encountered restricted character"

**Comment by PabstMirror** [comment]
The xeh error is only at preStart, will be fixed at next release

The issue with modules happens without CBA, 
reported on BIF - https://forums.bistudio.com/topic/160288-arma-3-stable-server-164-performance-binary-feedback/page-89#entry3112919

**Comment by shukari** [comment]
oh... ok.

**Comment by PabstMirror** [comment]
I think a quick fix for the modules is to just give them a dummy "Variable Name" at the top
I think it just can't be empty

**Comment by commy2** [comment]
fixed in https://github.com/CBATeam/CBA_A3/pull/536

for the modules... wait for BI to fix it
