### ISSUE TITLE
No addon key bindings with newest CBA

### ISSUE THREAD

**Issue by ohally** [CBATeam/CBA_A3#546]
**Arma 3 Version:** 1.64.138732 stable
**CBA Version:** v3.1.2.161105 stable

**Mods:**
-@CBA_A3
-@ACE

**Description:**
-Upon entering the main screen of Arma3 the error "Script Any Not Found" appears, once in game you are unable to use any addon based key bindings including ACE and the configure addons tab in the options does not open.

**Steps to reproduce:**
-launch with @CBA_A3 and @ACE place a unit in the editor and attempt to use ace interaction.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal *ALL*

**RPT log file:**
[https://www.dropbox.com/s/1j3k2uici11c5ne/arma3_2016-11-11_08-49-03.rpt?dl=0](url)

**Comment by PabstMirror** [comment]
You are running ace 3.7, not sure if that is compatible with CBA 3.1.2
Might want to give it a try with 3.8.1 - https://github.com/acemod/ACE3/releases/latest

**Comment by ohally** [comment]
fixed the issue, my group uses a repo and i guess the last version of CBA needed to be completely removed before installing the updated version.
