### ISSUE TITLE
CBA version Crashes Dedicated server running CUP mods

### ISSUE THREAD

**Issue by hobart666** [CBATeam/CBA_A3#547]
**Arma 3 Version:** `x.xx` (stable / rc / dev) 1.64.138732
**CBA Version:** `2.x.x` (stable / dev + commit hash)name =  "Community Base Addons v3.1.2";

**Mods:**
mod=@CUP_Terrains_Core;@CUP_Terrains_Maps;@CUP_Units;@CUP_Vehicles;@CUP_Weapons" "-

serverMod=@CBA_A3;@SLZ;@AdvancedUrbanRappelling;@JS_JC_FA18;@Advanced Rappelling;@Advanced Sling Loading;@Advanced Towing"

**Description:**
2016/11/13,  7:11:03 Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.
cup_camisc

**Steps to reproduce:**
add new cba version and restart the server. Goes into a loop.

**Where did the issue occur?**
- Dedicated Server

**RPT log file:**
[arma3server_2016-11-13_07-09-47.rpt.txt](https://github.com/CBATeam/CBA_A3/files/587818/arma3server_2016-11-13_07-09-47.rpt.txt)

returning to the older version makes the server work properly.

**Comment by PabstMirror** [comment]
What version of CBA does it work with?
Could you upload a RPT of the server working with that version?

**Comment by commy2** [comment]
Delete this:
`D:\Games\ArmA3\a3master\@CBA_A3\addons\cba_linux.pbo`

You seem to have broken the mods by drag and dropping new versions onto the old folders, which leaves old and removed files in there. You should delete all mods, download the latest versions again and always delete the old folder before updating them.

**Comment by hobart666** [comment]
The very last one uploaded to the workshop previous to this version. I can
get you the .Roy Mon evening. I'm on the road.

**Comment by hobart666** [comment]
I never do that. I delete the old folders first, then copy over the new
ones. But I'll see if that holds any weight.

Joshua Lee
603-913-3265

**Comment by hobart666** [comment]
ya man, no joy with that. do you still want the .rpt? or are you gonna
assume more?

Joshua Lee
603-913-3265

**Comment by dixon13** [comment]
If you're still having problems, then it's best if you post you're rpt file so we can see what's going on. Thanks.

**Comment by dixon13** [comment]
Wait I just saw this...

> Mods:
mod=@CUP_Terrains_Core;@CUP_Terrains_Maps;@CUP_Units;@CUP_Vehicles;@CUP_Weapons" "-

> serverMod=@CBA_A3;@SLZ;@AdvancedUrbanRappelling;@JS_JC_FA18;@Advanced Rappelling;@Advanced Sling Loading;@Advanced Towing"

Issue could be related to `@CBA_A3` not being in `-mod` parameter depending on how you start you're game. You should just put `@CBA_A3` in the `-mod` parameter anyways because everyone should download @CBA_A3 as some mods, and I think CBA itself, to run for both clients and server, if people join you're server through the Arma 3 Launcher.

**Comment by PabstMirror** [comment]
```
 7:10:15 D:\Games\ArmA3\a3master\@CUP_Terrains_Core\addons\cup_terrains_ca_misc.pbo - unknown
```
and that pbo does
```
class CfgPatches {
	class CUP_CAMisc {
```
which the game says is missing
```
Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.
cup_camisc
```
???

really not sure why, I agree with dixon13, it might be related to the `serverMod` param
