### ISSUE TITLE
Script any not found

### ISSUE THREAD

**Issue by RavenTactical** [CBATeam/CBA_A3#549]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.2.161105` (stable)

**Mods:**
- `@CBA_A3`
- `@ACE` (error is caused both with and w/o)

**Description:**
- When launching the game, upon arriving at the main menu, the game prompts with a popup error "Script any not found."  When a scenario is loaded, no CBA features function (most noticeable when running ACE).  NOTE: This problem appears to be localized to one machine.  Other users appear unable to reproduce this error.

**Steps to reproduce:**
- Load CBA A3 off of the SW
- Load ACE 3 off of the SW
- Attempt to launch the game, observe main menu screen

**Where did the issue occur?**
- Any scenario, single or multi, local or dedi

**RPT log file:**
- http://pastebin.com/TM6zn4uN (CBA / ACE)
- http://pastebin.com/LJ7xGmpB (CBA only)
- http://pastebin.com/gFVCnk7x (Vanilla)

**Previous Troubleshooting**
- Uninstalled / Reinstalled ARMA & all mods
- Restarted the computer in question
- Tried both ARMAHolic and Steam Workshop sourced code

**Other Comments**
We're not expecting miracle work, but since this is holding one of us back from being able to play A3 with the latest CBA, it's a huge dent to our already small group of regular players.  Any insight to what might be causing this would be great.

**Comment by PabstMirror** [comment]
```
19:16:51 addons\cba_linux.pbo - 7b37670b
```
looks like there is that single pbo in you `arma install\addons` folder

**Comment by commy2** [comment]
Remove:
`D:\Steam\steamapps\common\Arma 3\addons\cba_linux.pbo`
and never put anything into that folder again.

**Comment by commy2** [comment]
Proof, excerpt of the "vanilla" RPT:
```
19:19:00 addons\cba_ai.pbo - 7b37670b
19:19:00 addons\cba_arrays.pbo - 7b37670b
19:19:00 addons\cba_common.pbo - 7b37670b
19:19:00 addons\cba_diagnostic.pbo - 7b37670b
19:19:00 addons\cba_events.pbo - 7b37670b
19:19:00 addons\cba_hashes.pbo - 7b37670b
19:19:00 addons\cba_help.pbo - 7b37670b
19:19:00 addons\cba_jr.pbo - 7b37670b
19:19:00 addons\cba_jr_prep.pbo - 7b37670b
19:19:00 addons\cba_keybinding.pbo - 7b37670b
19:19:00 addons\cba_linux.pbo - 7b37670b
19:19:00 addons\cba_main.pbo - 7b37670b
19:19:00 addons\cba_main_a3.pbo - 7b37670b
19:19:00 addons\cba_modules.pbo - 7b37670b
19:19:00 addons\cba_network.pbo - 7b37670b
19:19:00 addons\cba_settings.pbo - 7b37670b
19:19:00 addons\cba_statemachine.pbo - 7b37670b
19:19:00 addons\cba_strings.pbo - 7b37670b
19:19:00 addons\cba_ui.pbo - 7b37670b
19:19:00 addons\cba_ui_helper.pbo - 7b37670b
19:19:00 addons\cba_vectors.pbo - 7b37670b
19:19:00 addons\cba_versioning.pbo - 7b37670b
19:19:00 addons\cba_xeh.pbo - 7b37670b
```

**Comment by RavenTactical** [comment]
Well I'll be darned!  You guys were spot on!  We simply didn't see it!  I guess when you're staring at a problem for so long, you start to miss the little details.  This was absolutely the fix, and we've "motivated" our member to make sure there are no other addons in his A3/Addons folder other than the vanilla ones.

Thanks guys!
