### ISSUE TITLE
RPT error with HC

### ISSUE THREAD

**Issue by shukari** [CBATeam/CBA_A3#557]
**Arma 3 Version:** `1.64.138732` (performace)
**CBA Version:** `3.1.2.161105` (stable)

**Mods:**
- `@CBA_A3`
- `@Ace3`

**Description:**
- start server with hc on it
```
 0:37:58 Error in expression <spawn {
private _text = cba_help_keys;

cba_keybinding_handlers params [["_modNa>
 0:37:58   Error position: <cba_keybinding_handlers params [["_modNa>
 0:37:58   Error Undefined variable in expression: cba_keybinding_handlers
 0:37:58 File x\cba\addons\help\XEH_postClientInit.sqf, line 65
```

**Steps to reproduce:**
- start server with hc on it

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- https://gist.github.com/shukari/4e154299a596de7a28ada3ffb8e73e68

**Comment by Dorbedo** [comment]
@commy2 again the question: Why is the help component compiled on the HC-Clients?
I think it's related to #467

**Comment by commy2** [comment]
@Dorbedo similar, but not the same.

**Comment by Dorbedo** [comment]
Yes, indeed. Does the HC need anything from this Component?

**Comment by commy2** [comment]
No. It was written under the assumption that all clients have an interface (postInitClient), but that is no longer true in A3, due to the addition of headless clients.

**Comment by Dorbedo** [comment]
Why not skip the Preinit & Prestart too?

**Comment by commy2** [comment]
Can't skip the preStart, as you don't know it's a headless client at that point afaik. Could skip the other ones _I think_, but I don't want to break anything else unnecessarily.
