### ISSUE TITLE
[Not a bug] Change server settings?

### ISSUE THREAD

**Issue by condolent** [CBATeam/CBA_A3#559]
Hello, I have a mod called Task Force Radio that uses CBA. How can I change the server settings for this mod? I heard people talk about that userconfig no longer exists and that it's all done through CBA now.

But when I go to game settings -> configure addons and then click the server-sided settings, there's nothing I can change. How can I allow myself and other accounts to change server settings? And how does server settings save? Is there a file that the user will need to download aswell?

**Comment by bux578** [comment]
@condolent You should probably ask that here: https://github.com/michail-nikolaev/task-force-arma-3-radio

**Comment by condolent** [comment]
But it's a question about CBA? All I want to know is how to make CBA recognize me as a server admin so I can change CBA settings server-sided

**Comment by commy2** [comment]
`#login <password>`
