### ISSUE TITLE
Serverkey RC7 soft crashes server

### ISSUE THREAD

**Issue by ArcanumSK** [CBATeam/CBA_A3#56]
As reported several times, when I add actual fresh bikey server will not load past port bind. It will never reach mission screen. Fix ASAP.

**Comment by ViperMaul** [comment]
You are experiencing this bug with the A3 server: [0022133: Some .bikey file combinations prevent dedicated server from loading] (http://feedback.arma3.com/view.php?id=22133)
BIS are working on it. If you read that report you will see some workarounds. 
Make sure you remove all CBA bikeys, Make sure CBA mod is the first in the list. And if that fails, try to rename the biki key to cba.bikey and hope that works around the bug.

**Comment by ViperMaul** [comment]
@ArcanumSK 
I see that 1.46RC has made some changes in this area. Would you be willing to test with Arma 1.46RC which is currently available and may be released officially next week?
* Fixed: Server issue when using a larger list of BIKEY signature files

Source: http://forums.bistudio.com/showthread.php?149636-Development-Branch-Changelog&p=2939180&viewfull=1#post2939180
Reference: https://twitter.com/Arma3official/status/606835768317890560
