### ISSUE TITLE
RETNIL and RETDEF throwing script errors

### ISSUE THREAD

**Issue by Dorbedo** [CBATeam/CBA_A3#566]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (stable)

**Mods:**
- `@CBA_A3`

**Description:**

the new RETNIL and RETDEF macros are throwing errors if the value is not defined (only sheduled environment)

```
_apple = nil;
_juice = [_apple] param [0]; // throws error
```
old version:
```
_cherry = nil;
_juice = If (isNil{_cherry}) then {nil}else{_cherry}; // no error
```

**Comment by Dorbedo** [comment]
Possible fix ? :
```
#define RETDEF(VARIABLE,DEFAULT_VALUE) ([VARIABLE,DEFAULT_VALUE] select isNil{VARIABLE})
#define RETNIL(VARIABLE) ([VARIABLE,nil] select isNil{VARIABLE})
```

**Comment by commy2** [comment]
^ would error too

**Comment by commy2** [comment]
my proposal:
```
#define RETDEF(VAR,DEF) (if (isNil QUOTE(VAR)) then [{DEF}, {VAR}])
#define RETNIL(VAR) RETDEF(VAR,nil)
```

**Comment by commy2** [comment]
should also add some unit tests for these, so they are not broken again in future

**Comment by 654wak654** [comment]
Why use that syntax commy, the normal if-else syntax doesn't error.

**Comment by commy2** [comment]
Just a command less, doesn't make much difference.
