### ISSUE TITLE
QUESTION: Some help getting to grips with XEH_PREP

### ISSUE THREAD

**Issue by legman** [CBATeam/CBA_A3#569]
I was wondering if someone here could help me try and troubleshoot what i'm doing wrong with XEH_PREP.

I have set it up so that the preStart.sqf includes a XEH_PREP file which uses the PREP macro on several functions. No error is thrown on bootup so that means my functions are being compiled, I can even trace my functions from the uinamespace.

But when I call FUNC(functionName) nothing happens. If i trace FUNC(functionName) i get 'any'.

I have set up my modules correctly using a MAINPREFIX, PREFIX and COMPONENT. I have been using the GVAR macros with not trouble what so ever and if i trace out QFUNC(functionName) i get what i would expect.

Is there documentation on this topic because i have searched far and wide and found nothing. I have been piecing this together using ACE3 and ACRE2 as reference. I feel I missing something really silly due to lack of basic knowledge on the subject.

Any help would be massively appreciated.

Thank you!

**Comment by commy2** [comment]
You need to include the `XEH_PREP.hpp` in preInit and preStart.
preStart caches them in ui namespace, which makes the mission start faster and prevents them from being overwritten by cheaters.
preInit defines them in mission namespace, which makes them usable in scripts.

**Comment by legman** [comment]
ah ok i haven't included them in the preInit!

Could you explain why its included in both preStart and preInit?

**Comment by bux578** [comment]
he did...

**Comment by legman** [comment]
OK sorry, so i miss read what he said. So the preInit sorts the functions out for the mission?

**Comment by commy2** [comment]
>preInit defines them in mission namespace, which makes them usable in scripts.

There is really nothing more to it.

**Comment by legman** [comment]
Sorry, just one more question. Are the recompile start stop macros required for the preinit or is that only if you actually wish to use recompiling!

**Comment by commy2** [comment]
"recompile start stop macros" ?

**Comment by legman** [comment]
for example ive seen

```
PREP_RECOMPILE_START;
#include "XEH_PREP.hpp"
PREP_RECOMPILE_END;
```

**Comment by commy2** [comment]
Nah. Leave them, unless you're working with ACE. That is something @PabstMirror came up with.
https://github.com/acemod/ACE3/blob/a3c50a6c761c7e1f48ea07a57c9c5168e3f4bb93/addons/main/script_debug.hpp#L7-L15
It's not part of CBA by default.

**Comment by legman** [comment]
Thanks again

**Comment by legman** [comment]
Sorry I have one more question more geared towards ACE3 and why they define a DFUNC macro which seems to do the same thing as FUNC?

**Comment by commy2** [comment]
They are the same, unless you use the callstack thing from ACE. The only reason `DFUNC()` exists, is because sometimes you cannot put quotes around functions that are not identifiers.

```sqf
QUOTE(FUNC(test)); // with callstack enabled
->
"{<insert magic sqf>; call ACE_common_fnc_test; <insert more magic sqf>}"
```
vs.
```
QUOTE(DFUNC(test));
->
"ACE_common_fnc_test"
```

**Comment by legman** [comment]
Gotcha!
