### ISSUE TITLE
Global settings forced on server instead of in mission by default

### ISSUE THREAD

**Issue by jonpas** [CBATeam/CBA_A3#580]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (dev `9b824dc1b497b2a549b28c4b7a016d5f692df7e0`)

**Mods:**
- `@CBA_A3`
- `@acre2`

**Description:**
- Global settings are forced on server by default instead of in mission (requiring a server admin to un-force the setting on server to allow mission maker to set it in mission).
- Should probably be forced in mission by default and only forced on server if set so.
- @PabstMirror pointed out a possible bug in https://github.com/CBATeam/CBA_A3/blob/d6ef65be9d78bf7989de1e5b69540eeb673cb1aa/addons/settings/fnc_isForced.sqf#L26

**Steps to reproduce:**
- Load some default global settings.
- See they are forced on server instead of in mission.

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- Not applicable

Point of observation is "Force" column:
![20170125191253_1](https://cloud.githubusercontent.com/assets/7935003/22304329/40633632-e337-11e6-8496-48fb16d84a8d.jpg)
![20170125191254_1](https://cloud.githubusercontent.com/assets/7935003/22304330/40661a46-e337-11e6-876c-494d7a76db95.jpg)

**Comment by GuzzenVonLidl** [comment]
I was about to ask this myself however I found a workaround in the meantime by using in the postInit `["server"] call CBA_settings_fnc_clear;`
