### ISSUE TITLE
issues taskpatrol

### ISSUE THREAD

**Issue by twenz** [CBATeam/CBA_A3#604]
**Arma 3 Version:** `1.66.139586` (stable)
**CBA Version:** `3.2.0.1702224` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- error getpos type bool , fnc_taskpatrol.sqf line 39.

**Steps to reproduce:**
- i use "[this, getmarkerpos "objective1", 50] call CBA_fnc_taskPatrol" 
  but this error

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Comment by commy2** [comment]
https://github.com/CBATeam/CBA_A3/issues/584
