### ISSUE TITLE
Attack,Defend,Patrol functions broken

### ISSUE THREAD

**Issue by GodlikeRU** [CBATeam/CBA_A3#605]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.2.0` (stable)

**Mods:**
```
- CBA_A3
- Task_Force_Radio
- CUP (ALL)
- RHS (ALL)
```

**Description:**
- All ATTACK,DEFEND,PATROL functions are broken. Gives error when trying to used properly. Im using other CBA functions and they work.
- I can provide full mission files if needed

**Steps to reproduce:**
- Start editor
- Execute following script
```
_enemyGROUP1 = [getMarkerPos "Marker_spawnPos3", ENEMY_SIDE, (configfile >> "CfgGroups" >> "Indep" >> "rhs_faction_insurgents" >> "Infantry" >> "IRG_InfSquad_Weapons")] call BIS_fnc_spawnGroup;

[_enemyGROUP1, [2976.07,5500.49,0]] call CBA_fnc_taskAttack;
```
- You can also execute script from wiki, it won't  work too - https://dev.withsix.com/docs/cba/files/ai/fnc_taskAttack-sqf.html

- I wanted to be sure so I tested following code - https://github.com/TheWreckingCrew/TWC-Insurgency/blob/1c23206f3f746bca5f2b46ef9f5100948f375610/client/sys_iedAttack/fn_iedAttack.sqf

Same behaviour. 

**Where did the issue occur?**
- Editor (Singleplayer) 

**RPT log file:**
- http://pastebin.com/gAJ6Aah6

**Comment by commy2** [comment]
Dup #602 #604 #601
