### ISSUE TITLE
CBA 3.2.1 mod.cpp incorrect

### ISSUE THREAD

**Issue by SniperMunyShotz** [CBATeam/CBA_A3#607]
No servers are showing up in the launchers because of the latest update.  Launchers are reporting that the mod.cpp has an error that needs corrected in order for people to see servers.  Any update on this?

**Comment by jonpas** [comment]
How is it incorrect? Even the version number is correct.

**Comment by SniperMunyShotz** [comment]
Waiting for a response from the launcher guys.  I just know myself and a few other server owners are not listed and we received something is wrong with the mod.cpp.  Should have something shortly

**Comment by PabstMirror** [comment]
Are you using a download from github, steam workshop or other source?

**Comment by SniperMunyShotz** [comment]
I personally use the steam workshop and I am able to join just fine.  The issue is for whatever reason I do not understand yet is the launchers do not show the servers.  From my understanding, they use steam workshop as well, but I did find this so far while waiting for a response:

"CBA put version numbers into the mod name, which in my opinion doesnt really make sense but unless they change this "habit", every time CBA updates on Steam, there will be a small period of downtime afterwards."

**Comment by SniperMunyShotz** [comment]
Looks to be fixed now after trying to get an answer......sorry to waste your time, was just chasing down some possible causes.

**Comment by commy2** [comment]
I don't get it.
