### ISSUE TITLE
CBA_fnc_searchNearby improvement

### ISSUE THREAD

**Issue by DevastatorCM** [CBATeam/CBA_A3#613]
**Description:**
Is it possible to improve CBA_fnc_searchNearby so that it has extra parameters likepossibility to enter buildings, range to find buildings, and random duration to stay inside?

Also it will be nice if it doesn't adjust the units combat mode because when I use patrol with safe it switches to aware mode which looks weird..

**Comment by commy2** [comment]
This is a bug tracker, but feel free to open a pull request with your proposed changes.

**Comment by commy2** [comment]
inva
