### ISSUE TITLE
Unit changed PlayerEH not called when leaving Zeus RemoteControl

### ISSUE THREAD

**Issue by dedmen** [CBATeam/CBA_A3#615]
**Arma 3 Version:** `1.66` (stable / rc / dev)
**CBA Version:** `3.2.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- TFAR
```

**Description:**
When leaving a Zeus Remote Control by Pressing the `Z` button the [currentUnit changed Event](https://github.com/CBATeam/CBA_A3/blob/master/addons/events/fnc_addPlayerEventHandler.sqf#L173) is not executed. It only runs after the Zeus Interface was completly closed by Pressing Z again and going back into the Zeus Players eyeCamera

This is probably because the Arma PlayerViewChanged EH doesn't trigger when Zeus leaves Remote Control and goes back into Zeus Interface Camera

Reference: https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1211

**Steps to reproduce:**
- Use this:
```
["unit", {
    systemChat str ["playerChanged",_this];
},true] call CBA_fnc_addPlayerEventHandler;
```
- Go Into Zeus Interface and Remote Control a unit
- Press `Z` to go back into Zeus Interface
- Press `Z` again to close Zeus Interface
- You'll see that the Eventhandler is only called after you exit the Zeus Interface. Although after you quit remote Control and went back into Zeus Interface `CBA_fnc_currentUnit` report's player already.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**Comment by dedmen** [comment]
This could also be a Arma bug because technically the PlayerView changed.. But I'd rather not wait months for BI to fix it

**Comment by commy2** [comment]
Doesn't even fire consistently when using `selectPlayer`. It was a nice idea, but the CBA eventhandlers were specifically made to have a reliable solution. Sometimes things fail and one has to accept that.
