### ISSUE TITLE
Feature Request: Screenshot Mode

### ISSUE THREAD

**Issue by dedmen** [CBATeam/CBA_A3#642]
Feature Request:

Screenshot Mode. CBA Function to enable/disable Screenshot Mode. Eventhandler and Variable for Mods to hook into. Hotkey to toggle it.
Should disable all UI elements. CBA might take care of the Vanilla UI stuff and for example ACE can hook into it to hide for example Nametags when Screenshot Mode is enabled.

I might PR it later just want to hear your thoughts are about this.

Just like the Splendid camera does. But with the ability to do it quickly with just a hotkey press in the middle of battle. Cause everyone likes taking screenshots.

**Comment by commy2** [comment]
I haven't got the `screenshot` SQF command to work, probably because I have the steam overlay disabled.

**Comment by dedmen** [comment]
Not what I meant. I mean just a hotkey that disables every UI element. So you can screenshot using the Steam overlay hotkey or whatever you have. Or take video or anything without these unsighly UI elements interfering. 
Was just looking at a bunch of screenshots and there are so many duplicates in there beceause one forgot to disable the GPS or a ACE Nametag was in the way or something.

**Comment by commy2** [comment]
I suggest using this:
```sqf
(findDisplay 46) createDisplay "RscDisplayEmpty";
```
That should get rid of all visible controls on the main display. It's called "empty", but still has the vignette. Not sure if that should be disabled too.

**Comment by jonpas** [comment]
Vignette is disabled in ACE3 anyways.

If the solution is really just that, then this is a more ACEX feature than CBA/ACE as it needs to hooks, just a keybind and possibly some other tweaks.

**Comment by commy2** [comment]
@dedmen 
Would this be sufficient?
https://armaworld.de/index.php?thread/2957-zeus-auge-bei-ausgeblendetem-hud-entfernen/&postID=22506#post22506
That simply deletes the Zeus watermark. I could see it being part of CBA.

**Comment by dedmen** [comment]
No. I don't care about Zeus as they can already hide everything. I would also like that in CBA but not my aim.
My aim was easy screenshot mode for everyone. Not only for Zeus.
Should also hide ACE Nametags in additon to HUD.

**Comment by commy2** [comment]
How would it be different from the Splendid Camera?

**Comment by dedmen** [comment]
Wouldn't be much different. Except that there is no extra camera. The player is still viewing out of his eyes.

**Comment by commy2** [comment]
But what would the benefit be then? Why not use the Splendid Camera where you can move freely to make screenshots?

**Comment by dedmen** [comment]
Because I can't just give every player access to a freely moveable camera. They would missuse it to look around corners.
I just want to disable the HUD stuff so they can take screenshots out of their current viewing angle with no crap on screen.

**Comment by commy2** [comment]
So it's supposed to be a screenshot mode for active play?

**Comment by commy2** [comment]
```sqf
[
    "Screenshot Mode", "myMod_screenshot", "Screenshot Mode", {
        private _display = findDisplay 46 createDisplay "RscDisplayEmpty";

        _display displayAddEventHandler ["KeyDown", {_this select 1 != 0x01}];

        [{
            (_this select 0) params ["_display", "_shownHUD"];

            if ({_x} count shownHUD > 0) then {
                (_this select 0) set [1, shownHUD]; systemChat str shownHUD;
                showHUD (shownHUD apply {false});
            }; 

            if (isNull _display) then {
                showHUD _shownHUD;
                (_this select 1) call CBA_fnc_removePerFrameHandler;
            };
        }, 0, [_display, []]] call CBA_fnc_addPerFrameHandler;
    }, {}, [0x15, [false, false, false]] 
] call CBA_fnc_addKeybind;
```

**Comment by dedmen** [comment]
Doesn't completly work. Hint's are still showing,

**Comment by commy2** [comment]
I feel like this would be better off in ACE. Not because of what it does, but because of the amount of code that would be required to get it to work. With ACE you could probably build it on top of the selective ui framework, while here we'd have to recreate most of it.

**Comment by dedmen** [comment]
Agree
