### ISSUE TITLE
x\cba\addons\xeh\fnc_startFallbackLoop.sqf, line 12 cba_xeh error in expression

### ISSUE THREAD

**Issue by golden-brigade** [CBATeam/CBA_A3#648]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `2.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
{
    // don't run init and initPost event handlers on objects that already exist
    SETINITIALIZED(_x);
    true
} count (entities [[], [], true, true]);
```

**Description:**
- I had this error pop up after i enabled the CBA mod in the ARMA APEX game in the editor screen. I have the code opened, but cant seem to find the issue.

**Steps to reproduce:**
- ARMA 3 Apex Launch > Editor > Error pops up

**Where did the issue occur?**

- Editor (Singleplayer)
**RPT log file:**
[cba_xeh.pbo.txt](https://github.com/CBATeam/CBA_A3/files/945588/cba_xeh.pbo.txt)

- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by golden-brigade** [comment]
also have this error as well in the same file

![image](https://cloud.githubusercontent.com/assets/27832228/25254599/5ea97444-25f4-11e7-920b-94f2f1dad1a7.png)

**Comment by PabstMirror** [comment]
Need an RPT
Can be found by going to `%userprofile%\AppData\Local\Arma 3` in windows explorer.
Then upload most recent rpt file like `arma3_2017-04-19_23-22-14.rpt`

Not positive but based on screenshot it seems like your game doesn't recognize the `toFixed` command, double check steam is updating it correctly to version 1.68.

**Comment by commy2** [comment]
No error for me. Needs proper RPT file.

**Comment by commy2** [comment]
@golden-brigade Status?

**Comment by commy2** [comment]
No response
