### ISSUE TITLE
Arma 3 - CBA mod not working?

### ISSUE THREAD

**Issue by YReyneke** [CBATeam/CBA_A3#650]
**Arma 3 Version:** `1.68.141205` (stable)
**CBA Version:** `3.2.1.170227` (stable - steam current)

**Mods:**
```
- CBA_A3
- ace
- task_force_radio
```

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.
1: Once game has loaded, and before main menu start up, the message "Script any not found" appears.
2: Once in a game/loaded onto a server, pressing 'configure addons' button has no effect, it responds to the click but no window appears and the game continues running as if nothing happened.
3: For ace3, the options window found in the pause menu, a window opens but there is no information/functionality on it, it is a blank window with very mixed up boxes/regions... Correct title though :')

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
1:     
        • Select mods in launcher
        • Load game
        • Read popup message: "Script any not found".

2: Follow on from '1'
        • Close error message
        • Either when joining a server containing these mods, or when hosting a private (LAN) server (used in this example), and once in game as a player
        • Ace 3 was not working so I attempt to setup controls
        • Open pause menu, go into configure>controls>
        • Configure addons button visible, but not effecting anything (would like to be able to set up controls for both TFAR and ACE3, no surprises)

3:     
        • Going back to pause menu, clicking on Ace 3 options
        • Window appears, but all fields are blank and only some colour info appears on the right 
        

**Where did the issue occur?**
- Dedicated & Self-Hosted Multiplayer

**RPT log files (multiple examples found within folder):**
[ A3-CBA-RPT+Logs_etc.zip ]( https://github.com/CBATeam/CBA_A3/files/949178/A3-CBA-RPT.Logs_etc.zip )

**Comment by commy2** [comment]
Steam Workshop broke your mod installation.

Try deleting:
```
C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CBA_A3\addons\cba_linux.pbo - 7b37670b
```

**Comment by YReyneke** [comment]
Well, thank you so much, I almost spent a whole day trying to solve that issue. I deleted both files related to linux and now everything works as desired :)
