### ISSUE TITLE
Debug console doesn't hold last statement on init

### ISSUE THREAD

**Issue by SilentSpike** [CBATeam/CBA_A3#681]
**Arma 3 Version:** rc
**CBA Version:** dev (fee70aaa838fa287620db82ee10aac007a716a88)

**Mods:**
```
- CBA_A3
- ACE3
```

**Description:**
- When the escape menu is first opened, the most recently executed statement is not shown in the debug console. If I hit "previous statement" then "next statement" it comes back.

**Where did the issue occur?**
- Editor (Singleplayer)

**Comment by SilentSpike** [comment]
@McDiod pointed out in slack, this only happens when the code opens a dialog.

Example:
`["Initialize", [player]] call BIS_fnc_EGSpectator;`

**Comment by commy2** [comment]
Does the same happen with the vanilla debug console?

**Comment by SilentSpike** [comment]
Yeah it looks like the same happens in vanilla, could probably close as a non-issue
