### ISSUE TITLE
File x\cba\addons\strings\fnc_formatNumber.sqf

### ISSUE THREAD

**Issue by alioe3** [CBATeam/CBA_A3#682]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `2.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
```
all other mods disabled ,but 3den is enabled which i guess doesnt interfere with that

**Description:**
- i used the latest CBA version it gave a lot of errors when am still on the main menu, although it doesnt crash the game,  i rolled back to v3.2.1 it launch and load normally, until going into editor, it gives this:
```
"File x\cba\addons\strings\fnc_formatNumber.sqf"
Error in expression <er < 0; private _return = (abs _number) toFixed _decimalPlaces; private _dotInde>..."
```

thanks in advance guys :)

**Steps to reproduce:**
-Just open the editor

**Where did the issue occur?**
- Editor (Singleplayer) 

**RPT log file:**
https://pastebin.com/mxYVJ7zq

**Comment by PabstMirror** [comment]
```
Original output filename: Arma3Retail_DX11
Exe timestamp: 2016/07/11 10:11:04
Current time:  2017/05/15 22:29:43
 
Type: Public
Build: Stable
Version: 1.62.137494
```

You need to let steam update ARMA to the latest version (1.68)

**Comment by 654wak654** [comment]
> You need to let steam update ARMA to the latest version (1.68)
Steam wouldn't let anyone start the game with a version as old as 1.62, plus the game is located in `C:\Arma 3 - Apex\arma3.exe`.

☠️

**Comment by dedmen** [comment]
Your CBA is very outdated. It was probably already fixed.

**Comment by commy2** [comment]
CBA outdated, game very outdated. Cracked games is not supported and will fail with any mods. Please buy the game.
