### ISSUE TITLE
CBA settings in editor dont work since 3.3.1

### ISSUE THREAD

**Issue by Radeni** [CBATeam/CBA_A3#684]
**Arma 3 Version:** `1.70` stable
**CBA Version:** `3.3.1` stable

**Mods:**
```
- CBA_A3 only
```

**Description:**
When a mission.sqm is loaded into the editor,the CBA settings stoped working

**Steps to reproduce:**
https://www.youtube.com/watch?v=HOyEquBoRpc

**Where did the issue occur?**
-  Editor 

**RPT log file:**
https://gist.github.com/Radeni/9eb3c5a8630f19dc796dcc2f70efcb9e

**Comment by PabstMirror** [comment]
Temp fix is load another blank world, then load your mission

**Comment by commy2** [comment]
```sqf
[cba_settings, cba_keybinding]
[any,any]
```
after using NEW or OPEN with the same map as currently.

**Comment by PabstMirror** [comment]
loading a mission clears missionNamespace now

**Comment by Radeni** [comment]
thats actually when the issue occurs,when a blank world is replaced by a mission so that isnt a temporary fix. In my mission's case it works,its just that its currently impossible to edit its settings for DCG but it does work. Hopefully you'll manage to fix it soon.

**Comment by commy2** [comment]
Loading the mission when you currently have a different terrain opened is what should work.

**Comment by PabstMirror** [comment]
Sorry @Radeni 

From debug console (Ctrl + D) you should be able to run command
```
[] call CBA_fnc_preInit
```
Can verify by checking var `cba_xeh_isProcessed`

**Comment by Radeni** [comment]
Allright guys. Yea,wont be hard to use the console obv
