### ISSUE TITLE
PlayerEventhandler "vehicle" values after gettingOut

### ISSUE THREAD

**Issue by Dorbedo** [CBATeam/CBA_A3#687]
**Arma 3 Version:** `1.70` (stable)
**CBA Version:** `3.3.1` (stable )

**Mods:**
```
- CBA_A3
- ACE3
```

**Description:**
- The "vehicle" playerEventhandler doesn't pass the expected value.

**Steps to reproduce:**
```
["vehicle", { 
   hintSilent format["%1 - %2",typeof (_this select 0),typeof (_this select 1)]; 
},true] call CBA_fnc_addPlayerEventHandler;
``` 
It passes [player,player] instead of [player,oldvehicle] after getting out of a vehicle (testet with hummingbird)
On gettingIn, the values are [player,vehicle player].

**Where did the issue occur?**
- Editor (Singleplayer)

**RPT log file:**
- none

**Comment by Dorbedo** [comment]
The question is: Is this by design, or is this a bug?

**Comment by commy2** [comment]
It passes `player, vehicle player` essentially, just like how `weapon` passes `player, currentWeapon player`.

**Comment by Dorbedo** [comment]
Alright then - the issue is invalid.

This function could use some additional documentation or examples.

**Comment by commy2** [comment]
Doc is here: https://github.com/CBATeam/CBA_A3/wiki/Player-Events
