### ISSUE TITLE
ErrorMessage: Include file x\cba\addons\main\script_macros_common.hpp not found

### ISSUE THREAD

**Issue by jpoblocki77** [CBATeam/CBA_A3#691]
**Arma 3 Version:** newest rc` (stable / rc / dev)
**CBA Version:** `Newest` (stable / dev + commit hash)

**Mods:**
```;@Advanced Rappelling;@Advanced Rappelling;@Ares Mod - Achilles Expansion;@CBA_A3;@CUP ACE3 Compatibility Addon - Vehicles;@CUP ACE3 Compatibility Addon - Weapons;@CUP Units;@CUP Vehicles;@CUP Weapons;@Enhanced Movement;@MCC Sandbox 4 -  Mission Making The Easy Way;@Remove stamina;@Remove stamina - ACE 3  
- CBA_A3
```

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.
ErrorMessage: Include file x\cba\addons\main\script_macros_common.hpp not found

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
boot he server.

**Where did the issue occur?**
- Dedicated server at boot

**RPT log file:**
https://pastebin.com/9BBfa8yh

**Comment by jpoblocki77** [comment]
wait a min not a release client its the stable game

**Comment by PabstMirror** [comment]
`-mod=@ace;@Advanced Rappelling;.....`
 I think the space in mod names is the problem
Wrap the mod list in quotes
`-mod="@ace;@Advanced Rappelling;....."`

**Comment by jonpas** [comment]
It has to be `"-mod=@ace;@Advanced Rappelling;..."` (spaces around whole thing) IIRC.

**Comment by jpoblocki77** [comment]
on just the mods that have spaces or the entire command line?

**Comment by jpoblocki77** [comment]
and i cannot wrop mod in quotes

**Comment by jpoblocki77** [comment]
the part that says - mod is part of the command line i dont have acess to
all i can do is list the mods

**Comment by commy2** [comment]
You have to start CBA. This has nothing to do with CBA_A3. It's more of an error with whoever hosts the server.

>on just the mods that have spaces or the entire command line?
The entire command line. If it's a Linux server, also make sure the capitalization is the same as the mod folders have.

Close?

**Comment by Killswitch00** [comment]
Yes. jonas reply above holds the solution - quote the whole `-mod` launch parameter (Another example: `"-mod=aaa;bbb bb;ccc"`)
