### ISSUE TITLE
Request player event for joining / leaving group

### ISSUE THREAD

**Issue by Crazy538** [CBATeam/CBA_A3#693]
Is there scope for a "player joined group" and "player left group" event in your player events framework? Currently, there is no way of detecting these events without polling (please correct me if I'm wrong) and seeing as you are already doing the polling with the intention of reducing the need elsewhere I figured I'd ask. The main use I can think of is restricting group sizes in missions and game modes but it could be used in all sorts of situations I imagine.

**Comment by commy2** [comment]
All the currently available events are used in ACE or at least were used at some point. Sure we could add a check for the players group, but then it does check for that every frame. Is it worth it? I'm not convinced it is.

**Comment by Crazy538** [comment]
Ah, are they every frame? Yea, possibly not worth it at that level. Thought I'd ask is all. If you guys don't' see a use for this then fair enough :)

**Comment by Killswitch00** [comment]
Support added to CBA 3.4.0
