### ISSUE TITLE
CBA_settings - Addon Options in Editor only availible after the first run of a mission

### ISSUE THREAD

**Issue by Dorbedo** [CBATeam/CBA_A3#695]
**Arma 3 Version:** `1.70` (stable)
**CBA Version:** `3.3.1` (stable)

**Mods:**
```
- CBA_A3
- ACE3
- ...
```

**Description:**
- The AddOn options inside the 3den Editor are only accessible after you've run the mission for at least 1 time

**Steps to reproduce:**
1. start the game
2. open 3den
3. load a mission
4. no AddOn settings availlible

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**RPT log file:**
- None

**Comment by PabstMirror** [comment]
See https://github.com/CBATeam/CBA_A3/issues/684

Will be fixed in 3.4, for now just run this in debug console:
`[] call CBA_fnc_preInit`

**Comment by Dorbedo** [comment]
Ahh, damn. I forgot this issue.
