### ISSUE TITLE
XEH Init doesn't honour BIS_fnc_vehicleInit for certain assets (i.e. SAM and AA assets in JETS DLC)

### ISSUE THREAD

**Issue by tupolov** [CBATeam/CBA_A3#704]
**Arma 3 Version:** `1.72` rc
**CBA Version:** `3.x.x` stable

**Mods:**
```
- CBA_A3
- ALiVE
```

**Description:**
- When creating a variant of the SAM/AA vehicles, BIS_fnc_initVehicle doesn't fire and therefore vehicle customizations are not honoured.
- If you manually add the BIS init in the vehicle config, customization works fine.
- Is this a similar issue to what was experienced with the Taru Helicopter init? 

**Steps to reproduce:**
- Add the following config to CfgVehicles
```
    class StaticMGWeapon;
    class AAA_System_01_base_F : StaticMGWeapon
    {
        class textureSources
        {
            class Sand
            {
                factions[] = {"BLU_F","OPF_F"};
            };
        };
    };
    class B_AAA_System_01_F;
    class O_AAA_System_01_F : B_AAA_System_01_F
    {
        crew = "O_UAV_AI";
        faction = "OPF_F";
        side = 0;
        typicalCargo[] = {"O_UAV_AI"};
        textureList[] = {"Sand",1};
    };
```
- Go into the editor and place the vehicle, it should have a Sand/Tan colour - it doesn't.

**Where did the issue occur?**
- Editor

**Comment by Dorbedo** [comment]
Can not reproduce with CBA only.
XEH works like a charm.

**Comment by tupolov** [comment]
You seem to misunderstand my point here. 

I shouldn't have to add the init manually to fix this. XEH should take care of any vehicles where BIS has added vehicle customization code in the vehicle init.

**Comment by Dorbedo** [comment]
I personally don't see why cba should handle this.
You could just add the lines by yourself, since you are already creating a custom unit / modifiying an unit.

Currently I only see disadvantages: e.g. the performance drain and the need to detect if the vanilla function was already executed.

Maybe someone else can see an improvement for CBA, because I can not.

**Comment by tupolov** [comment]
Well there's a precedent set already in CBA for this issue as far as I can see:

https://github.com/CBATeam/CBA_A3/blob/2c3006216ac2ab2ff50d7cd83bfd2fae3ff18ec4/addons/xeh/CfgVehicles.hpp#L323

**Comment by commy2** [comment]
Does `BIS_fnc_initVehicle` execute when you create "a variant of the SAM/AA vehicles" without CBA?.

**Comment by tupolov** [comment]
Good point, will test.

**Comment by commy2** [comment]
@tupolov Updates?
