### ISSUE TITLE
Movement Bug

### ISSUE THREAD

**Issue by runedog48** [CBATeam/CBA_A3#714]
**Arma 3 Version:** `1.72.14223` (stable)
**CBA Version:** `3.4.0` (stable/workshop)

**Mods:**
```
- CBA_A3
```

**Description:**
Edit: Video ( https://www.youtube.com/watch?v=SEGCIc47V1c&feature=youtu.be )
Whenever I try to move forwards it will sometimes get stuck and not allow me to move forward as if there were a small prop obstructing my movement. This seems to occur most often when moving diagonally ( eg. holding W and D ). It does not occur when sprinting forwards however, it always occurs when sprinting diagonally. The functionality of the mod seems to remain intact but this bug makes the game is rendered unplayable with this movement 'clipping'. The movement bug occurs with or without other mods being loaded. 

I unsubscribed from the mod, resubscribed, and then created a new user profile ( to clear my keybinds? ) but it still occurs.
Edit: Forgot to mention I resub'd after unsub'ing. For clarity: It does not occur when CBA is not loaded.

**Steps to reproduce:**
Move forwards.

**Where did the issue occur?**
Editor ( Singleplayer )

**Comment by runedog48** [comment]
The issue is only present when using the workshop version.

**Comment by commy2** [comment]
>I unsubscribed from the mod, created a new user profile ( to clear my keybinds ) and it still occurs.

You're doing something very wrong then.

**Comment by runedog48** [comment]
I'm not sure what is wrong. I included a video in the OP to demonstrate what is happening. It occurs even with only CBA loaded. I figure it's something wrong with my client considering nobody else is having these issues I just don't know how to fix it.

**Comment by Dorbedo** [comment]
Can you try this with a different keyboard?

**Comment by commy2** [comment]
Needs RPT file.

**Comment by runedog48** [comment]
There is no problem with CBA the issue is my keyboard. It's a cheap USB which features "anti-ghosting" and it doesn't seem to work correctly. I didn't notice an issue before because I primarily use Linux and had to get custom drivers for the keyboard to work ( basically turned it into a generic USB ). I recently installed Arma on Windows ( Linux didn't play well with mods ) and didn't notice this problem at first. Sorry for wasting your time.

**Comment by commy2** [comment]
No problem. Glad you could resolve your issue!
