### ISSUE TITLE
CBA_fnc_addKeybind memory exhaustion

### ISSUE THREAD

**Issue by MaHuJa** [CBATeam/CBA_A3#715]
**Arma 3 Version:** `1.72` current stable
**CBA Version:** `3.4.0` 'stable'. (3.3.1 tested to work).

**Mods:**
```
- CBA_A3
```

**Description:**
- Out of memory crash on function call
- ALiVEOS/ALiVE.OS#339

**Steps to reproduce:**
- In controls, user, set 'user action 20' to alt+`  (key left of 1)
- Run 
```
tmp = [(ActionKeys "User20" select 0),[false,false,false]];
["ALiVE","openMenu", "Open Menu (Requires Restart)", {playsound "HintCollapse"}, {}, tmp] call CBA_fnc_addKeybind;
```

FWIW `(ActionKeys "User20" select 0)` returns **9.39524e+008** in this case.

**Where did the issue occur?**
- On game start if running `@alive` mod, else done in editor.

**RPT log file:**
- https://gist.github.com/MaHuJa/f92851380fc199714262513ef797f961

**Comment by PabstMirror** [comment]
Key codes above 255 don't make sense
https://community.bistudio.com/wiki/actionKeys 
has some info on the mess that the command returns, but it doesn't seem usable if it's bound with modifies

 https://github.com/CBATeam/CBA_A3/pull/638#discussion_r115583326 - life found a way :smile:

**Comment by MaHuJa** [comment]
A change on the repro - I unbound the user20 key, so the tmp was printed as [<NULL>,...] and the issue still occurs.

**Comment by PabstMirror** [comment]
Start editor and open debug console and run
```
tmp = [0,[false,false,false]];
["ALiVE","openMenu", "Open Menu (Requires Restart)", {playsound "HintCollapse"}, {}, tmp, false, 0, true] call CBA_fnc_addKeybind;
```
Hopefully that should overwrite the saved setting in your profile and fix the issue for now

**Comment by MaHuJa** [comment]
Next repro was setting appmenu (22) and it crashed. Calling it with 0 did not crash. After which 22 also worked.
