### ISSUE TITLE
Group renaming reverted when loading the missionfile

### ISSUE THREAD

**Issue by chris579** [CBATeam/CBA_A3#718]
**Arma 3 Version:** `1.72` (stable)
**CBA Version:** `3.4.0.170627` (stable)

**Mods:**
```
- CBA_A3
- ACE3
- a ton of other mods that shouldn't affect this issue
```

**Description:**
- When downloading the missionfile the group renaming will be reverted. The groups will get their old naming (e.g. `Alpha 1-1`) and the unit that is containing the group name will be shown with the full role description (e.g. `Group leader@Alpha 1`)

![](https://steamuserimages-a.akamaihd.net/ugc/848216256553246108/8D4A04182725C503EB958E6E32CCEB0A7D297869/)

**Steps to reproduce:**
- Load a mission on a dedicated server where at least one group is renamed. The mission should include some bigger files that you can see the loading process.

**Where did the issue occur?**
- Dedicated

**Comment by PabstMirror** [comment]
The system runs on
```
_display displayAddEventHandler ["MouseMoving", _fnc_update];
_display displayAddEventHandler ["MouseHolding", _fnc_update];
```
I'm guessing that that progress bar blocks the display's mouse EH
Probably nothing we can do about this

**Comment by chris579** [comment]
Does the CBA pfh only run on mission startup? If so this could be achieved with the BI pfh or by hooking up into the progress bar and adding the display handler there too.

**Comment by commy2** [comment]
PFH don't work inside the lobby and neither does BI's EachFrame mission eventhandler. That is why I used this method. I guess the solution would be to also add these eventhandlers to the loading bar display.
