### ISSUE TITLE
weapon Attachments not found or not usable.

### ISSUE THREAD

**Issue by pabclsn** [CBATeam/CBA_A3#721]
**Arma 3 Version:**  `1.72` (stable)
**CBA Version:**CBA_A3 v3.4.0.170627

**Mods:**
```
- CBA_A3
```

**Description:**
- Hi guys, I'm making an altis life server v4.4r4, everything is working fine so far but only one thing is wrong. When I start my server with the CBA_A3, I can't buy weapons attachments anymore. Without CBA my shops are working fine I can buy the weapons, magazines and attachments, with CBA only weapons and magazines. Here is some screenshots  this one without CBA : ![sans cba](https://user-images.githubusercontent.com/25625769/27900916-5f0d5f04-6230-11e7-97b1-f4b614583134.PNG)
then with CBA : ![avec cba](https://user-images.githubusercontent.com/25625769/27900929-6bbf9f64-6230-11e7-83a2-501af4e78ce3.PNG)

**Where did the issue occur?**
- Dedicated Server WS2012 R2

**RPT log file:**
- RPT file without CBA : https://gist.github.com/pabclsn/172767a039b4f93310ef2d148c495d96
- RPT file with CBA : https://gist.github.com/pabclsn/afcc5f9cec16714484d6eaf552a06ef8

**Comment by commy2** [comment]
Looks like your script is incompatible with the way Joint Rails adds weapon attachments. Since that way is totally legitimate and used by many asset mods, it's a problem with your script.
The difference is between using the "compatibleItems[]" array vs. the "class compatibleItems" sub class.

**Comment by pabclsn** [comment]
here is my configuration file for weapons and magazines : https://gist.github.com/pabclsn/c7c24f98fd817008585f090cae4fcf47

can i do something about it or it's simply not possible ?

**Comment by commy2** [comment]
It has nothing to do with that config, but with the script you're using for that store. And it can be easily fixed if the script is somewhat reasonably made.

**Comment by pabclsn** [comment]
Ok i'm gonna look for it thanks.

**Comment by commy2** [comment]
Maybe it's as simple as replacing `BIS_fnc_compatibleItems` with `CBA_fnc_compatibleItems`. Idk.

**Comment by pabclsn** [comment]
I'm pretty new to Sqf arma 3 server Etc so I'm gonna search. Thanks

**Comment by pabclsn** [comment]
Do you know where you can switch between BIS_fnc_compatibleItems and CBA_fnc_compatibleItems ?

**Comment by commy2** [comment]
In a text editor?

**Comment by pabclsn** [comment]
no but the file who is concerned ;)

**Comment by pabclsn** [comment]
Because the compatibleItems thing you talk I found it in the weaponShopAccs (https://gist.github.com/pabclsn/10861d5bfb02d36d5142806af032f92f) and in (https://gist.github.com/pabclsn/ee5fea83aa6d0ba345119677b7e9ee31)

**Comment by commy2** [comment]
https://gist.github.com/pabclsn/10861d5bfb02d36d5142806af032f92f#file-fn_weaponshopaccs-sqf-L14-L40
These lines should be deleted and L14 be changed to:
```sqf
_weaponArray = _weapon call CBA_fnc_compatibleItems;
```

And these lines should be deleted
https://gist.github.com/pabclsn/ee5fea83aa6d0ba345119677b7e9ee31#file-fn_weaponshopselection-sqf-L55-L80
and replaced with:
```sqf
_itemArray = _weapon call CBA_fnc_compatibleItems;
```

That is my guess. Idk Life at all, so you're probably better off asking the authors for further help.

**Comment by pabclsn** [comment]
Ok thanks a lot @commy2  👍
