### ISSUE TITLE
Virtual Arsenal Crashes Game After Some Use.

### ISSUE THREAD

**Issue by Kruger48** [CBATeam/CBA_A3#738]
**Arma 3 Version: stable, Version 1.74
**CBA Version: Steam Version

So I've been having this problem for awhile now and it seems that I am not alone (Link In Description) but everytime after limited use of the Virtual Arsenal on the Eden (3D) Editor, the game just essentially freezes on the loadscreen, preventing me from further creating, let alone completing scenarios within the editor ever since. Through research and trialing on the previous versions of ARMA, the issue has been isolated to the CBA mod and given the level of dependency updates on CBA from other mods, I find myself with zero options and zero solutions...

Thanks in advance...

Link:
https://www.reddit.com/r/arma/comments/49kmb4/arma_3_crashing_please_help/ # #

**Comment by Dorbedo** [comment]
Could you please upload your *.rpt file? Since you are talking of other mods: does the issue occur with CBA only too?
> **RPT log file:**
Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by Kruger48** [comment]
Here you go, thanks by the way.

https://gist.github.com/Kruger48/82c4a34f488b2a16b276638cef521b5e

**Comment by commy2** [comment]
Please upload a RPT file with only CBA enabled. Thanks!

**Comment by commy2** [comment]
>everytime after limited use
Does this mean I have to try multiple times to open the arsenal in the editor? Or does the issue happen _every time_?

**Comment by Kruger48** [comment]
Well usually, I'd open up a new map on editor (Mostly Altis) and then I'd go about "building" my "scenario". Initially, every-time, the Virtual Arsenal would work fine but after like say twenty-five to thirty uses on that specific scenario, the next time you'd use it, the game crashes/freezes. Oddly enough, whenever I repeat the entire process on a different or new "scenario", it'd initially work just as fine like the last one, then unexpectedly cease working and crashes after some use.

**Comment by Dorbedo** [comment]
The Problem is, that you are using a lot of mods. It could be anyone of these mods, a combination of two or even just the amount of mods.

How did you identify CBA as the source of your issue?

**Comment by commy2** [comment]
I couldn't reproduce the error by opening the arsenal 25 times, waiting a few minutes and opening it 25 times again.

**Comment by commy2** [comment]
>Please upload a RPT file where you reproduce the freeze with only CBA enabled. Thanks!

**Comment by Kruger48** [comment]
You mean with just CBA installed and no other mods?

**Comment by commy2** [comment]
Yes.
