### ISSUE TITLE
error: `cba_xeh` requires addon `A3_Props_F_Orange`

### ISSUE THREAD

**Issue by AlexTriada** [CBATeam/CBA_A3#748]
**Arma 3 Version:** `1.76.142872` (stable)
**CBA Version:** `3.4.1.170912` (stable)

**Mods:**
```
- ace
- rhs
- tfr
- CBA_A3
```

**Description:**
- error: `cba_xeh` requires addon `A3_Props_F_Orange`

**Steps to reproduce:**
- start dedicated server

**Where did the issue occur?**
- Dedicated

**Comment by commy2** [comment]
Needs RPT file.

**Comment by AlexTriada** [comment]
до обновления всё работало как надо

**Comment by AlexTriada** [comment]
before the update everything worked as it should

**Comment by AlexTriada** [comment]
https://drive.google.com/open?id=0B_ZGo50ikdTyR2FSWGdtRnBwNDA

**Comment by AlexTriada** [comment]
Sorry, close  the issue, pls) 
I already fix this
