### ISSUE TITLE
TargetDebug console selection bug

### ISSUE THREAD

**Issue by shukari** [CBATeam/CBA_A3#752]
**Arma 3 Version:** stable
**CBA Version:** stable

**Mods:**
```
- Ace3
- CBA_A3
```

**Description:**
- https://youtu.be/GsMK4GLidPI

**Steps to reproduce:**
- https://youtu.be/GsMK4GLidPI

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**RPT log file:**
- https://gist.github.com/shukari/77810f1a91a4f14615afa8811655b338

**Comment by Dorbedo** [comment]
I have the same bug.

**Comment by commy2** [comment]
```
Description:
https://youtu.be/GsMK4GLidPI

Steps to reproduce:
https://youtu.be/GsMK4GLidPI
```
I laughed. Can confirm, have the same bug.

**Comment by jonpas** [comment]
> [22:33] Target Debug target selection drop-down is kinda broken
> [22:33] you can't click select, arrow keys work

@commy2 told you on Slack already! 😆 Forgot to make an issue though.

**Comment by PabstMirror** [comment]
Confirm bug, but couldn't make any progress on fixing it,
UI seems fine and it worked prior to 1.76

**Comment by shukari** [comment]
What seams to be the problem? That someone can create a feedback ticket for that.

**Comment by PabstMirror** [comment]
Can't change selection on the `RscCombo`
https://github.com/CBATeam/CBA_A3/blob/master/addons/diagnostic/fnc_initTargetDebugConsole.sqf#L57

**Comment by jonpas** [comment]
Looks like the same thing that was (still is?) plaguing Eden boxes on certain UI sizes.

**Comment by commy2** [comment]
Not having it as child control of the RscDebugConsole controls group makes it selectable. I tried to change the order of the controls, but it didn't help.
Sadly that also means that it appears in the background and has to be tab selected.
