### ISSUE TITLE
Calling CBA_fnc_removeMagazineCargo on GroundWeaponHolders "removes" all magazines

### ISSUE THREAD

**Issue by ACyprus** [CBATeam/CBA_A3#756]
**Arma 3 Version:** 

Type: `Public`
Build: `Stable`
Version: `1.76.142872` `64-bit`

**CBA Version:** `3.4.1.170912-77f6349d`

**Mods:**
```
- CBA_A3
```

**Description:**   
  
This may be intended functionality, in which case _I apologise for logging the issue_. I am aware the function header examples refer to boxes, where this issue would never arise, but decided to raise this just in case.  
  
Calling `CBA_fnc_removeMagazineCargo` where the cargo space is a `GroundWeaponHolder` containing only magazines results in the holder itself being removed. I'm assuming the engine is deleting the empty holder before the function can re-add the remaining magazines.  
  
**Steps to reproduce:**
- Drop a variety of magazines into the same space on the ground.
- Run the function to remove 1 magazine of a particular class.
- _All magazines disappear._
  
Then, repeat but drop another item into the same holder, for example a weapon accessory, _before_ running the function.
- _only the desired magazine is "removed"._

**Where did the issue occur?**
- Editor (Singleplayer), but the function uses `clearMagazineCargoGlobal`.

**RPT log file:**
- Nothing interesting in the RPT.

**Comment by jonpas** [comment]
Should be fixed by #747.

**Comment by ACyprus** [comment]
Thanks, apologies for wasting your time.

**Comment by jonpas** [comment]
I suggest you try it, because I didn't test anything with holders directly, #747 fixes removing all magazines when it shouldn't do, but I don't think it's exactly your use case.
