### ISSUE TITLE
Feature Request: Retrievable Lobby Slots

### ISSUE THREAD

**Issue by Bosenator** [CBATeam/CBA_A3#761]
Currently there's no function available for a mod to list all MP playable slots including non-occupied ones in game, if the respawn type in Description.ext is not SIDE or GROUP. At least that I could find. See: https://community.bistudio.com/wiki/switchableUnits

CBA iterates through the Mission Lobby UI already, for the renaming of groups. Could it be possible on first iteration of this list, that an array is constructed housing the groups, and within each group all the possible slots, occupied or not. Then making this array retrievable, so mod makers and mission makers alike can make dynamic and reliable slot lists in game. From that we can use existing BI functions to retrieve and intersect occupied roles, so I believe that element may be unnecessary. 

Thanks for reading,
Bosenator

**Comment by commy2** [comment]
It could store an array of strings - the role descriptions. There're a few issues with that though.
This array would not be available on a machine without interface, as there's no ui to read from. I guess you could synch it as public global variable from the host though.
There are four pages for the groups, west, east, indep and civ. There's no guarantee that all four of them have been looked at. If a sides page has not been looked at, the ui script can't know which slots the side has.
From the wiki description, wouldn't it make more sense to use:
```sqf
playableUnits select {side group _x == playerSide
```
to report these units?

**Comment by Bosenator** [comment]
The following:
```sqf
playableUnits select {side group _x == playerSide}
```
Would unfortunately return only currently player occupied slots, or slots that have AI enabled.

I didn't consider the fact other pages might not be observed, sorry - I'm used to only CO-OP.

**Comment by commy2** [comment]
```sqf
playableSlotsNumber playerSide
```
Would report the number of slots of the side of the player. And subtracting this from the `count` of the previous would report the open slots.
But I guess you need the role descriptions?

**Comment by Bosenator** [comment]
That's correct.

**Comment by Cuel** [comment]
I made some validation thing a while ago, pasted below, related to your request. You could modify it for your needs.

description.ext
```
class MissionSQM
{
	#include "mission.sqm"
};
```

some script
```sqf
private _cfg = (getMissionConfig "MissionSQM");
private _grps = "true" configClasses (_cfg >> "Mission" >> "Entities") select {getText (_x >> "dataType") == "Group"};
{
	private _ents = "true" configClasses (_x >> "Entities") select {getText (_x >> "dataType") == "Object"};
	private _playableInGroup = {
		private _attrs = _x >> "Attributes";
		if (getNumber(_attrs >> "isPlayer") isEqualTo 1 || getNumber(_attrs >> "isPlayable") isEqualTo 1) exitWith {true};
		false
	} forEach _ents;
	
	if (_playableInGroup) then {
		private _leader = (_ents select 0) >> "Attributes";
		private _description = getText (_leader >> "description");
		// ...
	};
} forEach _grps;
```

**Comment by commy2** [comment]
You need to not binarize the mission for this ^ to work.

**Comment by Bosenator** [comment]
Someone mentioned doing something similar to that on Discord, Cuel. Thanks for the code. However this is dependant on a mission maker doing this, which isn't very friendly from an addon point of view.

**Comment by Bosenator** [comment]
I believe this just isn't going to be possible in a nice, non-niche manner. Thanks for the help, it's greatly appreciated.

Would be okay if I use your existing code @commy2 as a basis, and iterate on it for our more specialised need?

**Comment by commy2** [comment]
Sure. I suggest adding another DisplayLoad XEH on top of it. See:
https://github.com/CBATeam/CBA_A3/blob/master/addons/ui/CfgEventHandlers.hpp#L21-L23

**Comment by Bosenator** [comment]
Thanks a lot, commy2. I'll close the issue.
