### ISSUE TITLE
keybinding with Alive

### ISSUE THREAD

**Issue by jtareb** [CBATeam/CBA_A3#790]
Arma 3 1.76.143187
cba 3.4.1

mods
Alive

Description

The Alive mod uses the action key( right side Win key) to open its in game menu's. Since my keyboard does not recognize this key I re-binded it to another, control+middle mouse button.  

That in turn will not work and generates this error message.
18:51:17 [CBA] (keybinding) WARNING: Keybind alive$openmenu's default keybind is invalid [DIK: 4.87653e+008] x\cba\addons\keybinding\fnc_addKeybind.sqf:106

No idea what it means or what the solution is. At this point I cannot rebind anything to use the in game Alive menu as the cba will not accept whatever I input. There have been multiple users with the same problem.

**Comment by commy2** [comment]
Good report.

**Comment by dedmen** [comment]
Thank you for participating and goodbye.

**Comment by jtareb** [comment]
I was editing the comments. 

I hope this is not your usual demeanor

**Comment by commy2** [comment]
@jtareb Try the following:
- completely unbind everything from User20 in the Custom category of the vanilla keybinding menu.
- close and reopen the game. Don't use load a savegame. Start a new one.
- open Keybinding menu -> CONFIGURE ADDONS -> ALiVE -> "Open Menu (Requires Restart)"
- bind to whatever you want
- never bind anything to User20 ever again

Ref: https://github.com/ALiVEOS/ALiVE.OS/blob/master/addons/main/XEH_preInit.sqf#L7

**Comment by jtareb** [comment]
Thx

Never bound anything to User20 but when I checked it was listed as my new bind. Did your fix with a new scenario and the CBA error went away but still cannot access the Alive menu. I hear a beeping sound when I try to access it so there is a some kind of connection being made, just not the right one. 

Am getting multiple ALive errors though so its back to them.

**Comment by commy2** [comment]
I checked their code and it seems that all the keybind does is to make this beeping sound. And then they add their own key handlers to various menus and read what the action is bound to in CBA. The problem with that is, that the way they do it is not supporting mouse buttons. So you probably have to use something other than middle mouse button.
