### ISSUE TITLE
x\cba\addons\main\script_mod.hpp not found

### ISSUE THREAD

**Issue by TBSJJ** [CBATeam/CBA_A3#793]
**Arma 3 Version:** `x.xx` (stable
**CBA Version:** `3.x.x` (stable 

**Mods:**
```
- CBA_A3
```

**Description:**
-on server everything else loads fine then error message comes up and single player is a gamble sometimes it works with mods enabled sometimes it doesnt work same message

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
Launching arma 3 sometimes then launching dedicated server

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer  

**RPT log file:**
https://pastebin.com/R8sbqDky

**Comment by commy2** [comment]
CBA was not used in that session, which is why the error message pops up. The RPT is also incomplete, but I can still tell.

**Comment by TBSJJ** [comment]
CBA is loaded as a server mod and in the the files it is also loaded first and if cba wasnt loaded id get a different message as ive tried to run without cba and it stops when loading CUP assetts

**Comment by PabstMirror** [comment]
```
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_accessory.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_ai.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_arrays.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_common.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_diagnostic.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_events.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_hashes.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_help.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_keybinding.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_main_a3.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_modules.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_music.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_network.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_settings.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_statemachine.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_strings.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_ui.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_ui_helper.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_vectors.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_versioning.pbo - 77f6349d
19:11:40 C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\cba_xeh.pbo - 77f6349d
```
There should be a cba_main.pbo and cba_main_a3.pbo
I only see  cba_main_a3.pbo

I would recomend re-downloading a fresh copy
https://github.com/CBATeam/CBA_A3/releases/download/v3.4.1.170912/CBA_A3_v3.4.1.zip

**Comment by TBSJJ** [comment]
ive just done that twice over still same error message i dont get it when i check the directory the script its trying to find does exist

**Comment by commy2** [comment]
Good find, pabst. It's only cba_main.pbo that's missing (not to be confused with cba_main_a3.pbo).
You're probably looking into the wrong folder if that PBO file exists for you.

**Comment by TBSJJ** [comment]
cheers guys i hope this works its been bugging me for days

**Comment by TBSJJ** [comment]
https://pastebin.com/hc4MHENy <<< Same issue again

**Comment by commy2** [comment]
Post screenshot from the folder. I also wonder if servermod even works for all these mods with assets. Everyone needs those, not just the server machine.

**Comment by commy2** [comment]
`C:\TCAFiles\Users\JamesB\21866\@CBA_A3\addons\` I mean by "the folder".

**Comment by TBSJJ** [comment]
![screenshot_11](https://user-images.githubusercontent.com/33402946/32693036-ac695050-c71b-11e7-9562-be1efef7aa21.png)
![screenshot_12](https://user-images.githubusercontent.com/33402946/32693038-b2ddc9d4-c71b-11e7-96f5-2f4e7e3a119c.png)
![screenshot_13](https://user-images.githubusercontent.com/33402946/32693039-b5f6c120-c71b-11e7-9543-298440e9a08d.png)
![screenshot_14](https://user-images.githubusercontent.com/33402946/32693040-b8a9fef0-c71b-11e7-87b4-4d70aac55194.png)

**Comment by commy2** [comment]
Bad filebrowser doesn't give the full path...
I'd try to just start @CBA_A3 _only_ and check if all files are loaded correctly. Also, use -mod, not -servermod.

**Comment by TBSJJ** [comment]
i cant access the full path as this is a dedicated server that file is there side i just tried again and still same message

**Comment by commy2** [comment]
Start only CBA_A3 (no other mods) and upload the RPT file.

**Comment by TBSJJ** [comment]
ok will do

**Comment by TBSJJ** [comment]
https://pastebin.com/bRSkEgrA

**Comment by commy2** [comment]
Incomplete, need full file.

**Comment by Dorbedo** [comment]
I'd recommend you to just start a default mission and see if it fails

**Comment by commy2** [comment]
Not needed, I just need the full RPT. Mission fail due to missing mods is no problem.

**Comment by TBSJJ** [comment]
all the console was doing was looping after the final line

**Comment by commy2** [comment]
The header is important, not the end.

**Comment by TBSJJ** [comment]
that is the header thats the start

**Comment by commy2** [comment]
No. It must start with
```
=====================================================================
== C:\TCAFiles\Users\JamesB\21866\arma3server.exe
```
etc.

**Comment by TBSJJ** [comment]
ill run it again

**Comment by TBSJJ** [comment]
no header not sure why its exactly the same as previous 
i managed to fix this issue single player by re arranging the load order on mod manager but cant seem to replicate the same results on a dedicated server

**Comment by commy2** [comment]
Bad tools if they delete the beginning of the RPT file. Can't really help then. My suspicion is, that it's a bad mod breaking it. Enable mod after mod and check if the error returns.

**Comment by TBSJJ** [comment]
ok dude can do

**Comment by commy2** [comment]
If you find which mod, then please share.
