### ISSUE TITLE
Undefined Var in CBA_fnc_init

### ISSUE THREAD

**Issue by bgillissen** [CBATeam/CBA_A3#797]
Arma 3 Version: 1.76.1343187 (stable)
CBA Version: 3.4.1 (stable / workshop)

**Mods:**
- CBA_A3
the issue also occurs with alot more mods, all 3 rhs, ace, tfar

**Description:**
14:42:33 [XEH]: preInit already executed. Abort preInit.
14:42:33 Error in expression <
params ["_this"];

if (_this call CBA_fnc_isTerrainObject) exit>
14:42:33   Error position: <_this call CBA_fnc_isTerrainObject) exit>
14:42:33   Error Undefined variable in expression: _this
14:42:33 File \x\cba\addons\xeh\fnc_init.sqf [CBA_fnc_init], line 1935

**Steps to reproduce:**
Start the directAction mission, sources available at : https://bitbucket.org/bgillissen/direct-action/src
I think the error appeared after i added support of return values in my mission core events to be able to prevent an inventory to be opened. my event system is not using CBA at all, 
the only CBA functions i use are the add keybinding one, and the one to garrison units i think.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

**RPT log file:**
https://pastebin.com/73c5rCxK

**Comment by commy2** [comment]
Please upload the full rpt file.

**Comment by bgillissen** [comment]
rpt uploaded : https://pastebin.com/73c5rCxK

**Comment by commy2** [comment]
Can't reproduce. What is `@Task Force Unicorn- Content Pack for Direct Action`?
There is unusually many `Attempt to override final function`.

**Comment by bgillissen** [comment]
That mod contains texture files, insignia entries for our groups, SFX entries for the national anthems of our members and overwrite the RadioProtocol entries to mute all the callouts, and some settings related to the mission (blacklisted weapons, mags)

**Comment by commy2** [comment]
@bgillissen 

This function:
<details><summary>feats\assets\serverInit.sqf</summary>

```sqf
/*
@filename: feats\assets\serverInit.sqf
Author:
	Ben
Description:
	run on server
	check which mods are available and init them,
	broadcast assets list to players
*/

#include "_debug.hpp"

{
	_x params ["_name", "_isPresent", "_sides"];
	if ( _isPresent ) then {
		private _fnc =  format["%1_fnc_init", _name];
		if ( !isNil _fnc ) then {
			private _code = compile format["call %1", _fnc];
			#ifdef DEBUG			
			private _debug = format["assets: %1 init", _name];
			debug(LL_DEBUG, _debug, 0);
			#endif
			call _code;
		#ifdef DEBUG
		} else {
			private _debug = format["assets: %1 init failed, function %2 is not defined", _name, _fnc];
			debug(LL_ERR, _debug, 0);
		#endif
		};
	};
} count MODS;

//broadcast computed assets to clients
{
	_x params ["_prefix", "_vars", "_broadcast"];
	if ( _broadcast ) then {
		{
			publicVariable format["%1_%2", _prefix, _x];
		} count _vars;
	};
	true
} count PV;

nil
```

</details>  

Executes `CBA_fnc_init` in scheduled environment without arguments. `CBA_fnc_init` is an internal function that is not meant to be executed by mission or addon makers manually. I suspect it's a collision caused by your mission violating the namespace rules (creating functions tagged with "CBA_" that are not yours).

<details><summary>Value of GVAR "MODS" was:</summary>

```sqf
MODS // [["cba",true],["ace",false],["advSlingLoading",true],["advTowing",true],["directAction",false],["vanilla",true],["kart",true],["marksmen",true],["heli",true],["apex",true],["jet",true],["orange",true],["achilles",false],["shacktac",false],["rhsAFRF",false],["rhsGREF",false],["rhsUSAF",false],["tfar",false],["tfuBerets",false],["rmSplinter",false],["adr97",false],["unsung",false]]
```

</details>

**Comment by bgillissen** [comment]
Ho god thx alot mate, i had no clue i was calling it myself.
I added a cba entry in my assets settings just to check his presence for the key bindings, completly forgot that it checks for a %mod%_fnc_serverInit....and call it, just gonna set a name property in my settings for the cba entry to it does not catch your internal function.

Again thanks alot for your support.
