### ISSUE TITLE
[Feature Request] Settings - add settingname als variable into the script

### ISSUE THREAD

**Issue by Dorbedo** [CBATeam/CBA_A3#801]
**Arma 3 Version:** `1.76` (stable / rc / dev)
**CBA Version:** `3.4.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
```

**Description:**
- It would be great, if you would have the settingsname inside the settings script:
e.g.: `_thisSetting`

**Comment by commy2** [comment]
```sqf
    ["CBA_SettingChanged", {
        params ["_setting", "_value"];

        private _message = format ["%1 = %2", _setting, _value];
        systemChat _message;
    }] call CBA_fnc_addEventHandler;
```
Isn't this already arg0 ?
