### ISSUE TITLE
Client error since Arma 3 1.78

### ISSUE THREAD

**Issue by MGTDB** [CBATeam/CBA_A3#812]
**Arma 3 Version:** `1.78 143717` (stable)
**CBA Version:** `v3.4.1` (stable)

**Mods:**
```
- CBA_A3
```

**Description:**
Client error popup constantly

**Steps to reproduce:**
Join a server running CBA

**Where did the issue occur?**
Client error

16:25:34 Error in expression <f (!isClass _eventClass) then {
{
_unit addEventHandler [_x, format ['call cba_x>
16:25:34   Error position: <addEventHandler [_x, format ['call cba_x>
16:25:34   Error Foreign error: Unknown enum value: "FiredBis"
16:25:34 File \x\cba\addons\xeh\fnc_initEvents.sqf [CBA_fnc_initEvents], line 1946

**Comment by ReDBaroN1** [comment]
+1 
This is spamming hard in both the client and server reports for us as well on all servers running CBA

**Comment by commy2** [comment]
Already fixed in #811.
Release candidate is currently being tested and if everything goes well the update will be released soon.
