### ISSUE TITLE
Arma 3 crashes on ACE spectator when use scroll wheel to zoom (arma3 V1.78)

### ISSUE THREAD

**Issue by Beneris** [CBATeam/CBA_A3#815]
**Arma 3 Version:** `1.78 ` (stable / rc / dev)
**CBA Version:** `3.4.1.170912` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ACE3
```

**Description:**
- When using ace spectator turn ScrollWheel for zoom game crashes

**Steps to reproduce:**
- Run latest arma3 with ace3 and cba3, use scroll Wheel

**Where did the issue occur?**
- Dedicated

**RPT log file:**
in RPT only Errors from CBA ;)

**Comment by commy2** [comment]
This belongs on the ACE github.
But no need to open a ticket there, because there already is one: https://github.com/acemod/ACE3/pull/5844

Close?

**Comment by Beneris** [comment]
Yes, sorry for inconvenience.

**Comment by commy2** [comment]
NP
