### ISSUE TITLE
Integrate Weapon Eventhandler Framework 

### ISSUE THREAD

**Issue by ViperMaul** [CBATeam/CBA_A3#82]
Add Weapon Eventhandler Framework 
Re: http://forums.bistudio.com/showthread.php?192780-Weapon-Eventhandler-Framework

**Comment by ViperMaul** [comment]
Status?

**Comment by kerckasha** [comment]
Gonna try and get this implemented this month, sort of got pushed to the backburner and then fell off

**Comment by ViperMaul** [comment]
:+1:

**Comment by kerckasha** [comment]
Alright got the basics converted over, I need to rewrite most of the functions for better performance

**Comment by jonpas** [comment]
What is the status on this @kerckasha ?

**Comment by kerckasha** [comment]
With the recent addition of event handlers to weapons it might be prudent to retool this.
