### ISSUE TITLE
Headless client possible CBA issue ?? 

### ISSUE THREAD

**Issue by northrivergeek** [CBATeam/CBA_A3#824]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
1.80 stable
**CBA Version:** `3.x.x` (stable / dev + commit hash)
Community Base Addons v3.5 
**Mods:**
``@exile;@jbad;@Lythium;@CBA_A3;@NIArms;@KAWeaponsPackNEWRC;@TRYK;@TAC_VESTS;@6x6AllTerrain;@Hidden_Ghillies;@Extended_Base_Mod;@Fox_SurvivalCars;@Friths_Ruin;@FFAA_MOD;@Pook_H-13;@NATO_Rus_Vehicle;@NATO_Rus_Weapons;@Enhanced_Movement;@Tempfixminiguns;"      "-servermod=@exileserver;@A3XAI;@Advanced_Urban_Rappelling;@infiSTAR_Exile;@infiSTAR_TM" `
- CBA_A3
```

**Description:**
Here is RPT and mdmp from the crash .. it only crashes on the HC load , this is Lythium Map EXILE

**Steps to reproduce:**
Start Headless Client 

**Where did the issue occur?**
 Dedicated 

**RPT log file:**
mdmp
https://pastebin.com/ce0jLidU

HC Rpt
https://pastebin.com/WXCSUshc

Server RPT 
https://pastebin.com/gthE1hv2

**Comment by commy2** [comment]
What makes you think this is an issue specific to CBA?

**Comment by northrivergeek** [comment]
Error about CBT . in the HC rpt .. grasping for straws .. but thought it was a possiblility

**Comment by commy2** [comment]
I can see 28.8k errors about faulty asset configs. I'm very sure this crash is a problem of badly configured content mods.
While they may "work" on their own, combining two or more of them just hits the point where a critical error occurs.
I'd remove all mods and then enable them one by one. Compare the RPT files of all sessions and you'll see which mods/combinations of mods cause lots of errors (e.g. `Warning Message: No entry`).

**Comment by northrivergeek** [comment]
Ok thanks for the advice .. there is a mention of KA .. that might be the culprit  KA Weapons RC
