### ISSUE TITLE
CBA-Hashes question

### ISSUE THREAD

**Issue by TheMysteriousVincent** [CBATeam/CBA_A3#831]
**Arma 3 Version:** `-`
**CBA Version:** `-`

**Mods:**
```
- CBA_A3
```

**Description:**
I have a question about the CBA Hashes:
Why are the hashes aren't based on local logic objects? It would be pretty much faster to load a hash from an object than an array.
Moreover, the object contains a pointer to the destination, while an array just copies itself as input parameter(s),
for example this:
`someArr = [someArr, "test", "1"] call CBA_fnc_hashSet`
could just be simplified to this:
`[someArr, "test", "1"] call CBA_fnc_hashSet`
.

**Steps to reproduce:**
-

**Where did the issue occur?**
-

**Comment by commy2** [comment]
I think this is more like what you want: https://github.com/CBATeam/CBA_A3/blob/master/addons/common/fnc_createNamespace.sqf

These things can't just be changed on a whim now. It would very likely break mods using it. There is a good reason for those hashes being array based though. This makes them able to survive through mission change when put in uiNamespace or even into new sessions when put in profileNamespace. Keybinds for example are stored in a hash in the profile. Objects don't survive the mission end, so their namespace is lost too. The settings are another example. If you change a mission setting, it is stored in a hash in a custom hidden 3den setting in the mission.sqm.

**Comment by commy2** [comment]
CBA hash can use anything as key (and value), while CBA namespace can only use strings as key (and anything* as value).

**Comment by TheMysteriousVincent** [comment]
Well then. Thanks for your answer! #closed
