### ISSUE TITLE
Need help with arma 3 dedicated server

### ISSUE THREAD

**Issue by 0sj** [CBATeam/CBA_A3#836]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
```

**Description:**
- 16:39:23 Warning Message: Addon 'cba_common' requires Addon 'A3_3DEN'

**Steps to reproduce:**
- I went to launch my Arma 3 server with CBA_A3 on and it gave the error to me

**Where did the issue occur?**
- Dedicated

**RPT log file:**

=====================================================================
== C:\TCAFiles\Users\JaydnO\10958\arma3server.exe
== "C:\TCAFiles\Users\JaydnO\10958\arma3server.exe" -ip=103.231.90.10 -port=2322 -noPause -noSound -cpuCount=4 -maxMem=2048 -exThreads=7 -cfg=A3DS\basic.cfg -config=A3DS\server.cfg -profiles=A3DS\Profiles -servermod= -mod=@CBA_A3; -world=empty 

Original output filename: Arma3Retail_Server
Exe timestamp: 2016/02/17 17:35:50
Current time:  2017/12/16 16:37:51

Type: Public
Build: Stable
Version: 1.56.134627

Allocator: C:\TCAFiles\Users\JaydnO\10958\dll\tbb4malloc_bi.dll
=====================================================================

16:37:51 SteamAPI initialization failed. Steam features wont's be accessible!
16:38:00 DS_
16:38:00 A3DS\Profiles\Users\SYSTEM\
16:38:00 Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
16:38:00 sessionID: 217d1b0d6ef37ecd8056ddd945c135cb6d0d4746
16:39:23 Warning Message: Addon 'cba_common' requires addon 'A3_3DEN'

this is just the log i got

**Comment by PabstMirror** [comment]
`Version: 1.56.134627`
need to update server to most recent version (1.80)

**Comment by 0sj** [comment]
thank you

**Comment by commy2** [comment]
Cracked version is not supported. Buy the game.

**Comment by 0sj** [comment]
i brought it off steam?

**Comment by 0sj** [comment]
![image](https://user-images.githubusercontent.com/29569096/34067150-846eac76-e282-11e7-959d-85de49235b5f.png)

**Comment by commy2** [comment]
Steam only has v1.80. This is v1.56 and if you google the version, you end up at dubious sites.
Update the server to run v1.80 and everything will work fine.
