### ISSUE TITLE
Question: ACE 3 interaction system

### ISSUE THREAD

**Issue by TheMysteriousVincent** [CBATeam/CBA_A3#840]
I've got a question about the ace 3 interaction system:

Why is the ace 3 interaction framework not available in CBA or a package of CBA?
That would make more sense to me because the interaction menu could be used in more mods if they only want to use CBA as a dependence.

**Comment by Soldia1138** [comment]
Cause it would require a massive rewrite of both CBA and ACE due to the tight integration of the interaction system in ACE. Although the idea to do this is as old as ACE itself, there has been no real attempt to do it.

**Comment by TheMysteriousVincent** [comment]
Well, good to know. It's a pity that this isnt in CBA. Woudln't it be a point to implement it in both, CBA and ACE?

**Comment by commy2** [comment]
CBA_A3 still has the Arma 2/ACE 2 fleximenu.
...

**Comment by bux** [comment]
> CBA_A3 still has the Arma 2/ACE 2 fleximenu.

WOW, MUCH HYPE 😁

**Comment by commy2** [comment]
btt: There are no plans to move the ACE interaction menu to CBA_A3.

**Comment by TheMysteriousVincent** [comment]
Sure.
