### ISSUE TITLE
Debug Console doesn't respond to Enter key input

### ISSUE THREAD

**Issue by CreepPork** [CBATeam/CBA_A3#844]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5` (stable)

**Mods:**
```
- CBA_A3
```

**Description:**
When using the debug console and entering anything, pressing Enter doesn't do anything. It should have executed the code but it didn't do anything.

**Steps to reproduce:**
1. Open the Debug Console and enter valid code
2. Press Enter and notice that nothing happened.

**Where did the issue occur?**
Multiplayer

**RPT log file:**
N/A

**Comment by commy2** [comment]
Does work in 3den.
Does work in 3den preview.
Does work in single player scenario (Only bothered with VR mission).
It does not work in multiplayer and in a 3den multiplayer preview. :(

For some reason, the X EXEC buttons are color coded there too. Strange.

**Comment by commy2** [comment]
The statement is also logged correctly (prev / next), but never executed. Seems like a vanilla problem.

**Comment by CreepPork** [comment]
Updated issue, it only doesn't work in multiplayer.

**Comment by commy2** [comment]
Tested with vanilla. Same problem there. Which is not surprising, because this part is carried over from the base game without any added code.

**Comment by commy2** [comment]
Auto close didn't work. :/

**Comment by jonpas** [comment]
Well that's because there is no reference from the PR anymore. :P
