### ISSUE TITLE
Settings: Error when exporting a single change without clicking Ok in Addons Options Menu

### ISSUE THREAD

**Issue by bux** [CBATeam/CBA_A3#848]
**Arma 3 Version:** `1.80` stable
**CBA Version:** `3.5.0` dev 124140c7d2437c128df2a3f70ffc08f302cc858f

**Mods:**
```
- CBA_A3
- ACE3 3.12.0
```

**Description:**
An error is thrown when trying to export a single setting change without clicking the "OK" button in the addons options menu

**Steps to reproduce:**
- Create a new blank mission in 3DEN and save it
- Open the Addon Options Menu
- Go to "ACE3 Common" category and just change `ace_common_checkPBOsAction` to `2` ![image](https://user-images.githubusercontent.com/1235520/34342373-6b869a74-e9ae-11e7-839e-4a58a6066eab.png)
- Immediately click the "Export" button
- An error is thrown
```
20:16:58 Error in expression <e isEqualTo _defaultValue) ||
_priority > [0,1] select (cba_settings_default get>
20:16:58   Error position: <> [0,1] select (cba_settings_default get>
20:16:58   Error >: Type Bool, expected Number,Not a Number
20:16:58 File x\cba\addons\settings\fnc_export.sqf, line 31
```

**Where did the issue occur?**
- Editor (Singleplayer)

**NOTE:**
A cba_settings.sqf file is present in the userconfig folder

**RPT log file:**
https://pastebin.com/5E2FpWi1

**Comment by commy2** [comment]
Can reproduce.
BI error message is confusing, but it seems like:
```sqf
true > 1
```
which throws:
```
 9:58:54 Error in expression <true > 1>
 9:58:54   Error position: <> 1>
 9:58:54   Error >: Type Bool, expected Number,Not a Number
```

**Comment by commy2** [comment]
Crucial step in the repro is to uncheck "export default values".

**Comment by bux** [comment]
> Crucial step in the repro is to uncheck "export default values".

true. UI did remember this from previous bug report.
