### ISSUE TITLE
Question about creating settings manipulation addon

### ISSUE THREAD

**Issue by MiatWarp** [CBATeam/CBA_A3#849]
**Arma 3 Version:** `1.78` (stable)
**CBA Version:** `3.x.x` (stable)

**Mods:**
```
- CBA_A3
```

**Description:**
Hello! I'm writing addon, which set another addon (ACE) settings (via CBA settings). 
I'm spent whole day to determine how to do it. Wiki page about settings say a lot of information how create setting, and use it. But not how overwrite **existing** setting and set default value. I'm tried to use `CBA_settings_fnc_set` function, but I'm think it's not what i need. I will appreciate any help, thanks!

**Steps to reproduce:**
- Not a bug

**Where did the issue occur?**
- Nowhere

**Comment by commy2** [comment]
I'm not 100% sure this works, but have you tried simply using `cba_settings_fnc_init` with the same setting, but updated parameters from an addons preInit that has the original setting as required addon?

**Comment by MiatWarp** [comment]
I can't add original addon as required because it can be not installed. 
But without it - it works! After editor opened options is checked, but after mission get started check got unchecked. Thanks for support! 
Also i found a bug: `["my_setting", false, **99**, "mission"] call CBA_settings_fnc_set;` will freeze the game (because int (99) in priority arg - but documentations says it can be bool or int (`_priority - New setting priority <NUMBER, BOOLEAN>`))

**Comment by commy2** [comment]
Range is 0 ... 2 for priority.

**Comment by commy2** [comment]
The original addon being a requiredAddon is to ensure the loading order is correct. Now I don't know which of them is loaded first and I can't add it to the wiki without determining the behavior myself.

**Comment by MiatWarp** [comment]
Loading order defined by `MAINPREFIX` or `requiredAddons` array in config.cpp or by `-mod` arma startup argument?

**Comment by bux** [comment]
> requiredAddons

**Comment by Dystopian** [comment]
@MiatWarp Doesn't [Userconfig](https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System#userconfig) suit you?

**Comment by commy2** [comment]
The loading order is determined by `requiredAddons` first and only if it is ambiguous by the start parameters.
Doubt it would be ambiguous with ACE, since ACE is requiring all addons and therefore will load last pretty much all the time.

**Comment by MiatWarp** [comment]
@Dystopian userconfig needs to be manually installed by user. Sadly, for steam workshop it's not user-friendly way.

**Comment by commy2** [comment]
@MiatWarp 
You can make a static settings addon for clients and upload it to the workshop.

**Comment by commy2** [comment]
See: https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System#userconfig

**Comment by MiatWarp** [comment]
@commy2 I'm tried that way. Downloaded `cba_settings_userconfig` template, added some exported from addon settings menu parameters to `cba_settings.sqf` (like `force my_variable = false`), loaded that addon, and... nothing happens. Later I will try to do it again, but for now `cba_settings_fnc_init ` working perfectly.
And your manual says that I must place my settings addon to `@CBA_A3\addons\`, but again - I can't do it via steam workshop.

**Comment by commy2** [comment]
I edited it. It can be placed anywhere really.

**Comment by commy2** [comment]
The problem is, that the way you're doing it isn't the "right way". As in, it could easily break in an update.

**Comment by commy2** [comment]
You could upload the addon you made. Maybe it's some obvious error for me, because I know what it should look like.

**Comment by MiatWarp** [comment]
I'm fully understand it, and will try to use userconfig addon way later. 
My addon (currently I'm trying to learn how write Arma 3 addons with modern things)
[addon.zip](https://github.com/CBATeam/CBA_A3/files/1587288/addon.zip)

**Comment by commy2** [comment]
I meant the addon with the template and the cba_settings.sqf file.

**Comment by MiatWarp** [comment]
@commy2 [settings.zip](https://github.com/CBATeam/CBA_A3/files/1587295/settings.zip)

**Comment by MiatWarp** [comment]
@commy2 for now (with CBA userconfig settings pbo) everything works as planned: desired option now deactivated and grayed out, and I can't check it to enable. Perfect! Many thanks!

**Comment by commy2** [comment]
No idea what was wrong the first time, but sounds good!

**Comment by Dystopian** [comment]
you can load userconfig addon on server only with forced settings and clients don't have to download your addon.

**Comment by MiatWarp** [comment]
@commy2 I have an idea - last time I'm added class `cba_settings_userconfig` into my addon's CfgPatches, maybe because of this it's doesn't work.

**Comment by MiatWarp** [comment]
@Dystopian thanks for tip
