### ISSUE TITLE
Save only changed settings into mission

### ISSUE THREAD

**Issue by jonpas** [CBATeam/CBA_A3#850]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- acex
- acre
- tac_mods
- NIArms
- A few more without CBA Settings
```

**Description:**
- Currently Settings save all settings into `mission.sqm`, even those that are untouched/default, resulting in about 200 KB size increase (~12.800 lines) with above mods.
- Major improvement would be to only save changed settings.
- Possibly also happens when saving to profile (client or server), but that was not verified.

**Steps to reproduce:**
- Check `mission.sqm` size or line count
- Save settings in mission
- Check `mission.sqm` size or line count

**Where did the issue occur?**
- Editor (Singleplayer)

**RPT log file:**
- N/A

**Comment by commy2** [comment]
It does only save changed settings. What happens is, that all global flag settings are recognized as changed from the default, because they have the priority set to 1 instead of 0.

**Comment by jonpas** [comment]
I see, so it's actually a bug?

**Comment by commy2** [comment]
Kind of. It doesn't break anything functionally, but the original intention was to only store changed settings (incl. priority), which got broken during development when global settings were added.
