### ISSUE TITLE
CBA Settings has greyed-out MISSION tab in 3DEN

### ISSUE THREAD

**Issue by freghar** [CBATeam/CBA_A3#865]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)

**Mods:**
```
- CBA_A3
- ACE3 v3.12.0
```

**Description:**
- In some cases (which turns out to be most cases for me), the MISSION settings tab is greyed out, making me unable to set the mission settings - https://i.imgur.com/n33NQ5d.jpg .
- Even though the screenshot shows extra mods used, I tested it with just CBA and ACE3 and then with CBA only, with new missions (both via the "New" button in 3den as well as loading the mission via arma3.exe cmdline), with existing missions, with a clean Arma 3 profile, with and without `-world=empty -nosplash`, after a mission preview, after MP preview, and so far I cannot get a reliable reproducer - I can edit the MISSION tab in ~10% of random cases, usually when loading an existing mission via arma3.exe cmdline.

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**RPT log file:**
- https://pastebin.com/9KrZfmtV (nothing interesting even with `cba_diagnostic_enable_logging.pbo`)

**Comment by commy2** [comment]
You have to save the mission first. Otherwise there is no mission.sqm to save the mission settings to.

**Comment by freghar** [comment]
Thanks, saving the mission under some name indeed seems to work, regardless of whether there are further modifications or not.

But why? As far as I can tell, CBA seems to be using
```
set3DENMissionAttributes [["Scenario", QGVAR(hash), _settingsHash]];
```
which should AFAIK just work regardless of whether there's a physical `mission.sqm` file or not - the attributes get saved to memory anyway.

For example:
  1. create a new mission, don't save it
  1. `"Scenario" get3DENMissionAttribute "cba_settings_hash"` returns `["#CBA_HASH#",[],[],any]`
  1. do ```set3DENMissionAttributes [["Scenario", "cba_settings_hash", ["#CBA_HASH#",
["ace_advanced_ballistics_enabled"],[[true,true]],any]]];```
  1.  `"Scenario" get3DENMissionAttribute "cba_settings_hash"` returns what was set in previous step
  1. save the mission to "refresh" the CBA settings UI logic
  1. load the mission, open CBA settings UI, see ACE Advanced Ballistics enabled

The "simpler" single-attribute `set3DENMissionAttribute` should work the same (not tested).

**Comment by commy2** [comment]
Will look into improving this behavior.
