### ISSUE TITLE
Float to string musing...

### ISSUE THREAD

**Issue by fishykins** [CBATeam/CBA_A3#868]
Not so much an issue, rather a question re cba_fnc_floatToString. I have, on rare occasion, been sending values of 0 to this function. The result is a thrown error but nothing broken. Having taken a look at it, I can see that it is highly bare bones and designed to run super-duper fast which is great. Is there a possibility of catching this value of "0" in the function or should this be included before? 

eg: 

private _string = if (_float isEqualto 0) then {"0";} else {float call cba_fnc_floatToString;};

Thanks!

**Comment by SilentSpike** [comment]
Would it not be faster to use the engine command `toFixed`?

**Comment by fishykins** [comment]
looks like it, yes. Does that not render the function as depreciated?

**Comment by commy2** [comment]
I'd say so.

**Comment by commy2** [comment]
Function will be marked as deprecated (though probably never removed in A3)
