### ISSUE TITLE
Problems with Make.py processing .hpp's

### ISSUE THREAD

**Issue by fishykins** [CBATeam/CBA_A3#870]
**CBA Version:** `v3.5

**Description:**
- I am having problems with the make.py. I can produce a "Finished" CBA but for some reason the end product seems to have lost all the .hpp files as they have been preprocessed. for example, CfgFunctions.hpp is gone and has been cooked into the config.hpp file where the include used to be. 
All the make.cfg settings are as default except for project file locations. 

CfgPatches {
    class ADDON {
        author = "$STR_CBA_Author";
        name = CSTRING(component);
        url = "$STR_CBA_URL";
        units[] = {};

becomes in release:

class CfgPatches
{
	class cba_main
	{
		author = "$STR_CBA_Author";
		name = "$STR_cba_main_component";
		url = "$STR_CBA_URL";
		units[] = {};

**Steps to reproduce:**
- Git pull CBA, Make.py. Cry uncontrollably 

**Where did the issue occur?**
Probably at birth

Appreciate that this is probably my issue and not CBA's, but I would be mega grateful if anyone can help me out. Thanks!

**Comment by jonpas** [comment]
Remove ".hpp" from pboProject's exclusion list.

**Comment by fishykins** [comment]
Wonderful, thanks for the quick response! As an after thought, that might be a good bit of info to include in the https://github.com/CBATeam/CBA_A3/wiki/Building-CBA-from-source bit of the wiki. Thanks!

**Comment by jonpas** [comment]
Agreed, it was added on ACE3 wiki as well.

**Comment by jonpas** [comment]
Added in https://github.com/CBATeam/CBA_A3/wiki/Building-CBA-from-source/_compare/e7f6ef5cf0e0636b6944a428596dad3e5824e7d8...a29fdfc4b7f8b5e24ce65463b746528d8a85080c
