### ISSUE TITLE
WARNING: Some client seems to have overriden the versions array; please report to CBA devs!"]

### ISSUE THREAD

**Issue by hoffy** [CBATeam/CBA_A3#871]
**Arma 3 Version:** `Exe timestamp: 2017/12/19 16:48:16` (stable / rc / dev)
**CBA Version:** `3.5.0` (stable / dev + commit hash)

**Mods:**
`
CBA_A3;
ace;
acex;
ace_optionals;
ACE Compat - RHS Armed Forces of the Russian Federation;
ACE Compat - RHS GREF;
ACE Compat - RHS United States Armed Forces;
ADV-ACE CPR;
ALiVE;
AliveServer;
task_force_radio;
isladuala_a3;
Spyder Addons;
Advanced Train Simulator (ATS);
6 x 6 All Terrain Vehicle;
A-10 Warthog;
Advanced AI Command;
Advanced Rappelling;
Advanced Sling Loading;
Advanced Towing;
Advanced Urban Rappelling;
Airfield Logistic Tractor;
Ares Mod - Achilles Expansion;
BackpackOnChest;
Boeing C-17;
CLA CLAFGHAN;
CUP Terrains - Core;
CUP Terrains - CWA;
CUP Terrains - Maps;
CUP Units;
CUP Vehicles;
CUP Weapons;
CUP ACE3 Compatibility Addon - Vehicles;
CUP ACE3 Compatibility Addon - Weapons;
C_17v1_7;
EA-18G Growler;
Enhanced Movement;
Eurocopter EC-635;
EWK_HMMWV;
Extended Fortifications Mod;
F-14 Skin Pack 1;
F-14 Tomcat;
F-15 Eagle;
F-15C 1st PACK;
F-16 Fighting Falcon;
F-16 Skin Pack 1;
F-16 Skin Pack 2;
F-2 Viper ZERO;
F-22 Raptor;
FIR AWS(AirWeaponSystem);
FIR Pilot&Crew Pack;
Forklift;
fox_suicide_bomber;
HAFM_EC635;
HAFM_EC635 - 3rd Infantry Division Copy;
HunterGPK;
Jonzie Carpack - Core;
Marine Expeditionary Force;
Means sheriff 2015 Tahoe;
Means sheriff CVPI;
Medical Backpack Tents for ACE3;
MilGearPack;
Military Gear Pack - Extended 01;
Military Gear Pack AOR Extension;
NATO_Rus_Vehicle;
NATO_Rus_Weapons;
NATO_Rus_Weapons_CBA;
USS Nimitz;
US MARSOC Marine Raider Regiment;
USMC_Vehicles_mas;
Peral_Airfield_Logistics;
PLP Containers;
Project OPFOR;
RHSAFRF;
RHSGREF;
RHSSAF;
RHSUSAF;
Sabs C-130 Hercules;
SMA RHS compatibility Patch;
Specialist Military Arms (SMA) Version 2.7.1;
TalibanFighters;
US MARSOC Marine Raider Regiment;
Vehicle_Customizer_Jonzie_Edition;
Vcom AI V2.94;
VSM All-In-One Collection;
[TFD] USMC Ranks Insignias Pack;
A3MT.Net - Hospitalbed;
CFB Skins;
Canadian Military Additions;
Open Source Vehicle, PD , EMS;
JSO role insignia;
PLP Urban Packs- Barriers and Fences;
ACE 3 Extension (Placeables);
Complementary Special Weapons;
ARP_Safety - High visibility reflective belts;

`
**Description:**

We get this error when our headless client tries to connect to our server

2:52:20 [11476,654.975,293.904,["#CBA_HASH#",["cba","ka","alive_main","ace","acex"],[[[3,5,0,171204],-1],[[1,0,2],-1],[[1,5,2,1.71207e+006],-1],[[3,12,0,29],-1],[[3,3,0,6],-1]],[[0,0,0],0]],"WARNING: Some client seems to have overriden the versions array; please report to CBA devs!"]
 2:52:20 [["#CBA_HASH#",["cba","ka","alive_main","ace","acex"],[[[3,5,0,171204],-1],[[1,0,2],-1],[[1,5,2,1.71207e+006],-1],[[3,12,0,29],-1],[[3,3,0,6],-1]],[[0,0,0],0]],any]
 2:52:20 Attempt to override final function - bis_fnc_preload_server
 2:52:21 Unexpected array size (size=61 message struct NetworkMessagePublicVariable, item value)
 2:52:21 Unexpected message data from 234486672: message struct NetworkMessagePublicVariable, item value
 2:52:21 Before (0x00000000): 7e 07 00 00 03 04 0a 0a 0a 0a ea 10 00
 2:52:21 Current (0x0000000d): 3d
 2:52:21 BEServer::finishDestroyPlayer(234486672): users.get failed

**Steps to reproduce:**
- In our case it happens repeatedly when the headless attempts connection to our dedicated server

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

[arma3server_2018-01-10_02-41-25.rpt.txt](https://github.com/CBATeam/CBA_A3/files/1618492/arma3server_2018-01-10_02-41-25.rpt.txt)

**Comment by jonpas** [comment]
Anyone got a clue which mod is `ka`? It adds some very weird number to it.

**Comment by Cuel** [comment]
That's alot of tagged users 😆

**Comment by hoffy** [comment]
never considered that, lol
I removed the at symbols

**Comment by hoffy** [comment]
> 

Anyone got a clue which mod is ka? It adds some very weird number to it.
--

I have no, I have never had any mods on the server identifying as such.

**Comment by hoffy** [comment]
> Anyone got a clue which mod is ka? It adds some very weird number to it.

Maybe this?? I've never used it. but, thought it might help
[(https://steamcommunity.com/sharedfiles/filedetails/?id=1119907855)]

**Comment by jonpas** [comment]
It's in your mods list you wrote above, so it's definitely something you've not only used, but are using. :P

**Comment by commy2** [comment]
Seems like this script is bugging out: https://github.com/CBATeam/CBA_A3/blob/master/addons/versioning/XEH_postInitServer.sqf#L40
It's from A2, so I wouldn't worry about the log message.

**Comment by hoffy** [comment]
It didn't exist before yesterday, and it is keeping our headless from connecting so I am very worried about it. and no "KA", unless involved in another mod somehow, is not is my mods list.

**Comment by commy2** [comment]
Are you worried because of the wording?
From what I can tell, this was originally implemented as anti-cheat. But as such, it's not very effective anyway, and this is very likely just a false positive.

**Comment by Dorbedo** [comment]
@commy2 Did you noticed, that an error displays an annoying ingame warning?
How about scrapping the feature?

@hoffy One of your mods or the mission itself seems to be overwriting an internal variable. Since you are running a lot of mods, Its hard to tell which one. If possible I would recommend to disable some mods and try to track down which one it is.

**Comment by commy2** [comment]
I'm all for scrapping this undocumented and frankly undesirable feature.

**Comment by jokoho48** [comment]
@hoffy KA is For KickAss and Complementary Special Weapons is from KA.

**Comment by Dorbedo** [comment]
@jokoho48 the mod, he mentioned, has the same CfgPatches name `KA`

**Comment by commy2** [comment]
Planning to remove it.

**Comment by commy2** [comment]
I say we keep this for now.
The error says some script overwrites a variable and sends it across the network. Doubt it's a bug in CBA. Either some addon, or the mission messing with internals. Doesn't seem to be KA either.
Unless you can find out which addon or mission, nothing we can do.
Btw. this is not an error popup as Dorbedo said. Just a `diag_log`.

**Comment by commy2** [comment]
dead
