### ISSUE TITLE
Settings set by admin are not persisted on dedicated Server

### ISSUE THREAD

**Issue by Xyaren** [CBATeam/CBA_A3#873]
**Arma 3 Version:** `1.80.143869` stable
**CBA Version:** `3.5.0.171204` 

**Mods:**
```
- CBA_A3
- ACE3
```

**Description:**
Settings are not persisted on server. After restart settings are lost

*Manualy* executing `saveProfileNamespace` after changing settings, persists them in the profile (.vars File).

**Steps to reproduce:**
- action: Change ACE3 Advanced Ballistic Setting to Enabled (Logged In)
- action: restart server
- state: settings are back to default

**Where did the issue occur?**
- Dedicated

**Comment by commy2** [comment]
Can't reproduce. They're saved without `saveProfileNamespace` for me. Are you sure this is needed? Or have you just read it and not tried?

**Comment by Xyaren** [comment]
I tried it.
The timestamp of the file also matches the time I executed the command.
I used a completely new profile without a *vars* file.
When I stopped the server without executing the command no file was in the
profile directory.


2018-01-14 17:22 GMT+01:00 commy2 <notifications@github.com>:

**Comment by Dorbedo** [comment]
@commy2 I think I had the same issue on my Linux servers too. (Never did a deeper research on this Issue. I've just switched to settings packed as a mod)

Maybe it's OS related?

**Comment by Xyaren** [comment]
@Dorbedo I had the issue on a Windows host.

**Comment by Xyaren** [comment]
I think executing `saveProfileNamespace`  on the server when pressing the "Ok" Button (on the Server Tab!) is a solution that has no side effects. There are no disadvantages for me.

**Comment by Cuel** [comment]
Surely it could just be added? Doesn't seem to do any damage

**Comment by commy2** [comment]
Don't want to add placebos, and I'm still not convinced this is needed or would change anything. I can't reproduce the issue, even with killing the games task.

**Comment by Xyaren** [comment]
BI discibes it like this: 

> By default the variables set in this namespace will exist while the game is running. In order to make variables save permanently, use saveProfileNamespace before the game is over. 
https://community.bistudio.com/wiki/profileNamespace

**Comment by commy2** [comment]
I don't trust the wiki. It's pretty much wrong on all details. That's not enough to convince me.

**Comment by Xyaren** [comment]
Try reproducing it with a brand new profile (on the server)

**Comment by Dorbedo** [comment]
I was able to reproduce it several times.

If I just kill the server, the settings are not saved.
If I use the `saveProfileNamespace` or change the mission, the settings are saved.

**Comment by 654wak654** [comment]
> Don't want to add placebos, and I'm still not convinced this is needed or would change anything. I can't reproduce the issue, even with killing the games task.

Are you testing with a dedicated server or the game itself. Remember how dedicated servers used to have issues with profileNamespace? This could be related.

**Comment by commy2** [comment]
arma3server.exe

**Comment by PabstMirror** [comment]
`profileNamespace setVariable` - Close server via UI's X Button = Works
`profileNamespace setVariable` - End process via task manager = Fail
`profileNamespace setVariable; saveProfileNamespace;` - End process via task manager = Works

You can watch file `Arma3Dedicated\profiles\Users\server\server.vars.Arma3Profile`
It will update mid-mission when running the saveProfileNamespace command


Some people will be using server managers that might hard kill the proces;
So I'm pretty sure we should just add it.
