### ISSUE TITLE
Flightstick won't register key's when setting costum keybindings for Arma 3 addons.

### ISSUE THREAD

**Issue by wdejonge97** [CBATeam/CBA_A3#875]
**Arma 3 Version:** `latest steam update` (stable)
**CBA Version:** `3.5.0.171204-945b81e3` (stable)
**Mods:**
``` Taskforce Radio: 0.9.12
- CBA_A3
```

**Description:**
`When trying to rebind the keybindings of the t16000m joystick to fly it doesn't recognise they joystick key's.`

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- `Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal.`

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by jonpas** [comment]
Top of https://github.com/CBATeam/CBA_A3/wiki/Bind-Addon-Key-Actions-to-Joystick-Buttons says:
> requires CBA_A3 **v3.6.0** or later

You say:
> CBA Version: **`3.5.0.171204-945b81e3`**

**Comment by commy2** [comment]
3.6 released
