### ISSUE TITLE
Add whitelist for server settings editing

### ISSUE THREAD

**Issue by chris579** [CBATeam/CBA_A3#876]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)

**Mods:**
```
- CBA_A3
- ACE3
```

**Description:**
- Adding a whitelist of player uids for server settings editing could be helpful to protect the editing of server settings in large communities. In our community every member has got the server password to load missions on the fly however server settings should not be editable by them. I would like to request a security feature where the server owner can specify certain uid's allowed to change server settings.

**Comment by Cuel** [comment]
Can't you set voting treshold really low instead, to allow players to vote themselves admin?

**Comment by jonpas** [comment]
> Can't you set voting treshold really low instead, to allow players to vote themselves admin?

Is what we do with our not-official-missions server.

**Comment by chris579** [comment]
We're currently doing this but it's not working when HCs are connected to the server. Also we want to distribute the password to our closest members but some tend to play around with the settings even though they should not.
I could submit a PR if you're up to it.

**Comment by commy2** [comment]
I could see this working. Where should that setting be? Itself being a global cba setting? Description.ext entry? Config entry?

**Comment by chris579** [comment]
Global CBA setting could be the easiest way. There should be a fallback option in case the server owner is locking out himself, maybe a config entry could fit this scenario the best.

**Comment by commy2** [comment]
Logged admin would have access regardless, so no way to lock out yourself. The setting would only be for additional "admins".

**Comment by chris579** [comment]
What do you mean with `additional admins`?

**Comment by commy2** [comment]
Users that can edit the Server tab settings. Which is atm only possible as logged in admin.

**Comment by chris579** [comment]
Well, this doesn't fit the intentional idea of a whitelist for logged in admins.

**Comment by commy2** [comment]
I see. I got it wrong and confused this with a different proposal that was brought up in Slack.
