### ISSUE TITLE
CBA_A3 crashing the game during start up

### ISSUE THREAD

**Issue by Irishhero294** [CBATeam/CBA_A3#877]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.5.x` (stable / dev + commit hash)

Launcher version: 1.5.143751

Game version: 1.80.143869

Branch: main / beta branch not specified

**Mods:**

CUP Terrains- Core
TRYK[TRYK'S Multi-play Uniforms]
TornZ2
CBA_A3
NIArms All in One
JointRails Unofficial
DS Houses
Sabs Ultralight
CCG Mod
Enhanced Movement
Esseker
Chernarus Redux
Hollow's Vehicle Pack
Exile Mod
```
- CBA_A3
```

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.
When Arma 3 is starting up I keep getting this error   "include file x\cba\addons\main\script_mod.hpp not found"
**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

Starting up Arma 3

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

Start Up

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by PabstMirror** [comment]
That error probably means that you are missing CBA
Please include a RPT

**Comment by commy2** [comment]
No reply providing crucial information.
