### ISSUE TITLE
(settings) Indicator for non live-editable settings

### ISSUE THREAD

**Issue by dedmen** [CBATeam/CBA_A3#879]
**Arma 3 Version:** `1.80`
**CBA Version:** `3.5.0`

**Mods:**
```
- CBA_A3
```

**Description:**
- Add a per setting indicator whether it can be live-edited mid-mission or not.
As many ACE settings and other Mods don't support live-changing it's confusing to the user that the setting doesn't take effect.
Not sure about how we should solve that with server-side settings. As they need to be saveable/editable mid-mission but the user also needs to know about it not taking effect till restart.
For Mission/Client settings I think we can just block the editing ability.

**Comment by commy2** [comment]
So, FUNC(init) is pretty overloaded already. How should this be implemented?
