### ISSUE TITLE
ALiVE and possibly other mods referencing obsolete file ui_helper\script_dikCodes.hpp

### ISSUE THREAD

**Issue by MamaAuito** [CBATeam/CBA_A3#882]
This seemed the quickest way of contacting you, the latest update on Steam (31/01/18) throws an error when launching the game, causing it to CTD
https://gyazo.com/6f0601655b4b700cedc4f748fe74c88d

"file x\cba\addons\ui_helper\script_dikCodes.hpp not found"

**Comment by dedmen** [comment]
ALiVE mod's fault. But hotfix incoming.
ALiVE mod is also pushing for a fix already but they will take longer than a CBA hotfix.

**Comment by ViperMaul** [comment]
Hotfix released

**Comment by TheMysteriousVincent** [comment]
Probably CUP created this exactly problem again with the last update.
