### ISSUE TITLE
Arma 3 server problem with extended event handlers

### ISSUE THREAD

**Issue by KyleGas** [CBATeam/CBA_A3#886]
Hello. I installed some mods on my server and now the prt gives me this:

`XEH]: Car does not support Extended Event Handlers! Addon: @ace
 3:10:45 [XEH]: Tank does not support Extended Event Handlers! Addon: @ace
 3:10:45 [XEH]: Air does not support Extended Event Handlers! Addon: @ace
 3:10:45 [XEH]: rhsusf_RQ11MONITOR does not support Extended Event Handlers! Addon: @RHSUSAF
 3:10:45 [XEH]: rhsusf_RQ11RAVEN_STATIC does not support Extended Event Handlers! Addon: @RHSUSAF
 3:10:45 [XEH]: rhsusf_RQ11RAVEN_B_STATIC does not support Extended Event Handlers! Addon: @RHSUSAF
 3:10:45 [XEH]: H75th_Ranger_Rifleman does not support Extended Event Handlers! Addon: @75th Ranger Regiment
 3:10:45 [XEH]: H75th_Ranger_Tm_Ldr does not support Extended Event Handlers! Addon: @75th Ranger Regiment
 3:10:45 [XEH]: H75th_Ranger_ARifleman does not support Extended Event Handlers! Addon: @75th Ranger Regiment
 3:10:45 [XEH]: H75th_Ranger_Grenadier does not support Extended Event Handlers! Addon: @75th Ranger Regiment
 3:10:45 [XEH]: H75th_Ranger_Medic does not support Extended Event Handlers! Addon: @75th Ranger Regiment
 3:10:45 [XEH]: H75th_Ranger_Sniper does not support Extended Event Handlers! Addon: @75th Ranger Regiment
 3:10:45 [XEH]: H75th_Ranger_NCP does not support Extended Event Handlers! Addon: @75th Ranger Regiment
 3:10:45 [XEH]: H75th_Recon_Tm_Ldr does not support Extended Event Handlers! Addon: @75th Ranger Regiment
 3:10:45 [XEH]: H75th_Recon_Rifleman does not support Extended Event Handlers! Addon: @75th Ranger Regiment
 3:10:45 [XEH]: H75th_Recon_ARifleman does not support Extended Event Handlers! Addon: @75th Ranger Regiment
 3:10:45 [XEH]: H75th_Recon_Grenadier does not support Extended Event Handlers! Addon: @75th Ranger Regiment
 3:10:45 [XEH]: H75th_Recon_Medic does not support Extended Event Handlers! Addon: @75th Ranger Regiment
 3:10:45 [XEH]: FIR_ECM_Dummy_Base does not support Extended Event Handlers! Addon: @FIR AWS(AirWeaponSystem)
 3:10:45 [XEH]: aces_ejection_seat does not support Extended Event Handlers! Addon: @FIR AWS(AirWeaponSystem)
 3:10:45 [XEH]: FIR_AV8B_Base does not support Extended Event Handlers! Addon: @AV-8B Harrier 2
 3:10:45 [XEH]: FIR_AV8B_NA_Base does not support Extended Event Handlers! Addon: @AV-8B Harrier 2
 3:10:45 [XEH]: FIR_AV8BWreck does not support Extended Event Handlers! Addon: @AV-8B Harrier 2
 3:10:45 [XEH]: fir_av8b_ejection_seat does not support Extended Event Handlers! Addon: @AV-8B Harrier 2
 3:10:45 [XEH]: rhs_2P3_1 does not support Extended Event Handlers! Addon: @RHSAFRF
 3:10:45 [XEH]: rhs_mig29s_base does not support Extended Event Handlers! Addon: @RHSAFRF`

It says right there what the problem is but i do not know how to solve this.... i found in your documentation it is possible to exclude vehicle from the XEH? but i dont get it, where does the code go? how do i tell the server to do it? Sorry for beeing so noobish at this that i cant even tell you what i did so far, because i actually did nothing at all so far, cos i just dont know what :)   any help is appreciated.

**Comment by Cuel** [comment]
You should include the full [RPT file](https://community.bistudio.com/wiki/arma.RPT)

**Comment by KyleGas** [comment]
I though i could. But even though i dont know i changed nothing.... i get this rpt now, completely different:

`=====================================================================
== C:\SERVICES\ni1484673_1_SHARE\ftproot\arma3\arma3server.exe
== "C:\SERVICES\ni1484673_1_SHARE\ftproot\arma3\arma3server.exe" -mod="@3CB BAF Equipment;@3CB BAF Vehicles;@ace;@RHSAFRF;@RHSUSAF;@ACEX;@BackpackOnChest;@Enhanced Movement;@Military Gear Pack;@task_force_radio;@Advanced Rappelling;@Advanced Towing;@Advanced Urban Rappelling;@FIR AWS(AirWeaponSystem);@G.O.S Leskovets;@Green Sea Battalion Uniforms;@Spec4Gear.v4.6;@UKSF_mas;@VSM All-In-One Collection;@NATO_Rus_Weapons;@75th Ranger Regiment;" -serverMod="" -ip=5.101.160.121 -port=2302 -maxmem=2047 -noCB -exThreads=1 -filePatching -malloc=tbb4malloc_bi -profiles=config -config=config\server.cfg -cfg=config\basic.cfg -name=arma3 -autoinit -loadMissionToMemory

Original output filename: Arma3Retail_Server
Exe timestamp: 2017/12/13 18:03:13
Current time:  2018/02/13 11:11:43

Type: Public
Build: Stable
Version: 1.80.143869

Allocator: C:\SERVICES\ni1484673_1_SHARE\ftproot\arma3\Dll\tbb4malloc_bi.dll [2017.0.0.0] [2017.0.0.0]
PhysMem: 384 GiB, VirtMem : 4.0 GiB, AvailPhys : 47 GiB, AvailVirt : 3.9 GiB, AvailPage : 173 GiB
=====================================================================

11:11:43 SteamAPI initialization failed. Steam features won't be accessible!
11:11:43 Cannot register unknown string STR_3DEN_CAMERA_NAME
11:11:43 Cannot register unknown string STR_DIFF_SCENE_ONLY
11:11:43 Cannot register unknown string STR_DIFF_SCENE_AND_MAP
11:11:44 Initializing stats manager.
11:11:44 Stats config disabled.
11:11:44 sessionID: 8051ee15c061d8664ef7bad347695a1af8f5a47a
11:11:57 Unsupported language English in stringtable
11:11:57 Unsupported language English in stringtable
11:11:57 Item STR_RHS_KAB500_NAME listed twice
11:11:57 Unsupported language English in stringtable
11:11:57 Unsupported language English in stringtable
11:11:57 Item str_a3_to_c01_m02_036_ta_mechanized_briefing_SOLDIERC_0 listed twice
11:11:57 Cannot evaluate 'ReadAndCreate' - no file
ErrorMessage: Include file x\cba\addons\main\script_macros_common.hpp not found.
`

**Comment by commy2** [comment]
All it means is that the configs of these classes do not support XEH due to them overwriting CBA's EventHandlers subclass.
If another addon adds eventhandlers to these classes or any of the parents of these classes, then CBA will run a fallback loop that checks for newly created objects by comparing the current entities list to a previous entities list. All eventhandlers are then added by SQF command manually.
This solves most compatibility issues, but it has drawbacks:
- Some object types may not even appear in the entities list, and no XEH based events will run for them.
- Scripted eventhandlers may behave differently than config based eventhandlers (e.g. config based eventhandlers ignore return values).
- The `init` event is executed one frame after the object was created, which may or may not cause timing issues with some code using this event.
- Overhead one frame after any affected object was created due to having to manually add ~30 or so eventhandlers by script.
- Scripted events can be removed using `removeAllEventHandlers`. Therefore can "bad" missions break "bad" addons, while they can't break "good" addons.
- Having to compare the entities list at all.

There's nothing you can do if you don't own these addons, aside from writing a compatibility addon readding CBA's EventHandlers subclass or disabling the addons. It shouldn't really matter though, as the complications I listed are pretty minor.

**Comment by KyleGas** [comment]
So you're saying the server should still work? Because it doesnt :) or am i misunderstanding you?

**Comment by commy2** [comment]
I can tell you that if the server doesn't work, then it has nothing to do with these log messages.
Your second RPT says, that you haven't loaded CBA_A3, and therefore some addon cannot find an included header file.

**Comment by KyleGas** [comment]
ok.... i see. i started to reenter the mods one by one in the command line testing out when it stops working and i DID run into some other issues, which i might be able to solve. I'll let you know.

Thanks! that actually helped me quite a bit, surprisingly :)

**Comment by KyleGas** [comment]
It is working, i had to rename some ace folders.... didnt even get the XEH complaints anymore...... thanks i would have tried this for weeks ;)
