### ISSUE TITLE
Help on mod settings

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [CBATeam/CBA_A3#895]
**Arma 3 Version:** `1.80` (stable )
**CBA Version:** `3.6.1.180131` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
```
-My own WIP mod

**Description:**
- This is most certainly not a bug but me doing something wrong, I have carefully read the documentation but am at my wit's ends.
I want to implement mod options settings and make them available in the editor.
I'm using this in my config.cpp
`class Extended_PreInit_EventHandlers 
{
    class MRHSatKeyBinds 
	{
        init = "call compile preProcessFileLineNumbers '\MRHSatellite\Functions\fn_KeyBinds.sqf'";
		
    };
	class MRHSatSettings
	{
		init = "call compile preProcessFileLineNumbers '\MRHSatellite\Functions\fn_ModSettings.sqf'";
		
		
	};
};`
the keybinds work alright and are available as a setting from the editor.
the settings however do not show up while they do show up if I put the same line in class Extended_PostInit_EventHandlers 

I have used https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System for reference but must have missed something

for the record here's the contents of fn_ModSettings.sqf:

 `///////////adds options to the menu
_allowFullscreenText = localize "STR_MRH_SETTINGSALLOWFULLSCREENTEXT";
_allowFullscreenToolTip = localize "STR_MRH_SETTINGSALLOWFULLSCREENTOOLTIP";
_allowLaseringText = localize "STR_MRH_SETTINGSALLOWLASERINGTEXT";
_allowLaseringTooltip = localize "STR_MRH_SETTINGSALLOWLASERINGTOOLTIP";
_allowTargetDetectionText = localize "STR_MRH_SETTINGSALLOWTARGETDETECTIONTEXT";
_allowTargetDetectionTooltip = localize "STR_MRH_SETTINGSALLOWTARGETDETECTIONTOOLTIP";
_allowTragetTrackingText = localize "STR_MRH_SETTINGSALLOWTARGETTRACKINGTEXT";
_allowTargetTrackingTooltip = localize "STR_MRH_SETTINGSALLOWTARGETTRACKINGTOOLTIP";
["MRH_SAT_allowFullscreen" , "CHECKBOX",[_allowFullscreenText,_allowFullscreenToolTip], "MRHSatellite Options", true,1] call cba_settings_fnc_init;
["MRH_SAT_allowLasering" , "CHECKBOX",[_allowLaseringText,_allowLaseringTooltip], "MRHSatellite Options", true,1] call cba_settings_fnc_init;
["MRH_SAT_allowTargetDetection" , "CHECKBOX",[_allowTargetDetectionText,_allowTargetDetectionTooltip], "MRHSatellite Options", true,1] call cba_settings_fnc_init;
["MRH_SAT_allowTargetTracking" , "CHECKBOX",[_allowTragetTrackingText,_allowTargetTrackingTooltip], "MRHSatellite Options", true,1] call cba_settings_fnc_init;
`

**Comment by MisterHLunaticwraith** [comment]
yeeeesss thank you! I could kiss you right now!

**Comment by commy2** [comment]
Alternatively one can fetch the function from the cache:
```sqf
<blah> call (uiNamespace getVariable "cba_settings_fnc_init");
```
The problem occurs when the custom preInit script is executed before this function is copied from cache. Adding `cba_settings` into `requiredAddons` ensures that the custom preInit script is executed after the one from the `cba_settings` addon, which defines the `cba_settings_fnc_init` function in mission namespace.
