### ISSUE TITLE
Armaholic website still offers version 3.6 for download instead of 3.6.1

### ISSUE THREAD

**Issue by celticalliance** [CBATeam/CBA_A3#896]
**Arma 3 Version:** `1.80` (stable / rc / dev)
**CBA Version:** `3.6` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
```

**Description:**
- The Armaholic website still offers the previous CBA version for download.

Can this be fixed please?

**Comment by 654wak654** [comment]
Tell this to armaholic?

**Comment by Justice-Molton** [comment]
Done, i say it to him. He‘ll have a look

Von meinem iPhone gesendet

**Comment by celticalliance** [comment]
I just figured to share it here. I thought mod creators themselves need to update that page? I am not really in the know of where to go with this sort of issues either as well.

My apologies if me mentioning it here ticked people off because apparently I should have known where to go.

**Comment by commy2** [comment]
>I thought mod creators themselves need to update that page?

We only maintain the releases page on this Github project, the Steam Workshop and the BI forums thread.

**Comment by celticalliance** [comment]
Right. I didn't know that. I'll update the page we use to check for updates so we know for certain if there is a new version out.

Thanks for the info.
