### ISSUE TITLE
UI System documentation is missing

### ISSUE THREAD

**Issue by ImplicitDeny** [CBATeam/CBA_A3#897]
It seems that there is no more documentation for the CBA UI system, while the wiki page is created :
[CBA Wiki page](https://github.com/CBATeam/CBA_A3/wiki/UI%20System)

Considering the complexity of ArmA 3 UI design, having a powerful CBA framework would be a great thing, but it's currently very hard to use due to the lack of documentation.

Thanks

**Comment by commy2** [comment]
The cba_ui component contains:

- [`CBA_fnc_addPauseMenuOption`](https://github.com/CBATeam/CBA_A3/blob/master/addons/ui/fnc_addPauseMenuOption.sqf#L1-L21)
- [naming of groups in the lobby](https://github.com/CBATeam/CBA_A3/wiki/Name-Groups-in-Lobby)
- and the flexi menu

I don't think anybody left still knows how the flexi menu actually works.
