### ISSUE TITLE
MAINPREFIX\PREFIX\SUBPREFIX\COMPONENT naming logic and defining them

### ISSUE THREAD

**Issue by Bummeri** [CBATeam/CBA_A3#900]
**Arma 3 Version:** `x.xx`stable
**CBA Version:** `3.6.1` stable

**Mods:**
```
- CBA_A3
```

**Description:**
I am having diffculty understanding what MAINPREFIX\PREFIX\SUBPREFIX\COMPONENT should stand for and how they should be defined properly. They are referred to in the documentation here: http://cbateam.github.io/CBA_A3/docs/files/main/script_macros_common-hpp.html

What is the intended naming convention and how should it be done?

**Comment by commy2** [comment]
| | CBA | ACE |
|-|-|-|
| MAINPREFIX | x | z
| PREFIX | cba | ace
| SUBPREFIX | addons | addons
| COMPONENT | xeh | medical

**Comment by Dorbedo** [comment]
`MAINPREFIX` defaults to `x`
`SUBPREFIX` defaults to `addons`
