### ISSUE TITLE
Curator interface opening/closing EH

### ISSUE THREAD

**Issue by Timi007** [CBATeam/CBA_A3#907]
**Arma 3 Version:** `1.82`
**CBA Version:** `3.6.1`

**Mods:**
```
- CBA_A3
```

**Request:**
- Is it possible to add an eventhandler which raises an event when the curator interface is opening/closing? Something like ACE did: [Fancy link](https://github.com/acemod/ACE3/blob/master/addons/common/XEH_postInit.sqf#L266-L278)

**Comment by commy2** [comment]
That's already possible.
```cpp
class Extended_DisplayLoad_EventHandlers {
    class RscDisplayCurator {
        commy_curatorDisplayOpened = "systemChat str _this";
    };
};
```
config.cpp for addon or description.ext for mission. You can then proceede and call a function or compile/preprocess a script file from there.

**Comment by Timi007** [comment]
Didn't know that yet. Thanks, I will try that out.

**Comment by dedmen** [comment]
If you happen to need the EH before Arsenal starts replacing backpacks and deleting their variables for no reason.. Then:
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/addons/core/CfgEventHandlers.hpp#L46-L53

**Comment by Timi007** [comment]
@commy2 Tried it out, works fine.
@dedmen I will keep it in mind (maybe).
