### ISSUE TITLE
Question: Preset Settings

### ISSUE THREAD

**Issue by madpat3** [CBATeam/CBA_A3#908]
Where is the Preset stored on the mashine.
i searched my profile, but couldn't find it.

**Comment by Cuel** [comment]
What preset?

**Comment by dedmen** [comment]
They are stored in your profile. 
This is a issue tracker. Not a question asking forum.

**Comment by madpat3** [comment]
i will try asking somewhere else.
you can close this "issue"

**Comment by dedmen** [comment]
Why ask elsewhere? I already answered your question. Or do you have further questions to that?
Also you can close it yourself if you want to.

**Comment by PabstMirror** [comment]
`profileNamespace getVariable ["cba_settings_hash", -1];`
`profileNamespace getVariable ["cba_settings_presetsHash", -1];`

But I don't recommend messing with these arrays unless you're sure you know what you're doing; storing bad values could cause problems.
