### ISSUE TITLE
Add documentation about CBA Setting sub-categories/separators to the wiki

### ISSUE THREAD

**Issue by Bummeri** [CBATeam/CBA_A3#919]
EDIT: SEE https://github.com/CBATeam/CBA_A3/issues/919#issuecomment-388448329

**Arma 3 Version:** Stable
**CBA Version:** `3.x.x` Stable

**Mods:**
```
- CBA_A3
```

**Description:**
It would be great if it would be possible to add a separator such as to the cba settings submenu:
---------------------Such and such settings:---------------------------

Maybe edit CBA_Settings_fnc_init to have a new _settingType parameter such as "SEPARATOR". When used the _title could be the text displayed there between the dashes or somesuch.

This would help organize large amount of settings in a more userfriendly way.

**Comment by PabstMirror** [comment]
Take a look at https://github.com/CBATeam/CBA_A3/pull/869

**Comment by Bummeri** [comment]
Oh, Great, Thanks!

This ticket should be changed to "Add documentation about CBA Setting sub-categories to the wiki".

Update this: https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System#arguments-of-cba_settings_fnc_init

With this info: _category    - Category for the settings menu + optional sub-category <STRING, ARRAY>

And also perhaps update this pic somewhere in the guide: 
https://user-images.githubusercontent.com/9376747/34646187-353c22e0-f327-11e7-9be3-4b4b539d34d1.jpg

Thanks again!

**Comment by commy2** [comment]
Done. Ongoing, so it doesn't appear in the changelog, as it's no change to the code base.
