### ISSUE TITLE
Compatibility Button shows ammo but not muzzles and scopes

### ISSUE THREAD

**Issue by grrminator** [CBATeam/CBA_A3#921]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.7.0` (stable / dev + commit hash)

**Mods:**
NIARMS
Nato Rus Weapons
- CBA_A3
```

**Description:**
When you press the compatibility button in Exile Trader, it will show the ammo for the gun but *NOT* the scopes and muzzle for the gun on any addon. It will do it for base exile and arma weapons.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by dedmen** [comment]
>When you press the compatibility button in Exile Trader

This is CBA Github not exile.

**Comment by commy2** [comment]
That's a bug in Exile. They're only scanning `compatibleItems[]` (ARRAY) to retrieve the compatible items from config, but don't read from `class compatibleItems`.
They don't even have to manually read these configs and could instead use `BIS_fnc_compatibleItems`, but they don't.
Nothing we can do.
