### ISSUE TITLE
Server failing to start - Requires A3_Data_F_Tank_Loadorder

### ISSUE THREAD

**Issue by JerichoReynolds** [CBATeam/CBA_A3#924]
**Arma 3 Version:** `1.76.143187` (stable)
**CBA Version:** `3.7.0.180430` (latest)

**Mods:**
```
- CBA_A3
-CUP Weapons
-CUP Units
-CUP Vehicles
-ace
-Enhanced Movement
-RHAAFRF
-RHSGREF
-RHSSAF
-RHSUSAF
-Task Force Radio
```

**Description:**
- Rented a new Arma 3 server through Wombat Servers and I am currently attempting to setup the server to run the antistasi - Warlords of the Pacific scenario. So far I am just working on installing the mods but haven't been able to get CBA_A3 to work due to a error coming up during server startup. Vanilla (no mods) launch of the server seems to start up fine but as soon as CBA_A3 is added to the launch parameters the server gets the following error: Warning Message: Addon 'cba_jr_prep' requires addon 'A3_Data_F_Tank_Loadorder' and doesn't go any further then this point.

**Steps to reproduce:**
- Download latest CBA_A3.
- Move @CBA_A3 to server directory.
- Add @CBA_A3 to launch parameters.
- Start server.

**Where did the issue occur?**
- Dedicated server during startup.

**RPT log file:**
- https://pastebin.com/12nNGNz6

**Comment by dedmen** [comment]
>Arma 3 Version: 1.76.143187 (stable)

Latest is 1.82.

**Comment by JerichoReynolds** [comment]
Interesting, I have used the hosting sites steam update feature already but I'll give it another try and see if it makes any difference.

**Comment by JerichoReynolds** [comment]
7 more attempts at finishing the update and it is finally done and the server starts up perfectly. Sorry for wasting your time.
