### ISSUE TITLE
cba_settings.sqf breaks addon settings UI

### ISSUE THREAD

**Issue by SilentSpike** [CBATeam/CBA_A3#930]
**Arma 3 Version:** `1.82` stable
**CBA Version:** `3.7.0` dev 3c45a0614c0d61d7b415a989a3c3e06a4680f0d3

**Mods:**
```
- CBA_A3
- ACE3
```

**Description:**
- When the `cba_settings.sqf` file is present the addon settings UI displays default values instead of changed values.
- I was also told the mission sqm values can't be updated via the UI once this takes effect, but didn't manage to reproduce this part of the issue myself.

**Steps to reproduce:**
- Open a new mission, change any addon setting and save the mission.
- Open the mission folder and create `cba_settings.sqf` file.
- Re-open the addon settings UI and notice that the setting changed is seemingly reset.
- Delete the `cba_settings.sqf` file and then re-open the addon settings UI again and notice that they are back to normal.

**Where did the issue occur?**
- Editor (Singleplayer)

**RPT log file:**
https://pastebin.com/0hD7SPEY

**Comment by jonpas** [comment]
That is `cba_settings.sqf` in mission?

**Comment by SilentSpike** [comment]
Correct, see repro steps 👍

**Comment by jonpas** [comment]
Can't confirm, but I think I noticed that too. Doesn't happen with static addon settings though.
