### ISSUE TITLE
Feature Request: API for overriden BIS functions

### ISSUE THREAD

**Issue by shukari** [CBATeam/CBA_A3#933]
**Description:**
- some mods override for example the "ModuleRemoteControl_f" function... so an api for this problem seams nice
- original thread: https://github.com/acemod/ACE3/issues/6253

**Comment by commy2** [comment]
Not sure how this would be best implemented if it is supposed to work for every function while not causing overhead for every function call.

**Comment by SilentSpike** [comment]
I don't really know what an API could do in this scenario anyway? Would it run all overrides? Pick one at random?

It's not like CBA can merge the code at runtime.

**Comment by bux** [comment]
add to an array of functions that get executed by CBA in the order they've been added

or if one needs fine grained control over the time of execution have multiple arrays of functions that get called sequentially or add an additional priority param.

**Comment by commy2** [comment]
Yeah, but for which functions should this be done? All of them? That's a lot of overhead for something basically unused.

**Comment by SilentSpike** [comment]
@bux right, but then you're executing multiple copies of the function?

**Comment by SilentSpike** [comment]
e.g. we override moduleZeus and so does another addon, now you have two zeus instances running for every module.

**Comment by commy2** [comment]
No worries, shukari :-]

Honestly, it wouldn't be too heavy, but you know how people are... They get really picky about performance (even though most problems are structural and not mended by changing around isolated commands), and this'd be one additional check per function call.

**Comment by Dorbedo** [comment]
I would find this this anoying, if this would be added to every BIS-Funktion for the whole time of a mission.
If you still want to do this, I'd prefer to stop the overwriting for every unused function after the init is done.

**Comment by dedmen** [comment]
We can provide a API so that certain functions are called before/after a BIS function. Making every BIS function a little bit slower. And it still doesn't help for the ACE/Ares usecase where we want to keep the original script but just insert a few lines.

Not possible.

**Comment by shukari** [comment]
🔨
