### ISSUE TITLE
CBA keybinding: Dialogs only open every second keydown when on the map

### ISSUE THREAD

**Issue by Timi007** [CBATeam/CBA_A3#934]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.7.0` (stable)

**Mods:**
```
- CBA_A3
```

**Description:**
- In normal 3D a dialog, created by the CBA keybinding function on keydown, always opens. But on the map you get an odd behaviour. For most keys (with and without modifiers), the dialog only opens every second keydown. If mouse buttons with modifiers are assigned, it gets even weirder. After the first creation of the dialog with the assigned keys (e.g. shift + left mouse button), you can create the dialog only by pressing left mouse button, provided you didn't press any other button after closing the dialog.

**Steps to reproduce:**
- Create a mission with init.sqf and description.ext
- Put the following in the description.ext: https://pastebin.com/aVr5eUZT
- Put the following in the init.sqf: https://pastebin.com/zbsdLnqG
- If you press shift + left mouse button, a dialog will appear and the number will count one up
- Go on the map and press the key multiple times, you will see that the dialog only opens every second keydown
- After the first creation of the dialog on the map, you can create the dialog only by pressing left mouse button

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**RPT log file:**
- There is nothing intresting in the RPT logs.

Now you probably asking yourself how I find such bugs but I cannot answers you that question because even I don't know the answer to that.

**Comment by commy2** [comment]
Debug console only test version for lazy people like me:
```sqf
n = 0;

["Dialog Mod", "test_key_3", "Open dialog",
    {
        private _display = uiNamespace getVariable ["test_display", displayNull];
        if (!isNull _display) exitWith {};

        _display = allDisplays;
        createDialog "RscDisplayEmpty";
        _display = (allDisplays - _display)#0;
        uiNamespace setVariable ["test_display", _display];

        private _vignette = _display displayCtrl 1202;
        _vignette ctrlShow false;

        private _control = _display ctrlCreate ["RscText", -1];

        _control ctrlSetPosition [
            0.4 * safezoneW + safezoneX,
            0.3 * safezoneH + safezoneY,
            0.15 * safezoneW,
            0.05 * safezoneH
        ];
        _control ctrlCommit 0;

        n = n + 1;
        _control ctrlSetText format ["Let's count together: %1", n];
    },
    "",
    [0x14, [false, true, false]] // Ctrl + T
] call CBA_fnc_addKeybind;
```

**Comment by commy2** [comment]
I don't think there is any feasible work around for this sadly. Closing it.
