### ISSUE TITLE
Assigning key combinations with Ctrl+Num XYZ doesn't behave correctly.

### ISSUE THREAD

**Issue by Pergor** [CBATeam/CBA_A3#938]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.7.1.180604`
**Task Force Radio Version:** `1.-1.0.295`

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
- Assigning key combinations with Ctrl+Num XYZ for TFAR doesn't work.
- I will create a similar issue at the TFAR github, in case it's a TFAR problem.
https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1430
- I use Num5 and Num8 for SW and LR transmit accordingly, since these keys are free for radio usage. That's why I use the Ctrl-modifier for additional channel transmitting. Doesn't seem to work though.

**Steps to reproduce:**
- Assign a key combination for example for SW Transmit Additional to Ctrl+Num5.
- Set additional channel on SW radio.
- Switch to regular channel.
- Press Ctrl+Num5
- Only Num5 is registered

**Additional information:**
I can recreate this problem with CBA only:
- Using Num1 for "Next optics state" and Ctrl+Num1 for "Previous optics state" will render changing the optics state impossible.
- Using Ctrl+Num1 for "Next optics state" and nothing for "Previous optics state", pressing Num1 without Ctrl executes "Next optics state", whereas pressing the set Ctrl+Num1 doesn't do anything.
- Using Num1 for "Next optics state" and nothing for "Previous optics state", disables changing the optics state as well.

**Comment by commy2** [comment]
Cannot reproduce. Tried with `Next Rail State`, `Previous Rail State`.

Tbh, I suspect this is something specific to your keyboard. You should debug using `displayAddEventHandler`:
```sqf
uiNamespace getVariable "RscDisplayMission" displayAddEventHandler ["KeyDown", {
    params ["_mission", "_key", "_shift", "_control", "_alt"];
    systemChat str ([_key, _shift, _control, _alt] call CBA_fnc_localizeKey);
}];
```

**Comment by Pergor** [comment]
I use a very ordinary Logitech keyboard (the one without any functions for 12€ ;)). The display-EVH returns the right values...
Ctrl
Ctrl
Ctrl
Ctrl+Num5
Ctrl+Num5
Ctrl
Ctrl+Num5

and more like this.

**Comment by commy2** [comment]
![https://i.imgur.com/CrB5Nla.png](https://i.imgur.com/CrB5Nla.png)

Can't reproduce.

**Comment by commy2** [comment]
I blame it on TFAR as they 1) [mess with the system](https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/addons/core/functions/events/keys/fnc_onSwTangentReleasedHack.sqf), and 2) no one can reproduce with basic keybinds.
