### ISSUE TITLE
Synch fireteam colours

### ISSUE THREAD

**Issue by BaerMitUmlaut** [CBATeam/CBA_A3#94]
This is kind of fixing a BI "feature", but I think CBA should take care of this since it's one of the most used addons out there.

Currently fireteam colours are not synched in MP. This causes addons having to do workarounds that watch the assigned team colour on the team leaders client and manually synch it. If you use more than one addon that tries to do something like that, you can easily cause issues, and if you use none, the fireteam colours won't get synched at all.

**Comment by Killswitch00** [comment]
We accept submissions for new functionality in CBA. If you have a solution for the problem, feel free to submit it for review and possible inclusion in CBA.

**Comment by BaerMitUmlaut** [comment]
My solution would be adding a PFH on the squad leader's client. He has the authority and can assign team colors, so if the color of a team member gets changed on his client this change should get broadcasted to all squad members. Mods would have to change the team color on the squad leaders client.

I have no idea what CBA's internal structure is though, so if you can give me a hint where I could add such a PFH that would be great.

**Comment by jonpas** [comment]
> I have no idea what CBA's internal structure is though, so if you can give me a hint where I could add such a PFH that would be great.

It's same as ACE3's except functions are in the root of the module folder and NOT in a `functions` subfolder.

**Comment by BaerMitUmlaut** [comment]
I'm more interested in what module it should be. Networking maybe?
