### ISSUE TITLE
Settings always forced

### ISSUE THREAD

**Issue by Meiestrix** [CBATeam/CBA_A3#943]
**Arma 3 Version:** stable 1.82
**CBA Version:** 3.7.1.180604
**Mods:** many :)

**Description:**
 Hi, i have a problem with the settings system and i am not sure what is wrong.
  So, I have all my ACE settings stored in a cba_settings.sqf file and packed them as a pbo, that file runs only on the dedicated server, which worked fine some time ago. But know i have the problem, that even my not forced settings are always forced on the clients and i cant change this.

Example:
All my nightvision settings are not forced, so that the admin can adjust them to the scenario / map.
They look like this in the settings sqf:

ace_nightvision_aimDownSightsBlur = 0.3; 
ace_nightvision_disableNVGsWithSights = false; 
ace_nightvision_effectScaling = 0.3; 
ace_nightvision_fogScaling = 0.4; 
ace_nightvision_noiseScaling = 0.4;
ace_nightvision_shutterEffects = true;

But for some reason all settings expect the ace_nightvision_shutterEffects setting are forced, see screenshot.
[https://www.dropbox.com/s/n7gafujoyhrqtu3/20180629170740_1.jpg?dl=0](https://www.dropbox.com/s/n7gafujoyhrqtu3/20180629170740_1.jpg?dl=0)

The night vision settings are only an example and not the only settings where this happens.

I have no idea why this happens and i hope someone here can help me.
To validate, that my setting file is loading correct i have changed a setting in the sqf and confirmed it ingame.
I have already tried to delete the user profile on the dedicated server, but that did not help.
Is there any other place where the settings are stored?

**Where did the issue occur?**
- Dedicated

**Comment by commy2** [comment]
`aimDownSightsBlur` is set up by ACE to be a global setting, meaning that it is required to be the same everywhere, meaning that the client settings are always discarded, meaning always forced by either mission or the server. See:
https://github.com/acemod/ACE3/blob/master/addons/nightvision/initSettings.sqf#L34

Probably the same for the other ones as well.

**Comment by Meiestrix** [comment]
Okay thanks, but I have the same problem for example for the ace_goggles_effects, is this also a global variable? I am not sure how i can identify this.

**Comment by commy2** [comment]
Probably. I used the ACE github search function.
