### ISSUE TITLE
All players in server getting Error messages regarding Version Mismatch 

### ISSUE THREAD

**Issue by TandelK** [CBATeam/CBA_A3#954]
**Arma 3 Version:** `stable` (stable)
**CBA Version:** `3.7.1` (stable)

**Mods:**
```
- CBA_A3
-ACE
-ACEX
-ACE3 ( Animation and Actions)
-3Den Enhanced 
-RHSUSAF
-RHSAFRF
-Ace Compat RHSUSAF
-Ace Compat RHSAFRF
-ITC Air Systems
- ITC Air Systems ACE Compat
-Enhanced Movement 
-Achilles Expansion
-Shacktac User Interface
-[MELB] Little Bird
-BackpackOnChest
-Task Force Radio
-MCC Sandbox

```

**Description:**
I am getting following error when connecting to my Dedicated Server for each and every player. 

> cba_versioning - mymod - Version Mismatch!(machine:bis_02_342 (Username) version 0.0.0 , serverVersion 2.0," "Level:2")
I am using Steam Workshop on both Client Side as well as Server side . 
Client Side - Using Steam Client Workshop section and loading the CBA 3 from the Arma 3 Launcher 
Server Side - Created a script for downloading mods from Steam Workshop using Steam CMD and using Symbolic Link of that folder to the main folder of Arma 3 Server Installation directory. 

**Steps to reproduce:**
Just launch the server and Arma 3 Client and join server using ARma 3 Server Browser auto selecting mods and when entering server i am facing the error message for every player mentioned above

**Where did the issue occur?**
- Dedicated Server 

**RPT log file:**
Client Side RPT - https://pastebin.com/HUDCu4he
Server Side RPT - https://pastebin.com/W7Y8uHxj

**Comment by commy2** [comment]
Remove "mymod" from the server.

**Comment by commy2** [comment]
Close?

**Comment by TandelK** [comment]
There is no mymod named thing in the server

**Comment by commy2** [comment]
To explain Pabst's answer, connect on your server with the debug console enabled and execute:
```sqf
{
    private _rogueAddon = configSourceAddonList (configfile >> "CfgSettings" >> "CBA" >> "Versioning" >> "myMod");
    str _rogueAddon remoteExec ["systemChat", remoteExecutedOwner];
} remoteExec ["call", 2];
```
via LOCAL EXEC to print the Addon folder containing "mymod" in Chat.
