### ISSUE TITLE
Error with custom addon since latest update

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [CBATeam/CBA_A3#957]
**Arma 3 Version:** `1.84` (stable / rc / dev)
**CBA Version:** `3.8.0.180801` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3 //latest workshop distribution
-Ace 3 3.12.2.33 //latest workshop distribution
-Custom addon [source files on github](https://github.com/MisterHLunaticwraith/MRHMilsimTools/tree/master/Addons/MRHFiberScope)
```

**Description:**
- Ever since the latest CBA update some of my addons  cause an issue when arma loads (same untouched addons didn't have the issue with the previous version. On arma main title screen I get the error message 
`No entry 'bin\config.bin/RscDisplayMain/controls/TitleSingleplayer.textureNoShortcut'.`
in a message box. I cannot click anywhere and have to ctrl alt del to kill the game.

I'm guessing this has something to do with the required addons line in the config.cpp so I changed "cba_settings" to "cba_main" and still have the same issue.
Removing the requirement altogether has a strange effect:
-The game will start properly.
-The settings created by the addon (keybinds) do show, but have no effect in game, the keys do not work.
Strangely enough this only happens with certain addons and not others.

**Steps to reproduce:**
- Pack addon provided in github link above.
-Start arma with addon, cba and ace3.

**Where did the issue occur?**
- Game start

**RPT log file:**
[Pastebin rpt](https://pastebin.com/q2U3BYTU)
did not see anything useful in there though.

**Comment by dedmen** [comment]
>I'm using custom created dialogs and the defines for these dialog seem to interfere with arma, renaming the base classes to tagged custom names fixes the issue.

So if you know it's not CBA's fault why not close this report?

**Comment by MisterHLunaticwraith** [comment]
Because it's kindda cba's fault, I think (I am not sure) that there's an issue with:

> IMPROVED:

 CfgPatches ordering (#923, #936) commy2 PabstMirror (from changelog)
Somehow the addon must be loaded before arma's addons so:

> cba_main is now all that is needed in CfgPatches requiredAddons[] to ensure your addon configs are being loaded after CBA and thereby after all base game configs.

does not work as intended

**Comment by 654wak654** [comment]
> ...and the defines for these dialog...
If you have a modded dialog and you have a file that defines simple things like `CfgButton`, you're doing something wrong. You don't need to redefine those base UI classes in a mod config, you can just use them like you use any other game class. The exporting of UI classes is only useful in missions because description.ext and config.bin are in different namespaces.

**Comment by MisterHLunaticwraith** [comment]
Thanks, I didn't know that! however I often modify directly the base classes for various reasons. As far as I am concerned this solves the issue.
