### ISSUE TITLE
Prep FSMs? how shall I handle them?

### ISSUE THREAD

**Issue by ArcticSnowSky** [CBATeam/CBA_A3#97]
Hey guys,
I tried to stay as compatible as possible to CBA3 and ACE3.
My filetree looks like that:
y:
aceai/
- addons/
  - medical/
    - fsm/
      - reactOnSituation.fsm
    - functions/
      - fnc_handleDamage.sqf
      - script_component.hpp
    - script_component.hpp
    - XEH_init.sqf
    - XEH_preInit.sqf
  - lalala...

my question is, how would I bind the fsm file properly (like PREP for the functions)?
For the moment I'd need to use execFSM "y\aceai\addons\medical\fsm\reactOnSituation.fsm".

Sorry if this question is dumb, but I am very unexperienced with all the cba macro magic yet.
At the moment I'm still using a lot of copy and paste just to get my project a little bit organized (before I was using pure SQF through one file, but I have seen fast that with all those functions adding the whole ASS_Addon_module_function each time was becoming messy)

Edit: Do macros in FSM even work?

**Comment by Killswitch00** [comment]
"PREP" is used to preload (preprocess and compile) functions. FSM files are (AFAIK) always ```execVM``:ed, so there's no need to prep them.

I haven't tried macros inside an FSM, so no idea there.
