### ISSUE TITLE
CBA Settings: Whitelisted can't save

### ISSUE THREAD

**Issue by neilzar** [CBATeam/CBA_A3#977]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.8.0` (stable)

**Mods:**
```
- CBA_A3
- ACE 3
```

**Description:**  
I tried to change the PBO whitelist on our server when not logged in as admin. I am on the whitelist of people allowed to edit the settings. I can edit it, but when I click OK, it doesn't save. I tried this on both our servers and neither worked.  
Once I logged into admin, I was able to save it.

`cba_settings_whitelist[] = {"admin","bunchofUIDsremovedforprivacy"};` is set in `description.ext`

**Steps to reproduce:**
- Have your UID in `cba_settings_whitelist[]`
- Go on to a server and load that mission
- Once either on the briefing screen or in-game, go to addon options
- Edit the needed values
- Click OK

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- [gist](https://gist.github.com/neilzar/38fd9675c27c37723ef3b10fec2c9c68)

**Comment by neilzar** [comment]
#978 should fix the issue

**Comment by commy2** [comment]
#978 merged
