### ISSUE TITLE
Setting and variable value can differ when using "SLIDER"-type CBA Settings

### ISSUE THREAD

**Issue by xrufix** [CBATeam/CBA_A3#989]
**Arma 3 Version:** `1.84` (?) (stable)
**CBA Version:** `3.8.0` (stable)

**Mods:**
```
- CBA_A3
- ACE3
- own mod in development
```

**Description:**
- CBA settings of the `SLIDER` type are always saved as unrounded floats. Expected behaviour would be that the setting saved as a global variable is exactly the same as the number shown in the settings menu (rounded to 0, 1 or 2 decimals).

**Steps to reproduce:**
- Set a CBA Setting using a slider to some value.
- read the corresponding variable and compare to the value displayed in Settings menu.

**Where did the issue occur?**
- Editor, Singleplayer

**RPT log file:**
- no

**Comment by xrufix** [comment]
In my mod, i use the slider to add a certain amount of "rounds" to an APS. Each time it is triggered the number of rounds is reduced by 1, and I check if it has reached 0. So when setting the Slider to 3 (.0), but getting a value of for example 3.3, the check would return false if it reaches 0.3. This way, the system can run 4 times instead of 3.

Of course, this can easily be avoided by rounding immediately after calling cba_setting_fnc_init, but i'ld prefer if this wasn't necessary.

**Comment by Soldia1138** [comment]
This is definitely something you should handle on your side. If changed on CBA‘s side it may have a major impact on other mods with unforeseen consequences.

**Comment by commy2** [comment]
Close? I agree with Soldia1138 and Pabst's solution should solve this anyway.
