### ISSUE TITLE
Gray out, None editable client settings

### ISSUE THREAD

**Issue by GuzzenVonLidl** [CBATeam/CBA_A3#992]
To make it easier to edit client settings if needed, they should be grayed out similarly to mission settings when they are read from the cba_settings.sqf

How it looks now for Clients
<a href="https://gyazo.com/f1a5b3e245fd070f4f32210bb08a47c0"><img src="https://i.gyazo.com/f1a5b3e245fd070f4f32210bb08a47c0.png" alt="Image from Gyazo" width="671"/></a>

How it should look for Clients
<a href="https://gyazo.com/3f1af0dd5c05a31dd5dd430cfb06acd9"><img src="https://i.gyazo.com/3f1af0dd5c05a31dd5dd430cfb06acd9.png" alt="Image from Gyazo" width="842"/></a>

To go in even more advanced, may make it so only editable settings are sorted and is in the top of the list

Side note that may be applicable is that at same time as this is done, maybe change so only the "green box" and "red cross" is shown for in the "Server" and "Mission" tab and is not for shown in "Clients" tab

**Comment by commy2** [comment]
Client settings should already be greyed out if they are read from the cba_settings.sqf put inside the userconfig folder inside the main game folder.
I see no reason why they should be not editable just because they are inside the mission's settings config file.
