### ISSUE TITLE
Weapon Accessories stop working with CBA_A3 loaded

### ISSUE THREAD

**Issue by binghamt** [CBATeam/CBA_A3#993]
**Arma 3 Version:** `Latest` (stable)
**CBA Version:** `3.8.0.180801 (stable)

**Mods:**
```
- CBA_A3
```

**Description:**
- When loading up CBA_A3 alone the server's weapon shop attachments button stopped working I'm not sure why but I have tried a lot of different things to get it working, I have also ran into a few people saying they had this issue but It stopped them and they never found a fix. 

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**RPT log file:**
- Nothing in the RPT Log. 

Extra Information: I'm not sure which ones would help finding a solution so here is all the scripts for the weapon shop.

[fn_weaponShopFilter.sqf ](https://pastebin.com/JYjArg5X)
[fn_weaponShopMags.sqf](https://pastebin.com/hxn3mQnk)
[fn_weaponShopMenu.sqf](https://pastebin.com/rcYyPsbg)
[fn_weaponShopSelection.sqf](https://pastebin.com/2tjKzxfP) 
[fn_weaponShopAccs.sqf](https://pastebin.com/x9KVkDrb)
[fn_fetchCfgDetails.sqf](https://pastebin.com/c20SYTi8)

Better to have all of them then need one. :) Without the mod loaded it works fine with it loaded It's just messed up like all of the weapon accessories stop working like it cant find any that work... I'm confused because I have tried using CBA_fnc_compatibleItems; No matter how many different ways I tried it. It still didn't work

**Comment by PabstMirror** [comment]
might be same as https://github.com/CBATeam/CBA_A3/issues/969

**Comment by binghamt** [comment]
Any idea's :) I have spent way to much time trying to figure this out. Thanks!

**Comment by PabstMirror** [comment]
```
    if (isArray (configFile >> "CfgWeapons" >> _weapon >> "WeaponSlotsInfo" >> "PointerSlot" >> "compatibleItems")) then {
        _slotArray = FETCH_CONFIG3(getArray,"CfgWeapons",_weapon,"WeaponSlotsInfo","PointerSlot","compatibleItems");
        {
            _weaponArray pushBack _x;
        } forEach _slotArray;
    };
```
replace that with a call to `private _pointers = [_weapon, 301] call BIS_fnc_compatibleItems;`

**Comment by binghamt** [comment]
Could you add me on discord :) 
iTz Waffle#8440

**Comment by commy2** [comment]
Close?
